-- Migration 054: Add intake & enrichment columns to network_opportunities
-- Uses ALTER TABLE ... ADD COLUMN IF NOT EXISTS (idempotent)

ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS first_name TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS last_name TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS address_line1 TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS address_line2 TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS zip TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS county TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS monthly_bill_amount NUMERIC(10,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS current_electricity_rate NUMERIC(8,4);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS home_ownership TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS roof_type TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS roof_shade TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS roof_age_years INTEGER;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS square_feet INTEGER;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS source_system TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS source_channel TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS source_name TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS funnel_id UUID;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS campaign_id UUID;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS utm_source TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS utm_medium TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS utm_campaign TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS utm_content TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS utm_term TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS gclid TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS fbclid TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS ttclid TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS consent_given BOOLEAN DEFAULT false;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS consent_text TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS consent_timestamp TIMESTAMPTZ;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS ip_address INET;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS user_agent TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS referer TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS is_duplicate BOOLEAN DEFAULT false;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS duplicate_score NUMERIC(5,4);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS duplicate_of_id UUID;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS is_blocked BOOLEAN DEFAULT false;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS is_flagged BOOLEAN DEFAULT false;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS enrichment_status TEXT DEFAULT 'pending';
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS property_enriched_at TIMESTAMPTZ;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS solar_enriched_at TIMESTAMPTZ;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS utility_enriched_at TIMESTAMPTZ;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS formatted_address TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS fips_code TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS census_tract TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS parcel_id TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS year_built INTEGER;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS owner_name TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS owner_occupied BOOLEAN;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS assessed_value NUMERIC(12,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS market_value NUMERIC(12,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS peak_sun_hours_daily NUMERIC(5,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS recommended_system_kw NUMERIC(8,3);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS annual_kwh_production NUMERIC(10,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS annual_savings_year1 NUMERIC(10,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS savings_25_year NUMERIC(12,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS estimated_system_cost_gross NUMERIC(12,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS federal_itc_amount NUMERIC(10,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS estimated_system_cost_net NUMERIC(12,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS payback_period_years NUMERIC(5,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS offset_percentage NUMERIC(5,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS co2_offset_lbs_year NUMERIC(10,2);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS utility_name TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS utility_eiaid TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS electricity_rate_kwh NUMERIC(8,5);
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS net_metering_available BOOLEAN;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS net_metering_policy TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS ahj_name TEXT;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS interconnection_complexity INTEGER;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS state_incentives_available BOOLEAN;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS srec_market_active BOOLEAN;
ALTER TABLE network_opportunities ADD COLUMN IF NOT EXISTS intake_completed_at TIMESTAMPTZ
