-- Migration 056: enrichment_queue — per-provider job queue with UNIQUE(opportunity_id)

CREATE TABLE IF NOT EXISTS enrichment_queue (
  id                          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  opportunity_id              UUID UNIQUE NOT NULL REFERENCES network_opportunities(id) ON DELETE CASCADE,
  status                      TEXT NOT NULL DEFAULT 'pending',
  priority                    INTEGER NOT NULL DEFAULT 5,
  attempt_count               INTEGER NOT NULL DEFAULT 0,
  max_attempts                INTEGER NOT NULL DEFAULT 3,
  providers_requested         TEXT[] DEFAULT ARRAY['property','solar','utility'],
  providers_completed         TEXT[] DEFAULT ARRAY[]::TEXT[],
  providers_failed            TEXT[] DEFAULT ARRAY[]::TEXT[],
  providers_skipped           TEXT[] DEFAULT ARRAY[]::TEXT[],
  property_status             TEXT DEFAULT 'pending',
  property_provider_used      TEXT,
  property_enriched_at        TIMESTAMPTZ,
  property_error              TEXT,
  solar_status                TEXT DEFAULT 'pending',
  solar_provider_used         TEXT,
  solar_enriched_at           TIMESTAMPTZ,
  solar_error                 TEXT,
  utility_status              TEXT DEFAULT 'pending',
  utility_provider_used       TEXT,
  utility_enriched_at         TIMESTAMPTZ,
  utility_error               TEXT,
  ahj_status                  TEXT DEFAULT 'pending',
  ahj_provider_used           TEXT,
  ahj_enriched_at             TIMESTAMPTZ,
  ahj_error                   TEXT,
  demographics_status         TEXT DEFAULT 'pending',
  demographics_provider_used  TEXT,
  demographics_enriched_at    TIMESTAMPTZ,
  demographics_error          TEXT,
  satellite_status            TEXT DEFAULT 'pending',
  satellite_provider_used     TEXT,
  satellite_enriched_at       TIMESTAMPTZ,
  satellite_error             TEXT,
  started_at                  TIMESTAMPTZ,
  completed_at                TIMESTAMPTZ,
  failed_at                   TIMESTAMPTZ,
  next_retry_at               TIMESTAMPTZ,
  last_error                  TEXT,
  error_details               JSONB DEFAULT '{}',
  duration_ms                 INTEGER,
  force_refresh               BOOLEAN DEFAULT false,
  dry_run                     BOOLEAN DEFAULT false,
  triggered_by                TEXT NOT NULL DEFAULT 'system',
  created_at                  TIMESTAMPTZ DEFAULT NOW(),
  updated_at                  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_enrichment_queue_status ON enrichment_queue(status);
CREATE INDEX IF NOT EXISTS idx_enrichment_queue_next_retry ON enrichment_queue(next_retry_at) WHERE status = 'retry';
CREATE INDEX IF NOT EXISTS idx_enrichment_queue_priority ON enrichment_queue(priority DESC, created_at ASC) WHERE status = 'pending'
