-- ============================================================================
-- Migration 106: Membership and Organization Lifecycle Correction
--
-- Phase 1B.1 — Organization Authority Boundary and Lifecycle Correction
--
-- This migration corrects two lifecycle defects from Phase 1B (migration 105):
--
--   1. MEMBERSHIP LIFECYCLE (ADR-001, Threat Model T-12):
--      Phase 1B used only three membership statuses (active, invited,
--      suspended) and performed hard DELETE on member removal. ADR-001
--      specifies a fourth status — 'removed' — with accompanying
--      removed_at / removed_by / joined_at audit columns. Hard deletion
--      destroys the audit trail; soft-delete via 'removed' status retains
--      the row for audit while excluding it from active membership queries.
--
--   2. ORGANIZATION LIFECYCLE (ADR-001):
--      Phase 1B used 'deleted' as the terminal org status. The canonical
--      authority model uses 'archived' — organizations are never truly
--      deleted; they are archived (soft-delete) with the row retained for
--      audit trail integrity. This migration adds 'archived' to the status
--      vocabulary and an archived_at timestamp column. The legacy 'deleted'
--      status is RETAINED in the CHECK constraint for backward compatibility
--      with any existing data; the application layer treats both 'deleted'
--      and 'archived' as terminal (authorization.ts checks both).
--
-- Transaction mode: REQUIRED (all DDL is transaction-safe).
-- Idempotent: uses IF NOT EXISTS / IF EXISTS guards throughout.
-- ============================================================================

-- ============================================================================
-- 1. Membership Lifecycle: add 'removed' status
-- ============================================================================

-- Drop the existing status CHECK constraint (created by migration 105 as
-- organization_members_status_check) and replace it with one that includes
-- 'removed'. The constraint name is auto-generated by PostgreSQL from the
-- column name, so it is consistent across environments.
ALTER TABLE organization_members DROP CONSTRAINT IF EXISTS organization_members_status_check;
ALTER TABLE organization_members ADD CONSTRAINT organization_members_status_check
  CHECK (status IN ('active', 'invited', 'suspended', 'removed'));

-- ============================================================================
-- 2. Membership Lifecycle: add audit timestamp and actor columns
-- ============================================================================

-- joined_at: when the user accepted the invitation / was added to the org.
-- Distinct from created_at (when the membership row was inserted) because
-- an invited member's row is created at invitation time but joined_at is
-- set when they accept. Backfilled from accepted_at or created_at below.
ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS joined_at TIMESTAMPTZ;

-- removed_at: when the member was removed (soft-delete timestamp).
-- Null when the membership is active, invited, or suspended.
ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS removed_at TIMESTAMPTZ;

-- removed_by: the user who performed the removal (for audit trail).
-- ON DELETE SET NULL so the audit record survives even if the remover's
-- user account is later deleted.
ALTER TABLE organization_members ADD COLUMN IF NOT EXISTS removed_by UUID
  REFERENCES users(id) ON DELETE SET NULL;

-- Backfill joined_at from accepted_at (for members who accepted an invite)
-- or created_at (for members who were directly added). This ensures every
-- existing membership row has a non-null joined_at after migration.
UPDATE organization_members
  SET joined_at = COALESCE(accepted_at, created_at)
  WHERE joined_at IS NULL;

-- ============================================================================
-- 3. Membership Lifecycle: index for removed-member audit queries
-- ============================================================================

-- Partial index for finding removed members of an org (audit, compliance,
-- re-add checks). Only indexes rows with status = 'removed', keeping the
-- index small and efficient.
CREATE INDEX IF NOT EXISTS idx_organization_members_org_removed
  ON organization_members (organization_id)
  WHERE status = 'removed';

-- ============================================================================
-- 4. Organization Lifecycle: add 'archived' status
-- ============================================================================

-- Drop the existing status CHECK constraint (created by migration 105 as
-- organizations_status_check) and replace it with one that includes
-- 'archived'. The legacy 'deleted' status is RETAINED for backward
-- compatibility with any existing data rows that use it. The application
-- layer treats both 'deleted' and 'archived' as terminal org states.
ALTER TABLE organizations DROP CONSTRAINT IF EXISTS organizations_status_check;
ALTER TABLE organizations ADD CONSTRAINT organizations_status_check
  CHECK (status IN ('active', 'suspended', 'deleted', 'archived'));

-- ============================================================================
-- 5. Organization Lifecycle: add archived_at timestamp
-- ============================================================================

-- archived_at: when the org was archived (soft-delete timestamp).
-- Null when the org is active or suspended.
-- Note: The legacy deleted_at column from migration 105 is retained for
-- backward compatibility. New archive operations should set both
-- archived_at and status = 'archived'. The application layer may also
-- set deleted_at for dual-write compatibility during the transition.
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS archived_at TIMESTAMPTZ;

-- ============================================================================
-- 6. Summary
-- ============================================================================
-- Membership lifecycle corrections:
--   - organization_members.status now accepts 'removed' (4 statuses total)
--   - New columns: joined_at, removed_at, removed_by
--   - New index: idx_organization_members_org_removed (partial, status='removed')
--   - Backfilled joined_at from accepted_at or created_at
--
-- Organization lifecycle corrections:
--   - organizations.status now accepts 'archived' (4 statuses total, 'deleted' retained)
--   - New column: archived_at
--   - Legacy deleted_at column retained for backward compatibility
--
-- Application-layer changes (in lib/organizations/):
--   - removeMember() now soft-deletes (status='removed') instead of hard DELETE
--   - addMember() reactivates removed members instead of returning ALREADY_MEMBER
--   - getOrganization() excludes both 'deleted' and 'archived' orgs
--   - authorization.ts already checks both 'archived' and 'deleted' (no change needed)
