
[program:8090_python3]
command=/bin/bash -c "source ~/.bashrc 2>/dev/null; exec python3 -m http.server 8090"
directory=/workspace
user=root
autostart=true
autorestart=true
startsecs=3
startretries=3
stderr_logfile=/var/log/supervisor/8090_python3.err.log
stdout_logfile=/var/log/supervisor/8090_python3.out.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=2


[program:8099_python3]
command=/bin/bash -c "source ~/.bashrc 2>/dev/null; exec python3 -m http.server 8099"
directory=/workspace
user=root
autostart=true
autorestart=true
startsecs=3
startretries=3
stderr_logfile=/var/log/supervisor/8099_python3.err.log
stdout_logfile=/var/log/supervisor/8099_python3.out.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=2
stderr_logfile_maxbytes=5MB
stderr_logfile_backups=2

