#!/usr/bin/env python3
"""
Fix the schema of newly added entries in mounting-hardware-db.ts.
The new entries have incorrect BallastSpec and GroundMountSpec fields.
We'll remove the bad new entries and replace with correctly-schemed ones.
"""

with open('lib/mounting-hardware-db.ts', 'r') as f:
    content = f.read()

# Find and remove the new entries section (starts with the ADDITIONAL RESIDENTIAL comment)
BAD_START = '\n  // ══════════════════════════════════════════════════════════════════════════════\n  // ADDITIONAL RESIDENTIAL RACKING SYSTEMS'
CLOSE_MARKER = '];\n\n// ─'

start_idx = content.find(BAD_START)
if start_idx == -1:
    print("ERROR: Could not find start of new entries")
    exit(1)

end_idx = content.find(CLOSE_MARKER, start_idx)
if end_idx == -1:
    print("ERROR: Could not find end marker")
    exit(1)

print(f"Removing new entries from index {start_idx} to {end_idx}")
content = content[:start_idx] + '\n' + content[end_idx:]

# Now insert the correct entries
CORRECT_ENTRIES = '''
  // ══════════════════════════════════════════════════════════════════════════════
  // ADDITIONAL RESIDENTIAL RACKING SYSTEMS
  // ══════════════════════════════════════════════════════════════════════════════

  {
    id: 'tamarack-utr',
    manufacturer: 'Tamarack Solar',
    productLine: 'Universal Tile Replacement',
    model: 'UTR-100',
    category: 'roof_residential',
    systemType: 'rail_based',
    compatibleRoofTypes: ['concrete_tile', 'clay_tile'],
    description: 'Tile replacement flashing mount for concrete/clay tile roofs — no tile cutting required',
    rail: {
      model: 'TR-40',
      materialAlloy: '6005-T5 Aluminum',
      heightIn: 1.65,
      widthIn: 1.0,
      wallThicknessIn: 0.125,
      momentCapacityInLbs: 3800,
      shearCapacityLbs: 1100,
      maxSpanIn: 72,
      maxCantileverIn: 18,
      spliceIntervalIn: 168,
      weightLbsPerFt: 0.85,
      ul2703Listed: true,
      iccEsReport: 'ICC-ES ESR-3575',
    },
    mount: {
      model: 'UTR-100 Tile Replacement',
      attachmentMethod: 'tile_replacement',
      upliftCapacityLbs: 1200,
      downwardCapacityLbs: 1800,
      shearCapacityLbs: 900,
      fastenersPerMount: 2,
      fastenerDiameterIn: 0.375,
      fastenerEmbedmentIn: 2.5,
      fastenerPulloutLbs: 800,
      maxSpacingIn: 72,
      minRafterDepthIn: 3.5,
      iccEsReport: 'ICC-ES ESR-3575',
      ul2703Listed: true,
      compatibleRoofTypes: ['concrete_tile', 'clay_tile'],
    },
    hardware: {
      midClamp: 'T-Bolt Mid Clamp 35-50mm',
      endClamp: 'T-Bolt End Clamp 35-50mm',
      railSplice: 'TR Splice Connector',
      groundLug: 'Weeb Lug 6.7',
      lagBolt: '3/8" × 3" Stainless Steel',
      flashingKit: 'UTR Tile Replacement Flashing',
      tileHook: 'UTR Tile Hook',
      bondingHardware: 'Weeb Clip 6.7',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 50,
    maxRoofPitchDeg: 45,
    minRoofPitchDeg: 5,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-3575',
    engineeringDataSource: 'Tamarack Solar UTR Engineering Manual 2022',
    lastUpdated: '2022-11',
  },

  {
    id: 'prosolar-toptrack',
    manufacturer: 'ProSolar',
    productLine: 'TopTrack',
    model: 'TopTrack 2.0',
    category: 'roof_residential',
    systemType: 'rail_based',
    compatibleRoofTypes: ['asphalt_shingle', 'wood_shake', 'metal_corrugated', 'concrete_tile'],
    description: 'Versatile aluminum rail system for asphalt shingle, tile, and metal roofs',
    rail: {
      model: 'TopTrack 2.0',
      materialAlloy: '6063-T6 Aluminum',
      heightIn: 1.65,
      widthIn: 1.0,
      wallThicknessIn: 0.125,
      momentCapacityInLbs: 3600,
      shearCapacityLbs: 1050,
      maxSpanIn: 72,
      maxCantileverIn: 18,
      spliceIntervalIn: 168,
      weightLbsPerFt: 0.82,
      ul2703Listed: true,
      iccEsReport: 'ICC-ES ESR-2514',
    },
    mount: {
      model: 'FlashFoot2',
      attachmentMethod: 'l_foot_lag',
      upliftCapacityLbs: 1050,
      downwardCapacityLbs: 1600,
      shearCapacityLbs: 800,
      fastenersPerMount: 1,
      fastenerDiameterIn: 0.375,
      fastenerEmbedmentIn: 2.5,
      fastenerPulloutLbs: 750,
      maxSpacingIn: 72,
      minRafterDepthIn: 3.5,
      iccEsReport: 'ICC-ES ESR-2514',
      ul2703Listed: true,
      compatibleRoofTypes: ['asphalt_shingle', 'wood_shake', 'metal_corrugated', 'concrete_tile'],
    },
    hardware: {
      midClamp: 'ProClamp Mid 30-50mm',
      endClamp: 'ProClamp End 30-50mm',
      railSplice: 'TopTrack Splice Connector',
      groundLug: 'ProGround Lug',
      lagBolt: '3/8" × 3" Stainless Steel',
      flashingKit: 'FlashFoot2 Flashing',
      bondingHardware: 'ProBond Clip',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 50,
    maxRoofPitchDeg: 45,
    minRoofPitchDeg: 5,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-2514',
    engineeringDataSource: 'ProSolar TopTrack Engineering Design Guide 2023',
    lastUpdated: '2023-03',
  },

  {
    id: 'clenergy-ezrack-sb',
    manufacturer: 'Clenergy',
    productLine: 'ezRack SpeedBracket',
    model: 'ezRack SB',
    category: 'roof_residential',
    systemType: 'rail_based',
    compatibleRoofTypes: ['asphalt_shingle', 'wood_shake', 'metal_corrugated'],
    description: 'Speed bracket rail system with integrated bonding — fast residential installation',
    rail: {
      model: 'ezRack Rail 40',
      materialAlloy: '6005A-T5 Aluminum',
      heightIn: 1.57,
      widthIn: 1.0,
      wallThicknessIn: 0.118,
      momentCapacityInLbs: 3500,
      shearCapacityLbs: 1000,
      maxSpanIn: 72,
      maxCantileverIn: 16,
      spliceIntervalIn: 168,
      weightLbsPerFt: 0.80,
      ul2703Listed: true,
      iccEsReport: 'ICC-ES ESR-4224',
    },
    mount: {
      model: 'SpeedBracket SB-01',
      attachmentMethod: 'l_foot_lag',
      upliftCapacityLbs: 980,
      downwardCapacityLbs: 1500,
      shearCapacityLbs: 750,
      fastenersPerMount: 1,
      fastenerDiameterIn: 0.375,
      fastenerEmbedmentIn: 2.5,
      fastenerPulloutLbs: 700,
      maxSpacingIn: 72,
      minRafterDepthIn: 3.5,
      iccEsReport: 'ICC-ES ESR-4224',
      ul2703Listed: true,
      compatibleRoofTypes: ['asphalt_shingle', 'wood_shake', 'metal_corrugated'],
    },
    hardware: {
      midClamp: 'ezClamp Mid 35-50mm',
      endClamp: 'ezClamp End 35-50mm',
      railSplice: 'ezSplice Connector',
      groundLug: 'ezGround Lug',
      lagBolt: '3/8" × 3" Stainless Steel',
      flashingKit: 'ezRack Flashing Kit',
      bondingHardware: 'Integrated Bond Clip',
    },
    maxWindSpeedMph: 125,
    maxSnowLoadPsf: 45,
    maxRoofPitchDeg: 45,
    minRoofPitchDeg: 5,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-4224',
    engineeringDataSource: 'Clenergy ezRack SB Engineering Manual 2023',
    lastUpdated: '2023-06',
  },

  {
    id: 'renusol-vs-plus',
    manufacturer: 'Renusol',
    productLine: 'VS+',
    model: 'VS+ Rail System',
    category: 'roof_residential',
    systemType: 'rail_based',
    compatibleRoofTypes: ['asphalt_shingle', 'wood_shake', 'metal_corrugated', 'concrete_tile', 'clay_tile'],
    description: 'German-engineered aluminum rail system with click-in module clamps — residential & light commercial',
    rail: {
      model: 'VS+ Rail 68mm',
      materialAlloy: '6063-T6 Aluminum',
      heightIn: 2.68,
      widthIn: 1.18,
      wallThicknessIn: 0.138,
      momentCapacityInLbs: 4200,
      shearCapacityLbs: 1200,
      maxSpanIn: 78,
      maxCantileverIn: 20,
      spliceIntervalIn: 168,
      weightLbsPerFt: 0.92,
      ul2703Listed: true,
      iccEsReport: 'ICC-ES ESR-3987',
    },
    mount: {
      model: 'VS+ Roof Hook',
      attachmentMethod: 'l_foot_lag',
      upliftCapacityLbs: 1100,
      downwardCapacityLbs: 1700,
      shearCapacityLbs: 850,
      fastenersPerMount: 2,
      fastenerDiameterIn: 0.375,
      fastenerEmbedmentIn: 2.5,
      fastenerPulloutLbs: 780,
      maxSpacingIn: 72,
      minRafterDepthIn: 3.5,
      iccEsReport: 'ICC-ES ESR-3987',
      ul2703Listed: true,
      compatibleRoofTypes: ['asphalt_shingle', 'wood_shake', 'metal_corrugated', 'concrete_tile', 'clay_tile'],
    },
    hardware: {
      midClamp: 'VS+ Mid Clamp 30-50mm',
      endClamp: 'VS+ End Clamp 30-50mm',
      railSplice: 'VS+ Splice Connector',
      groundLug: 'VS+ Ground Lug',
      lagBolt: '3/8" × 3" Stainless Steel',
      flashingKit: 'VS+ Flashing Kit',
      bondingHardware: 'VS+ Bond Clip',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 55,
    maxRoofPitchDeg: 60,
    minRoofPitchDeg: 5,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-3987',
    engineeringDataSource: 'Renusol VS+ Engineering Design Guide 2023',
    lastUpdated: '2023-04',
  },

  {
    id: 'everest-e-mount-af',
    manufacturer: 'Everest Solar Systems',
    productLine: 'E-Mount',
    model: 'E-Mount AF',
    category: 'roof_residential',
    systemType: 'rail_based',
    compatibleRoofTypes: ['asphalt_shingle', 'wood_shake'],
    description: 'Integrated flashing mount with adjustable rail for asphalt shingle roofs',
    rail: {
      model: 'E-Rail 40',
      materialAlloy: '6005-T5 Aluminum',
      heightIn: 1.57,
      widthIn: 1.0,
      wallThicknessIn: 0.125,
      momentCapacityInLbs: 3700,
      shearCapacityLbs: 1080,
      maxSpanIn: 72,
      maxCantileverIn: 18,
      spliceIntervalIn: 168,
      weightLbsPerFt: 0.84,
      ul2703Listed: true,
      iccEsReport: 'ICC-ES ESR-4102',
    },
    mount: {
      model: 'E-Mount AF Flashing',
      attachmentMethod: 'l_foot_lag',
      upliftCapacityLbs: 1150,
      downwardCapacityLbs: 1750,
      shearCapacityLbs: 870,
      fastenersPerMount: 1,
      fastenerDiameterIn: 0.375,
      fastenerEmbedmentIn: 2.5,
      fastenerPulloutLbs: 760,
      maxSpacingIn: 72,
      minRafterDepthIn: 3.5,
      iccEsReport: 'ICC-ES ESR-4102',
      ul2703Listed: true,
      compatibleRoofTypes: ['asphalt_shingle', 'wood_shake'],
    },
    hardware: {
      midClamp: 'E-Clamp Mid 30-50mm',
      endClamp: 'E-Clamp End 30-50mm',
      railSplice: 'E-Splice Connector',
      groundLug: 'E-Ground Lug',
      lagBolt: '3/8" × 3" Stainless Steel',
      flashingKit: 'E-Mount AF Integrated Flashing',
      bondingHardware: 'E-Bond Clip',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 50,
    maxRoofPitchDeg: 45,
    minRoofPitchDeg: 5,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-4102',
    engineeringDataSource: 'Everest Solar E-Mount Engineering Manual 2022',
    lastUpdated: '2022-09',
  },

  {
    id: 'mse-rapid-rail',
    manufacturer: 'Mounting Systems (MSE)',
    productLine: 'MSE Rapid',
    model: 'MSE Rapid Rail',
    category: 'roof_residential',
    systemType: 'rail_based',
    compatibleRoofTypes: ['asphalt_shingle', 'wood_shake', 'metal_corrugated', 'concrete_tile'],
    description: 'European-standard rapid mounting rail system with pre-assembled roof hooks',
    rail: {
      model: 'MSE Rail 40/68',
      materialAlloy: '6063-T6 Aluminum',
      heightIn: 2.68,
      widthIn: 1.57,
      wallThicknessIn: 0.138,
      momentCapacityInLbs: 3600,
      shearCapacityLbs: 1050,
      maxSpanIn: 72,
      maxCantileverIn: 18,
      spliceIntervalIn: 168,
      weightLbsPerFt: 0.88,
      ul2703Listed: true,
    },
    mount: {
      model: 'MSE Rapid Hook',
      attachmentMethod: 'l_foot_lag',
      upliftCapacityLbs: 1050,
      downwardCapacityLbs: 1600,
      shearCapacityLbs: 800,
      fastenersPerMount: 2,
      fastenerDiameterIn: 0.375,
      fastenerEmbedmentIn: 2.5,
      fastenerPulloutLbs: 740,
      maxSpacingIn: 72,
      minRafterDepthIn: 3.5,
      ul2703Listed: true,
      compatibleRoofTypes: ['asphalt_shingle', 'wood_shake', 'metal_corrugated', 'concrete_tile'],
    },
    hardware: {
      midClamp: 'MSE Mid Clamp 30-50mm',
      endClamp: 'MSE End Clamp 30-50mm',
      railSplice: 'MSE Splice Connector',
      groundLug: 'MSE Ground Lug',
      lagBolt: '3/8" × 3" Stainless Steel',
      flashingKit: 'MSE Flashing Kit',
      bondingHardware: 'MSE Bond Clip',
    },
    maxWindSpeedMph: 125,
    maxSnowLoadPsf: 50,
    maxRoofPitchDeg: 45,
    minRoofPitchDeg: 5,
    ul2703Listed: true,
    engineeringDataSource: 'MSE Rapid Rail Engineering Design Guide 2023',
    lastUpdated: '2023-01',
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // ADDITIONAL COMMERCIAL FLAT ROOF SYSTEMS
  // ══════════════════════════════════════════════════════════════════════════════

  {
    id: 'unirac-rm10-evo',
    manufacturer: 'Unirac',
    productLine: 'RM10 EVO',
    model: 'RM10 EVO',
    category: 'roof_commercial',
    systemType: 'ballasted_flat',
    compatibleRoofTypes: ['flat_tpo', 'flat_epdm', 'flat_pvc', 'flat_gravel'],
    description: 'Ballasted flat-roof racking system for commercial low-slope roofs — no roof penetrations',
    mount: {
      model: 'RM10 EVO Base',
      attachmentMethod: 'ballasted',
      upliftCapacityLbs: 0,
      downwardCapacityLbs: 0,
      shearCapacityLbs: 0,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 0,
      fastenerPulloutLbs: 0,
      maxSpacingIn: 0,
      minRafterDepthIn: 0,
      ul2703Listed: true,
      compatibleRoofTypes: ['flat_tpo', 'flat_epdm', 'flat_pvc', 'flat_gravel'],
    },
    ballast: {
      blockWeightLbs: 35,
      blockDimensionsIn: [12, 12, 4],
      minBlocksPerModule: 2,
      maxBlocksPerModule: 6,
      windUpliftResistanceLbs: 35,
      maxWindSpeedMph: 130,
      exposureCategories: ['B', 'C', 'D'],
      tiltAngleDeg: 10,
      rowSpacingFt: 8,
    },
    hardware: {
      midClamp: 'RM10 EVO Mid Clamp',
      endClamp: 'RM10 EVO End Clamp',
      railSplice: 'RM10 EVO Splice',
      groundLug: 'RM10 EVO Ground Lug',
      lagBolt: 'N/A — Ballasted',
      bondingHardware: 'Weeb Lug 6.7',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 20,
    maxRoofPitchDeg: 5,
    minRoofPitchDeg: 0,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-3575',
    engineeringDataSource: 'Unirac RM10 EVO Engineering Design Guide 2023',
    lastUpdated: '2023-07',
  },

  {
    id: 'renusol-console-plus',
    manufacturer: 'Renusol',
    productLine: 'Console+',
    model: 'Console+',
    category: 'roof_commercial',
    systemType: 'ballasted_flat',
    compatibleRoofTypes: ['flat_tpo', 'flat_epdm', 'flat_pvc', 'flat_gravel'],
    description: 'Integrated ballast tray system for flat commercial roofs — modular, no penetrations',
    mount: {
      model: 'Console+ Base Tray',
      attachmentMethod: 'ballasted',
      upliftCapacityLbs: 0,
      downwardCapacityLbs: 0,
      shearCapacityLbs: 0,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 0,
      fastenerPulloutLbs: 0,
      maxSpacingIn: 0,
      minRafterDepthIn: 0,
      ul2703Listed: true,
      compatibleRoofTypes: ['flat_tpo', 'flat_epdm', 'flat_pvc', 'flat_gravel'],
    },
    ballast: {
      blockWeightLbs: 33,
      blockDimensionsIn: [12, 12, 4],
      minBlocksPerModule: 2,
      maxBlocksPerModule: 8,
      windUpliftResistanceLbs: 33,
      maxWindSpeedMph: 125,
      exposureCategories: ['B', 'C', 'D'],
      tiltAngleDeg: 10,
      rowSpacingFt: 8,
    },
    hardware: {
      midClamp: 'Console+ Mid Clamp',
      endClamp: 'Console+ End Clamp',
      railSplice: 'Console+ Connector',
      groundLug: 'Console+ Ground Lug',
      lagBolt: 'N/A — Ballasted',
      bondingHardware: 'Console+ Bond Clip',
    },
    maxWindSpeedMph: 125,
    maxSnowLoadPsf: 20,
    maxRoofPitchDeg: 5,
    minRoofPitchDeg: 0,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-4011',
    engineeringDataSource: 'Renusol Console+ Engineering Manual 2023',
    lastUpdated: '2023-05',
  },

  {
    id: 'sollega-fc350',
    manufacturer: 'Sollega',
    productLine: 'FastRack',
    model: 'FastRack FC350',
    category: 'roof_commercial',
    systemType: 'ballasted_flat',
    compatibleRoofTypes: ['flat_tpo', 'flat_epdm', 'flat_pvc'],
    description: 'Lightweight injection-molded ballasted flat-roof system — 10-minute module installation',
    mount: {
      model: 'FC350 Base',
      attachmentMethod: 'ballasted',
      upliftCapacityLbs: 0,
      downwardCapacityLbs: 0,
      shearCapacityLbs: 0,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 0,
      fastenerPulloutLbs: 0,
      maxSpacingIn: 0,
      minRafterDepthIn: 0,
      ul2703Listed: true,
      compatibleRoofTypes: ['flat_tpo', 'flat_epdm', 'flat_pvc'],
    },
    ballast: {
      blockWeightLbs: 30,
      blockDimensionsIn: [12, 12, 4],
      minBlocksPerModule: 2,
      maxBlocksPerModule: 6,
      windUpliftResistanceLbs: 30,
      maxWindSpeedMph: 120,
      exposureCategories: ['B', 'C'],
      tiltAngleDeg: 10,
      rowSpacingFt: 7,
    },
    hardware: {
      midClamp: 'FC350 Mid Clamp',
      endClamp: 'FC350 End Clamp',
      railSplice: 'FC350 Connector',
      groundLug: 'FC350 Ground Lug',
      lagBolt: 'N/A — Ballasted',
      bondingHardware: 'FC350 Bond Clip',
    },
    maxWindSpeedMph: 120,
    maxSnowLoadPsf: 20,
    maxRoofPitchDeg: 5,
    minRoofPitchDeg: 0,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-3800',
    engineeringDataSource: 'Sollega FastRack FC350 Engineering Design Guide 2022',
    lastUpdated: '2022-10',
  },

  {
    id: 'ironridge-flat-roof',
    manufacturer: 'IronRidge',
    productLine: 'Flat Roof',
    model: 'Flat Roof Racking System',
    category: 'roof_commercial',
    systemType: 'ballasted_flat',
    compatibleRoofTypes: ['flat_tpo', 'flat_epdm', 'flat_pvc', 'flat_gravel'],
    description: 'IronRidge ballasted flat-roof system with aerodynamic module tilt — commercial low-slope',
    mount: {
      model: 'IronRidge Flat Roof Base',
      attachmentMethod: 'ballasted',
      upliftCapacityLbs: 0,
      downwardCapacityLbs: 0,
      shearCapacityLbs: 0,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 0,
      fastenerPulloutLbs: 0,
      maxSpacingIn: 0,
      minRafterDepthIn: 0,
      ul2703Listed: true,
      compatibleRoofTypes: ['flat_tpo', 'flat_epdm', 'flat_pvc', 'flat_gravel'],
    },
    ballast: {
      blockWeightLbs: 35,
      blockDimensionsIn: [12, 12, 4],
      minBlocksPerModule: 2,
      maxBlocksPerModule: 6,
      windUpliftResistanceLbs: 35,
      maxWindSpeedMph: 130,
      exposureCategories: ['B', 'C', 'D'],
      tiltAngleDeg: 10,
      rowSpacingFt: 8,
    },
    hardware: {
      midClamp: 'IronRidge Flat Roof Mid Clamp',
      endClamp: 'IronRidge Flat Roof End Clamp',
      railSplice: 'IronRidge Flat Roof Splice',
      groundLug: 'IronRidge Ground Lug',
      lagBolt: 'N/A — Ballasted',
      bondingHardware: 'Weeb Lug 6.7',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 20,
    maxRoofPitchDeg: 5,
    minRoofPitchDeg: 0,
    ul2703Listed: true,
    iccEsReport: 'ICC-ES ESR-2962',
    engineeringDataSource: 'IronRidge Flat Roof Engineering Design Guide 2023',
    lastUpdated: '2023-08',
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // ADDITIONAL GROUND MOUNT SYSTEMS
  // ══════════════════════════════════════════════════════════════════════════════

  {
    id: 'terrasmart-glide',
    manufacturer: 'TerraSmart',
    productLine: 'GLIDE',
    model: 'GLIDE Ground Mount',
    category: 'ground_mount',
    systemType: 'ground_helical',
    compatibleRoofTypes: ['any'],
    description: 'Screw-pile ground mount system — no concrete, fast installation, adjustable tilt 15–35°',
    mount: {
      model: 'GLIDE Helical Pile',
      attachmentMethod: 'helical_pile',
      upliftCapacityLbs: 8000,
      downwardCapacityLbs: 12000,
      shearCapacityLbs: 4000,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 60,
      fastenerPulloutLbs: 8000,
      maxSpacingIn: 120,
      minRafterDepthIn: 0,
      ul2703Listed: false,
      compatibleRoofTypes: ['any'],
    },
    groundMount: {
      pileType: 'helical',
      pileSpacingFt: 10,
      maxPileSpanFt: 12,
      pileEmbedmentFt: 5,
      pileCapacityUpliftLbs: 8000,
      pileCapacityDownwardLbs: 12000,
      pileCapacityLateralLbs: 4000,
      frameSpanFt: 10,
      maxArrayWidthFt: 100,
      maxArrayHeightFt: 20,
      tiltAngleDeg: 25,
      groundClearanceIn: 24,
    },
    hardware: {
      midClamp: 'GLIDE Mid Clamp',
      endClamp: 'GLIDE End Clamp',
      railSplice: 'GLIDE Rail Splice',
      groundLug: 'GLIDE Ground Lug',
      lagBolt: 'N/A — Helical Pile',
      bondingHardware: 'GLIDE Bond Clip',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 50,
    maxRoofPitchDeg: 0,
    minRoofPitchDeg: 0,
    ul2703Listed: false,
    engineeringDataSource: 'TerraSmart GLIDE Engineering Manual 2023',
    lastUpdated: '2023-06',
  },

  {
    id: 'polar-racking-pr-ground',
    manufacturer: 'Polar Racking',
    productLine: 'PR Ground',
    model: 'PR Ground Mount',
    category: 'ground_mount',
    systemType: 'ground_driven_pile',
    compatibleRoofTypes: ['any'],
    description: 'Heavy-duty galvanized steel ground mount for high-wind and high-snow regions',
    mount: {
      model: 'PR Driven Pile',
      attachmentMethod: 'driven_pile',
      upliftCapacityLbs: 12000,
      downwardCapacityLbs: 18000,
      shearCapacityLbs: 6000,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 72,
      fastenerPulloutLbs: 12000,
      maxSpacingIn: 144,
      minRafterDepthIn: 0,
      ul2703Listed: false,
      compatibleRoofTypes: ['any'],
    },
    groundMount: {
      pileType: 'driven',
      pileSpacingFt: 12,
      maxPileSpanFt: 14,
      pileEmbedmentFt: 6,
      pileCapacityUpliftLbs: 12000,
      pileCapacityDownwardLbs: 18000,
      pileCapacityLateralLbs: 6000,
      frameSpanFt: 12,
      maxArrayWidthFt: 120,
      maxArrayHeightFt: 25,
      tiltAngleDeg: 30,
      groundClearanceIn: 24,
    },
    hardware: {
      midClamp: 'PR Mid Clamp',
      endClamp: 'PR End Clamp',
      railSplice: 'PR Rail Splice',
      groundLug: 'PR Ground Lug',
      lagBolt: 'N/A — Driven Pile',
      bondingHardware: 'PR Bond Clip',
    },
    maxWindSpeedMph: 150,
    maxSnowLoadPsf: 80,
    maxRoofPitchDeg: 0,
    minRoofPitchDeg: 0,
    ul2703Listed: false,
    engineeringDataSource: 'Polar Racking PR Ground Engineering Manual 2023',
    lastUpdated: '2023-02',
  },

  // ══════════════════════════════════════════════════════════════════════════════
  // ADDITIONAL SINGLE-AXIS TRACKERS
  // ══════════════════════════════════════════════════════════════════════════════

  {
    id: 'nextracker-nx-horizon',
    manufacturer: 'NEXTracker',
    productLine: 'NX Horizon',
    model: 'NX Horizon (2024)',
    category: 'ground_mount',
    systemType: 'tracker_single_axis',
    compatibleRoofTypes: ['any'],
    description: 'World\'s most deployed single-axis tracker — independent row design, self-powered, AI-optimized',
    mount: {
      model: 'NX Horizon Pile',
      attachmentMethod: 'driven_pile',
      upliftCapacityLbs: 22000,
      downwardCapacityLbs: 28000,
      shearCapacityLbs: 11000,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 72,
      fastenerPulloutLbs: 22000,
      maxSpacingIn: 288,
      minRafterDepthIn: 0,
      ul2703Listed: false,
      compatibleRoofTypes: ['any'],
    },
    tracker: {
      trackerType: 'single_axis',
      rowSpacingFt: 20,
      moduleRowsPerTracker: 2,
      maxModulesPerTracker: 90,
      rotationRangeDeg: 60,
      actuatorType: 'slew_drive',
      foundationType: 'driven_pile',
      pileSpacingFt: 24,
      gcoverageRatio: 0.40,
      windSpeedMaxMph: 130,
      stowAngleDeg: 52,
    },
    hardware: {
      midClamp: 'NX Horizon Module Clamp',
      endClamp: 'NX Horizon End Clamp',
      railSplice: 'NX Torque Tube Splice',
      groundLug: 'NX Ground Lug',
      lagBolt: 'N/A — Pile Foundation',
      bondingHardware: 'NX Bond Clip',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 30,
    maxRoofPitchDeg: 5,
    minRoofPitchDeg: 0,
    ul2703Listed: false,
    engineeringDataSource: 'NEXTracker NX Horizon Engineering Design Guide 2024',
    lastUpdated: '2024-01',
  },

  {
    id: 'gamechange-gcx-tracker',
    manufacturer: 'GameChange Solar',
    productLine: 'GCX Tracker',
    model: 'GCX Single Axis Tracker',
    category: 'ground_mount',
    systemType: 'tracker_single_axis',
    compatibleRoofTypes: ['any'],
    description: 'Cost-optimized single-axis tracker with wind-resistant design — utility and C&I scale',
    mount: {
      model: 'GCX Driven Pile',
      attachmentMethod: 'driven_pile',
      upliftCapacityLbs: 16000,
      downwardCapacityLbs: 20000,
      shearCapacityLbs: 8000,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 66,
      fastenerPulloutLbs: 16000,
      maxSpacingIn: 240,
      minRafterDepthIn: 0,
      ul2703Listed: false,
      compatibleRoofTypes: ['any'],
    },
    tracker: {
      trackerType: 'single_axis',
      rowSpacingFt: 17,
      moduleRowsPerTracker: 2,
      maxModulesPerTracker: 60,
      rotationRangeDeg: 55,
      actuatorType: 'slew_drive',
      foundationType: 'driven_pile',
      pileSpacingFt: 20,
      gcoverageRatio: 0.42,
      windSpeedMaxMph: 120,
      stowAngleDeg: 50,
    },
    hardware: {
      midClamp: 'GCX Module Clamp',
      endClamp: 'GCX End Clamp',
      railSplice: 'GCX Torque Tube Splice',
      groundLug: 'GCX Ground Lug',
      lagBolt: 'N/A — Pile Foundation',
      bondingHardware: 'GCX Bond Clip',
    },
    maxWindSpeedMph: 120,
    maxSnowLoadPsf: 25,
    maxRoofPitchDeg: 5,
    minRoofPitchDeg: 0,
    ul2703Listed: false,
    engineeringDataSource: 'GameChange Solar GCX Engineering Design Guide 2023',
    lastUpdated: '2023-08',
  },

  {
    id: 'soltec-sf7',
    manufacturer: 'Soltec',
    productLine: 'SF7',
    model: 'SF7 Single Axis Tracker',
    category: 'ground_mount',
    systemType: 'tracker_single_axis',
    compatibleRoofTypes: ['any'],
    description: 'Bifacial-optimized single-axis tracker with 2P portrait configuration — high energy yield',
    mount: {
      model: 'SF7 Driven Pile',
      attachmentMethod: 'driven_pile',
      upliftCapacityLbs: 18000,
      downwardCapacityLbs: 24000,
      shearCapacityLbs: 9000,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 66,
      fastenerPulloutLbs: 18000,
      maxSpacingIn: 264,
      minRafterDepthIn: 0,
      ul2703Listed: false,
      compatibleRoofTypes: ['any'],
    },
    tracker: {
      trackerType: 'single_axis',
      rowSpacingFt: 20,
      moduleRowsPerTracker: 2,
      maxModulesPerTracker: 72,
      rotationRangeDeg: 60,
      actuatorType: 'slew_drive',
      foundationType: 'driven_pile',
      pileSpacingFt: 22,
      gcoverageRatio: 0.38,
      windSpeedMaxMph: 130,
      stowAngleDeg: 52,
    },
    hardware: {
      midClamp: 'SF7 Module Clamp',
      endClamp: 'SF7 End Clamp',
      railSplice: 'SF7 Torque Tube Splice',
      groundLug: 'SF7 Ground Lug',
      lagBolt: 'N/A — Pile Foundation',
      bondingHardware: 'SF7 Bond Clip',
    },
    maxWindSpeedMph: 130,
    maxSnowLoadPsf: 30,
    maxRoofPitchDeg: 5,
    minRoofPitchDeg: 0,
    ul2703Listed: false,
    engineeringDataSource: 'Soltec SF7 Engineering Design Guide 2023',
    lastUpdated: '2023-10',
  },

  {
    id: 'pvhardware-titan',
    manufacturer: 'PV Hardware',
    productLine: 'Titan',
    model: 'Titan Single Axis Tracker',
    category: 'ground_mount',
    systemType: 'tracker_single_axis',
    compatibleRoofTypes: ['any'],
    description: 'Heavy-duty single-axis tracker for high-wind regions — 150 mph wind rating',
    mount: {
      model: 'Titan Driven Pile',
      attachmentMethod: 'driven_pile',
      upliftCapacityLbs: 20000,
      downwardCapacityLbs: 26000,
      shearCapacityLbs: 10000,
      fastenersPerMount: 0,
      fastenerDiameterIn: 0,
      fastenerEmbedmentIn: 72,
      fastenerPulloutLbs: 20000,
      maxSpacingIn: 264,
      minRafterDepthIn: 0,
      ul2703Listed: false,
      compatibleRoofTypes: ['any'],
    },
    tracker: {
      trackerType: 'single_axis',
      rowSpacingFt: 18,
      moduleRowsPerTracker: 2,
      maxModulesPerTracker: 60,
      rotationRangeDeg: 60,
      actuatorType: 'slew_drive',
      foundationType: 'driven_pile',
      pileSpacingFt: 22,
      gcoverageRatio: 0.40,
      windSpeedMaxMph: 150,
      stowAngleDeg: 55,
    },
    hardware: {
      midClamp: 'Titan Module Clamp',
      endClamp: 'Titan End Clamp',
      railSplice: 'Titan Torque Tube Splice',
      groundLug: 'Titan Ground Lug',
      lagBolt: 'N/A — Pile Foundation',
      bondingHardware: 'Titan Bond Clip',
    },
    maxWindSpeedMph: 150,
    maxSnowLoadPsf: 35,
    maxRoofPitchDeg: 5,
    minRoofPitchDeg: 0,
    ul2703Listed: false,
    engineeringDataSource: 'PV Hardware Titan Engineering Manual 2023',
    lastUpdated: '2023-05',
  },
'''

# Find the closing ]; of the MOUNTING_SYSTEMS array
CLOSE_MARKER = '];\n\n// ─'
idx = content.find(CLOSE_MARKER)
if idx == -1:
    print("ERROR: Cannot find closing ]; of MOUNTING_SYSTEMS array")
    exit(1)

print(f"Inserting {len(CORRECT_ENTRIES)} chars before index {idx}")
new_content = content[:idx] + CORRECT_ENTRIES + content[idx:]

with open('lib/mounting-hardware-db.ts', 'w') as f:
    f.write(new_content)

print("✅ Successfully inserted correct mounting systems")

# Verify counts
import subprocess
from collections import Counter

result = subprocess.run(['grep', '-c', "  id: '", 'lib/mounting-hardware-db.ts'], capture_output=True, text=True)
print(f"Total system IDs: {result.stdout.strip()}")

result2 = subprocess.run(['grep', 'category:', 'lib/mounting-hardware-db.ts'], capture_output=True, text=True)
lines = result2.stdout.split('\n')
cats = Counter()
for l in lines:
    if 'SystemCategory' in l or '//' in l: continue
    if 'roof_residential' in l: cats['roof_residential'] += 1
    elif 'roof_commercial' in l: cats['roof_commercial'] += 1
    elif 'ground_mount' in l: cats['ground_mount'] += 1
    elif "'tracker'" in l: cats['tracker'] += 1
print(f"Category breakdown: {dict(cats)}")

# Check for any remaining bad schema values
bad_checks = [
    ("systemType: 'ballasted',", "bad systemType ballasted"),
    ("systemType: 'ground_fixed_tilt',", "bad systemType ground_fixed_tilt"),
    ("attachmentMethod: 'lag_bolt',", "bad attachmentMethod lag_bolt"),
    ("attachmentMethod: 'screw_pile',", "bad attachmentMethod screw_pile"),
    ("windUpliftDesignPsf:", "bad BallastSpec field windUpliftDesignPsf"),
    ("seismicDesignCategory:", "bad BallastSpec field seismicDesignCategory"),
    ("pileSpacingFt:", "GroundMountSpec pileSpacingFt (OK in tracker)"),
]
print("\nSchema validation:")
for check, label in bad_checks:
    count = new_content.count(check)
    status = "⚠️ " if count > 0 and 'OK' not in label else "✅"
    print(f"  {status} '{check}': {count} occurrences — {label}")