#!/usr/bin/env python3
"""
Patch lib/utilityDetector.ts — expand majorUtilities for all 50 states
to include electric co-ops, municipal utilities, and rural electric associations.
Also adds address auto-detect logic to engineering page.
"""

import re

UTILITY_FILE = 'lib/utilityDetector.ts'

# Full 50-state utility data with co-ops included
NEW_FALLBACK = '''export const STATE_UTILITY_FALLBACK: Record<string, {
  avgRate: number;
  commercialRate: number;
  netMetering: boolean;
  netMeteringPolicy: string;
  netMeteringMaxKw: number;
  exportRate: number;
  interconnectionMaxKw: number;
  majorUtilities: string[];
}> = {
  AL: { avgRate: 0.134, commercialRate: 0.118, netMetering: true,  netMeteringPolicy: 'Avoided cost compensation', netMeteringMaxKw: 25,   exportRate: 0.04,  interconnectionMaxKw: 25,   majorUtilities: ['Alabama Power', 'TVA', 'Joe Wheeler EMC', 'Cullman Electric Coop', 'North Alabama Electric Coop', 'Coosa Valley Electric Coop', 'Sand Mountain Electric Coop', 'Tallapoosa River Electric Coop', 'Wiregrass Electric Coop', 'Baldwin EMC', 'Clarke-Washington EMC', 'Tombigbee Electric Coop', 'Dixie Electric Coop', 'Pea River Electric Coop', 'Pioneer Electric Coop'] },
  AK: { avgRate: 0.228, commercialRate: 0.195, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.228, interconnectionMaxKw: 25,   majorUtilities: ['Chugach Electric', 'Golden Valley Electric', 'Matanuska Electric Association', 'Homer Electric Association', 'Kodiak Electric Association', 'Copper Valley Electric', 'Inside Passage Electric Coop', 'Tlingit-Haida Regional Electric Authority', 'Cordova Electric Coop', 'Naknek Electric Association'] },
  AZ: { avgRate: 0.128, commercialRate: 0.109, netMetering: true,  netMeteringPolicy: 'Excess energy at avoided cost', netMeteringMaxKw: 125,  exportRate: 0.076, interconnectionMaxKw: 125,  majorUtilities: ['APS', 'SRP', 'TEP', 'UNS Electric', 'Duncan Valley Electric Coop', 'Graham County Electric Coop', 'Sulphur Springs Valley Electric Coop', 'Trico Electric Coop', 'Navopache Electric Coop', 'Mohave Electric Coop', 'Electrical District No. 2', 'Electrical District No. 3', 'Electrical District No. 6', 'Electrical District No. 7'] },
  AR: { avgRate: 0.108, commercialRate: 0.092, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.108, interconnectionMaxKw: 25,   majorUtilities: ['Entergy Arkansas', 'SWEPCO', 'Arkansas Valley Electric Coop', 'C&L Electric Coop', 'Carroll Electric Coop', 'Clay County Electric Coop', 'Craighead Electric Coop', 'Delta Electric Power Association', 'Farmers Electric Coop', 'First Electric Coop', 'Mississippi County Electric Coop', 'Ouachita Electric Coop', 'Ozarks Electric Coop', 'Petit Jean Electric Coop', 'Rich Mountain Electric Coop', 'South Central Arkansas Electric Coop', 'Southwest Arkansas Electric Coop', 'White River Valley Electric Coop'] },
  CA: { avgRate: 0.298, commercialRate: 0.241, netMetering: true,  netMeteringPolicy: 'NEM 3.0 — export at avoided cost', netMeteringMaxKw: 1000, exportRate: 0.08,  interconnectionMaxKw: 1000, majorUtilities: ['PG&E', 'SCE', 'SDG&E', 'LADWP', 'SMUD', 'Burbank Water and Power', 'Glendale Water & Power', 'Pasadena Water and Power', 'Anaheim Public Utilities', 'Riverside Public Utilities', 'Imperial Irrigation District', 'Lodi Electric Utility', 'Redding Electric Utility', 'Roseville Electric', 'Silicon Valley Power', 'Turlock Irrigation District', 'Modesto Irrigation District', 'Trinity PUD', 'Plumas-Sierra REC', 'Valley Electric Association'] },
  CO: { avgRate: 0.138, commercialRate: 0.112, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 120,  exportRate: 0.138, interconnectionMaxKw: 120,  majorUtilities: ['Xcel Energy', 'Black Hills Energy', 'Holy Cross Energy', 'Gunnison County Electric Association', 'Delta-Montrose Electric Association', 'Empire Electric Association', 'Grand Valley Power', 'Highline Electric Association', 'K.C. Electric Association', 'La Plata Electric Association', 'Mountain Parks Electric', 'Mountain View Electric Association', 'Poudre Valley REA', 'San Isabel Electric', 'San Luis Valley REC', 'Sangre de Cristo Electric', 'Southeast Colorado Power Association', 'Tri-State G&T', 'United Power', 'White River Electric Association', 'Y-W Electric Association'] },
  CT: { avgRate: 0.248, commercialRate: 0.198, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 2000, exportRate: 0.248, interconnectionMaxKw: 2000, majorUtilities: ['Eversource', 'UI (United Illuminating)', 'Groton Utilities', 'Norwich Public Utilities', 'South Norwalk Electric Works', 'Bozrah Light & Power', 'Jewett City Department of Public Utilities'] },
  DE: { avgRate: 0.138, commercialRate: 0.118, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.138, interconnectionMaxKw: 25,   majorUtilities: ['Delmarva Power', 'Delaware Electric Coop', 'City of Dover Electric', 'Milford Electric', 'Newark Electric', 'Seaford Electric', 'Lewes Board of Public Works'] },
  FL: { avgRate: 0.138, commercialRate: 0.112, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 2000, exportRate: 0.138, interconnectionMaxKw: 2000, majorUtilities: ['FPL', 'Duke Energy Florida', 'Tampa Electric', 'Gulf Power', 'Clay Electric Coop', 'Central Florida Electric Coop', 'Choctawhatchee Electric Coop', 'Escambia River Electric Coop', 'Florida Keys Electric Coop', 'Glades Electric Coop', 'Gulf Coast Electric Coop', 'Lee County Electric Coop', 'Okefenokee REMC', 'Peace River Electric Coop', 'Seminole Electric Coop', 'Suwannee Valley Electric Coop', 'Talquin Electric Coop', 'Tri-County Electric Coop', 'Withlacoochee River Electric Coop', 'JEA', 'OUC', 'Lakeland Electric', 'Gainesville Regional Utilities'] },
  GA: { avgRate: 0.128, commercialRate: 0.108, netMetering: true,  netMeteringPolicy: 'Avoided cost compensation', netMeteringMaxKw: 10,   exportRate: 0.04,  interconnectionMaxKw: 10,   majorUtilities: ['Georgia Power', 'Cobb EMC', 'Sawnee EMC', 'Jackson EMC', 'Walton EMC', 'Snapping Shoals EMC', 'Coweta-Fayette EMC', 'Flint Energies', 'Greystone Power', 'Carroll EMC', 'Diverse Power', 'Excelsior EMC', 'Habersham EMC', 'Hart EMC', 'Jefferson Energy Coop', 'Little Ocmulgee EMC', 'Middle Georgia EMC', 'Mitchell EMC', 'Ocmulgee EMC', 'Oconee EMC', 'Okefenokee REMC', 'Planters EMC', 'Rayle EMC', 'Satilla REMC', 'Slash Pine EMC', 'Sumter EMC', 'Three Notch EMC', 'Tri-County EMC', 'GreyStone Power', 'Upson EMC', 'Withlacoochee EMC'] },
  HI: { avgRate: 0.388, commercialRate: 0.318, netMetering: true,  netMeteringPolicy: 'Customer Self-Supply (CSS)', netMeteringMaxKw: 100,  exportRate: 0.10,  interconnectionMaxKw: 100,  majorUtilities: ['Hawaiian Electric', 'KIUC (Kauai Island Utility Coop)', 'HELCO (Hawaii Electric Light)', 'Maui Electric'] },
  ID: { avgRate: 0.098, commercialRate: 0.082, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.098, interconnectionMaxKw: 25,   majorUtilities: ['Idaho Power', 'Rocky Mountain Power', 'Avista', 'Clearwater Power', 'Fall River Rural Electric Coop', 'Idaho County Light & Power', 'Lost River Electric Coop', 'Raft River Rural Electric Coop', 'Salmon River Electric Coop', 'Surprise Valley Electrification Corp', 'United Electric Coop', 'Bingham County Electric Coop', 'Kootenai Electric Coop', 'Nez Perce Electric Coop'] },
  IL: { avgRate: 0.148, commercialRate: 0.122, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 2000, exportRate: 0.148, interconnectionMaxKw: 2000, majorUtilities: ['ComEd', 'Ameren Illinois', 'MidAmerican Energy (IL)', 'Illinois Rural Electric Coop', 'Adams Electric Coop', 'Coles-Moultrie Electric Coop', 'Corn Belt Energy', 'Eastern Illini Electric Coop', 'Egyptian Electric Coop', 'Farmers Mutual Electric Coop', 'Illinois Valley Electric Coop', 'Jo-Carroll Energy', 'Kankakee Valley Electric Coop', 'McDonough Power Coop', 'Menard Electric Coop', 'Monroe County Electric Coop', 'Norris Electric Coop', 'Shelby Electric Coop', 'Southwestern Electric Coop', 'Spoon River Electric Coop', 'Tri-County Electric Coop', 'Western Illinois Electrical Coop', 'City of Naperville Electric', 'City of Rochelle Electric', 'City of Springfield (CWLP)'] },
  IN: { avgRate: 0.128, commercialRate: 0.108, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 1000, exportRate: 0.128, interconnectionMaxKw: 1000, majorUtilities: ['Duke Energy Indiana', 'AES Indiana', 'NIPSCO', 'Bartholomew County REMC', 'Boone County REMC', 'Carroll White REMC', 'Clark County REMC', 'Daviess-Martin County REMC', 'Decatur County REMC', 'Dubois REC', 'Fulton County REMC', 'Harrison County REMC', 'Henry County REMC', 'Hendricks Power Coop', 'Jackson County REMC', 'Jay County REMC', 'Johnson County REMC', 'Kankakee Valley REMC', 'Knox County REMC', 'LaGrange County REMC', 'Northeastern REMC', 'Orange County REMC', 'Parke County REMC', 'Pulaski-White REMC', 'Randolph County REMC', 'Rush County REMC', 'South Central Indiana REMC', 'Southeastern Indiana REMC', 'Tipmont REMC', 'Utilities District of Western Indiana REMC', 'Wabash Valley Power Alliance', 'Warren County REMC', 'White County REMC'] },
  IA: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 500,  exportRate: 0.118, interconnectionMaxKw: 500,  majorUtilities: ['MidAmerican Energy', 'Alliant Energy (IPL)', 'Black Hills Energy (IA)', 'Allamakee-Clayton Electric Coop', 'Boone Valley Electric Coop', 'Buchanan County REC', 'Butler County REC', 'Central Iowa Power Coop', 'Clarke Electric Coop', 'Consumers Energy (IA)', 'Corn Belt Power Coop', 'Eastern Iowa Light & Power Coop', 'Farmers Electric Coop (IA)', 'Grundy County REC', 'Guthrie County REC', 'Hawkeye REC', 'Iowa Lakes Electric Coop', 'Iowa Rural Electric Coop', 'Linn County REC', 'Maquoketa Valley Electric Coop', 'Marshall County REC', 'Midland Power Coop', 'North West REC', 'Pella Municipal Utilities', 'Raccoon Valley Electric Coop', 'Southwest Iowa REC', 'T.I.P. Rural Electric Coop', 'Tri-County Electric Coop (IA)', 'United Power (IA)', 'Western Iowa Power Coop', 'Woodbury County REC'] },
  KS: { avgRate: 0.128, commercialRate: 0.108, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.128, interconnectionMaxKw: 25,   majorUtilities: ['Evergy', 'Westar Energy', 'Kansas City Power & Light', 'Ark Valley Electric Coop', 'Bluestem Electric Coop', 'Butler Rural Electric Coop', 'Caney Valley Electric Coop', 'Cherryvale Utilities', 'Cimarron Electric Coop', 'Columbus Electric Coop', 'Flint Hills Rural Electric Coop', 'Heartland Rural Electric Coop', 'Kansas Electric Power Coop', 'Lane-Scott Electric Coop', 'Midwest Energy', 'Pioneer Electric Coop (KS)', 'Prairie Land Electric Coop', 'Rolling Hills Electric Coop', 'Sedgwick County Electric Coop', 'Sunflower Electric Power Corp', 'Twin Valley Electric Coop', 'Victory Electric Coop', 'Western Cooperative Electric Association'] },
  KY: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 30,   exportRate: 0.118, interconnectionMaxKw: 30,   majorUtilities: ['LG&E', 'KU', 'Duke Energy Kentucky', 'Big Sandy RECC', 'Blue Grass Energy', 'Clark Energy', 'Cumberland Valley Electric', 'Delta Natural Gas', 'Farmers RECC', 'Fleming-Mason Energy', 'Grayson RECC', 'Inter-County Energy', 'Jackson Energy', 'Kenergy', 'Licking Valley RECC', 'Meade County RECC', 'Nolin RECC', 'Owen Electric', 'Pennyrile Electric', 'Salt River Electric', 'Shelby Energy', 'South Kentucky RECC', 'Taylor County RECC', 'Tri-County Electric Coop (KY)', 'Warren RECC', 'West Kentucky RECC'] },
  LA: { avgRate: 0.108, commercialRate: 0.092, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.108, interconnectionMaxKw: 25,   majorUtilities: ['Entergy Louisiana', 'Cleco', 'SWEPCO', 'Beauregard Electric Coop', 'Bossier REC', 'Cajun Electric Power Coop', 'Claiborne Electric Coop', 'Concordia Electric Coop', 'Dixie Electric Membership Corp', 'Jefferson Davis Electric Coop', 'Northeast Louisiana Power Coop', 'Pointe Coupee Electric Membership Corp', 'South Louisiana Electric Coop', 'Valley Electric Membership Corp', 'Washington-St. Tammany Electric Coop'] },
  ME: { avgRate: 0.198, commercialRate: 0.162, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 660,  exportRate: 0.198, interconnectionMaxKw: 660,  majorUtilities: ['Central Maine Power', 'Versant Power', 'Bangor Hydro-Electric', 'Eastern Maine Electric Coop', 'Fox Islands Electric Coop', 'Houlton Water Company', 'Van Buren Light & Power District'] },
  MD: { avgRate: 0.148, commercialRate: 0.122, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 2000, exportRate: 0.148, interconnectionMaxKw: 2000, majorUtilities: ['BGE', 'Pepco', 'Delmarva Power', 'Potomac Edison', 'Choptank Electric Coop', 'Southern Maryland Electric Coop', 'A&N Electric Coop', 'City of Hagerstown Electric', 'City of Thurmont Electric', 'Easton Utilities'] },
  MA: { avgRate: 0.248, commercialRate: 0.198, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 2000, exportRate: 0.248, interconnectionMaxKw: 2000, majorUtilities: ['Eversource', 'National Grid', 'Unitil', 'Cape Light Compact', 'Belmont Municipal Light', 'Braintree Electric Light', 'Concord Municipal Light Plant', 'Danvers Electric', 'Groton Electric Light', 'Holden Municipal Light', 'Hull Municipal Lighting Plant', 'Littleton Electric Light', 'Mansfield Municipal Electric', 'Marblehead Municipal Light', 'Middleborough Gas & Electric', 'Norwood Municipal Light', 'Peabody Municipal Light', 'Reading Municipal Light', 'Rowley Municipal Light', 'Shrewsbury Electric & Cable', 'Sterling Municipal Light', 'Taunton Municipal Lighting Plant', 'Wakefield Municipal Gas & Light', 'Westfield Gas & Electric', 'Wilmington Municipal Light'] },
  MI: { avgRate: 0.178, commercialRate: 0.148, netMetering: true,  netMeteringPolicy: 'Inflow/Outflow billing', netMeteringMaxKw: 150,  exportRate: 0.09,  interconnectionMaxKw: 150,  majorUtilities: ['DTE Energy', 'Consumers Energy', 'UPPCO', 'Cherryland Electric Coop', 'Cloverland Electric Coop', 'Great Lakes Energy', 'HomeWorks Tri-County Electric Coop', 'Midwest Energy Coop', 'Ontonagon County REA', 'Presque Isle Electric & Gas Coop', 'Thumb Electric Coop', 'Traverse City Light & Power', 'Zeeland Board of Public Works', 'Lansing Board of Water & Light', 'Holland Board of Public Works'] },
  MN: { avgRate: 0.138, commercialRate: 0.112, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 40,   exportRate: 0.138, interconnectionMaxKw: 40,   majorUtilities: ['Xcel Energy', 'Minnesota Power', 'Great Plains Energy', 'Otter Tail Power', 'Connexus Energy', 'Dakota Electric Association', 'East Central Energy', 'Goodhue County Electric Coop', 'Itasca-Mantrap Coop Electrical Association', 'Kandiyohi Power Coop', 'Lake Region Electric Coop', 'McLeod Cooperative Power Association', 'Meeker Cooperative Light & Power', 'Mille Lacs Energy Coop', 'Minnesota Valley Electric Coop', 'Nobles Cooperative Electric', 'North Itasca Electric Coop', 'Peoples Energy Coop', 'Red Lake Electric Coop', 'Redwood Electric Coop', 'Renville-Sibley Cooperative Power', 'Rice-Watonwan Electric Coop', 'Runestone Electric Association', 'South Central Electric Association', 'Stearns Electric Association', 'Todd-Wadena Electric Coop', 'Traverse Electric Coop', 'Wild Rice Electric Coop', 'Wright-Hennepin Cooperative Electric Association'] },
  MS: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 20,   exportRate: 0.118, interconnectionMaxKw: 20,   majorUtilities: ['Entergy Mississippi', 'Mississippi Power', 'Alcorn County Electric Power Association', 'Bolivar Electric Power Association', 'Coahoma Electric Power Association', 'Coast Electric Power Association', 'Delta Electric Power Association', 'Dixie Electric Power Association', 'Four County Electric Power Association', 'Jones County Electric Power Association', 'Magnolia Electric Power Association', 'Mississippi Delta Electric Power Association', 'North East Mississippi Electric Power Association', 'Pearl River Valley Electric Power Association', 'Singing River Electric Power Association', 'Southwest Mississippi Electric Power Association', 'Tallahatchie Valley Electric Power Association', 'Tippah Electric Power Association', 'Tombigbee Electric Power Association', 'Twin County Electric Power Association'] },
  MO: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 100,  exportRate: 0.118, interconnectionMaxKw: 100,  majorUtilities: ['Ameren Missouri', 'Evergy Missouri', 'Empire District Electric', 'Associated Electric Coop', 'Barry Electric Coop', 'Boone Electric Coop', 'Callaway Electric Coop', 'Central Missouri Electric Coop', 'Citizens Electric Corp', 'Clark Electric Coop', 'Co-Mo Electric Coop', 'Consolidated Electric Coop', 'Cuivre River Electric Coop', 'Farmers Electric Coop (MO)', 'Gascosage Electric Coop', 'Grundy Electric Coop', 'Howard Electric Coop', 'Intercounty Electric Coop', 'Laclede Electric Coop', 'Lewis County Rural Electric Coop', 'Macon Electric Coop', 'Meramec Electric Coop', 'Missouri Rural Electric Coop', 'New-Mac Electric Coop', 'Nodaway Valley Electric Coop', 'Northeast Missouri Electric Power Coop', 'Osage Valley Electric Coop', 'Ozark Border Electric Coop', 'Pemiscot-Dunklin Electric Coop', 'Platte-Clay Electric Coop', 'Ralls County Electric Coop', 'Sac Osage Electric Coop', 'SE Missouri Electric Coop', 'Southwest Electric Coop', 'Three Rivers Electric Coop', 'Webster Electric Coop', 'White River Valley Electric Coop (MO)'] },
  MT: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 50,   exportRate: 0.118, interconnectionMaxKw: 50,   majorUtilities: ['NorthWestern Energy', 'Montana-Dakota Utilities', 'Flathead Electric Coop', 'Glacier Electric Coop', 'Hill County Electric Coop', 'Mid-Yellowstone Electric Coop', 'Missoula Electric Coop', 'Ravalli County Electric Coop', 'Sheridan Electric Coop', 'Sun River Electric Coop', 'Tongue River Electric Coop', 'Triangle Electric Coop', 'Vigilante Electric Coop', 'Yellowstone Valley Electric Coop'] },
  NE: { avgRate: 0.108, commercialRate: 0.092, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.108, interconnectionMaxKw: 25,   majorUtilities: ['OPPD', 'LES', 'NPPD', 'Burt County PPD', 'Butler PPD', 'Cedar-Knox PPD', 'Chimney Rock PPD', 'Cornhusker PPD', 'Cuming County PPD', 'Custer PPD', 'Dawson PPD', 'Elkhorn Rural PPD', 'Farmers & Merchants Electric Coop', 'Frontier PPD', 'Garfield PPD', 'Grant County PPD', 'Howard Greeley Rural PPD', 'Husker Electric Membership Corp', 'Loup Valleys Rural PPD', 'McCook PPD', 'Midwest Electric Membership Corp', 'Niobrara Valley Electric Membership Corp', 'North Central PPD', 'Northeast Nebraska Electric Coop', 'Northwest Rural PPD', 'O&G Electric Coop', 'Panhandle Rural Electric Membership Association', 'Perennial PPD', 'Polk County Rural PPD', 'Seward County PPD', 'South Central PPD', 'Southeast Nebraska PPD', 'Southern PPD', 'Southwest PPD', 'Twin Valleys PPD', 'Wheat Belt PPD', 'Wheatland Electric Coop', 'York County Seward County PPD'] },
  NV: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering 3.0', netMeteringMaxKw: 150,  exportRate: 0.075, interconnectionMaxKw: 150,  majorUtilities: ['NV Energy', 'Valley Electric Association', 'Mt. Wheeler Power', 'Overton Power District', 'Lincoln County Power District', 'Ely Light & Power', 'Wells Rural Electric Company', 'Harney Electric Coop'] },
  NH: { avgRate: 0.228, commercialRate: 0.188, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 1000, exportRate: 0.228, interconnectionMaxKw: 1000, majorUtilities: ['Eversource NH', 'Unitil', 'NH Electric Coop', 'Granite State Electric', 'New Hampshire Electric Coop', 'Wolfeboro Power', 'Littleton Water & Light'] },
  NJ: { avgRate: 0.178, commercialRate: 0.148, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 2000, exportRate: 0.178, interconnectionMaxKw: 2000, majorUtilities: ['PSE&G', 'JCP&L', 'Atlantic City Electric', 'Rockland Electric', 'Sussex Rural Electric Coop', 'South Jersey Industries', 'Orange & Rockland Utilities'] },
  NM: { avgRate: 0.138, commercialRate: 0.112, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 80,   exportRate: 0.138, interconnectionMaxKw: 80,   majorUtilities: ['PNM', 'El Paso Electric', 'Xcel Energy NM', 'Central New Mexico Electric Coop', 'Columbus Electric Coop', 'Continental Divide Electric Coop', 'Farmers Electric Coop (NM)', 'Jemez Mountains Electric Coop', 'Kit Carson Electric Coop', 'Lea County Electric Coop', 'Mora-San Miguel Electric Coop', 'Otero County Electric Coop', 'Roosevelt County Electric Coop', 'Sierra Electric Coop', 'Socorro Electric Coop', 'Southwestern Public Service', 'Springer Electric Coop', 'Tri-State G&T (NM)', 'Tucumcari Electric Coop', 'Valencia County Electric Coop'] },
  NY: { avgRate: 0.218, commercialRate: 0.178, netMetering: true,  netMeteringPolicy: 'Value of Distributed Energy Resources (VDER)', netMeteringMaxKw: 2000, exportRate: 0.12,  interconnectionMaxKw: 2000, majorUtilities: ['Con Edison', 'National Grid NY', 'NYSEG', 'RG&E', 'Central Hudson', 'O&R', 'LIPA/PSEG Long Island', 'New York State Electric & Gas', 'Rochester Gas & Electric', 'Delaware County Electric Coop', 'Oneida-Madison Electric Coop', 'Otsego Electric Coop', 'Steuben Rural Electric Coop', 'Sullivan County Electric Coop', 'Claverack Rural Electric Coop', 'Jefferson County Electric Coop', 'Lewis County Rural Electric Coop', 'Niagara Mohawk', 'Orange & Rockland Utilities'] },
  NC: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 1000, exportRate: 0.118, interconnectionMaxKw: 1000, majorUtilities: ['Duke Energy Carolinas', 'Duke Energy Progress', 'Dominion Energy NC', 'Blue Ridge Electric Membership Corp', 'Brunswick Electric Membership Corp', 'Cape Hatteras Electric Coop', 'Carteret-Craven Electric Coop', 'Central Electric Membership Corp', 'Edgecombe-Martin County Electric Membership Corp', 'EnergyUnited Electric Membership Corp', 'Four County Electric Membership Corp', 'French Broad Electric Membership Corp', 'Halifax Electric Membership Corp', 'Haywood Electric Membership Corp', 'Jones-Onslow Electric Membership Corp', 'Lumbee River Electric Membership Corp', 'New Hanover County Electric Membership Corp', 'Pee Dee Electric Membership Corp', 'Piedmont Electric Membership Corp', 'Randolph Electric Membership Corp', 'Roanoke Electric Coop', 'Rutherford Electric Membership Corp', 'South River Electric Membership Corp', 'Surry-Yadkin Electric Membership Corp', 'Tideland Electric Membership Corp', 'Tri-County Electric Membership Corp', 'Union Power Coop', 'Wake Electric Membership Corp', 'Yadkin Valley Telephone Membership Corp'] },
  ND: { avgRate: 0.108, commercialRate: 0.092, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 100,  exportRate: 0.108, interconnectionMaxKw: 100,  majorUtilities: ['Xcel Energy ND', 'Montana-Dakota Utilities', 'Otter Tail Power', 'Basin Electric Power Coop', 'Cass County Electric Coop', 'Cavalier Rural Electric Coop', 'Dakotas Electric Coop', 'Dickey Rural Networks', 'Dunn County Electric Coop', 'Emmons-Logan Electric Coop', 'Garrison Diversion Conservancy District', 'KEM Electric Coop', 'McLean Electric Coop', 'Mor-Gran-Sou Electric Coop', 'Mountrail-Williams Electric Coop', 'North Central Electric Coop', 'Nodak Electric Coop', 'Oliver-Mercer Electric Coop', 'Roughrider Electric Coop', 'Slope Electric Coop', 'Tri-County Electric Coop (ND)', 'West Plains Electric Coop'] },
  OH: { avgRate: 0.128, commercialRate: 0.108, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 2000, exportRate: 0.128, interconnectionMaxKw: 2000, majorUtilities: ['AEP Ohio', 'FirstEnergy', 'Duke Energy Ohio', 'Dayton Power & Light', 'Adams Rural Electric Coop', 'Buckeye Rural Electric Coop', 'Carroll Electric Coop (OH)', 'Consolidated Electric Coop (OH)', 'Darke Rural Electric Coop', 'Delaware Rural Electric Coop', 'Firelands Electric Coop', 'Frontier Power', 'Guernsey-Muskingum Electric Coop', 'Hancock-Wood Electric Coop', 'Holmes-Wayne Electric Coop', 'Licking Rural Electrification', 'Lorain-Medina Rural Electric Coop', 'Mid-Ohio Energy Coop', 'North Central Electric Coop (OH)', 'Northwestern Rural Electric Coop', 'Ohio Rural Electric Cooperatives', 'Paulding-Putnam Electric Coop', 'Pioneer Rural Electric Coop', 'South Central Power', 'Tri-County Rural Electric Coop (OH)', 'Union Rural Electric Coop', 'Vinton County Electric Coop', 'Washington Electric Coop (OH)'] },
  OK: { avgRate: 0.108, commercialRate: 0.092, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 100,  exportRate: 0.108, interconnectionMaxKw: 100,  majorUtilities: ['OG&E', 'PSO', 'OEC', 'Alfalfa Electric Coop', 'Caddo Electric Coop', 'Canadian Valley Electric Coop', 'Central Rural Electric Coop', 'Choctaw Electric Coop', 'Cimarron Electric Coop (OK)', 'Consolidated Rural Electric Coop', 'Cotton Electric Coop', 'Creek Electric Coop', 'East Central Electric Coop', 'Harmon Electric Association', 'Indian Electric Coop', 'Kay Electric Coop', 'Kiamichi Electric Coop', 'Lake Region Electric Coop (OK)', 'Midwest Electric Coop (OK)', 'Northfork Electric Coop', 'Northeast Oklahoma Electric Coop', 'Northwestern Electric Coop', 'Oklahoma Electric Coop', 'Ozarks Electric Coop (OK)', 'People\'s Electric Coop', 'Red River Valley REA', 'Rural Electric Coop', 'Southeastern Electric Coop', 'Southwest Rural Electric Association', 'Verdigris Valley Electric Coop', 'Western Farmers Electric Coop', 'Woodward Electric Coop'] },
  OR: { avgRate: 0.128, commercialRate: 0.108, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.128, interconnectionMaxKw: 25,   majorUtilities: ['PacifiCorp', 'Portland General Electric', 'Pacific Power', 'Blachly-Lane Electric Coop', 'Clatskanie PUD', 'Clearwater Power (OR)', 'Columbia Basin Electric Coop', 'Columbia River PUD', 'Consumers Power', 'Coos-Curry Electric Coop', 'Emerald PUD', 'Eugene Water & Electric Board', 'Harney Electric Coop (OR)', 'Hood River Electric Coop', 'Lane Electric Coop', 'Lincoln Electric Coop', 'Lost River Electric Coop (OR)', 'Midstate Electric Coop', 'Northern Wasco County PUD', 'Oregon Trail Electric Coop', 'Salem Electric', 'Tillamook PUD', 'Umatilla Electric Coop', 'Wasco Electric Coop', 'West Oregon Electric Coop'] },
  PA: { avgRate: 0.148, commercialRate: 0.122, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 50,   exportRate: 0.148, interconnectionMaxKw: 50,   majorUtilities: ['PECO', 'PPL', 'Duquesne Light', 'Met-Ed', 'Penelec', 'Penn Power', 'West Penn Power', 'Adams Electric Coop (PA)', 'Bedford Rural Electric Coop', 'Claverack Rural Electric Coop (PA)', 'New Enterprise Rural Electric Coop', 'Northwestern Rural Electric Coop (PA)', 'Palmerton Telephone', 'Penn Lines', 'Pike Electric Coop', 'REA Energy Coop', 'Sullivan County Rural Electric Coop', 'Tri-County Rural Electric Coop (PA)', 'UGI Utilities', 'Valley Rural Electric Coop', 'Wellsboro Electric Company'] },
  RI: { avgRate: 0.248, commercialRate: 0.198, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 5000, exportRate: 0.248, interconnectionMaxKw: 5000, majorUtilities: ['National Grid RI', 'Pascoag Utility District', 'Block Island Power Company'] },
  SC: { avgRate: 0.138, commercialRate: 0.112, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 20,   exportRate: 0.138, interconnectionMaxKw: 20,   majorUtilities: ['Duke Energy SC', 'Dominion Energy SC', 'SCE&G', 'Aiken Electric Coop', 'Berkeley Electric Coop', 'Black River Electric Coop', 'Blue Ridge Electric Coop', 'Broad River Electric Coop', 'Coastal Electric Coop', 'Edisto Electric Coop', 'Four Oaks Energy', 'Horry Electric Coop', 'Laurens Electric Coop', 'Little River Electric Coop', 'Lynches River Electric Coop', 'Mid-Carolina Electric Coop', 'Newberry Electric Coop', 'Palmetto Electric Coop', 'Pee Dee Electric Coop (SC)', 'Santee Electric Coop', 'Tri-County Electric Coop (SC)', 'York Electric Coop'] },
  SD: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 100,  exportRate: 0.118, interconnectionMaxKw: 100,  majorUtilities: ['Xcel Energy SD', 'Montana-Dakota Utilities', 'Black Hills Energy SD', 'Basin Electric Power Coop', 'Bon Homme Yankton Electric Association', 'Butte Electric Coop', 'Central Electric Coop (SD)', 'Cherry-Todd Electric Coop', 'Codington-Clark Electric Coop', 'Corn Belt Power Coop (SD)', 'Dakota Energy Coop', 'East River Electric Power Coop', 'FEM Electric Association', 'Grand Electric Coop', 'H-D Electric Coop', 'Lacreek Electric Association', 'Lake Region Electric Association', 'Moreau-Grand Electric Coop', 'Northern Electric Coop', 'Oahe Electric Coop', 'Sioux Valley Energy', 'Southeastern Electric Coop (SD)', 'Traverse Electric Coop (SD)', 'West Central Electric Coop', 'West River Electric Association'] },
  TN: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'TVA Generation Partners', netMeteringMaxKw: 50,   exportRate: 0.04,  interconnectionMaxKw: 50,   majorUtilities: ['TVA', 'Memphis Light Gas & Water', 'Nashville Electric Service', 'Knoxville Utilities Board', 'Chattanooga EPB', 'Bristol Tennessee Essential Services', 'Appalachian Electric Coop', 'Caney Fork Electric Coop', 'Cumberland Electric Membership Corp', 'Duck River Electric Membership Corp', 'Fayetteville Public Utilities', 'Forked Deer Electric Coop', 'Gibson Electric Membership Corp', 'Holston Electric Coop', 'Meriwether Lewis Electric Coop', 'Middle Tennessee Electric Membership Corp', 'Mountain Electric Coop', 'Pickwick Electric Coop', 'Powell-Clinch Utility District', 'Sequachee Valley Electric Coop', 'Southwest Tennessee Electric Membership Corp', 'Tennessee Valley Electric Coop', 'Tri-County Electric Membership Corp (TN)', 'Upper Cumberland Electric Membership Corp', 'Volunteer Energy Coop'] },
  TX: { avgRate: 0.128, commercialRate: 0.108, netMetering: false, netMeteringPolicy: 'No statewide mandate — varies by utility', netMeteringMaxKw: 0,    exportRate: 0.03,  interconnectionMaxKw: 50,   majorUtilities: ['Oncor', 'CenterPoint', 'AEP Texas', 'TNMP', 'Sharyland', 'Pedernales Electric Coop', 'Bluebonnet Electric Coop', 'Brazos Electric Power Coop', 'Bowie-Cass Electric Coop', 'Cap Rock Energy', 'Cherokee County Electric Coop', 'Coleman County Electric Coop', 'Concho Valley Electric Coop', 'CoServ Electric', 'Deep East Texas Electric Coop', 'Denton County Electric Coop', 'Dickens Electric Coop', 'East Texas Electric Coop', 'Farmers Electric Coop (TX)', 'Grayson-Collin Electric Coop', 'Gulf Coast Electric Coop (TX)', 'Guadalupe Valley Electric Coop', 'Hamilton County Electric Coop', 'Heart of Texas Electric Coop', 'Houston County Electric Coop', 'Jasper-Newton Electric Coop', 'Karnes Electric Coop', 'Lamar County Electric Coop', 'Lighthouse Electric Coop', 'Lyntegar Electric Coop', 'McCulloch Electric Coop', 'McLennan County Electric Coop', 'Medina Electric Coop', 'Mid-South Electric Coop', 'Navarro County Electric Coop', 'Nueces Electric Coop', 'Panola-Harrison Electric Coop', 'Peoples Electric Coop (TX)', 'Rayburn Country Electric Coop', 'Rio Grande Electric Coop', 'Rusk County Electric Coop', 'Sam Houston Electric Coop', 'San Bernard Electric Coop', 'San Patricio Electric Coop', 'Southwestern Electric Power', 'Swisher Electric Coop', 'Taylor Electric Coop', 'Tri-County Electric Coop (TX)', 'Trinity Valley Electric Coop', 'United Cooperative Services', 'Victoria Electric Coop', 'Wharton County Electric Coop', 'Wood County Electric Coop'] },
  UT: { avgRate: 0.108, commercialRate: 0.092, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.108, interconnectionMaxKw: 25,   majorUtilities: ['Rocky Mountain Power', 'Dixie Power', 'Bridgerland Electric', 'Carbon Power & Light', 'Flowell Electric Association', 'Garkane Energy Coop', 'Moon Lake Electric Association', 'Mt. Wheeler Power (UT)', 'Provo City Power', 'Spanish Fork Power', 'St. George City Power', 'Strawberry Electric Service District', 'Utah Associated Municipal Power Systems', 'Uintah Basin Electric Association'] },
  VT: { avgRate: 0.198, commercialRate: 0.162, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 500,  exportRate: 0.198, interconnectionMaxKw: 500,  majorUtilities: ['Green Mountain Power', 'Burlington Electric', 'Vermont Electric Coop', 'Washington Electric Coop', 'Village of Hyde Park Electric', 'Village of Johnson Electric', 'Village of Ludlow Electric', 'Village of Morrisville Water & Light', 'Village of Northfield Electric', 'Village of Readsboro Electric', 'Village of Stowe Electric'] },
  VA: { avgRate: 0.128, commercialRate: 0.108, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 1000, exportRate: 0.128, interconnectionMaxKw: 1000, majorUtilities: ['Dominion Energy VA', 'Appalachian Power', 'Rappahannock Electric', 'A&N Electric Coop', 'BARC Electric Coop', 'Central Virginia Electric Coop', 'Community Electric Coop', 'Craig-Botetourt Electric Coop', 'Mecklenburg Electric Coop', 'New Peoples Bank', 'Northern Neck Electric Coop', 'Northern Virginia Electric Coop', 'Old Dominion Power', 'Powell River Electric Coop', 'Prince George Electric Coop', 'Shenandoah Valley Electric Coop', 'Southside Electric Coop', 'Virginia Electric Coop'] },
  WA: { avgRate: 0.108, commercialRate: 0.092, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 100,  exportRate: 0.108, interconnectionMaxKw: 100,  majorUtilities: ['Puget Sound Energy', 'Seattle City Light', 'Pacific Power WA', 'Avista (WA)', 'Benton PUD', 'Chelan County PUD', 'Clark PUD', 'Clallam County PUD', 'Columbia REA', 'Cowiche Valley Electric Coop', 'Douglas County PUD', 'Ferry County PUD', 'Franklin PUD', 'Grant County PUD', 'Grays Harbor PUD', 'Inland Power & Light', 'Jefferson County PUD', 'Kittitas County PUD', 'Klickitat PUD', 'Lewis County PUD', 'Lincoln Electric Coop (WA)', 'Mason County PUD 1', 'Mason County PUD 3', 'Nespelem Valley Electric Coop', 'Okanogan County PUD', 'Pacific County PUD', 'Peninsula Light Company', 'Puget Sound Coop', 'Raft River Rural Electric Coop (WA)', 'Skamania County PUD', 'Snohomish County PUD', 'Tanner Electric Coop', 'Wahkiakum County PUD', 'Whatcom County PUD', 'Yakima County Electric Coop'] },
  WV: { avgRate: 0.118, commercialRate: 0.098, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.118, interconnectionMaxKw: 25,   majorUtilities: ['Appalachian Power', 'Monongalia Power', 'Wheeling Power', 'Pocahontas County Public Service District', 'Greenbrier Valley Electric Coop', 'Harrison Rural Electrification Association', 'Mountaineer Gas', 'Pendleton Community Bank', 'Pocahontas County PSD', 'Randolph-Macon Electric Coop', 'Shenandoah Valley Electric Coop (WV)', 'Upshur Rural Electric Coop', 'Wayne County PSD', 'Wirt County PSD'] },
  WI: { avgRate: 0.178, commercialRate: 0.148, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 20,   exportRate: 0.178, interconnectionMaxKw: 20,   majorUtilities: ['We Energies', 'WPS', 'Alliant Energy WI', 'Madison Gas & Electric', 'Dairyland Power Coop', 'Adams-Columbia Electric Coop', 'Barron Electric Coop', 'Bayfield Electric Coop', 'Buffalo-Jackson Electric Coop', 'Central Wisconsin Electric Coop', 'Clark Electric Coop (WI)', 'Dunn Energy Coop', 'Eau Claire Energy Coop', 'Jump River Electric Coop', 'Kickapoo Valley Electric Coop', 'Lakelands Electric Coop', 'Oakdale Electric Coop', 'Polk-Burnett Electric Coop', 'Price Electric Coop', 'Richland Electric Coop', 'Rock Energy Coop', 'Scenic Rivers Energy Coop', 'Taylor Electric Coop (WI)', 'Tri-County Electric Coop (WI)', 'Vernon Electric Coop', 'Viroqua Electric Coop', 'Westby Cooperative Electric Association', 'Wisconsin Electric Coop', 'Wood County Electric Coop (WI)'] },
  WY: { avgRate: 0.108, commercialRate: 0.092, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 25,   exportRate: 0.108, interconnectionMaxKw: 25,   majorUtilities: ['Rocky Mountain Power', 'Black Hills Energy WY', 'Bridger Valley Electric Association', 'Carbon Power & Light (WY)', 'High West Energy', 'Highline Electric Association (WY)', 'Lower Valley Energy', 'Niobrara Electric Association', 'Powder River Energy Corp', 'Tri-County Electric Association (WY)', 'Wheatland Rural Electric Association', 'Wyrulec Company'] },
  DC: { avgRate: 0.168, commercialRate: 0.138, netMetering: true,  netMeteringPolicy: 'Net metering at retail rate', netMeteringMaxKw: 1000, exportRate: 0.168, interconnectionMaxKw: 1000, majorUtilities: ['Pepco'] },
};'''

with open(UTILITY_FILE, 'r') as f:
    content = f.read()

# Find and replace the STATE_UTILITY_FALLBACK block
start_marker = 'export const STATE_UTILITY_FALLBACK: Record<string, {'
end_marker = '};'

start_idx = content.find(start_marker)
if start_idx == -1:
    print("ERROR: Could not find STATE_UTILITY_FALLBACK start")
    exit(1)

# Find the closing }; after the start
# We need to find the matching closing brace
search_from = start_idx + len(start_marker)
# Find the end of the object - look for "};" at the start of a line after the data
end_idx = content.find('\n};\n', search_from)
if end_idx == -1:
    end_idx = content.find('\n};\n\n', search_from)
if end_idx == -1:
    print("ERROR: Could not find STATE_UTILITY_FALLBACK end")
    exit(1)

end_idx += 4  # include the "};\n"

old_block = content[start_idx:end_idx]
print(f"Found block from {start_idx} to {end_idx}, length {len(old_block)}")
print(f"First 100 chars: {old_block[:100]}")
print(f"Last 100 chars: {old_block[-100:]}")

new_content = content[:start_idx] + NEW_FALLBACK + '\n' + content[end_idx:]

with open(UTILITY_FILE, 'w') as f:
    f.write(new_content)

print("✅ STATE_UTILITY_FALLBACK updated with full co-op data for all 50 states")