// ============================================================
// lib/engineering/artifactBuilders.ts
// Server-side artifact content generators.
//
// Used by:
//   - /api/engineering/save-outputs  (called after runCalc)
//   - /api/pipeline/run              (called by RUN PROJECT PIPELINE)
//
// All builders take an EngineeringReport and return plain-text /
// CSV / SVG strings suitable for storage in project_files table.
// Field names match types in lib/engineering/types.ts exactly.
// ============================================================

import type { EngineeringReport } from './types';

export interface ArtifactBuildInput {
  report:     EngineeringReport;
  projectId:  string;
  clientName: string;
  clientSlug: string; // sanitized for filenames: e.g. "John_Smith"
  reportDate: string; // e.g. "June 9, 2026"
}

// ── Engineering Report (text) ─────────────────────────────────
export function buildEngineeringReportText(input: ArtifactBuildInput): string {
  const { report, clientName, reportDate } = input;
  const sys  = report.systemSummary;
  const elec = report.electrical;
  const stru = report.structural;

  const lines: string[] = [
    '═══════════════════════════════════════════════════════════════',
    '  ENGINEERING REPORT',
    `  ${clientName}`,
    `  Generated: ${reportDate}`,
    '═══════════════════════════════════════════════════════════════',
    '',
    '── SYSTEM SUMMARY ──────────────────────────────────────────────',
    `  System Size (DC):       ${sys.systemSizeKw ?? 'N/A'} kW`,
    `  Panel Count:            ${sys.panelCount ?? 'N/A'}`,
    `  Panel Model:            ${sys.panelModel ?? 'Generic 400W Monocrystalline'}`,
    `  Panel Wattage:          ${sys.panelWattage ?? 400} W`,
    `  Inverter Type:          ${sys.inverterType ?? 'String'}`,
    `  Inverter Model:         ${sys.inverterModel ?? 'TBD'}`,
    `  Est. Annual Production: ${sys.estimatedAnnualKwh ? sys.estimatedAnnualKwh.toLocaleString() + ' kWh' : 'N/A'}`,
    `  Mount Type:             ${sys.mountType ?? 'Roof Mount'}`,
    `  Location:               ${sys.address ?? sys.ahj ?? 'N/A'}`,
    '',
  ];

  if (elec) {
    lines.push('── ELECTRICAL ENGINEERING ──────────────────────────────────────');
    lines.push(`  DC System Size:         ${elec.dcSystemSizeKw ?? sys.systemSizeKw ?? 'N/A'} kW`);
    lines.push(`  String Count:           ${elec.stringCount ?? 'N/A'}`);
    lines.push(`  Panels per String:      ${elec.panelsPerString ?? 'N/A'}`);
    lines.push(`  String Voc:             ${elec.stringVoc ?? 'N/A'} V`);
    lines.push(`  String Isc:             ${elec.stringIsc ?? 'N/A'} A`);
    lines.push(`  DC Wire:                ${elec.dcWireGauge ?? '#10 AWG'}`);
    lines.push(`  DC Conduit:             ${elec.dcConduitSize ?? '3/4" EMT'}`);
    lines.push(`  DC Disconnect:          ${elec.dcDisconnectAmps ?? 'N/A'} A`);
    lines.push(`  AC Wire:                ${elec.acWireGauge ?? '#8 AWG'}`);
    lines.push(`  AC Conduit:             ${elec.acConduitSize ?? '1" EMT'}`);
    lines.push(`  AC Breaker:             ${elec.acBreakerAmps ?? 'N/A'} A`);
    lines.push(`  Main Panel Bus:         ${elec.mainPanelBusAmps ?? 'N/A'} A`);
    lines.push(`  Backfeed Breaker:       ${elec.backfeedBreakerAmps ?? 'N/A'} A`);
    lines.push(`  Interconnection:        ${elec.interconnectionMethod ?? 'Supply-Side Tap'}`);
    lines.push(`  NEC Version:            ${elec.necVersion ?? 'NEC 2020'}`);
    lines.push(`  Rapid Shutdown:         ${elec.rapidShutdownRequired ? 'Required — NEC 690.12' : 'Not Required'}`);
    lines.push('');
  }

  if (stru) {
    lines.push('── STRUCTURAL ENGINEERING ──────────────────────────────────────');
    lines.push(`  Roof Type:              ${stru.roofType ?? 'Asphalt Shingle'}`);
    lines.push(`  Rafter Size:            ${stru.rafterSize ?? '2×6'}`);
    lines.push(`  Rafter Spacing:         ${stru.rafterSpacingIn ?? 24}" O.C.`);
    lines.push(`  Wind Speed:             ${stru.windSpeedMph ?? 'N/A'} mph`);
    lines.push(`  Snow Load:              ${stru.groundSnowLoadPsf ?? 0} psf`);
    lines.push(`  Attachment Spacing:     ${stru.attachmentSpacingFt ?? 'N/A'} ft O.C.`);
    lines.push('');
  }

  lines.push('═══════════════════════════════════════════════════════════════');
  lines.push('  This report was auto-generated by SolarPro Engineering Engine.');
  lines.push('  For permit submission, obtain engineer stamp as required by AHJ.');
  lines.push('═══════════════════════════════════════════════════════════════');

  return lines.join('\n');
}

// ── Bill of Materials (CSV) ───────────────────────────────────
export function buildBomCsvFromReport(input: ArtifactBuildInput): string {
  const { report } = input;
  const sys   = report.systemSummary;
  const sched = report.equipmentSchedule;

  const rows: string[] = [
    'Tag,Description,Manufacturer,Model,Qty,Unit,Notes',
  ];

  if (sched) {
    const allItems = [
      ...(sched.panels     ?? []),
      ...(sched.inverters  ?? []),
      ...(sched.mounting   ?? []),
      ...(sched.electrical ?? []),
      ...(sched.batteries  ?? []),
    ];
    for (const item of allItems) {
      const tag   = String((item as any).tag          ?? '').replace(/,/g, ';');
      const desc  = String(item.description           ?? '').replace(/,/g, ';');
      const mfr   = String(item.manufacturer          ?? '').replace(/,/g, ';');
      const model = String(item.model                 ?? '').replace(/,/g, ';');
      const qty   = (item as any).quantity            ?? '';
      const unit  = String((item as any).unit         ?? 'EA').replace(/,/g, ';');
      const notes = String((item as any).notes ?? (item as any).specs ?? '').replace(/,/g, ';');
      rows.push(`${tag},${desc},${mfr},${model},${qty},${unit},${notes}`);
    }
  } else {
    // Fallback: minimal BOM from system summary
    const panelMfr = sys.panelModel?.split(' ')[0] ?? 'Generic';
    rows.push(`PV,Solar Panel,${panelMfr},${sys.panelModel ?? '400W Panel'},${sys.panelCount ?? 0},EA,${sys.panelWattage ?? 400}W monocrystalline`);
    rows.push(`INV,Inverter,${sys.inverterModel?.split(' ')[0] ?? 'Generic'},${sys.inverterModel ?? 'String Inverter'},1,EA,${sys.systemSizeKw ?? 0}kW AC output`);
    rows.push(`MNT,Mounting System,IronRidge,XR100,1,LOT,Roof mount racking`);
    rows.push(`COND,DC Conduit,Carlon,EMT,1,LOT,DC wiring conduit`);
    rows.push(`DISC,DC Disconnect,Square D,DU200RB,1,EA,Fused DC disconnect`);
  }

  return rows.join('\n');
}

// ── Single-Line Diagram (SVG) ─────────────────────────────────
export function buildSldSvgFromReport(input: ArtifactBuildInput): string {
  const { report } = input;
  const sys  = report.systemSummary;
  const elec = report.electrical;

  const panelCount     = sys.panelCount     ?? 0;
  const systemKw       = sys.systemSizeKw   ?? 0;
  const inverterModel  = sys.inverterModel  ?? 'String Inverter';
  const panelModel     = sys.panelModel     ?? '400W Panel';
  const stringCount    = elec?.stringCount  ?? 1;
  const panelsPerStr   = elec?.panelsPerString ?? panelCount;
  const dcWire         = elec?.dcWireGauge  ?? '#10 AWG';
  const acWire         = elec?.acWireGauge  ?? '#8 AWG';
  const acBreaker      = elec?.acBreakerAmps ?? 'N/A';
  const backfeed       = elec?.backfeedBreakerAmps ?? 'N/A';
  const acConduit      = elec?.acConduitSize ?? '1" EMT';
  const interconnect   = elec?.interconnectionMethod ?? 'Supply-Side Tap';

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 500" width="800" height="500"
     font-family="Arial, sans-serif" font-size="11">
  <rect width="800" height="500" fill="#0f172a"/>

  <!-- Title -->
  <text x="400" y="28" text-anchor="middle" fill="#f59e0b" font-size="14" font-weight="bold">
    SINGLE-LINE DIAGRAM — ${systemKw} kW DC SOLAR PV SYSTEM
  </text>
  <text x="400" y="44" text-anchor="middle" fill="#94a3b8" font-size="10">
    ${panelCount} x ${panelModel}  |  ${stringCount} string(s) x ${panelsPerStr} panels/string
  </text>

  <!-- PV Array -->
  <rect x="30" y="70" width="150" height="80" rx="6" fill="#1e293b" stroke="#f59e0b" stroke-width="1.5"/>
  <text x="105" y="98" text-anchor="middle" fill="#f59e0b" font-weight="bold">PV ARRAY</text>
  <text x="105" y="115" text-anchor="middle" fill="#cbd5e1">${panelCount} Panels</text>
  <text x="105" y="130" text-anchor="middle" fill="#94a3b8" font-size="9">${panelModel}</text>

  <!-- DC line -->
  <line x1="180" y1="110" x2="245" y2="110" stroke="#f59e0b" stroke-width="2"/>
  <text x="212" y="104" text-anchor="middle" fill="#f59e0b" font-size="9">DC ${dcWire}</text>

  <!-- DC Disconnect -->
  <rect x="245" y="82" width="110" height="56" rx="6" fill="#1e293b" stroke="#60a5fa" stroke-width="1.5"/>
  <text x="300" y="105" text-anchor="middle" fill="#60a5fa" font-weight="bold">DC DISC</text>
  <text x="300" y="120" text-anchor="middle" fill="#94a3b8" font-size="9">${elec?.dcDisconnectAmps ?? ''}A 600VDC</text>
  <text x="300" y="132" text-anchor="middle" fill="#94a3b8" font-size="9">Fused</text>

  <!-- DC to inverter -->
  <line x1="355" y1="110" x2="420" y2="110" stroke="#f59e0b" stroke-width="2"/>
  <text x="387" y="104" text-anchor="middle" fill="#f59e0b" font-size="9">DC</text>

  <!-- Inverter -->
  <rect x="420" y="70" width="130" height="80" rx="6" fill="#1e293b" stroke="#a78bfa" stroke-width="1.5"/>
  <text x="485" y="98" text-anchor="middle" fill="#a78bfa" font-weight="bold">INVERTER</text>
  <text x="485" y="113" text-anchor="middle" fill="#cbd5e1" font-size="9">${inverterModel}</text>
  <text x="485" y="128" text-anchor="middle" fill="#94a3b8" font-size="9">${systemKw} kW</text>
  <text x="485" y="141" text-anchor="middle" fill="#94a3b8" font-size="8">${elec?.rapidShutdownRequired ? 'RS Required' : ''}</text>

  <!-- AC line -->
  <line x1="550" y1="110" x2="620" y2="110" stroke="#4ade80" stroke-width="2"/>
  <text x="585" y="104" text-anchor="middle" fill="#4ade80" font-size="9">AC ${acWire}</text>

  <!-- MSP / AC Disconnect -->
  <rect x="620" y="70" width="150" height="80" rx="6" fill="#1e293b" stroke="#4ade80" stroke-width="1.5"/>
  <text x="695" y="98" text-anchor="middle" fill="#4ade80" font-weight="bold">MSP / AC DISC</text>
  <text x="695" y="113" text-anchor="middle" fill="#cbd5e1" font-size="9">${acBreaker}A Breaker</text>
  <text x="695" y="127" text-anchor="middle" fill="#94a3b8" font-size="9">Backfeed: ${backfeed}A</text>
  <text x="695" y="141" text-anchor="middle" fill="#94a3b8" font-size="8">${acConduit}</text>

  <!-- Grounding conductors -->
  <line x1="105" y1="150" x2="105" y2="200" stroke="#94a3b8" stroke-width="1" stroke-dasharray="4,2"/>
  <line x1="485" y1="150" x2="485" y2="200" stroke="#94a3b8" stroke-width="1" stroke-dasharray="4,2"/>
  <line x1="695" y1="150" x2="695" y2="200" stroke="#94a3b8" stroke-width="1" stroke-dasharray="4,2"/>
  <line x1="75" y1="200" x2="730" y2="200" stroke="#94a3b8" stroke-width="1.5"/>
  <text x="400" y="216" text-anchor="middle" fill="#94a3b8" font-size="9">EQUIPMENT GROUNDING CONDUCTOR (EGC)</text>

  <!-- Notes -->
  <rect x="30" y="235" width="740" height="240" rx="6" fill="#1e293b" stroke="#334155" stroke-width="1"/>
  <text x="50" y="257" fill="#f59e0b" font-weight="bold">SYSTEM NOTES</text>
  <text x="50" y="276" fill="#cbd5e1">1. All equipment installed per manufacturer instructions and NEC ${elec?.necVersion ?? '2020'}.</text>
  <text x="50" y="293" fill="#cbd5e1">2. Rapid Shutdown: ${elec?.rapidShutdownRequired ? 'Required per NEC 690.12 — install RS device at array.' : 'Not required for this configuration.'}</text>
  <text x="50" y="310" fill="#cbd5e1">3. DC conductors: listed PV wire or USE-2 rated 90 deg C minimum.</text>
  <text x="50" y="327" fill="#cbd5e1">4. AC conductors: ${acWire} in ${acConduit}.</text>
  <text x="50" y="344" fill="#cbd5e1">5. String configuration: ${stringCount} string(s) x ${panelsPerStr} module(s) per string.</text>
  <text x="50" y="361" fill="#cbd5e1">6. System DC Voc: ${elec?.stringVoc ? `${elec.stringVoc.toFixed(1)}V` : 'See electrical calculations'}.</text>
  <text x="50" y="378" fill="#cbd5e1">7. All roof penetrations shall be properly flashed and sealed per building code.</text>
  <text x="50" y="395" fill="#cbd5e1">8. Interconnection method: ${interconnect}.</text>
  <text x="50" y="412" fill="#94a3b8" font-size="9">Auto-generated by SolarPro Engineering Engine. Verify all values before permit submission.</text>

  <text x="400" y="488" text-anchor="middle" fill="#475569" font-size="9">
    SolarPro Engineering Engine — For permit application purposes only
  </text>
</svg>`;
}

// ── Permit Packet (text) ──────────────────────────────────────
export function buildPermitPacketText(input: ArtifactBuildInput): string {
  const { report, clientName, reportDate } = input;
  const sys  = report.systemSummary;
  const elec = report.electrical;
  const stru = report.structural;
  const perm = report.permitPackage;

  return [
    '═══════════════════════════════════════════════════════════════',
    '  PERMIT PACKAGE',
    `  ${clientName}`,
    `  Generated: ${reportDate}`,
    '═══════════════════════════════════════════════════════════════',
    '',
    '── PROJECT INFORMATION ─────────────────────────────────────────',
    `  Client:                 ${clientName}`,
    `  System Size:            ${sys.systemSizeKw ?? 'N/A'} kW DC`,
    `  Panel Count:            ${sys.panelCount ?? 'N/A'}`,
    `  Panel Model:            ${sys.panelModel ?? 'Generic 400W Monocrystalline'}`,
    `  Inverter Type:          ${sys.inverterType ?? 'String'}`,
    `  Inverter Model:         ${sys.inverterModel ?? 'TBD'}`,
    `  Address:                ${perm?.projectAddress ?? sys.address ?? 'N/A'}`,
    '',
    '── AHJ & CODE COMPLIANCE ───────────────────────────────────────',
    `  AHJ:                    ${perm?.ahj ?? 'See project address'}`,
    `  NEC Version:            ${perm?.necVersion ?? elec?.necVersion ?? 'NEC 2020'}`,
    `  Utility:                ${perm?.utilityName ?? sys.utilityName ?? 'N/A'}`,
    `  Interconnection:        ${perm?.interconnectionType ?? elec?.interconnectionMethod ?? 'Supply-Side Tap'}`,
    `  Prepared Date:          ${reportDate}`,
    '',
    '── REQUIRED DOCUMENTS ──────────────────────────────────────────',
    '  ☐ Site Plan (roof layout with setbacks)',
    '  ☐ Single-Line Diagram (NEC compliant)',
    '  ☐ Equipment Cut Sheets (panels, inverter, mounting)',
    '  ☐ Structural Analysis (roof loading)',
    '  ☐ Electrical Calculations',
    '  ☐ Utility Interconnection Application',
    '',
    '── ELECTRICAL SUMMARY ──────────────────────────────────────────',
    `  DC System Size:         ${elec?.dcSystemSizeKw ?? sys.systemSizeKw ?? 'N/A'} kW`,
    `  AC Breaker:             ${elec?.acBreakerAmps ?? 'N/A'} A`,
    `  Main Panel Bus:         ${elec?.mainPanelBusAmps ?? 'N/A'} A`,
    `  Backfeed Breaker:       ${elec?.backfeedBreakerAmps ?? 'N/A'} A`,
    `  Rapid Shutdown:         ${elec?.rapidShutdownRequired ? 'Required — NEC 690.12' : 'Not Required'}`,
    '',
    '── STRUCTURAL SUMMARY ──────────────────────────────────────────',
    `  Roof Type:              ${stru?.roofType ?? 'Asphalt Shingle'}`,
    `  Wind Speed:             ${stru?.windSpeedMph ?? 'N/A'} mph (ASCE 7-22)`,
    `  Snow Load:              ${stru?.groundSnowLoadPsf ?? 0} psf`,
    `  Attachment:             Lag Bolt to Rafter`,
    '',
    '═══════════════════════════════════════════════════════════════',
    '  Auto-generated by SolarPro. Obtain engineer stamp as required.',
    '═══════════════════════════════════════════════════════════════',
  ].join('\n');
}

// ── System Estimate (text) ────────────────────────────────────
export function buildSystemEstimateText(input: ArtifactBuildInput): string {
  const { report, clientName, reportDate } = input;
  const sys = report.systemSummary;

  return [
    '═══════════════════════════════════════════════════════════════',
    '  SYSTEM ESTIMATE',
    `  ${clientName}`,
    `  Generated: ${reportDate}`,
    '═══════════════════════════════════════════════════════════════',
    '',
    '── SYSTEM SPECIFICATIONS ───────────────────────────────────────',
    `  System Size:            ${sys.systemSizeKw ?? 'N/A'} kW DC`,
    `  Panel Count:            ${sys.panelCount ?? 'N/A'} panels`,
    `  Panel Model:            ${sys.panelModel ?? 'Generic 400W Monocrystalline'}`,
    `  Inverter Model:         ${sys.inverterModel ?? 'TBD'}`,
    `  Est. Annual Production: ${sys.estimatedAnnualKwh ? sys.estimatedAnnualKwh.toLocaleString() + ' kWh' : 'N/A'}`,
    `  Mount Type:             ${sys.mountType ?? 'Roof Mount'}`,
    '',
    '── NOTES ───────────────────────────────────────────────────────',
    '  This estimate is based on live engineering engine calculations.',
    '  Final pricing subject to site assessment and equipment availability.',
    '',
    '═══════════════════════════════════════════════════════════════',
    '  Auto-generated by SolarPro Engineering Engine',
    '═══════════════════════════════════════════════════════════════',
  ].join('\n');
}

// ── Build all 5 artifacts at once ────────────────────────────
export interface ArtifactFile {
  fileName: string;
  fileType: string;
  mimeType: string;
  content:  string;
  notes:    string;
}

export function buildAllArtifacts(input: ArtifactBuildInput): ArtifactFile[] {
  const { clientSlug } = input;
  return [
    {
      fileName: `Engineering_Report_${clientSlug}.txt`,
      fileType: 'engineering',
      mimeType: 'text/plain',
      content:  buildEngineeringReportText(input),
      notes:    'Engineering report — pipeline run',
    },
    {
      fileName: `SLD_${clientSlug}.svg`,
      fileType: 'engineering',
      mimeType: 'image/svg+xml',
      content:  buildSldSvgFromReport(input),
      notes:    'Single-line diagram — pipeline run',
    },
    {
      fileName: `BOM_${clientSlug}.csv`,
      fileType: 'engineering',
      mimeType: 'text/csv',
      content:  buildBomCsvFromReport(input),
      notes:    'Bill of materials — pipeline run',
    },
    {
      fileName: `Permit_Packet_${clientSlug}.txt`,
      fileType: 'engineering',
      mimeType: 'text/plain',
      content:  buildPermitPacketText(input),
      notes:    'Permit packet — pipeline run',
    },
    {
      fileName: `System_Estimate_${clientSlug}.txt`,
      fileType: 'engineering',
      mimeType: 'text/plain',
      content:  buildSystemEstimateText(input),
      notes:    'System estimate — pipeline run',
    },
  ];
}