/**
 * lib/mfa.ts — Multi-Factor Authentication Module
 *
 * Implements TOTP-based MFA for SolarPro admin and staff accounts,
 * as required by POL-SEC-009 (Password & Authentication Policy).
 *
 * Features:
 *   - TOTP secret generation (RFC 6238)
 *   - QR code generation for authenticator app enrollment
 *   - TOTP verification with timing-safe comparison
 *   - Recovery code generation and verification
 *   - MFA enforcement check for admin/staff roles
 *
 * WebAuthn/FIDO2 support can be added in a future iteration.
 * SMS-based OTP is explicitly NOT supported (per POL-SEC-009).
 */

import crypto from 'crypto';
import { createHmac } from 'crypto';

// ─── Configuration ───────────────────────────────────────────────────────────

const TOTP_PERIOD = 30;        // 30-second time step (RFC 6238)
const TOTP_DIGITS = 6;         // 6-digit OTP
const TOTP_WINDOW = 1;         // Allow 1 step before/after for clock skew
const SECRET_LENGTH = 20;      // 160-bit secret (recommended by RFC 4226)
const RECOVERY_CODE_COUNT = 10; // Number of single-use recovery codes
const RECOVERY_CODE_LENGTH = 8; // Characters per recovery code

const ISSUER = 'SolarPro';

// Roles that require MFA per POL-SEC-009
const MFA_REQUIRED_ROLES = ['admin', 'super_admin', 'staff'];

// ─── TOTP Secret Generation ─────────────────────────────────────────────────

/**
 * Generate a new TOTP secret (base32-encoded per RFC 4226).
 * This secret is shared between the server and the user's authenticator app.
 * Base32 is the standard encoding required by Google Authenticator, Authy, 1Password, etc.
 */
export function generateTOTPSecret(): string {
  const buffer = crypto.randomBytes(SECRET_LENGTH);
  // Base32 encoding: A-Z + 2-7, with padding stripped per TOTP URI convention
  return base32Encode(buffer);
}

/**
 * Base32 encode a Buffer per RFC 4648 (used by TOTP per RFC 4226).
 * Strips padding '=' characters — authenticator apps expect unpadded base32.
 */
function base32Encode(buffer: Buffer): string {
  const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = 0;
  let value = 0;
  let output = '';

  for (const byte of buffer) {
    value = (value << 8) | byte;
    bits += 8;

    while (bits >= 5) {
      output += ALPHABET[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }

  if (bits > 0) {
    output += ALPHABET[(value << (5 - bits)) & 31];
  }

  return output;
}

/**
 * Base32 decode a string per RFC 4648 (used by TOTP per RFC 4226).
 * Handles unpadded base32 (as generated by base32Encode).
 */
function base32Decode(input: string): Buffer {
  const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
  let bits = 0;
  let value = 0;
  const bytes: number[] = [];

  for (const char of input) {
    const idx = ALPHABET.indexOf(char.toUpperCase());
    if (idx === -1) continue; // skip padding or invalid chars
    value = (value << 5) | idx;
    bits += 5;

    if (bits >= 8) {
      bytes.push((value >>> (bits - 8)) & 255);
      bits -= 8;
    }
  }

  return Buffer.from(bytes);
}

/**
 * Encrypt a TOTP secret for storage in the database.
 * Uses AES-256-GCM with a key derived from MFA_ENCRYPTION_KEY env var.
 *
 * ⚠️ The MFA_ENCRYPTION_KEY must be a 256-bit (32-byte) base64-encoded key
 *    stored in Vercel environment variables. It must NEVER be committed to code.
 */
export function encryptTOTPSecret(secret: string): string {
  const key = process.env.MFA_ENCRYPTION_KEY;
  if (!key) {
    throw new Error('MFA_ENCRYPTION_KEY environment variable is required for TOTP secret encryption');
  }

  const keyBuffer = Buffer.from(key, 'base64');
  if (keyBuffer.length !== 32) {
    throw new Error('MFA_ENCRYPTION_KEY must be 32 bytes (256 bits) base64-encoded');
  }

  const iv = crypto.randomBytes(12); // 96-bit IV for GCM
  const cipher = crypto.createCipheriv('aes-256-gcm', keyBuffer, iv);

  let encrypted = cipher.update(secret, 'utf8', 'base64');
  encrypted += cipher.final('base64');

  const authTag = cipher.getAuthTag();

  // Format: iv:authTag:encrypted (all base64)
  return `${iv.toString('base64')}:${authTag.toString('base64')}:${encrypted}`;
}

/**
 * Decrypt a TOTP secret from database storage.
 */
export function decryptTOTPSecret(encryptedSecret: string): string {
  const key = process.env.MFA_ENCRYPTION_KEY;
  if (!key) {
    throw new Error('MFA_ENCRYPTION_KEY environment variable is required');
  }

  const keyBuffer = Buffer.from(key, 'base64');
  const parts = encryptedSecret.split(':');
  if (parts.length !== 3) {
    throw new Error('Invalid encrypted TOTP secret format');
  }

  const [ivB64, authTagB64, encryptedB64] = parts;
  const iv = Buffer.from(ivB64, 'base64');
  const authTag = Buffer.from(authTagB64, 'base64');

  const decipher = crypto.createDecipheriv('aes-256-gcm', keyBuffer, iv);
  decipher.setAuthTag(authTag);

  let decrypted = decipher.update(encryptedB64, 'base64', 'utf8');
  decrypted += decipher.final('utf8');

  return decrypted;
}

// ─── TOTP Code Generation and Verification ───────────────────────────────────

/**
 * Generate a TOTP code from a secret at a given timestamp.
 * Implements RFC 6238 with HMAC-SHA1.
 */
export function generateTOTPCode(secret: string, timestamp?: number): string {
  const time = Math.floor((timestamp ?? Date.now()) / 1000 / TOTP_PERIOD);
  const timeBuffer = Buffer.alloc(8);
  timeBuffer.writeUInt32BE(Math.floor(time / 0x100000000), 0);
  timeBuffer.writeUInt32BE(time & 0xffffffff, 4);

  // Decode base32 secret (standard encoding per RFC 4226)
  const secretBuffer = base32Decode(secret);

  const hmac = createHmac('sha1', secretBuffer);
  hmac.update(timeBuffer);
  const hmacResult = hmac.digest();

  // Dynamic truncation (RFC 4226 §5.3)
  const offset = hmacResult[hmacResult.length - 1] & 0x0f;
  const binary =
    ((hmacResult[offset] & 0x7f) << 24) |
    ((hmacResult[offset + 1] & 0xff) << 16) |
    ((hmacResult[offset + 2] & 0xff) << 8) |
    (hmacResult[offset + 3] & 0xff);

  const otp = binary % Math.pow(10, TOTP_DIGITS);
  return otp.toString().padStart(TOTP_DIGITS, '0');
}

/**
 * Verify a TOTP code against a secret with a time window for clock skew.
 *
 * SECURITY: Uses timing-safe comparison to prevent timing attacks.
 *
 * @returns true if the code is valid within the time window
 */
export function verifyTOTPCode(
  secret: string,
  code: string,
  timestamp?: number,
): boolean {
  const now = timestamp ?? Date.now();

  // Check current step and ±1 step for clock skew
  for (let delta = -TOTP_WINDOW; delta <= TOTP_WINDOW; delta++) {
    const stepTime = now + delta * TOTP_PERIOD * 1000;
    const expectedCode = generateTOTPCode(secret, stepTime);

    // Timing-safe comparison to prevent timing attacks
    if (timingSafeEqual(code, expectedCode)) {
      return true;
    }
  }

  return false;
}

/**
 * Timing-safe string comparison. Prevents timing attacks on TOTP codes.
 */
function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) {
    // Still perform comparison to maintain constant time
    const _ = crypto.timingSafeEqual(
      Buffer.from(a.padEnd(b.length, '0')),
      Buffer.from(b),
    );
    return false;
  }
  return crypto.timingSafeEqual(Buffer.from(a), Buffer.from(b));
}

// ─── Recovery Codes ──────────────────────────────────────────────────────────

/**
 * Generate a set of single-use recovery codes.
 * These allow account recovery if the user loses their authenticator device.
 */
export function generateRecoveryCodes(): string[] {
  const codes: string[] = [];
  for (let i = 0; i < RECOVERY_CODE_COUNT; i++) {
    const bytes = crypto.randomBytes(RECOVERY_CODE_LENGTH);
    // Use alphanumeric characters, grouped for readability
    const code = bytes.toString('base64url')
      .substring(0, RECOVERY_CODE_LENGTH)
      .toUpperCase();
    codes.push(code);
  }
  return codes;
}

/**
 * Hash a recovery code for storage. Uses SHA-256 (one-way).
 * Recovery codes are never stored in plaintext.
 */
export function hashRecoveryCode(code: string): string {
  return crypto.createHash('sha256').update(code).digest('hex');
}

/**
 * Verify a recovery code against its stored hash.
 * Uses timing-safe comparison.
 */
export function verifyRecoveryCode(code: string, storedHash: string): boolean {
  const codeHash = crypto.createHash('sha256').update(code).digest('hex');
  return crypto.timingSafeEqual(Buffer.from(codeHash), Buffer.from(storedHash));
}

// ─── MFA Enforcement ─────────────────────────────────────────────────────────

/**
 * Check if a user's role requires MFA per POL-SEC-009.
 * Admin and staff accounts must have MFA enabled.
 *
 * @returns true if MFA is required but not yet enabled for this user
 */
export function isMFARequiredButNotEnabled(role: string | null, mfaEnabled: boolean): boolean {
  if (!role) return false;
  return MFA_REQUIRED_ROLES.includes(role) && !mfaEnabled;
}

/**
 * Get the list of roles that require MFA.
 */
export function getMFARequiredRoles(): string[] {
  return [...MFA_REQUIRED_ROLES];
}

// ─── QR Code URI Generation ──────────────────────────────────────────────────

/**
 * Generate a TOTP URI for QR code enrollment.
 * Format: otpauth://totp/Issuer:email?secret=SECRET&issuer=Issuer
 * Compatible with Google Authenticator, Authy, 1Password, etc.
 */
export function generateTOTPUri(
  secret: string,
  email: string,
): string {
  const label = encodeURIComponent(`${ISSUER}:${email}`);
  const params = new URLSearchParams({
    secret,
    issuer: ISSUER,
    algorithm: 'SHA1',
    digits: String(TOTP_DIGITS),
    period: String(TOTP_PERIOD),
  });
  return `otpauth://totp/${label}?${params.toString()}`;
}
