// ═══════════════════════════════════════════════════════════════════════════
// Roadmap to November RE+ 2026 — Las Vegas Convention Center, Nov 16–19, 2026
// lib/roadmapRE26.ts
//
// Single source of truth for all the engineering, product, sales, and go-to-market
// deliverables we want shipped by the time doors open at RE+ 2026. Rendered at
// /admin/roadmap.
//
// To add a todo: paste a new entry into ROADMAP_ITEMS. To update status, flip the
// `status` field and bump `updatedAt`. To link a commit, add the commit hash to
// `commits[]`. This file is the database.
// ═══════════════════════════════════════════════════════════════════════════

/** Target show dates (LVCC): https://www.re-plus.com/about/future-dates/ */
export const RE_PLUS_2026 = {
  name: 'RE+ 2026',
  venue: 'Las Vegas Convention Center',
  startDate: '2026-11-16',
  endDate: '2026-11-19',
  tagline: 'Largest clean-energy event in North America',
  website: 'https://www.re-plus.com',
} as const;

// ─── Status / Priority / Track enums ─────────────────────────────────────
export type RoadmapStatus =
  | 'idea'        // captured, not yet planned
  | 'planned'     // accepted, on the board, not started
  | 'in-progress' // actively being worked
  | 'blocked'     // waiting on external input
  | 'done';       // shipped + verified

export type RoadmapPriority = 'p0' | 'p1' | 'p2' | 'p3';
//   p0 = release-critical   p1 = important   p2 = nice-to-have   p3 = future

export type RoadmapTrack =
  | 'brand-onboarding'
  | 'engineering-core'
  | 'compliance'
  | 'bom-pricing'
  | 'ui-ux'
  | 'proposal-flow'
  | 'api-integrations'
  | 'admin-ops'
  | 'go-to-market'
  | 'infrastructure';

export interface RoadmapItem {
  id: string;               // stable slug
  title: string;
  summary: string;          // 1-2 sentences
  track: RoadmapTrack;
  priority: RoadmapPriority;
  status: RoadmapStatus;
  /** Optional effort estimate for capacity planning. */
  effort?: 's' | 'm' | 'l' | 'xl';
  /** Git commit hashes that landed work on this item. */
  commits?: string[];
  /** Related filepaths for fast jump-to-source. */
  files?: string[];
  /** Free-form notes / decisions / context the next dev will need. */
  notes?: string;
  /** Dependencies on other roadmap ids. */
  dependsOn?: string[];
  /** ISO date strings. */
  createdAt: string;
  updatedAt: string;
  /** If `status === 'done'`, the target version/build that shipped it. */
  shippedIn?: string;
}

// ═══ Track metadata ═════════════════════════════════════════════════════
export const TRACK_META: Record<RoadmapTrack, { label: string; color: string; description: string }> = {
  'brand-onboarding': {
    label: 'Brand Onboarding',
    color: 'emerald',
    description: 'Adding new inverter / battery / panel brands to the registry with CI-enforced datasheet auditing.',
  },
  'engineering-core': {
    label: 'Engineering Core',
    color: 'blue',
    description: 'Sizing engine, string generator, compliance evaluator, auto-heal, panel compatibility gate.',
  },
  'compliance': {
    label: 'Compliance & NEC',
    color: 'amber',
    description: 'NEC 690.x / 705.x / 710.x compliance, permit packages, AHJ-specific rulesets.',
  },
  'bom-pricing': {
    label: 'BOM & Pricing',
    color: 'violet',
    description: 'Bill of materials generation, pricing, margin, proposal financials.',
  },
  'ui-ux': {
    label: 'UI / UX',
    color: 'pink',
    description: 'Engineering page, design page, proposal viewer, marketing polish.',
  },
  'proposal-flow': {
    label: 'Proposal Flow',
    color: 'sky',
    description: 'Customer-facing proposal rendering, signatures, handoff to install.',
  },
  'api-integrations': {
    label: 'API & Integrations',
    color: 'cyan',
    description: 'External APIs — Google Maps, SolarReviews, NREL PVWatts, utility rate feeds.',
  },
  'admin-ops': {
    label: 'Admin & Ops',
    color: 'slate',
    description: 'Admin portal, company management, activity log, system health.',
  },
  'go-to-market': {
    label: 'Go-to-Market',
    color: 'rose',
    description: 'Demo booth, marketing site, pricing page, onboarding docs, RE+ booth prep.',
  },
  'infrastructure': {
    label: 'Infrastructure',
    color: 'zinc',
    description: 'Build system, test suite, deployment, observability.',
  },
};

// ═══ Roadmap data ═══════════════════════════════════════════════════════
// Edit this list directly. Keep entries concise — this is a board, not a wiki.
export const ROADMAP_ITEMS: RoadmapItem[] = [
  // ─── DONE ────────────────────────────────────────────────────────────
  {
    id: 'v47.424-panel-auto-heal-pipeline',
    title: 'Panel auto-heal: advisory → authoritative',
    summary: 'When a panel is electrically incompatible with the selected brand, the compliance pipeline auto-rewrites config.inverters[].strings[].panelId so the engine sees a compliant design.',
    track: 'engineering-core',
    priority: 'p0',
    status: 'done',
    effort: 'l',
    commits: ['6f89817'],
    files: ['app/engineering/page.tsx', 'lib/system/panelAutoHeal.test.ts'],
    shippedIn: 'v47.424',
    createdAt: '2026-05-07',
    updatedAt: '2026-05-07',
  },
  {
    id: 'v47.425-onboarding-smoke-suite',
    title: 'Brand Onboarding Smoke Suite',
    summary: '317 CI-blocking tests that validate every registered brand end-to-end. Every future brand addition inherits all v47.418-v47.424 protections automatically.',
    track: 'brand-onboarding',
    priority: 'p0',
    status: 'done',
    effort: 'xl',
    commits: ['70b5b2f'],
    files: ['lib/system/brandOnboardingSmoke.test.ts', 'lib/system/brandOnboardingSmoke.helpers.ts', 'docs/BRAND-ONBOARDING.md'],
    shippedIn: 'v47.425',
    createdAt: '2026-05-08',
    updatedAt: '2026-05-09',
  },
  {
    id: 'v47.426-solis-tesla-tigo',
    title: 'Batch Brand Onboarding: Solis + Tesla + Tigo',
    summary: '13 new inverter SKUs across 3 brands in one commit, proving the onboarding model works. 317/317 smoke tests passed on first run.',
    track: 'brand-onboarding',
    priority: 'p0',
    status: 'done',
    effort: 'l',
    commits: ['6e35b0a'],
    files: [
      'lib/system/brandProfiles/solis.ts',
      'lib/system/brandProfiles/tesla.ts',
      'lib/system/brandProfiles/tigo.ts',
      'lib/solis-datasheet.test.ts',
      'lib/tesla-datasheet.test.ts',
      'lib/tigo-datasheet.test.ts',
    ],
    shippedIn: 'v47.426',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-10',
  },
  {
    id: 'v47.428-battery-ecosystem-smoke',
    title: 'Battery Ecosystem Smoke Suite + 6 battery SKUs',
    summary: '120 CI-blocking battery tests + 6 new datasheet-verified battery SKUs (Tigo EI/GO, BYD HVM, Pylontech Force-H2, EG4 PowerPro, HomeGrid Stackd). Dangling-recommendation tokens across 4 BrandProfiles trimmed.',
    track: 'brand-onboarding',
    priority: 'p1',
    status: 'done',
    effort: 'l',
    commits: ['028abfc', '4af6a27'],
    files: [
      'lib/system/batteryEcosystemSmoke.test.ts',
      'lib/system/batteryEcosystemSmoke.helpers.ts',
      'lib/equipment-db.ts',
    ],
    shippedIn: 'v47.428',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-11',
  },
  {
    id: 'v47.429-stage6-racking-visibility',
    title: 'Stage 6 — Racking Visibility in UI',
    summary: 'Racking becomes a first-class citizen of the ecosystem story: compatibleRacking in ResolvedBrandEquipment, new Racking section in EcosystemKitPanel, 174 CI-blocking tests (154 smoke + 20 audit lock), recommendedRackingBrands populated conservatively on 9 brand profiles.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 'l',
    commits: ['120300c'],
    files: [
      'lib/system/brandProfiles/types.ts',
      'lib/system/brandProfiles/resolveBrandEquipment.ts',
      'lib/system/rackingEcosystemSmoke.test.ts',
      'lib/system/rackingEcosystemSmoke.helpers.ts',
      'lib/racking-database.test.ts',
      'components/engineering/EcosystemPicker.tsx',
    ],
    shippedIn: 'v47.429',
    notes: 'Conservative mapping: only 9 profiles got recommendedRackingBrands (tesla, enphase, solaredge, sma, fronius, apsystems, hoymiles, ecoflow — generac/solis/sol-ark/growatt/tigo/sungrow/goodwe left empty until industry evidence). Dangling-token invariant (Global 2) mirrors the v47.428 battery pattern. Two racking DBs still coexist (mounting-hardware-db = UI, racking-database = structural engine) — consolidation is Stage 7/8.',
    createdAt: '2026-05-11',
    updatedAt: '2026-05-11',
  },

  {
    id: 'v47.430-solaredge-allocation-regression',
    title: 'v47.430 — SolarEdge Inverter Allocation Regression Fix (Optimizer Voltage-Clamp Bypass)',
    summary: 'User-reported regression: SolarEdge auto-generated 4 inverters where Sol-Ark correctly sized 2 for the same panel count. Root cause: voltageAwarePanelsPerUnit() in lib/system/sizingEngine.ts applied the NEC 690.7 cold-Voc clamp unconditionally, collapsing SolarEdge SE7600H panelsPerUnit from 1×2×25=50 to 1×2×10=20 and forcing ceil(72/20)=4 inverters instead of the correct ceil(72/50)=2. The optimizer bypass already existed in feasibilityEvaluator.ts (v47.411) and in the inner voltageAwareMaxPPS closure — but was missed in the top-level voltageAwarePanelsPerUnit() used by sizeInverters() for unit-count determination. Fix: topology parameter on voltageAwarePanelsPerUnit(); optimizer topology bypasses the cold-Voc clamp and returns mpptCount × maxParallelStringsPerMppt × brandMaxPPS (hardware ceiling). String/hybrid/micro retain the voltage clamp. vaPPU closure forwards brand.topology at every call site. Plus test-incompleteness fix in brandOnboardingSmoke.test.ts (nominalDcVoltage forwarded so operating current uses actual 400V bus instead of mpptCenter 340V). 4 new regression-lock tests. Brand-agnostic: any future optimizer-topology brand inherits the correct ceiling automatically.',
    track: 'engineering-core',
    priority: 'p0',
    status: 'done',
    effort: 's',
    files: [
      'lib/system/sizingEngine.ts',
      'lib/system/sizingEngine.test.ts',
      'lib/system/brandOnboardingSmoke.test.ts',
    ],
    shippedIn: 'v47.430',
    notes: 'Hotfix between v47.429 (Stage 6 racking) and Stage 5 continuation. Full suite 1808/1808 pass (+4 regression-locks). TC=0, build clean. Zero API changes — topology parameter is optional.',
    createdAt: '2026-04-22',
    updatedAt: '2026-04-22',
  },

  {
    id: 'v47.431-stage7-consolidation-assessment',
    title: 'v47.431 — Stage 7 Consolidation Assessment (READ-ONLY)',
    summary: 'Read-only audit producing docs/STAGE7_CONSOLIDATION_ASSESSMENT.md per UPGRADE_ROADMAP_v47.399.md mandate. Three audit areas: (1) BOM engine proliferation — identified ~2,228 lines of dead code across bom-engine.ts / bom-v2-engine.ts / bom-unified.ts / bom-merge.ts + orphan /api/engineering/bom-v2 route; one live engine is bom-engine-v4.ts. Recommended Stage 8.1 atomic deletion. (2) Racking DB duality — racking-database.ts (14 rows, 1 consumer: structural-engine-v3) vs mounting-hardware-db.ts (42 rows, 8 consumers including structural-engine-v4 and the entire UI/BOM/permit surface); 14/14 IDs overlap but fields differ. Both structural routes are live. Three options documented; recommended Option B (drift-fence CI test). (3) equipment-db vs brandProfiles spec duplication — ~360 drift points across 6 fields duplicated per SKU; recommended drift-fence CI test with overridesEquipmentDb opt-out rather than full refactor. Stage 8 scope recommendation: 8.1 (BOM deletion -2,228 lines) + 8.2 (drift-fence tests); defer 8.3 (racking unification) and 8.4 (brand-profile centralization). Zero code changes.',
    track: 'infrastructure',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    files: [
      'docs/STAGE7_CONSOLIDATION_ASSESSMENT.md',
      'docs/UPGRADE_ROADMAP_v47.399.md',
      'lib/version.ts',
      'lib/roadmapRE26.ts',
    ],
    shippedIn: 'v47.431',
    notes: 'Pure read-only audit. Full test suite unchanged (1808/1808 pass). Exit criteria: user chooses Stage 8 scope from the three documented options.',
    createdAt: '2026-04-22',
    updatedAt: '2026-04-22',
  },

  {
    id: 'v47.432-stage8-bom-deletion-drift-guards',
    title: 'v47.432 — Stage 8.1 + 8.2: BOM Dead-Code Deletion + Drift-Fence CI Tests',
    summary: 'Executes the Stage 7 recommended scope per user directive (low-risk: pure deletion + additive tests only). STAGE 8.1: deletes 7 orphan BOM files totalling -3,278 lines (lib/bom-engine.ts / bom-v2-engine.ts / bom-unified.ts / bom-merge.ts + app/api/engineering/bom-v2/route.ts + 2 dead test files bom-merge.test.ts + bom-unified.test.ts). The one live engine that remains is bom-engine-v4.ts. 21 dangling comment pointers across bom-system-profiles.ts (16), app/engineering/page.tsx (4), bom-engine-v4.ts (1) rewritten as v47.432-tagged historical attribution. STAGE 8.2: +273 CI tests across 2 new drift-guard files. rackingDatabaseDriftGuard.test.ts (45 tests) enforces manufacturer + systemType coarse-bucket + compatibleRoofTypes overlap for the 14 IDs shared by racking-database.ts and mounting-hardware-db.ts; 2 pre-existing divergences documented in EXPECTED_DIVERGENCES allowlist (ecofasten-rockit, esdec-flatfix). brandProfileDriftGuard.test.ts (228 tests) enforces acKw/dcKwMax/mpptCount/maxParallelStringsPerMppt equality between every BrandInverterModelRef and its canonical STRING_INVERTERS row, with new overridesEquipmentDb opt-out flag added to the BrandInverterModelRef type. 5 SKUs tagged with the opt-out (sungrow-sg15rs, sma-sb-10.0 intentional; sma-sb-7.7, goodwe-gw10k-ms, generic-string::se-7600h/se-10000h stale — TODO Stage 8.4). Test suite grows 1808 → 2075 net (+267 after -67 dead + 273 new). TC=0, npm run build clean (46/46 pages). Zero API changes, zero value changes to existing data.',
    track: 'infrastructure',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    files: [
      // Stage 8.1 deletions
      'lib/bom-engine.ts',
      'lib/bom-v2-engine.ts',
      'lib/bom-unified.ts',
      'lib/bom-merge.ts',
      'lib/bom-merge.test.ts',
      'lib/bom-unified.test.ts',
      'app/api/engineering/bom-v2/route.ts',
      // Stage 8.1 comment rewrites
      'lib/bom-system-profiles.ts',
      'lib/bom-engine-v4.ts',
      'app/engineering/page.tsx',
      // Stage 8.2 new drift-guards
      'lib/system/rackingDatabaseDriftGuard.test.ts',
      'lib/system/brandProfileDriftGuard.test.ts',
      // Stage 8.2 type flag + per-brand opt-out tags
      'lib/system/brandProfiles/types.ts',
      'lib/system/brandProfiles/sungrow.ts',
      'lib/system/brandProfiles/sma.ts',
      'lib/system/brandProfiles/goodwe.ts',
      'lib/system/brandProfiles/generic-string.ts',
      // Release artifacts
      'docs/UPGRADE_ROADMAP_v47.399.md',
      'lib/version.ts',
      'lib/roadmapRE26.ts',
    ],
    shippedIn: 'v47.432',
    notes: 'Stage 8.3 (racking unification) and Stage 8.4 (brand-profile centralization + reconcile 3 documented stale profile drifts) remain deferred per user directive. Drift-guard audit log surfaces the full override list on every CI run for review visibility.',
    createdAt: '2026-04-22',
    updatedAt: '2026-04-22',
  },

  // v47.433 — Stage 8.4 Brand-Profile Centralization
  {
    id: 'v47.433-stage8_4-brand-profile-centralization',
    title: 'v47.433 — Stage 8.4: Brand-Profile Centralization',
    summary: 'Closes the brand-profile drift backlog surfaced by the v47.432 drift-guard. Per user directive: fix the 3 stale drifts, align the 2 intentional overrides to registry, leave zero overridesEquipmentDb=true flags remaining. Six value corrections across 4 brand profiles (no code-logic changes): (1) generic-string.ts se-7600h and se-10000h mpptCount 2 → 1 (SolarEdge HD-Wave is single-MPPT per optimizer inverter); (2) sma.ts sma-sb-7.7 mpptCount 2 → 3 (v47.417 US-41 datasheet correction now propagated); (3) sma.ts sma-sb-10.0 maxParallel 1 → 6 (TL-US external combiner per datasheet; active:false SKU so zero live-project impact); (4) goodwe.ts goodwe-gw10k-ms acKw/dcKwMax/mpptCount 10.0/15.0/2 → 9.6/14.4/3 (v47.417 remap to GW9600-MS-US); (5) sungrow.ts sungrow-sg15rs maxParallel 1 → 2 (SG15RS datasheet; active:false SKU so zero live-project impact). ALL 6 overridesEquipmentDb=true flags removed; the drift-guard audit log now reports zero overrides on every CI run. The overridesEquipmentDb?:boolean field on BrandInverterModelRef is retained so future legitimate overrides have a documented mechanism. BOM accuracy impact: direct sizing improvement for three live-brand SKUs (SMA SB-7.7, GoodWe GW10K-MS, SolarEdge catch-all via generic-string). Every BOM, string-allocation, and compliance path downstream of BRAND_PROFILES inherits the fix automatically. Full suite 2075/2075 pass (same count as v47.432 — the drift-guard tests pass cleanly on the corrected values, confirming the corrections ARE the canonical registry values). TC=0, npm run build clean (46/46 pages). Stage 8.3 (racking unification) remains deferred.',
    track: 'infrastructure',
    priority: 'p1',
    status: 'done',
    effort: 's',
    files: [
      'lib/system/brandProfiles/generic-string.ts',
      'lib/system/brandProfiles/sma.ts',
      'lib/system/brandProfiles/goodwe.ts',
      'lib/system/brandProfiles/sungrow.ts',
      'docs/UPGRADE_ROADMAP_v47.399.md',
      'docs/stage8_4-todo.md',
      'lib/version.ts',
      'lib/roadmapRE26.ts',
    ],
    shippedIn: 'v47.433',
    notes: 'Stage 8.3 (racking unification) remains deferred. With Stage 8.4 complete, the core sizing + BOM layer is fully aligned with canonical equipment-db values. Next: site survey app integration.',
    createdAt: '2026-04-23',
    updatedAt: '2026-04-23',
  },

  // v47.434 — Stage 9.1 Survey Integration Schema + HMAC + Admin Log
  {
    id: 'v47.434-stage9_1-survey-integration-schema-hmac',
    title: 'v47.434 — Stage 9.1: Survey Integration Schema + HMAC Verifier + Admin Webhook Log',
    summary: 'First release of the in-house survey tool integration pipeline. v1 is inbound-only (survey backend → SolarPro, never reverse), thin-event webhook architecture per partner doc: survey tool POSTs minimal envelope { event, schemaVersion, event_id, survey_id, completed_at, survey_url? } with HMAC-SHA256(`${timestamp}.${rawBody}`, secret) signature; SolarPro verifies + logs + (in v47.435+) fetches full payload. v47.434 SHIPS the contract + auth skeleton, DEFERS the ingest pipeline to v47.435 (blocked on survey-team thin-event body confirmation + sample POST). Seven new files + one migration: (1) migrations/011_survey_ingest.sql adds projects.survey_external_id/origin/survey_category/survey_meta columns, project_files.external_id/status, and webhook_deliveries table with 4 indexes + 2 partial-unique idempotency indexes. (2) lib/survey/types.ts frozen v1.0 contract: SchemaVersion=1.0 literal, SurveyEventType=survey.completed literal, SurveyCompletedEvent, WebhookSignatureVerification with 5 reason codes, WebhookDeliveryStatus 6-member union, ProjectOrigin closed enum manual|bill_upload|survey|api. (3) lib/survey/verifyWebhookSignature.ts pure-function HMAC verifier, 5-min timestamp tolerance, constant-time compare via crypto.timingSafeEqual with length-mismatch short-circuit, injectable nowSeconds for deterministic tests. (4) app/api/webhooks/survey-complete/route.ts POST receiver: reads raw body (bytes-exact), verifies HMAC, narrow envelope validator, idempotency check on event_id, logs every delivery (valid or invalid) to webhook_deliveries, returns 501 INGEST_NOT_IMPLEMENTED on success path. (5) app/api/admin/survey-webhook-log/route.ts admin GET with status/source/limit filters. (6) app/api/admin/survey-webhook-log/[id]/replay/route.ts 501 stub (full impl v47.437). (7) app/api/migrate/route.ts inline migration block 011. Tests (+26 across 2 new files): verifyWebhookSignature.test.ts (18 tests covering valid, all 5 failure reason codes, length-mismatch short-circuit, replay defence via timestamp mismatch, byte-exactness, determinism, custom tolerance); contractDriftGuard.test.ts (8 tests locking CURRENT_SCHEMA_VERSION=1.0, SUPPORTED_SURVEY_EVENT_TYPES, PROJECT_ORIGIN_VALUES order + no duplicates + lowercase snake_case DB-text invariant, WebhookDeliveryStatus 6-member snapshot). Full suite 2101/2101 pass across 49 test files (+26 from v47.433 2075). TC=0, npm run build clean (46/46 pages + 3 new API routes registered). ZERO behavioural changes to existing projects/engineering/BOM/proposal paths — entirely additive surface.',
    track: 'api-integrations',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    files: [
      'migrations/011_survey_ingest.sql',
      'app/api/migrate/route.ts',
      'lib/survey/types.ts',
      'lib/survey/verifyWebhookSignature.ts',
      'lib/survey/verifyWebhookSignature.test.ts',
      'lib/survey/contractDriftGuard.test.ts',
      'app/api/webhooks/survey-complete/route.ts',
      'app/api/admin/survey-webhook-log/route.ts',
      'app/api/admin/survey-webhook-log/[id]/replay/route.ts',
      'docs/SURVEY_INTEGRATION_PROPOSAL_v1.md',
      'docs/stage9_v47434-todo.md',
      'docs/UPGRADE_ROADMAP_v47.399.md',
      'lib/version.ts',
      'lib/roadmapRE26.ts',
    ],
    shippedIn: 'v47.434',
    notes: 'Blocked on survey team for v47.435: thin-event body shape confirmation, sample webhook POST, and access to GET /api/surveys/{id} on survey backend. Stage 9.2 will ship the ingest/transform layer; 9.3 photos+notes; 9.4 contract doc + replay impl. Partner contract pivoted mid-design from pull (SolarPro initiates) to receive-then-fetch (survey pushes webhook, SolarPro fetches full payload) after partner shared actual survey-tool doc — architecture and implementation updated before any code shipped. Single-tenant v1 (SURVEY_INGEST_DEFAULT_USER_ID env var owns survey-origin rows).',
    createdAt: '2026-04-23',
    updatedAt: '2026-04-23',
  },

  // v47.435 — Stage 9.2 Ingest Pipeline Skeleton
  {
    id: 'v47.435-stage9_2-ingest-pipeline-skeleton',
    title: 'v47.435 — Stage 9.2: Ingest Pipeline Skeleton (Live DB Writes, Q2/Q3 Stubs)',
    summary: 'Wires the ingest pipeline into POST /api/webhooks/survey-complete with live DB writes. After HMAC verification + delivery INSERT, the route now calls runIngestPipeline() and returns 202 INGEST_OK (project upserted) or 202 INGEST_FAILED_BUT_LOGGED (pipeline error, delivery still accepted). NEVER throws. Partner never retries on pipeline-only failures — delivery is always logged; replay is the v47.437 recovery path. NEW MODULES (4 files in lib/survey/ingest/): (1) types.ts — IngestContext (clean context, no NextRequest), IngestResult discriminated union (ingested|failed), IngestStatus, IngestErrorCode 6-member enum (MISSING_OWNER_ID/LINK_RESOLUTION_FAILED/TRANSFORM_FAILED/DB_WRITE_FAILED/DELIVERY_UPDATE_FAILED/UNKNOWN), SurveyProjectLinkStrategy 3-member enum (CREATE_ORPHAN/ATTACH_TO_EXISTING/TRIAGE_QUEUE), LinkResolution discriminated union (attach/create/triage/error), TransformInput/Output/Summary/File, SurveyRawPayload opaque type (Q3 pending). (2) projectLinkResolver.ts — resolveProjectLink() pure function, no DB calls. Reads SURVEY_PROJECT_LINK_STRATEGY env var (case-insensitive, whitespace-trimmed, fallback CREATE_ORPHAN + console.warn). CREATE_ORPHAN: create with surveyExternalId=event.survey_id. ATTACH_TO_EXISTING: attach with partnerProjectId, degrades to triage when partnerProjectId=null. TRIAGE_QUEUE: triage all deliveries for ops review. (3) transformLayer.ts — pluggable transformer registry (registerTransformer/getTransformer/listRegisteredTransformers). Built-in v1.0/survey.completed transformer registered at module load. rawPayload=null stub: projectName="Survey <survey_id>", address/lat/lng=null, files=[]. rawPayload non-null: defensive candidate-key extraction. buildTransformSummary() for delivery row + response body. (4) ingestPipeline.ts — runIngestPipeline() orchestrator. Steps: A validate ownerId → B resolveProjectLink → C fetch payload STUB (rawPayload=null, Q2 blocked) → D transform → E upsert project + insert files → F UPDATE webhook_deliveries. Project upsert: INSERT ... ON CONFLICT (user_id, survey_external_id) WHERE survey_external_id IS NOT NULL DO UPDATE; xmax=0 → created=true. File insert: ON CONFLICT DO NOTHING. _markDeliveryFailed() best-effort. TRIAGE creates placeholder project with [TRIAGE] reason + requiresManualLinkage=true. TypeScript fix: if (transformResult.ok === false) required for discriminated union narrowing (not !transformResult.ok). MIGRATION 012 (migrations/012_survey_ingest_v2.sql + app/api/migrate/route.ts): webhook_deliveries.ingest_version TEXT, webhook_deliveries.ingest_summary JSONB, projects.survey_triage_reason TEXT, project_files.fetch_error TEXT, project_files.fetch_attempts INTEGER DEFAULT 0, project_files.mime_type TEXT; 3 new indexes. TESTS (+91 across 6 files, 4 new + 2 updated): types.test.ts (14), projectLinkResolver.test.ts (21), transformLayer.test.ts (37), ingestPipeline.test.ts (17 with vi.mock DB isolation), webhookResponseContract.test.ts updated (18), producerVersionContract.test.ts updated (12). Full suite: 2291/2291 pass across 59 files (+91 from v47.434c 2200). TC=0, npm run build clean (all 6 routes registered). ZERO CONTRACT-DRIFT-GUARD BREAKS.',
    track: 'api-integrations',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    files: [
      'lib/survey/ingest/types.ts',
      'lib/survey/ingest/projectLinkResolver.ts',
      'lib/survey/ingest/transformLayer.ts',
      'lib/survey/ingest/ingestPipeline.ts',
      'lib/survey/ingest/types.test.ts',
      'lib/survey/ingest/projectLinkResolver.test.ts',
      'lib/survey/ingest/transformLayer.test.ts',
      'lib/survey/ingest/ingestPipeline.test.ts',
      'migrations/012_survey_ingest_v2.sql',
      'app/api/migrate/route.ts',
      'app/api/webhooks/survey-complete/route.ts',
      'lib/survey/webhookResponseContract.test.ts',
      'lib/survey/producerVersionContract.test.ts',
      'docs/UPGRADE_ROADMAP_v47.399.md',
      'lib/version.ts',
      'lib/roadmapRE26.ts',
      'scripts/bump_version_v47435.py',
    ],
    shippedIn: 'v47.435',
    notes: 'All field mappings are Q3 stubs (SurveyRawPayload = Record<string, unknown>). Project linkage strategy is env-var-controlled (SURVEY_PROJECT_LINK_STRATEGY, default CREATE_ORPHAN) until Q8 answered. Full payload fetch from GET /api/surveys/{id} deferred until Q2 bearer auth answered. Async photo fetch worker deferred to v47.436. Handoff JWT minter deferred to Stage 9.2b. Replay admin action deferred to v47.437.',
    createdAt: '2026-04-23',
    updatedAt: '2026-04-23',
  },

  // ─── IN PROGRESS ─────────────────────────────────────────────────────
  {
    id: 'admin-roadmap-page',
    title: 'Admin roadmap page — "Road to RE+ 2026"',
    summary: 'This page. Centralizes every to-do with priority/track filters and a live countdown to the Nov 16 show.',
    track: 'admin-ops',
    priority: 'p1',
    status: 'done',
    effort: 's',
    shippedIn: 'v62.0',
    files: ['app/admin/roadmap/page.tsx', 'lib/roadmapRE26.ts'],
    notes: 'Full roadmap page with track/priority/status filters, live countdown timer to RE+ 2026, progress bars per track, and card detail expansion. Roadmap data lives in lib/roadmapRE26.ts.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-28',
  },

  // ─── PLANNED — BRAND ONBOARDING BATCHES ──────────────────────────────
  {
    id: 'brand-batch-residential-string',
    title: 'Residential string-inverter batch (Chint + Delta + Yaskawa Solectria)',
    summary: 'Three proper grid-tie PV string inverter brands with US market presence. Clean pattern repeat from v47.426.',
    track: 'brand-onboarding',
    priority: 'p1',
    status: 'planned',
    effort: 'l',
    notes: 'Path 2 decision from v47.427 research — avoids the inverter/charger architectural detour that Schneider/Victron/OutBack would require.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'brand-batch-inverter-chargers',
    title: 'Inverter/charger ecosystem (Schneider + OutBack + their MPPT controllers)',
    summary: 'Off-grid / whole-home backup specialists. Requires new BrandProfile variant where "inverter" is a paired PV charge controller. Victron probably skipped (marine/RV focus).',
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'planned',
    effort: 'xl',
    notes: 'Architectural wrinkle — XW Pro / MultiPlus-II / Radian are battery-based inverter/chargers with no PV MPPT on the unit. PV enters via Conext MPPT 100-600 / Victron SmartSolar RS / OutBack FLEXmax. Need to decide: model the charge controller as the "inverter" SKU, or extend BrandProfile with an optional `pairedMpptController` field.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'brand-batch-commercial-3phase',
    title: 'Commercial 3-phase string inverters (Chint CPS SCA/SCE + Solectria commercial + Delta M-series)',
    summary: 'Breaks us out of residential-only. Essential for RE+ commercial-leaning attendees.',
    track: 'brand-onboarding',
    priority: 'p1',
    status: 'planned',
    effort: 'l',
    notes: 'Of our current brands only Sungrow, SolarEdge, Fronius, and Sol-Ark 30K-3P-208V are 208/480V 3φ. Commercial is a huge growth vector.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'brand-sma-sunny-boy-smart-energy',
    title: 'Expand SMA with Sunny Boy Smart Energy hybrid line',
    summary: 'SMA has new hybrid inverters (SBSE 3.0-US / 3.8-US / 5.0-US / 6.0-US / 7.7-US) we should carry — our SMA entry is pure grid-tie.',
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'planned',
    effort: 'm',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'brand-fronius-gen24',
    title: 'Expand Fronius with Primo GEN24 Plus',
    summary: 'Fronius Primo GEN24 Plus (3.0/3.8/5.0/6.0/7.6/10.0) is the current-gen residential hybrid.',
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'planned',
    effort: 'm',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },

  // ─── PLANNED — BATTERY ECOSYSTEM ─────────────────────────────────────
  {
    id: 'battery-ecosystem-smoke-suite',
    title: 'Battery Ecosystem Smoke Suite',
    summary: 'Parallel of the v47.425 brand-onboarding suite — CI-blocking tests enforcing schema, plausibility, chemistry allowlist, warranty minimums, datasheet traceability, and brand-to-battery recommendation integrity (no dangling tokens). 120 CI-blocking tests.',
    track: 'brand-onboarding',
    priority: 'p1',
    status: 'done',
    effort: 'l',
    shippedIn: 'v47.428',
    commits: ['028abfc'],
    files: ['lib/system/batteryEcosystemSmoke.test.ts', 'lib/system/batteryEcosystemSmoke.helpers.ts'],
    notes: 'Discovered & fixed 6 dangling recommendation tokens across Solis/Sol-Ark/Growatt/EcoFlow BrandProfiles. Global 2 invariant now permanently prevents regression.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'battery-tigo-ei-battery',
    title: 'Tigo EI Battery + GO Battery SKUs',
    summary: 'Both Tigo battery families (EI DC-coupled HV @ 400V / GO modular HV @ 400V) added to registry with full datasheet audit tests. Paired with v47.426 Tigo EI Inverter onboarding.',
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'done',
    effort: 'm',
    shippedIn: 'v47.428',
    commits: ['028abfc'],
    files: ['lib/equipment-db.ts', 'lib/tigo-battery-datasheet.test.ts'],
    dependsOn: ['v47.426-solis-tesla-tigo'],
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'battery-byd-pylontech-hv',
    title: 'BYD HVM 11.0 + Pylontech Force-H2 HV batteries',
    summary: 'Third-party HV batteries (BYD 204.8V, Pylontech 384V) paired with Solis S6-EH1P HV ecosystem. Datasheet-audited and registered.',
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'done',
    effort: 'm',
    shippedIn: 'v47.428',
    commits: ['028abfc'],
    files: ['lib/equipment-db.ts', 'lib/byd-pylontech-datasheet.test.ts'],
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'battery-eg4-homegrid-lv',
    title: "EG4 PowerPro + HomeGrid Stack'd LV batteries",
    summary: "Third-party 48V LV batteries paired with Sol-Ark and Growatt hybrid ecosystems. EG4 PowerPro WallMount (14.3 kWh) and HomeGrid Stack'd 9.6 kWh both registered with datasheet audits.",
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'done',
    effort: 'm',
    shippedIn: 'v47.428',
    commits: ['028abfc'],
    files: ['lib/equipment-db.ts', 'lib/eg4-homegrid-datasheet.test.ts'],
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'battery-solax-hv',
    title: 'SolaX Triple Power HV battery SKUs',
    summary: 'SolaX Triple Power HV (T-BAT-SYS-HV-5.8/11.6) pairs with Solis S6-EH1P. Deferred from v47.428 until we can source an authoritative US datasheet.',
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'planned',
    effort: 's',
    notes: 'Trimmed from solis BrandProfile.recommendedBatteryBrands in v47.428. Re-add token once SKU lands.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'battery-pytes-fortress-lv',
    title: 'Pytes eFLEX + Fortress LV batteries',
    summary: '48V LV batteries popular in Sol-Ark installs. Deferred from v47.428. Fortress eFLEX and Pytes E-BOX/V48 SKUs with datasheet audits.',
    track: 'brand-onboarding',
    priority: 'p1',
    status: 'planned',
    effort: 'm',
    notes: 'Trimmed from sol-ark BrandProfile.recommendedBatteryBrands in v47.428. Re-add tokens once SKUs land.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'battery-growatt-apx-lg',
    title: 'Growatt APX HV + LG enblock/Prime batteries',
    summary: 'Native Growatt APX (5 kWh modules, 5-30 kWh HV stack) and LG Energy Solution Prime/enblock. Deferred from v47.428.',
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'planned',
    effort: 'm',
    notes: 'Trimmed from growatt BrandProfile.recommendedBatteryBrands in v47.428. EG4 PowerPro fills the gap per manufacturer datasheet cross-compatibility.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },

  // ─── PLANNED — ENGINEERING CORE ──────────────────────────────────────
  {
    id: 'engineering-cold-temp-correction',
    title: 'Site-specific cold-temp Voc correction (ASHRAE 2% data)',
    summary: 'Currently using a conservative -10°C across the board. Should pull ASHRAE 2% extreme minimum by zip/lat-long for more accurate Voc_cold and looser/tighter string limits.',
    track: 'engineering-core',
    priority: 'p2',
    status: 'planned',
    effort: 'l',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'engineering-shade-analysis',
    title: 'Roof shade analysis + per-panel derate',
    summary: 'Import roof model + sun path, compute per-panel shade factor, feed into sizing and production estimate.',
    track: 'engineering-core',
    priority: 'p2',
    status: 'planned',
    effort: 'xl',
    notes: 'Could leverage Google Solar API shade data as a starting point.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },

  // ─── PLANNED — COMPLIANCE ────────────────────────────────────────────
  {
    id: 'compliance-nec-2023-rollup',
    title: 'NEC 2023 rollup (690.12 Article update, 705.12 changes)',
    summary: 'Audit all rule references, confirm every violation code cites the 2023 edition clauses. Some states still use 2020.',
    track: 'compliance',
    priority: 'p1',
    status: 'planned',
    effort: 'm',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'compliance-ahj-ruleset-matrix',
    title: 'AHJ-specific ruleset matrix',
    summary: 'Some AHJs (CA Rule 21, HECO 14H, PREPA, NYC) impose tighter constraints than NEC alone. Add a per-AHJ overlay to the compliance engine.',
    track: 'compliance',
    priority: 'p2',
    status: 'planned',
    effort: 'l',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },

  // ─── PLANNED — BOM & PRICING ─────────────────────────────────────────
  {
    id: 'bom-wire-run-length-derivation',
    title: 'Derive wire run lengths from roof model',
    summary: 'Currently BOM uses a flat default per-string run. Real installs vary 30–150ft. Pull from roof topology + racking layout.',
    track: 'bom-pricing',
    priority: 'p1',
    status: 'planned',
    effort: 'l',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'bom-labor-cost-model',
    title: 'Regional labor cost model',
    summary: 'Labor is $X/panel-installed + $Y/kW-AC + $Z base, adjusted by state and roof complexity. Currently flat.',
    track: 'bom-pricing',
    priority: 'p1',
    status: 'planned',
    effort: 'l',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'bom-distributor-pricing-feed',
    title: 'Live distributor pricing feed (CED Greentech / Soligent / KWh)',
    summary: 'BOM line items now carry unitCost + totalCost from a 3-tier price catalog (catalog -> DB overrides -> category fallback). Admin CRUD API at /api/admin/distributor-prices. DB migration 015 seeds 21 platform defaults.',
    track: 'bom-pricing',
    priority: 'p1',
    status: 'done',
    effort: 'xl',
    commits: ['TBD'],
    files: [
      'lib/bom/distributorPricing.ts',
      'lib/migrations/015_distributor_prices.sql',
      'app/api/admin/distributor-prices/route.ts',
      'app/api/engineering/bom/route.ts',
      'lib/bom/distributorPricing.test.ts',
    ],
    createdAt: '2026-05-10',
    updatedAt: '2026-05-23',
    shippedIn: 'v49.0',
  },

  // ─── PLANNED — UI/UX ─────────────────────────────────────────────────
  {
    id: 'ui-ecosystem-picker-audit',
    title: 'Ecosystem picker audit — surface all new brands',
    summary: 'Walk every UI surface that filters or lists brands to ensure v47.426 (Solis/Tesla/Tigo) and future brands appear automatically.',
    track: 'ui-ux',
    priority: 'p2',
    status: 'planned',
    effort: 's',
    dependsOn: ['v47.426-solis-tesla-tigo'],
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'ui-proposal-polish',
    title: 'Proposal viewer polish — demo-ready',
    summary: 'Clean up /proposals/view/[id] for the RE+ demo booth. Should be screenshot-ready.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    shippedIn: 'v62.0',
    files: ['app/proposals/view/[id]/page.tsx'],
    notes: 'Share/copy-link button, Download PDF button in header, hero kW text-5xl, accepted banner with gradient + pulse ring, CTA celebration state with post-accept PDF + share buttons.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'engineering-ui-overhaul-v50',
    title: 'Engineering page — world-class UI overhaul (v50.0)',
    summary: 'Full UX overhaul: sticky glassy command bar with live KPI chips, project identity strip, animated compliance gauge, conductor flow diagram, system overview hero cards on Config/Compliance/Electrical/Schedule tabs, admin distributor prices UI.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 'xl',
    commits: ['TBD'],
    files: [
      'app/engineering/page.tsx',
      'app/admin/distributor-prices/page.tsx',
      'app/admin/AdminShell.tsx',
      'lib/version.ts',
    ],
    createdAt: '2026-05-23',
    updatedAt: '2026-05-23',
    shippedIn: 'v50.0',
  },

  {
    id: 'ui-elevation-v52',
    title: 'Real Content Elevation v52.0 — Card Grids & Premium Components',
    summary: 'Projects flat list → elevated card grid (per-status glow, pipeline progress bar, KPI tiles, grid/list toggle). Clients premium cards (hue avatar, sparkline, contact pills). Dashboard WorkQueueRow elevated with status stripe & glow.',
    status: 'done',
    priority: 'p1',
    track: 'ui-ux',
    createdAt: '2026-04-25',
    updatedAt: '2026-04-25',
    shippedIn: 'v52.0',
  },
  {
    id: 'ui-elevation-v51',
    title: 'Full-Stack UI Elevation v51.0',
    summary: 'Engineering tab heroes (structural/SLD/permit/files), AppShell glassmorphism, glass command headers across all major pages (dashboard, projects, clients, analytics, proposals, settings)',
    status: 'done',
    priority: 'p1',
    track: 'ui-ux',
    createdAt: '2026-04-25',
    updatedAt: '2026-04-25',
    shippedIn: 'v51.0',
  },

    // ── Shipped: v53–v56 Engineering Overhaul ─────────────────────────────────
    {
      id: 'engineering-audit-v54',
      title: 'Engineering page machine-level audit & rebuild (v54.0)',
      summary: 'buildCalcPayload() now pulls real panel dimensions/weight from equipment DB (was hardcoded). rackingWeight wired to rail spec. meanRoofHeight wired to ASCE 7-22 Kz calc. panelOrientation wired to structural calc. Roof attachment diagram full rebuild: 3-view SVG (Top-Down, Cross-Section, Isometric). Structural tab Site & Wind Parameters section added.',
      track: 'engineering-core',
      priority: 'p0',
      status: 'done',
      effort: 'l',
      commits: ['cd8e29c'],
      files: ['app/engineering/page.tsx', 'lib/structural-engine-v4.ts'],
      createdAt: '2026-04-25',
      updatedAt: '2026-04-25',
      shippedIn: 'v54.0',
    },
    {
      id: 'engineering-config-tab-v55',
      title: 'Config tab full UX overhaul (v55.0)',
      summary: '3-col responsive grid, SystemFlowBar flow diagram (Array→Inverter→AC→Disconnect→Panel + Battery/Generator), ENABLE_CONFIG_V2_UI feature flag, branch visualization bars, Battery/Generator collapsible cards, Engineering Summary panel with 6 KPI tiles + health grid, segmented topology control.',
      track: 'ui-ux',
      priority: 'p0',
      status: 'done',
      effort: 'xl',
      commits: ['1bd75c1'],
      files: ['app/engineering/page.tsx', 'lib/version.ts'],
      createdAt: '2026-04-25',
      updatedAt: '2026-04-25',
      shippedIn: 'v55.0',
    },
    {
      id: 'engineering-tab-overhaul-v56',
      title: 'Full tab UX overhaul — all 9 engineering tabs (v56.0)',
      summary: 'Compliance: rule accordion (FAIL/WARNING/PASS groups), severity heat map, pass rate ring, jurisdiction panel, auto-resolutions panel, 2-col layout. Electrical: conductor cards (AC conductor, conduit, disconnect, grounding), conduit schedule table, wire runs panel. Structural/Diagram/Schedule/Files: max-w-none. Permit: readiness ring + sheet status grid. BOM: hero strip with gradient. Field name regressions fixed post-ship.',
      track: 'ui-ux',
      priority: 'p0',
      status: 'done',
      effort: 'xl',
      commits: ['7208868', '9d93895', '247a9e7', 'f07ccac'],
      files: ['app/engineering/page.tsx', 'lib/version.ts'],
      createdAt: '2026-04-25',
      updatedAt: '2026-04-25',
      shippedIn: 'v56.0',
    },

    // ── Shipped: YOLO Vision Pipeline ─────────────────────────────────────────
    {
      id: 'vision-yolo-replace-roboflow',
      title: 'In-house YOLOv8 pipeline — replaces Roboflow (zero recurring API cost)',
      summary: 'Full YOLOv8 microservice: FastAPI POST /vision/infer + /health + /vision/model. infer.py core inference (URL or local → VisionDetection[]). train.py ultralytics training script (yolov8n.pt base). validate.py post-training metrics. Dockerfile + start.sh for containerized deploy. 8-class solar dataset structure (dataset.yaml, classes.txt, LABELING_GUIDE.md, split + validate scripts). ingestPipeline._runVisionPipelineAsync now calls VISION_SERVICE_URL/vision/infer instead of Roboflow API. Removes ROBOFLOW_API_KEY / ROBOFLOW_MODEL_ID dependencies. VisionDetection / VisionBoundingBox / VisionInferenceResult types (backward-compat @deprecated aliases kept).',
      track: 'infrastructure',
      priority: 'p1',
      status: 'done',
      effort: 'xl',
      commits: ['2bef0e8'],
      files: [
        'services/vision/server.py',
        'services/vision/infer.py',
        'services/vision/train.py',
        'services/vision/validate.py',
        'services/vision/Dockerfile',
        'services/vision/start.sh',
        'services/vision/requirements.txt',
        'datasets/solarvision/dataset.yaml',
        'datasets/solarvision/classes.txt',
        'datasets/solarvision/LABELING_GUIDE.md',
        'lib/vision/types.ts',
        'lib/vision/visionAggregator.ts',
        'lib/survey/ingest/ingestPipeline.ts',
      ],
      notes: 'VISION_SERVICE_URL env var must be set to the deployed FastAPI service URL (e.g. https://vision.yourdomain.com). Model weights not committed — train with train.py on labeled solar dataset or provide a pre-trained .pt file. 8 classes: panel, inverter, conduit, disconnect, meter, service_panel, attic_access, roof_vent.',
      createdAt: '2026-04-25',
      updatedAt: '2026-04-25',
      shippedIn: 'v48.x',
    },

  {
    id: 'ui-dark-mode-pass',
    title: 'Dark mode pass on engineering page',
    summary: 'Engineering page is the flagship screen — should look great in both themes.',
    track: 'ui-ux',
    priority: 'p2',
    status: 'done',
    effort: 's',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-23',
    shippedIn: 'v50.0',
  },
  {
    id: 'stage7-racking-db-consolidation-assessment',
    title: 'Stage 7 — Racking DB consolidation assessment (READ-ONLY)',
    summary: 'Two racking DBs coexist: mounting-hardware-db.ts (42 systems, UI-wired) and racking-database.ts (12 systems, structural engine only). Produce a written KEEP/MERGE/DEPRECATE recommendation. No code changes.',
    track: 'ui-ux',
    priority: 'p2',
    status: 'planned',
    effort: 's',
    dependsOn: ['v47.429-stage6-racking-visibility'],
    notes: 'Goal: decide whether consolidation is worth the risk before touching imports. v47.429 proved both DBs can coexist with guardrails — Stage 7 decides if that is good enough long-term.',
    createdAt: '2026-05-11',
    updatedAt: '2026-05-11',
  },
  {
    id: 'stage8-racking-db-consolidation-execution',
    title: 'Stage 8 — Racking DB consolidation execution (CONDITIONAL)',
    summary: 'Only executes if Stage 7 says consolidation is worth it. One DB file merged at a time, old file becomes re-export shim for one release, then removed.',
    track: 'ui-ux',
    priority: 'p3',
    status: 'planned',
    effort: 'l',
    dependsOn: ['stage7-racking-db-consolidation-assessment'],
    notes: 'Holds until Stage 7 delivers its verdict. If Stage 7 says KEEP, this item gets closed without execution.',
    createdAt: '2026-05-11',
    updatedAt: '2026-05-11',
  },
  {
    id: 'racking-brand-evidence-pass',
    title: 'Racking brand-pairing evidence pass (fill remaining BrandProfiles)',
    summary: 'Eight BrandProfiles currently have empty recommendedRackingBrands (generac, solis, sol-ark, growatt, tigo, sungrow, goodwe, generic-string). Research installer docs + certified-compatibility lists and populate where evidence is strong.',
    track: 'brand-onboarding',
    priority: 'p2',
    status: 'planned',
    effort: 'm',
    dependsOn: ['v47.429-stage6-racking-visibility'],
    notes: 'The Racking Ecosystem Smoke Suite (v47.429 Global 2) will automatically catch any dangling token the moment one is added without a backing manufacturer in mounting-hardware-db.',
    createdAt: '2026-05-11',
    updatedAt: '2026-05-11',
  },

  // ─── PLANNED — API & INTEGRATIONS ────────────────────────────────────
  {
    id: 'api-nrel-pvwatts',
    title: 'NREL PVWatts integration',
    summary: 'Replace static production estimate with a PVWatts call keyed by site lat/long, tilt, azimuth, shade factor.',
    track: 'api-integrations',
    priority: 'p1',
    status: 'planned',
    effort: 'm',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'api-google-solar-api',
    title: 'Google Solar API — roof geometry + shade',
    summary: 'Replace manual roof sketching with Google Solar API roof-segment data for any US address with coverage.',
    track: 'api-integrations',
    priority: 'p1',
    status: 'planned',
    effort: 'l',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'admin-utility-policy-seed',
    title: 'Utility Intelligence Database — comprehensive seed (120+ US utilities)',
    summary: 'Seeded real interconnection_limit_kw, buyback_rate, rate_structure, net_metering for 120+ major US utilities covering all 50 states. Migration 022 + seed_utility_policies system tool. Admin can re-seed anytime from System Tools.',
    track: 'api-integrations',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
    shippedIn: 'v63.1',
    commits: ['6e4e4b9'],
  },
  {
    id: 'api-utility-rate-feed',
    title: 'Utility rate feed (Genability or OpenEI)',
    summary: 'Auto-populate tariff, TOU schedule, and NEM rules by utility + zip. Currently manual. Foundation laid by admin-utility-policy-seed (120+ static entries); live feed would replace static seed with daily-refreshed rates.',
    track: 'api-integrations',
    priority: 'p1',
    status: 'planned',
    effort: 'l',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },

  // ─── PLANNED — PROPOSAL FLOW ─────────────────────────────────────────
  {
    id: 'proposal-digital-signature',
    title: 'Digital signature on proposals (DocuSign or native)',
    summary: 'Customer should be able to e-sign the proposal from the proposal-viewer page. Triggers contract state + install handoff.',
    track: 'proposal-flow',
    priority: 'p1',
    status: 'planned',
    effort: 'l',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'proposal-pdf-export',
    title: 'PDF export of proposal',
    summary: 'One-click "Download as PDF" for sharing via email when the customer isn\'t ready to sign in-portal.',
    track: 'proposal-flow',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    shippedIn: 'v62.0',
    files: [
      'app/api/proposals/[id]/pdf/route.ts',
      'lib/proposal/buildCanonicalProposal.ts',
      'lib/proposal/renderProposalHTML.ts',
    ],
    notes: 'GET+POST /api/proposals/[id]/pdf. Uses wkhtmltopdf with HTML fallback for Vercel serverless. Rate-limited, auth+share-token access. Download button wired in proposal viewer (handleDownloadPdf in ui-proposal-polish).',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-28',
  },

  // ─── PLANNED — GO-TO-MARKET ──────────────────────────────────────────
  {
    id: 'gtm-replus-booth-prep',
    title: 'RE+ 2026 booth prep — demo script + fallback flows',
    summary: 'Rehearsed 5-minute and 15-minute demos with known-good project fixtures. Screenshot-ready pages. Offline mode in case LVCC wifi tanks.',
    track: 'go-to-market',
    priority: 'p0',
    status: 'done',
    effort: 'l',
    shippedIn: 'v63.0',
    files: [
      'REPLUS_2026_BOOTH_PREP.md',
      'public/offline-demo/index.html',
    ],
    notes: '5-min + 15-min demo scripts, objection-handling cheatsheet, persona playbook, screenshot-ready page reference, offline HTML snapshot at public/offline-demo/index.html (serves locally with npx serve). Booth setup + end-of-day reset checklists. Wi-Fi contingency for LVCC.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-28',
  },
  {
    id: 'gtm-marketing-site',
    title: 'Marketing site (solarpro.com landing pages)',
    summary: 'Public-facing site — hero, features, pricing, signup. Separate from the app.',
    track: 'go-to-market',
    priority: 'p1',
    status: 'planned',
    effort: 'l',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'gtm-pricing-page-live',
    title: 'Pricing page — Stripe subscription wiring',
    summary: 'Currently a static display. Wire to Stripe subscriptions for real plan changes.',
    track: 'go-to-market',
    priority: 'p1',
    status: 'planned',
    effort: 'm',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'gtm-demo-account-seeder',
    title: 'Demo-account seeder (reset-to-golden-state)',
    summary: 'One-click "reset demo account" that drops in 3 golden projects (residential retrofit, new-construction, commercial) for booth demos.',
    track: 'go-to-market',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    shippedIn: 'v63.0',
    files: [
      'app/api/admin/system-tools/route.ts',
      'app/admin/system-tools/page.tsx',
    ],
    notes: 'seed_demo_account tool case in system-tools route — accepts userEmail or userId, soft-deletes old [demo]-tagged projects, creates 3 golden clients+projects+layouts (Mitchell Residence 10.4kW roof Phoenix, Greenfield Lot 14 8.0kW roof Austin, RML Warehouse 49.6kW ground Denver). Violet Demo Account Seeder card in admin UI with email input + confirm modal.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-28',
  },

  // ─── PLANNED — ADMIN / OPS ───────────────────────────────────────────
  {
    id: 'admin-company-self-serve',
    title: 'Company self-serve onboarding',
    summary: 'Installer companies should be able to sign up without an admin invite. Logo upload, crew roster, default pricing, first project wizard.',
    track: 'admin-ops',
    priority: 'p1',
    status: 'planned',
    effort: 'xl',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'admin-activity-log-search',
    title: 'Activity log search + filters',
    summary: 'Current activity log is a firehose. Needs search by user/company/action and a date range.',
    track: 'admin-ops',
    priority: 'p2',
    status: 'done',
    effort: 's',
    shippedIn: 'v63.0',
    files: [
      'app/api/admin/activity-log/route.ts',
      'app/admin/activity-log/page.tsx',
    ],
    notes: 'API now accepts targetEmail, dateFrom, dateTo params with ISO date validation and safe ILIKE SQL. UI adds 4-column filter bar (action, target email, date from, date to) with active-filter chip display and clear-all button.',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-28',
  },

  // ─── PLANNED — INFRASTRUCTURE ────────────────────────────────────────
  {
    id: 'infra-ci-cd-pipeline',
    title: 'CI/CD pipeline — auto-deploy on merge to master',
    summary: 'Currently manual deploys. Hook a GitHub Action to run the full vitest suite + tsc + build, then deploy on green.',
    track: 'infrastructure',
    priority: 'p1',
    status: 'planned',
    effort: 'm',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'infra-observability',
    title: 'Observability — error tracking + perf monitoring',
    summary: 'Sentry for errors, Vercel Analytics or similar for perf. Essential before RE+ so we can see live booth-demo errors in real time.',
    track: 'infrastructure',
    priority: 'p1',
    status: 'planned',
    effort: 'm',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },

  // ─── v60.x (April 2026 sprint — save/restore + site-survey SSO) ──────
  {
    id: 'v60.4a-engineering-workspace-save-restore',
    title: 'Engineering workspace: Save/Restore pipeline',
    summary: 'Manual Save button in the sticky header, 800ms debounced autosave on config change, DB restore on page load with localStorage fallback. Fixes the long-standing "I lost my work" complaint.',
    track: 'ui-ux',
    priority: 'p0',
    status: 'done',
    effort: 'm',
    commits: ['a9d85b8'],
    files: ['app/engineering/page.tsx', 'app/api/engineering/save-config/route.ts'],
    shippedIn: 'v60.4a',
    createdAt: '2026-04-28',
    updatedAt: '2026-04-29',
  },
  {
    id: 'v60.4a-pre-existing-gate-cleanup',
    title: 'Fix pre-existing TS/lint/test drift',
    summary: 'Widened projectId (number → string|number), fixed capabilities test to match security removal of sharedSecretEnvVar, cast JSON.parse in site-survey upload. Result: typecheck 0, lint 0, tests 2573→2576.',
    track: 'infrastructure',
    priority: 'p0',
    status: 'done',
    effort: 's',
    commits: ['3e0f47d', 'b3c130a'],
    files: [
      'lib/engineering-automation.ts',
      'app/api/engineering/assist/route.ts',
      'app/api/site-survey/upload/route.ts',
      'lib/system/capabilities.test.ts',
    ],
    shippedIn: 'v60.4a',
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
  },
  {
    id: 'v60.4a-site-survey-pipeline-audit',
    title: 'Site-survey pipeline audit (7 findings)',
    summary: 'Full end-to-end audit of the site-survey → engineering pipeline. Found: (1) desktop Start-Survey dead-ends at sitesurvey:// deep link, (2) /api/site-survey/upload is dead code with missing target table, (3) 4 of 5 override modules have 0 callers, (4) engineering reads 4 of 20 physical_data fields, (5) two parallel pipelines with divergent DB targets, (6) no SSO for "survey from scratch", (7) contract drift between survey-app handoff docs and live code (X-Signature vs X-Survey-Signature).',
    track: 'engineering-core',
    priority: 'p0',
    status: 'done',
    effort: 'm',
    commits: ['0a3a572'],
    files: ['SURVEY_PIPELINE_AUDIT.md'],
    shippedIn: 'v60.4a',
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
  },
  {
    id: 'v60.5-site-survey-sso-authorize',
    title: 'Site-survey SSO: /api/auth/authorize endpoint',
    summary: 'OAuth-style authorize endpoint for the Expo mobile app. Validates redirect_uri against AUTHORIZE_ALLOWED_REDIRECTS allowlist, mints HS256 JWT (10 min TTL) with {sub, solarpro_user_id, email, name, iat, exp, jti}, records jti in mobile_sso_used_jtis for replay protection, 302-redirects to <redirect_uri>?token=<jwt>&state=<state>. Rate-limited, CSRF-safe (GET + bearer token only).',
    track: 'api-integrations',
    priority: 'p0',
    status: 'done',
    effort: 'l',
    commits: ['411298a'],
    files: [
      'app/api/auth/authorize/route.ts',
      'migrations/015_mobile_sso_jti.sql',
    ],
    shippedIn: 'v60.5',
    notes: 'SolarPro is the ONLY system that owns users, projects, and engineering data. Mobile app (B) and Render survey API (C) both now MUST trust this endpoint as the single source of identity truth.',
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
  },
  {
    id: 'v60.5-per-event-project-link-routing',
    title: 'Per-event project-link routing (Q8 answered)',
    summary: 'projectLinkResolver now per-event: if webhook carries solarpro_project_id → attach; if absent → auto-create project under the SSO user (Case 2: "user logs in from scratch" flow). TRIAGE_QUEUE env still honoured as the ops pause-everything override. +3 new unit tests; 2 existing tests updated for new contract.',
    track: 'engineering-core',
    priority: 'p0',
    status: 'done',
    effort: 'm',
    commits: ['411298a'],
    files: [
      'lib/survey/ingest/projectLinkResolver.ts',
      'lib/survey/ingest/projectLinkResolver.test.ts',
    ],
    shippedIn: 'v60.5',
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
  },
  {
    id: 'v60.5-survey-integration-contract',
    title: 'Site-survey integration contract + smoke test',
    summary: 'Canonical 3-party contract (SolarPro A / Mobile B / Render C) documenting auth flow, JWT claims, webhook HMAC rules, env vars, trust rules. End-to-end smoke test script (login → authorize → decode JWT → Case-2 auto-create → Case-1 attach).',
    track: 'api-integrations',
    priority: 'p0',
    status: 'done',
    effort: 'm',
    commits: ['411298a', 'e7ea6e0'],
    files: [
      'docs/SITE_SURVEY_SSO_CONTRACT.md',
      'scripts/smoke-test-sso.sh',
    ],
    shippedIn: 'v60.5',
    notes: 'e7ea6e0 corrected a webhook-header/HMAC divergence between my doc and kilby8/site_survey-app handoff docs (commit a503b096). Live code is authoritative — header family is X-Survey-*, HMAC is over `${timestamp}.${rawBody}`.',
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
  },
  {
    id: 'v60.5-full-system-audit-valuation',
    title: 'Full system audit + valuation (website + survey monorepo)',
    summary: 'Evidence-based audit of both codebases: 783 source files, ~256 700 prod LOC, 193 API endpoints, 16 wired pipelines, 2 576 passing tests. Valuation band: $25M tech-floor → $60-100M realistic upside. Comparables: Aurora Solar ($4B), Enerflo (~$150M), Scanifly (~$75M), OpenSolar (~$200-400M).',
    track: 'go-to-market',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    commits: ['1fced09'],
    files: ['docs/FULL_SYSTEM_AUDIT_AND_VALUATION.md'],
    shippedIn: 'v60.5',
    notes: 'Flagged diligence item: confirm IP/ownership arrangement between rayobrian6/Solarpro and kilby8/site_survey-app (either co-founder IP-assignment or license agreement).',
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
  },

  // ─── v60.x — BLOCKED ON PARTNER TEAMS ────────────────────────────────
  {
    id: 'v60.6-mobile-loginscreen-sso-swap',
    title: 'Mobile B: swap LoginScreen SSO URL → /api/auth/authorize',
    summary: 'One-line URL change in mobile/src/screens/LoginScreen.tsx plus deep-link handler for sitesurvey://login?token=&state=. Current button points at the legacy /mobile-login bridge. Owned by kilby8 team (B).',
    track: 'api-integrations',
    priority: 'p0',
    status: 'planned',
    effort: 's',
    notes: 'Handoff doc shipped by partner bot: kilby8 commit a503b096 docs/HANDOFF_B_MOBILE_SSO_INTEGRATION.md. Play pipeline now unblocked (internal draft live, version 5). SSO URL swap itself still pending implementation by B team. Partner also baked EXPO_PUBLIC_API_URL into app.json (commit 762ff86a) and added ADI signing + keystore flow (commit 6413dc96).',
    dependsOn: ['v60.5-site-survey-sso-authorize'],
    createdAt: '2026-04-29',
    updatedAt: '2026-05-28',
  },
  {
    id: 'v60.6-render-jwt-verify-middleware',
    title: 'Render C: JWT-verify middleware on /surveys endpoints',
    summary: 'Add Authorization: Bearer <jwt> verification using SOLARPRO_HANDOFF_SECRET (HS256) on /surveys POST. Extract solarpro_user_id from verified JWT — IGNORE any device-supplied user id. Webhook outbox already correct (no changes needed).',
    track: 'api-integrations',
    priority: 'p0',
    status: 'planned',
    effort: 's',
    notes: 'Handoff doc shipped by partner bot: kilby8 commit a503b096 docs/HANDOFF_C_RENDER_API_INTEGRATION.md. JWT middleware implementation itself still pending on C team (Render backend). Partner also confirmed API URL baked into app config (https://site-survey-api-bpyz.onrender.com) and Play internal draft submitted successfully.',
    dependsOn: ['v60.5-site-survey-sso-authorize'],
    createdAt: '2026-04-29',
    updatedAt: '2026-05-28',
  },
  {
    id: 'v60.6-play-pipeline',
    title: 'Android Play pipeline — EAS submit to internal draft',
    summary: 'EAS cloud build + automated submit to Google Play internal track (draft). gcloud ADC configured, service account linked, API unblocked, signing via keystore, ADI registration file added.',
    track: 'infrastructure',
    priority: 'p0',
    status: 'done',
    effort: 'm',
    shippedIn: 'v60.6',
    commits: ['a503b096', '2e99ce5d', '3c428c36', '6413dc96', '762ff86a'],
    notes: 'Shipped by partner bot (kilby8/site_survey-app). Play internal draft live at version code 5. EAS submit configured: android.track=internal, android.releaseStatus=draft. API URL baked into app.json (https://site-survey-api-bpyz.onrender.com). Privacy policy (PRIVACY_POLICY.md) and NDA template (NDA_TEMPLATE_UTS.md) added for store requirements.',
    createdAt: '2026-04-29',
    updatedAt: '2026-05-28',
  },
  {
    id: 'v60.6-end-to-end-smoke-test',
    title: 'Run end-to-end smoke test against staging',
    summary: 'Execute scripts/smoke-test-sso.sh against solarpro-dev.vercel.app + Render staging. Proves: login → authorize → JWT claims → jti recorded → Case-2 auto-create → Case-1 attach. Final verification step for v60.6.',
    track: 'infrastructure',
    priority: 'p0',
    status: 'planned',
    effort: 's',
    dependsOn: [
      'v60.6-mobile-loginscreen-sso-swap',
      'v60.6-render-jwt-verify-middleware',
    ],
    createdAt: '2026-04-29',
    updatedAt: '2026-05-28',
  },

  // ─── v60.x — FOLLOW-UP CLEANUP (flagged by audit) ───────────────────
  {
    id: 'v60.x-delete-dead-site-survey-upload',
    title: 'Delete dead /api/site-survey/upload endpoint',
    summary: 'Audit flagged: endpoint writes to a project_site_surveys table that was never created by any migration. Zero production callers. Safe to delete. 1-day PR.',
    track: 'engineering-core',
    priority: 'p2',
    status: 'done',
    effort: 's',
    shippedIn: 'v63.0',
    files: ['app/api/site-survey/upload/route.ts'],
    notes: 'Deleted app/api/site-survey/upload/route.ts (465 lines). Zero callers confirmed by grep. project_site_surveys table never existed in any migration. Empty upload/ and site-survey/ dirs also removed.',
    createdAt: '2026-04-29',
    updatedAt: '2026-05-28',
  },
  {
    id: 'v60.x-wire-or-delete-override-modules',
    title: 'Wire or delete unused siteSurvey/ override modules',
    summary: 'Audit flagged: 4 of 5 modules in lib/siteSurvey/ (applyToSystemDefinition, buildCADFromSurvey, permitIntegration, electricalFromSurvey) have ZERO callers in production routes. Decide: wire them into the engineering-generate flow, or delete them.',
    track: 'engineering-core',
    priority: 'p2',
    status: 'planned',
    effort: 'l',
    files: [
      'lib/siteSurvey/applyToSystemDefinition.ts',
      'lib/siteSurvey/buildCADFromSurvey.ts',
      'lib/siteSurvey/permitIntegration.ts',
      'lib/siteSurvey/electricalFromSurvey.ts',
    ],
    notes: 'See SURVEY_PIPELINE_AUDIT.md finding #3. Likely a wiring task, not a rebuild — the code itself is solid.',
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
  },
  {
    id: 'v60.x-consume-remaining-physical-data-fields',
    title: 'Engineering: consume remaining 16 physical_data fields',
    summary: 'Audit flagged: 20 fields captured by the survey app, only 4 (panel_rating_amps, rafter_spacing_in, roof_material, interconnection_point) are read by the engineering report. 16 fields are captured but discarded. Largest lever for improving engineering output quality.',
    track: 'engineering-core',
    priority: 'p1',
    status: 'planned',
    effort: 'xl',
    files: ['lib/engineering/reportGenerator.ts'],
    notes: 'See SURVEY_PIPELINE_AUDIT.md finding #4. Multi-week effort: each field needs its own engineering-logic hook (roof_pitch → structural load calc, panel_brand → BOM hint, etc).',
    createdAt: '2026-04-29',
    updatedAt: '2026-04-29',
  },

  // \u2500\u2500\u2500 v57.0 \u2014 SECURITY AUDIT (21 PHASES) 
  {
    id: 'v57.0-security-audit-phases-21-38',
    title: 'Comprehensive security audit \u2014 Phases 21\u201338 (46 fixes across 149 API routes)',
    summary: 'Full security sweep of all 149 API routes across 21 audit phases. Phase 21: 46 fixes (missing auth guards, input validation gaps, response leakage). Phase 22: rate limits, plan validation, PII log scrubbing, pricing auth. Phase 23: bill pipeline PII + prompt injection fixes. Phase 24: seed password hardening. Phase 25: remove JWT token from auth/me cookie logs. Phase 26: bcrypt DoS caps, open redirect fix, magic bytes on logo upload, rateLimiter expansion. Phase 27/27b: rate limiting on all 149 mutation routes including 16 previously missed. Phase 29: magic bytes on all file uploads, engineering route hardening, CSRF webhook exclusion. Phase 30/30b: UUID validation on all dynamic route params and body IDs. Phases 33\u201338: delete dangerous debug routes, UUID sweep, auth on unauthenticated mutations, timing-safe comparisons, global security response headers, static rate-limit imports (81 files), replace execSync with execFileSync.',
    track: 'infrastructure',
    priority: 'p0',
    status: 'done',
    effort: 'xl',
    commits: ['1890b41', '8ae28f7', '1243f93', 'cfae4ac', '4fa9e73', '3079be1', 'd9ed73f', '50f3d51', '23c6e7c', '0273b12', 'a89c604', '660e673', 'be4a20a', '0f15bb5', '66b50e5', '5d3e340'],
    files: ['next.config.js', 'lib/rateLimiter.ts'],
    shippedIn: 'v57.0',
    notes: '76-phase audit completed. Phases 21-38 shipped in this batch. Zero known vulnerabilities remaining in auth, authorization, input validation, file upload, rate limiting, or info disclosure.',
    createdAt: '2026-05-01',
    updatedAt: '2026-05-01',
  },
  {
    id: 'v57.1-security-audit-phases-62-76',
    title: 'Security audit completion \u2014 Phases 62\u201376 (final hardening + full report)',
    summary: 'Phase 62: numeric input validation + HTML escaping in SLD/PDF. Phase 63: Stripe webhook secret guard, rate-limit placement. Phase 64: account deletion UUID validation + self-deletion guard. Phases 65\u201369: open redirect, mass assignment, SSRF, command injection, prototype pollution \u2014 all clean. Phase 70: JWT HS256 enforcement + fix impersonation token URL leakage (POST body instead of query param). Phase 71: crypto.randomBytes replaces Math.random() for temp password generation. Phase 72: no stack traces in responses, debug routes admin-gated. Phase 73: cookie security \u2014 HttpOnly, Secure (prod), SameSite=Lax verified. Phase 74: CSP, HSTS, X-Frame-Options, Permissions-Policy, COEP/CORP verified in next.config.js. Phase 75: dependency audit \u2014 8 HIGH CVEs documented (all DoS/dev-only), picomatch/flatted overrides added. Phase 76: SECURITY_AUDIT_FINAL.md covering all 76 phases, 42 fixes, architecture properties.',
    track: 'infrastructure',
    priority: 'p0',
    status: 'done',
    effort: 'xl',
    commits: ['838e949', 'f5af513', 'ee9b006', 'f8a5031', '697bc2b', 'b30f875', '00132ee', '0b0ce97', '282a574', '248aba7', 'f32fab1', '0696b02', 'e87f783', '08ebad8', 'de51207'],
    files: ['docs/SECURITY_AUDIT_FINAL.md', 'next.config.js'],
    shippedIn: 'v57.1',
    notes: 'Final security posture: 42 real fixes across 76 phases. Remaining recommendations: Next.js 15 upgrade (CVE resolution), WAF layer for production.',
    createdAt: '2026-05-02',
    updatedAt: '2026-05-02',
  },

  // \u2500\u2500\u2500 v58.0 \u2014 SLD SYMBOL SYSTEM + WIRING FOUNDATION 
  {
    id: 'v58.0-sld-symbol-system-wiring',
    title: 'SLD engineering-grade symbol system + wiring foundation (v58.0\u20131)',
    summary: 'Complete ground-up rebuild of the Single Line Diagram renderer. v58.0: Engineering-grade symbol system v2.0 \u2014 all 18 symbols rebuilt at 2x scale with readable geometry. Hybrid realism v3.0 \u2014 realistic equipment cabinets + IEEE schematic infrastructure. Wiring foundation v1.0 \u2014 anchor contracts, routing engine, flow rules. Conductor-based rendering \u2014 one line per electrical conductor. SOT renderer \u2014 symbol sizes from SLD_SYMBOL_MAP, anchor-based wiring. WireEnvironment, conductor callouts, string summary, battery pipeline fix (phases 1\u20136). Multi-string DC conductor count and rendering corrected. Admin /admin/sld-emblems reference page. Ecosystem truth fix (8-phase): optimizer/disco/topology/conductor. v58.1: SLD Layout Architecture \u2014 grid engine, font hierarchy, spacing constants. SLD Audit Fix \u2014 conductor count, callout accuracy, EGC, THWN-2. 9-phase engineering accuracy fix. Neutral conductor on AC inverter feeder added.',
    track: 'engineering-core',
    priority: 'p0',
    status: 'done',
    effort: 'xl',
    commits: ['7585f78', 'fa063f1', 'f482243', '447c669', '450fa3c', '8e2c76f', '25041f9', 'e29da68', '51c09e0', '96a7aa5', '97eaa5a', '3c60f87', '5dcbeb6', '3ee0e77', 'a3bd26f', '947227a', '1ee572e'],
    files: ['lib/sld/sld-symbols.ts', 'lib/sld/renderer.ts', 'app/admin/sld-emblems/page.tsx'],
    shippedIn: 'v58.1',
    notes: 'All 18 IEC/NEC standard symbols at 2x resolution. Wiring engine is anchor-contract based \u2014 each symbol declares terminal points, router connects them deterministically. NEC 690.8 conductor ampacity, EGC sizing, and conduit fill all verified.',
    createdAt: '2026-05-03',
    updatedAt: '2026-05-03',
  },

  // \u2500\u2500\u2500 v58.7 \u2014 BATTERY/BUI PIPELINE + DEVICE ILLUSTRATIONS 
  {
    id: 'v58.7-battery-bui-pipeline-device-illustrations',
    title: 'Battery/BUI pipeline + device illustrations + survey ownership (v58.7\u201320)',
    summary: 'v58.7: Redesign ecosystem change button; engineering pipeline audit doc. v58.8: Auto-enable battery toggle when ecosystem applies a battery. v58.9: Battery symbol moved up 80px \u2014 no longer overlaps MSP/BUI. Brand audit complete \u2014 46 registry entries, all 13 brands verified in BOM pipeline. v58.10: Restore batteryEnabled on refresh from saved config. v58.11: BUI first-class SLD node between MSP and utility meter. v58.12: batteryEnabled hydration reads savedConfig directly. v58.13: Preserve ecosystem battery on Apply Recommended Configuration. v58.14: EcoFlow OCEAN Pro onboarded into ecosystem picker. v58.15: Brand emblems for inverter and battery symbols + Brand Emblems admin page. v58.16: Device illustrations for all 9 brands across 4 phases (Tesla Powerwall, EcoFlow OCEAN Pro, Tesla Gateway 2, EcoFlow Smart Home Panel, Enphase, SolarEdge, Generac, Sol-Ark, Growatt, Solis, APsystems, Hoymiles). v58.17: Neutral conductor on AC feeder. v58.18: Brand-aware BUI rendering for all 7 registered brands; BUI wiring corrected (MSP busOut\u2192BUI GRID and BUI LOAD\u2192Meter). v58.19: 3D render performance (reduce API calls, caching, tile MSE tuning). v58.20: Full survey ownership pipeline \u2014 JWT claims forwarding, admin reassign API, Fix Owner + Fix All Defaults UI, 4-strategy owner resolution, webhook log backfill.',
    track: 'engineering-core',
    priority: 'p0',
    status: 'done',
    effort: 'xl',
    commits: ['25569f9', '5df8a55', '0c349e8', '612226e', '731bebc', '79a53c4', '71da097', '9ba76b7', '3e304ae', 'cc3fb46', 'fb4627e', 'c93dcc7', '13f0bea', '4a68de8', 'b9a4067', '09ecc15', 'd3400f6', '3615e29', 'c143465', '095601d', 'b99a356', 'ed6271d', '77f563d', '0c0fc48', '026fe46', '848b826', 'e15a25c', 'ae61cce', '4035898', 'e7ddce0', 'ade32a3'],
    files: ['lib/sld/renderer.ts', 'components/engineering/EcosystemPicker.tsx', 'app/admin/sld-emblems/page.tsx', 'app/api/surveys/admin/page.tsx'],
    shippedIn: 'v58.20',
    notes: 'BUI (Backup Interface Unit) is now a first-class electrical node for all 7 battery brands. EcoFlow OCEAN Pro is the 10th battery ecosystem. Device illustrations bring the SLD to permit-submission quality. Survey ownership pipeline ensures field surveys land in the correct user account regardless of JWT claim timing.',
    createdAt: '2026-05-04',
    updatedAt: '2026-05-04',
  },

  // \u2500\u2500\u2500 v59.0 \u2014 ENGINEERING PAGE UX COMPACT 
  {
    id: 'v59.0-engineering-ux-compact',
    title: 'Engineering page audit + UI compact (v59.0\u20131)',
    summary: 'v59.0: Engineering audit + full UI compact pass \u2014 systemType dropdown corrected for all 3 mount types (roof/ground/fence), utilityMeter default fixed, batteryEnabled BOM payload corrected, battery/generator disabled states compacted. v59.1: Battery Storage card moved to right column top \u2014 eliminates dead space in System Config tab and puts the most-used setting at the top of the panel.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    commits: ['06d8f4d', '348623d'],
    files: ['app/engineering/page.tsx'],
    shippedIn: 'v59.1',
    notes: 'systemType dropdown was missing ground/fence options. utilityMeter was defaulting to a non-null value that inflated BOM cost. batteryEnabled payload fix ensures battery line items appear correctly in proposals.',
    createdAt: '2026-05-05',
    updatedAt: '2026-05-05',
  },

  // \u2500\u2500\u2500 v61.0 \u2014 INVERTER STRING PIPELINE UNIFICATION 
  {
    id: 'v61.0-inverter-string-pipeline',
    title: 'Inverter string pipeline unification + hydration stale-config fix (v61.2\u20139)',
    summary: 'Root-cause fix for the inverter configuration contamination bug where stale string configs from a previously loaded project would bleed into newly loaded ones. v61.2: Display Mode + Single Source of Truth for strings UI; strings dropdown + Change Project button fixed; reconcile stringsPerInverter vs inv.strings on hydration; audit 44x1 strings root cause; broaden corruption detector + panel-fix path; sync metadata on all rebuild paths. v61.3: Lock Architecture \u2014 all 8 phases complete. v61.4: Hydration Lock \u2014 normalizeInverterConfig + runtime guard + SolarDog truth lock. v61.5: Final Lock \u2014 all inverter mutations route through _buildInvCfg. v61.6: String Commit Integrity \u2014 electrical normalization. v61.7: String Pipeline Unification \u2014 single source of truth; Config Overwrite Kill Switch (isUserControlled master lock). v61.8: ROOT CAUSE FIX \u2014 hydration stale inverter config contamination confirmed and resolved; ROOT_CAUSE_AUDIT.md updated with final PASS verdict. v61.9: Clipping/Inverter Upsizing Audit + Fix. v61.10: Fix 24 failing tests (jest\u2192vi.spyOn + Sungrow RS activation).',
    track: 'engineering-core',
    priority: 'p0',
    status: 'done',
    effort: 'xl',
    commits: ['a395efa', 'cada02f', '73371f6', '097cf92', '7f4849a', 'c850961', '23a2313', '33d7267', 'bddabb6', 'afee5f5', '709373e', '1925b6f', 'd1f53b2', '20fe2f8', '17f3f23', 'a22891c'],
    files: ['app/engineering/page.tsx', 'lib/system/inverterConfig.ts', 'lib/system/stringPacking.ts'],
    shippedIn: 'v61.10',
    notes: 'isUserControlled kill switch prevents any automated pipeline from overwriting a user-set inverter config. normalizeInverterConfig is the single chokepoint for all hydration paths. ROOT_CAUSE_AUDIT.md documents the exact contamination vector and proves the fix.',
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
  },
  {
    id: 'v61.11-ecoflow-ecosystem-string-packing',
    title: 'EcoFlow OCEAN Pro + string packing + hydration gate (v61.11\u201313e)',
    summary: 'v61.11: Compact String Packing Fix \u2014 strings now pack to exact panel count without over-allocating inverter capacity. v61.12: EcoFlow Legacy Model Bypass Fix + hydration gate that discards stale active:false inverter configs on project load. v61.13: EcoFlow active-model selection fix (5 root-cause patches) \u2014 OCEAN Pro multi-unit support, tier boundary fixes, sizing advisory, hybrid-aware DC/AC floor fix, ASHRAE design temperatures in jurisdiction.ts corrected for NEC 690.7 cold-Voc accuracy. v61.13b: Fix Apply Recommended Configuration button broken in guided/manual mode.',
    track: 'engineering-core',
    priority: 'p0',
    status: 'done',
    effort: 'l',
    commits: ['8fd6406', 'cf56fce', '1e13e62', '406beca', '7497b71', 'de5a8fc', '1d7a621', '9491d67'],
    files: ['lib/system/stringPacking.ts', 'lib/system/ecoflow.ts', 'lib/jurisdiction.ts'],
    shippedIn: 'v61.13e',
    notes: 'ASHRAE design temperature fix is safety-critical \u2014 cold-Voc overvoltage is a NEC 690.7 code violation. EcoFlow OCEAN Pro supports multi-unit parallel stacking; sizing advisory now correctly accounts for hybrid inverter DC/AC floor requirements.',
    createdAt: '2026-05-06',
    updatedAt: '2026-05-06',
  },

  // \u2500\u2500\u2500 v61.14 \u2014 SOLARDOG AI ASSISTANT \u2500\u2500\u2500\u2500
  {
    id: 'v61.14-solardog-ai-assistant',
    title: 'SolarDog AI assistant \u2014 full build + context injection + knowledge base (v61.14\u201317)',
    summary: 'SolarDog is the in-app AI assistant \u2014 a knowledgeable solar sales/engineering helper living as a floating widget. Previous versions (v10.1\u201311): Think/Decide/Act master prompt, selective learning, real conversation, auth debug, honest memory, screen context, website knowledge base, wired into app layout. v61.14: UX polish \u2014 positioning, context-aware action buttons, personality fix. v61.15: New system prompt \u2014 CORE IDENTITY, PRIMARY JOBS, RESPONSE STYLE, PERSONALITY, FAILSAFE; widget positioning fixed (20px bottom). v61.16: Context Injection Layer \u2014 UI_MAP, WORKFLOW, buildContext, suggestedActions; enriched system prompt (KNOWLEDGE MODEL, CREATOR MODE, DATA USAGE RULES, BEHAVIOR EXAMPLES, ADAPTIVE INTELLIGENCE, GOAL). v61.17: Knowledge base seed \u2014 solardog_knowledge DB table created, knowledge seed data, simplified system prompt.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 'xl',
    commits: ['bdfba73', 'a3702af', '1c61640', 'cac7a1b', '6932028', '2e005fb', '1219753', 'fcc6435', '5955da8', 'e8249e2', 'a63a3d4', '51edcee', '8d6ead6', 'fb3641c'],
    files: ['components/SolarDog.tsx', 'app/api/solardog/chat/route.ts', 'lib/solardog/buildContext.ts'],
    shippedIn: 'v61.17',
    notes: 'SolarDog replaced the previous SolarAIBot widget. Knowledge base is seeded from solardog_knowledge DB table so responses are grounded in real product data. Context injection layer means SolarDog knows what page the user is on and what project they have loaded.',
    createdAt: '2026-05-07',
    updatedAt: '2026-05-07',
  },

  // \u2500\u2500\u2500 v61.18 \u2014 HOMEOWNER PORTAL + LEAD SYSTEM 
  {
    id: 'v61.18-homeowner-portal-lead-system',
    title: 'Homeowner portal + admin lead system (full build)',
    summary: 'Complete homeowner-facing portal plus a structured lead management system for admins. Admin Lead System: lead capture pipeline, /admin/leads page, lead creation modal, assign-owner UI, allow leads without user_id for admin creation. Homeowner Portal: /portal/login + /portal/dashboard, homeowner_stage column + admin stage management UI, premium dashboard (Phase 4), elite redesign (Phase 5/5.2), milestone feed + doc checklist on homeowner portal + admin preview, Phase 4.14.2 milestone integration UX, Phase 4.12 micro-stage hardening, Phase 4.11 micro-stage engine. Portal session cookie fixed (Path=/ so session reaches /api/portal/* routes). Admin portal dashboard projects API fix. Public lead capture page with dynamic contact info. Document visibility sections.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 'xl',
    commits: ['405a01c', '2601357', '0312a59', '225f276', 'b224bb2', '718ecba', '216b9b5', 'a500b4f', '89b0e9a', '89e0a8f', 'dac3c8c', 'f7574a3', '24d11d9', '1d5a4eb', '377c348', 'cb267fc', '0a494fc', 'a74a4af', 'b43fe4e', 'eb55b56', 'c914fff', 'd47b8f0', '669d235'],
    files: ['app/portal/login/page.tsx', 'app/portal/dashboard/page.tsx', 'app/admin/leads/page.tsx', 'app/api/portal/**'],
    shippedIn: 'v61.18',
    notes: 'Homeowner portal is fully isolated from the installer app (separate /portal/* routes, separate cookie namespace). The milestone stage system (not_started \u2192 proposal \u2192 signed \u2192 install \u2192 complete) is admin-managed. Lead capture page is publicly accessible without login.',
    createdAt: '2026-05-07',
    updatedAt: '2026-05-07',
  },

  // \u2500\u2500\u2500 v61.19 \u2014 LANDING PAGE + ONBOARDING + RESPONSIVE 
  {
    id: 'v61.19-landing-onboarding-responsive',
    title: 'Landing page overhaul + new-user onboarding tour + 5-phase responsive pass',
    summary: 'Full landing page overhaul \u2014 new marketing homepage at / with hero, features, social proof, and CTA. Middleware fix \u2014 added "/" to PUBLIC_PATHS so landing page stopped redirecting all visitors to login. New-user onboarding tour via SolarDog \u2014 first-login users get a guided app walkthrough. 5-phase responsive pass: Phase 1 auto-collapse sidebar on viewports <1280px, Phase 2 dashboard grid breakpoints + heading sizes, Phase 3 projects + clients KPI bar breakpoints, Phase 4 design studio panel widths shrink on <xl screens, Phase 5 engineering page padding responsive. Header notification dropdown fix \u2014 was rendering behind main content (z-index). React hydration fix \u2014 eliminate errors #418/#423/#425 on every page. Bill upload UX \u2014 elevate manual entry as primary CTA on parse failure.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 'l',
    commits: ['697a5fe', 'a220407', '98f2097', '4f2d6f6', 'b6b458c', '6ae87ca', '899049b', '76af8a8', 'c85555b', '5130f13', '9e1802c'],
    files: ['app/page.tsx', 'middleware.ts', 'app/layout.tsx', 'components/sidebar/Sidebar.tsx'],
    shippedIn: 'v61.19',
    notes: 'Landing page is now the public face of SolarPro \u2014 unauthenticated users see it, authenticated users route to /dashboard. Sidebar auto-collapses at 1280px so the app is usable on 13" laptops without horizontal scroll.',
    createdAt: '2026-05-07',
    updatedAt: '2026-05-07',
  },

  // \u2500\u2500\u2500 v61.20 \u2014 3D DESIGN STUDIO OVERHAUL 
  {
    id: 'v61.20-3d-design-studio-overhaul',
    title: '3D design studio \u2014 camera, toolbar, rail visualization, sidebar restructure',
    summary: 'Major 3D design studio overhaul. Camera: restored smooth pan/tilt with middle-mouse; full free-camera control (orbit, tilt, zoom, pan unrestricted); disabled collision detection so tilt goes past 45\u00b0 freely. Toolbar: replaced horizontal overflow strip with vertical icon sidebar; 3D toolbar scrolls on smaller screens; 15 tools condensed to 4 collapsible grouped flyout buttons with tooltips above buttons. Surface pick: nudge pickPosition 0.15m along surface normal to prevent points clipping inside roof mesh. Shade slider: now shows local solar time 5am\u201310pm (was UTC midnight\u20132pm). Address autocomplete on Quick Launch \u2014 fly to correct rooftop on first entry. Rail visualization Phase 1+2: system-aware panel offset + XR100 rail visualization; multiple geometry fixes using ECEF corners (span from actual placed-panel edges, geodetic cluster extent, axis-aware row grouping, projection-based rail span). Sidebar restructure: System Summary promoted to top, Calculate Production + Generate Proposal always visible without scrolling.',
    track: 'ui-ux',
    priority: 'p0',
    status: 'done',
    effort: 'xl',
    commits: ['6d28d0a', '13aaf0a', '8431d6f', 'ce975f8', '154d308', 'cf3a2c5', 'f3128a1', '37e1318', 'a17541f', '2418d6e', 'e127839', '2abb6fa', '1eb00fa', '6bedbb1', '1fce925', '7652434', '34be337', 'f5248ed', '1bf8647', 'b131e27', '8ef342d', 'bd6f026', '4366dc2'],
    files: ['components/design/DesignStudio.tsx', 'lib/3d/railVisualization.ts', 'lib/3d/camera.ts'],
    shippedIn: 'v61.20',
    notes: 'Camera collision detection disabled by user request \u2014 allows full sky/nadir views for roof angle assessment. Rail visualization uses ECEF coordinate math to span rails across actual placed-panel edges. Sidebar restructure ensures Calculate Production + Generate Proposal are always reachable without scrolling.',
    createdAt: '2026-05-08',
    updatedAt: '2026-05-08',
  },

  // \u2500\u2500\u2500 v63.1 \u2014 AUTH & ACCOUNT STABILITY \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  {
    id: 'v63.1-auth-infinite-reset-loop-fix',
    title: 'Fix: auth infinite password-reset loop for free-pass accounts',
    summary: 'Users with is_free_pass=true and a bcrypt-12 real hash were being re-routed to force-reset on every login due to Safety Net B over-matching. Fixed the Safety Net B predicate to trigger only on cost-10 placeholder hashes. Also replaced router.push() with window.location.href on login redirect so UserContext re-mounts cleanly after sign-in \u2014 eliminating stale-state loops where the nav bar would not reflect the logged-in user.',
    track: 'ui-ux',
    priority: 'p0',
    status: 'done',
    effort: 's',
    commits: ['2a6cde5', '92b7aa6', '67bd9d2'],
    files: [
      'app/api/auth/login/route.ts',
      'app/auth/login/page.tsx',
    ],
    shippedIn: 'v63.1',
    notes: 'Safety Net B condition narrowed from any bcrypt hash to cost-10 placeholder only (regex /^\\$2[aby]\\$10\\$/).  Login page redirect changed from router.push() to window.location.href to force full React tree remount and prevent stale UserContext.  Verified against raymond.obrian@yahoo.com test account.',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
  },
  {
    id: 'v63.1-free-pass-account-db-repair',
    title: 'DB repair: clear stale is_free_pass flag for 5 real-password accounts',
    summary: 'Five accounts (jeff@solfence.solar, googleplay.reviewer@solarpro.solutions, austinhancock47@gmail.com, michaelorrmusic@gmail.com, rayobrian6@gmail.com) had is_free_pass=true combined with bcrypt-12 hashes \u2014 meaning they had already set a real password but were still being treated as free-pass grants. Cleared is_free_pass=false for all five directly in Neon DB. Complements the Safety Net B code fix.',
    track: 'admin-ops',
    priority: 'p0',
    status: 'done',
    effort: 's',
    commits: [],
    files: [],
    shippedIn: 'v63.1',
    notes: 'DB surgery via psycopg2. Accounts audited: Group B (bcrypt-12 + is_free_pass=true) \u2014 4 users; Group C (legacy hash + is_free_pass=true) \u2014 1 user (rayobrian6@gmail.com). Group A (cost-10 placeholder, never set real password \u2014 5 users) left unchanged; Safety Net B on dev correctly routes them to Forgot Password flow.',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
  },

  // \u2500\u2500\u2500 v63.2 \u2014 CHANGE SYSTEM TYPE UI \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  {
    id: 'v63.2-change-system-type-ui',
    title: 'Allow users to change system type (Roof / Ground / Fence) after project creation',
    summary: 'Previously users who accidentally selected the wrong panel-placement method (Roof Mount, Ground Mount, or Fence Mount) during project creation had no way to correct it without creating a whole new project. Added a clickable pencil-badge on the system-type pill in the project detail header and a \"Change\" link inside DesignTab\'s System Configuration panel. Both open a modal that lets the user pick a new type; the change atomically updates both the projects and layouts tables via the existing /api/projects/[id]/repair-system-type endpoint. Current type is grayed-out with a checkmark; a warning is shown if existing layout rows would be cleared.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 'm',
    commits: ['fac8d73'],
    files: [
      'app/projects/[id]/page.tsx',
      'components/project/DesignTab.tsx',
    ],
    shippedIn: 'v63.2',
    notes: 'Used existing /api/projects/[id]/repair-system-type POST endpoint \u2014 no new API needed. Modal auto-opens when ?changeType=1 query param is present, enabling deep-link from DesignTab. Pencil icon from lucide-react.',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
  },

  // \u2500\u2500\u2500 v63.3 \u2014 ADDRESS AUTOCOMPLETE SITE-WIDE \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  {
    id: 'v63.3-address-autocomplete-site-wide',
    title: 'Address autocomplete (type-ahead) on New Project and Edit Client pages',
    summary: 'Users had to type addresses manually in the New Project and Edit Client forms with no suggestions. Replaced the plain <input> fields on both pages with the existing AddressAutocomplete component (backed by /api/geocode?mode=autocomplete, 300 ms debounce, keyboard-navigable). On New Project, selecting a suggestion immediately triggers resolveAddress() to populate lat/lng, utility zone, and irradiance data \u2014 no extra blur step needed. On Edit Client, selecting a suggestion auto-fills city, state, and zip fields via POST /api/geocode. Site-wide parity: every address input now has live type-ahead suggestions.',
    track: 'ui-ux',
    priority: 'p1',
    status: 'done',
    effort: 's',
    commits: ['aba8e75'],
    files: [
      'app/projects/new/page.tsx',
      'app/clients/[id]/edit/page.tsx',
    ],
    shippedIn: 'v63.3',
    notes: 'AddressAutocomplete component was already used on app/design/page.tsx and components/design/DesignStudio.tsx. This commit extends coverage to the two remaining user-facing address fields. Clearing the field also clears locationData/utilityData state on New Project.',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
  },

  // \u2500\u2500\u2500 v63.4 \u2014 CSS INPUT ICON OVERLAY FIX \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  {
    id: 'v63.4-css-input-icon-overlay-fix',
    title: 'Fix: leading icon overlaying first character in .input fields',
    summary: 'Across many pages (address autocomplete, client search, project search, city/state inputs) the leading icon was visually overlapping the first character of typed text \u2014 e.g. a MapPin icon covering the \"1\" of \"123 Main St\". Root cause: the global .input CSS class used @apply px-3 as plain-CSS, which Tailwind resolved at component build time and beat the pl-8/pl-9 padding-left utilities applied inline for icon offset. Fix: wrapped .input inside @layer components in globals.css so Tailwind\'s utility layer always overrides the component base \u2014 no changes to any component files required.',
    track: 'infrastructure',
    priority: 'p1',
    status: 'done',
    effort: 's',
    commits: ['e251b2b'],
    files: ['app/globals.css'],
    shippedIn: 'v63.4',
    notes: 'Fix: @layer components { .input { @apply ... px-3 ... } }. Utilities (pl-8, pl-9, pr-8) now always win per Tailwind cascade rules (base \u2192 components \u2192 utilities). Fixes AddressAutocomplete (pl-8/pr-8), clients/new (pl-9), clients/page search (pl-9), projects/page search (pl-9), and all future .input + pl-* combos.',
    createdAt: '2026-05-09',
    updatedAt: '2026-05-09',
  },

  // ─── IDEAS (parking lot) ─────────────────────────────────────────────
  {
    id: 'idea-ev-charger-ecosystem',
    title: 'EV charger ecosystem (Tesla Wall Connector, Enphase IQ EV, ChargePoint)',
    summary: 'Add EVSE as a first-class BOM line item with brand-based ecosystem pairing.',
    track: 'brand-onboarding',
    priority: 'p3',
    status: 'idea',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'idea-heat-pump-sizing',
    title: 'Heat-pump sizing module',
    summary: 'Solar + storage + heat-pump electrification package pricing.',
    track: 'engineering-core',
    priority: 'p3',
    status: 'idea',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
  {
    id: 'idea-mobile-app',
    title: 'Mobile crew app (installer-facing)',
    summary: 'Strip install-crew workflow out of the desktop app. Punch-list, photo capture, commissioning sign-off on iOS/Android.',
    track: 'ui-ux',
    priority: 'p3',
    status: 'idea',
    createdAt: '2026-05-10',
    updatedAt: '2026-05-10',
  },
];

// ═══ Derived helpers ════════════════════════════════════════════════════

export function getRoadmapCounts() {
  const by = {
    byStatus:   {} as Record<RoadmapStatus, number>,
    byPriority: {} as Record<RoadmapPriority, number>,
    byTrack:    {} as Record<RoadmapTrack, number>,
    total: ROADMAP_ITEMS.length,
  };
  for (const item of ROADMAP_ITEMS) {
    by.byStatus[item.status]     = (by.byStatus[item.status] ?? 0) + 1;
    by.byPriority[item.priority] = (by.byPriority[item.priority] ?? 0) + 1;
    by.byTrack[item.track]       = (by.byTrack[item.track] ?? 0) + 1;
  }
  return by;
}

/** Milliseconds remaining until RE+ 2026 doors open (Nov 16, 2026 08:00 PT). */
export function msUntilReplus(now: Date = new Date()): number {
  // Show opens Monday Nov 16, 2026. Use 09:00 PT (= 17:00 UTC) as anchor.
  const target = Date.UTC(2026, 10, 16, 17, 0, 0); // month is 0-indexed
  return target - now.getTime();
}

export function formatCountdown(ms: number): { days: number; hours: number; minutes: number; seconds: number; past: boolean } {
  const past = ms < 0;
  const abs = Math.abs(ms);
  const days    = Math.floor(abs / 86_400_000);
  const hours   = Math.floor((abs % 86_400_000) / 3_600_000);
  const minutes = Math.floor((abs % 3_600_000) / 60_000);
  const seconds = Math.floor((abs % 60_000) / 1000);
  return { days, hours, minutes, seconds, past };
}