// lib/version.ts -- SolarPro Build Version
export const BUILD_VERSION     = 'v47.20';
export const BUILD_DATE        = '2026-06-14';
export const BUILD_DESCRIPTION = 'v47.20: Full reliability audit -- vitest test suite (25 tests), env-var startup validation, DB health check endpoint (/api/health/database), GitHub Actions CI pipeline (test+lint+typecheck+build gate)';
export const BUILD_FEATURES    = [
  // v47.20 -- Full reliability audit + deployment safety
  'NEW: tests/bill-upload.test.ts -- 25 vitest unit tests covering parseBill(), parseBillText(), rate validation, sizing math, parser sanity guard, API response shape, and env validation -- all 25 passing',
  'NEW: vitest.config.ts -- vitest v4 config with node environment, globals, 10s timeout, @/* path alias',
  'NEW: package.json -- added test / test:watch / test:coverage / test:ci scripts; vitest ^4.1.0 devDependency',
  'NEW: lib/env-check.ts -- startup env validation: validateEnv() checks REQUIRED_VARS (DATABASE_URL, JWT_SECRET) and RECOMMENDED_VARS (OPENAI_API_KEY, GOOGLE_MAPS_API_KEY)',
  'NEW: lib/env-check.ts -- assertEnv() throws on missing required vars; logEnvStatus(routeLabel) logs once per cold start with [ENV_STATUS] tag',
  'FIX: app/api/bill-upload/route.ts -- logEnvStatus("bill-upload") called at module load -- cold-start env visibility',
  'FIX: app/api/system-size/route.ts -- logEnvStatus("system-size") called at module load -- cold-start env visibility',
  'NEW: app/api/health/database/route.ts -- GET /api/health/database: checks DATABASE_URL set, SELECT 1 ping, required tables [users,clients,projects] present, optional tables [proposals,utility_policies,bills]',
  'NEW: app/api/health/database/route.ts -- returns { status: healthy|degraded|unhealthy, database, tables, env, elapsed_ms }; HTTP 200=healthy, 503=degraded/unhealthy',
  'NEW: app/api/health/database/route.ts -- [HEALTH_DB] structured log tag on every check for Vercel log searchability',
  'NEW: .github/workflows/ci.yml -- GitHub Actions CI: runs on push/PR to master',
  'NEW: .github/workflows/ci.yml -- Job 1: test (vitest run --reporter=verbose) with stub env vars',
  'NEW: .github/workflows/ci.yml -- Job 2: type-check (tsc --noEmit)',
  'NEW: .github/workflows/ci.yml -- Job 3: lint (next lint)',
  'NEW: .github/workflows/ci.yml -- Job 4: build gate (npm run build) -- runs only after test+type-check+lint pass on push to master',
  'NEW: .github/workflows/ci.yml -- Job 5: env-audit -- verifies DATABASE_URL and JWT_SECRET are referenced in codebase (deployment blocker)',
  'NEW: .github/workflows/ci.yml -- Job 6: ci-complete -- summary job, fails CI if any upstream job failed',
  'NEW: .github/workflows/ci.yml -- concurrency group with cancel-in-progress to prevent redundant runs',
  // v47.19 -- Split bill pipeline to fix Vercel timeout ("Server returned an invalid response")
  'ROOT CAUSE: /api/bill-upload ran OCR + parse + geocoding + utility match + rate validation + system sizing in a single serverless function -- total time 15-60s exceeded Vercel 60s limit, causing HTML timeout response that res.json() could not parse',
  'FIX: app/api/bill-upload/route.ts -- SLIM: now only does OCR + text extraction + parseBill + AI fallback -- returns in <5s',
  'FIX: app/api/bill-upload/route.ts -- REMOVED from route: geocodeAddress, detectUtility, matchUtility, validateAndCorrectUtilityRate, getProductionFactor, checkNetMeteringLimit, saveBill, system sizing math',
  'FIX: app/api/bill-upload/route.ts -- maxDuration reduced from 60s to 30s (OCR only needs ~5-10s)',
  'FIX: app/api/bill-upload/route.ts -- returns locationData/utilityData/matchedUtility/systemSizing/rateValidation as null -- frontend calls /api/system-size to fill these',
  'NEW: app/api/system-size/route.ts -- POST endpoint receiving parsed bill fields (annual_kwh, monthly_kwh, address, utility, rate, offset_target)',
  'NEW: app/api/system-size/route.ts -- runs: geocodeAddress + matchUtility + detectUtility + validateAndCorrectUtilityRate + getProductionFactor + checkNetMeteringLimit + system size math',
  'NEW: app/api/system-size/route.ts -- returns: system_kw, estimated_panels, estimated_cost, locationData, matchedUtility, rateValidation, systemSizing',
  'NEW: app/api/system-size/route.ts -- maxDuration=30s; isolated from OCR so geocoding/DB errors never block text extraction',
  'FIX: app/api/bill-upload/route.ts -- 6s Promise.race timeout guard on OCR and AI extraction -- returns partial data rather than hanging',
  'FIX: components/onboarding/BillUploadModal.tsx -- two-phase flow: bill-upload advances uploading/extracting/parsing stages, then calls /api/system-size which advances geocoding/sizing',
  'FIX: components/onboarding/BillUploadModal.tsx -- runUploadStageSimulation replaces runStageSimulation (only covers upload phases, not geocoding/sizing)',
  'FIX: components/onboarding/BillUploadModal.tsx -- runSystemSizing() merges sizing result into upload result before setResult()',
  'FIX: components/onboarding/BillUploadModal.tsx -- handleManualEntry now calls runSystemSizing after bill-upload text parse',
  'FIX: components/onboarding/BillUploadFlow.tsx -- same two-phase flow and runSystemSizing pattern as BillUploadModal',
  'FIX: components/onboarding/BillUploadFlow.tsx -- handleManualEntry now calls runSystemSizing',
  'LOGS: BILL_UPLOAD_STARTED / OCR_COMPLETED / TEXT_LENGTH / FIELDS_EXTRACTED / BILL_UPLOAD_RETURNING added to bill-upload',
  'LOGS: SYSTEM_SIZE_STARTED / SIZING_COMPLETE / SIZING_SKIPPED / SYSTEM_SIZE_RETURNING added to system-size',
  'RESULT: bill upload completes in <5s (OCR only), sizing completes in <10s (geocoding+DB), total flow <15s -- well under Vercel 60s limit',
  // v47.18 -- Hard fail on empty parse + sizing gate + full pipeline logging
  'ROOT CAUSE: Pipeline silently returned success=true with 0 fields when OCR/parser found nothing -- review screen showed Extraction confidence: low, 0 fields, $0.130/kWh fallback, 0.0 kW, 0 annual kWh',
  'ROOT CAUSE: extractBillDataWithAI() sets usedLlmFallback=true even when AI returns nothing useful -- caused AI-assisted label on empty results',
  'ROOT CAUSE: systemSizeKw was calculated with annualKwhForSizing=0 giving 0.0 kW instead of null/omitted',
  'FIX: app/api/bill-upload/route.ts -- Hard fail gate: if totalFinalFields===0 AND !hasAnyKwh AND !hasLocation AND file -- return 422 with parseEmpty=true and actionable message',
  'FIX: app/api/bill-upload/route.ts -- Sizing gate: systemSizeKw only set when annualKwhForSizing > 0 OR monthlyKwhForSizing > 0 -- null when no kWh data available',
  'FIX: app/api/bill-upload/route.ts -- Buffer created ONCE via Buffer.from(await file.arrayBuffer()) at line ~67 -- confirmed no double-read regression',
  'FIX: app/api/bill-upload/route.ts -- saveBill runs AFTER parsing -- confirmed parse-before-save order preserved',
  'LOG: [FILE_RECEIVED] name/type/size/openai at top of file handler',
  'LOG: [FILE_BUFFER_CREATED] bytes/mime immediately after buffer creation',
  'LOG: [OCR_TEXT_LENGTH] chars/method/confidence after image OCR completes',
  'LOG: [FILE_SAVED] buffer_intact/extracted_chars after saveBill call',
  'LOG: [PARSED_FIELDS_COUNT] count/fields/monthlyKwh/annualKwh/confidence after parseBill()',
  'LOG: [AI_EXTRACTION_RESULT] totalFields/usedAI/monthlyKwh/annualKwh/utility/address after extractBillDataWithAI()',
  'LOG: [PARSE_EMPTY_FAIL] name/extractedChars/method on 422 hard fail',
  'LOG: [SIZING_INPUTS_READY] annualKwh/productionFactor/systemSizeKw when sizing proceeds',
  'LOG: [SIZING_SKIPPED_EMPTY_PARSE] annualKwh=0 monthlyKwh=0 when sizing skipped',
  'FIX: components/onboarding/BillUploadFlow.tsx -- 422 with parseEmpty=true shows: Bill text could not be extracted. Please re-upload a clearer image or enter manually.',
  'FIX: components/onboarding/BillUploadModal.tsx -- 422 with parseEmpty=true shows same actionable message',
  // v47.17 -- Harden bill upload JSON safety (fix "Unexpected token 'A'" crash)
  'ROOT CAUSE: frontend called res.json() without try/catch -- when server returned non-JSON (Vercel timeout HTML, module crash before handler runs), res.json() threw SyntaxError: Unexpected token A',
  'FIX: components/onboarding/BillUploadFlow.tsx -- both fetch sites (file upload + manual entry) now wrap res.json() in try/catch, throw friendly Error on parse failure',
  'FIX: components/onboarding/BillUploadModal.tsx -- both fetch sites (file upload + manual entry) now wrap res.json() in try/catch, throw friendly Error on parse failure',
  'FIX: app/api/bill-upload/route.ts -- outer catch block now maps error types to friendly messages (OCR failure, timeout, auth, file size)',
  'FIX: app/api/bill-upload/route.ts -- added safeJsonError() helper for any edge-case non-JSON escape paths',
  'FIX: app/api/bill-upload/route.ts -- BILL_UPLOAD_ERROR log tag on fatal errors for Vercel log searchability',
  'USER-VISIBLE: upload modal now shows "Bill processing failed — could not extract readable text" instead of "Unexpected token A is not valid JSON"',
  // v47.16 -- Fix critical auth outage (DATABASE_URL not loaded in production)
  'ROOT CAUSE: Vercel production deployment had encrypted env vars that were not decrypting at runtime -- DATABASE_URL and JWT_SECRET showed false in /api/health despite being configured in Vercel project settings',
  'ROOT CAUSE: Previous deployment (dpl_5b1USpSCLvYgpvEUazEoMoQFsi8D) was built without env vars properly injected -- forced redeploy (dpl_4MBQbPcsLyHQqe6zVLPhJSCFdad2) fixed the issue',
  'FIX: Forced fresh Vercel redeploy via API -- new deployment correctly injects DATABASE_URL and JWT_SECRET at runtime',
  'VERIFIED: /api/health now returns DATABASE_URL=true JWT_SECRET=true db.ok=true db.ts=2026-03-13',
  'VERIFIED: /api/auth/login returns 401 Invalid email or password (DB query works, auth pipeline functional)',
  'VERIFIED: /api/auth/me returns 401 Not authenticated (correct for unauthenticated request)',
  'NEW: app/api/health/auth/route.ts -- diagnostic endpoint GET /api/health/auth',
  'NEW: /api/health/auth checks: JWT_SECRET present, DATABASE_URL present, DB connection, users table accessible, session cookie present',
  'NEW: /api/health/auth returns { status: healthy|degraded, jwt, database, users_table, auth, user_count }',
  'NEW: /api/health/auth covered by /api/health PUBLIC_PATHS entry (startsWith match)',
  // v47.15 -- Fix OCR 401 (middleware blocking internal server-to-server call)
  'ROOT CAUSE: /api/ocr was not in middleware.ts PUBLIC_PATHS -- server-to-server fetch from billOcrEngine.ts had no auth cookie, middleware returned 401, all OCR failed',
  'FIX: middleware.ts -- added /api/ocr to PUBLIC_PATHS (internal route, no user data, same pattern as /api/health)',
  'FIX: lib/billOcrEngine.ts -- recognizeImage() now sends x-internal-secret header when INTERNAL_OCR_SECRET env var is set (defence-in-depth)',
  'FIX: app/api/ocr/route.ts -- added INTERNAL_OCR_SECRET bypass check: rejects wrong secret (403), allows no-header requests (PUBLIC_PATHS covers auth)',
  'FIX: app/api/ocr/route.ts -- added OCR_STARTUP log block: logs openai/google/internal_secret presence at cold start for Vercel log visibility',
  'FIX: app/api/bill-upload/route.ts -- Stage 1b runTesseractCliInline(): inline CLI fallback that bypasses HTTP entirely when /api/ocr returns empty/401',
  'FIX: app/api/bill-upload/route.ts -- Stage 1b detects 401 error code in tesseractResult.error and logs explicit warning before attempting inline CLI',
  'FIX: app/api/bill-upload/route.ts -- inline CLI result used directly if hasUsage, otherwise kept as candidate text and pipeline continues to Vision',
  'PIPELINE: upload -> pdftotext/pdf-parse (PDF) OR Tesseract-via-HTTP + CLI-inline (image) -> Vision AI -> extractBillDataWithAI -- never hard-aborts',
  // v47.14 -- Restore bill parsing pipeline
  'ROOT CAUSE: extractPdfTextPure returns 182 chars of chart-label text (J F M A M) from CMP bill -- passes old 50-char threshold but contains zero bill data, causing downstream parse failure',
  'ROOT CAUSE: pdftotext CLI (poppler) was only tried as last resort (Method 5) -- it is the highest-quality extractor and works perfectly on the CMP bill',
  'ROOT CAUSE: pdf-parse npm module was loaded but never called in extractPdfText -- import existed but call site was missing entirely',
  'FIX: app/api/bill-upload/route.ts -- new extractPdfText() with 6-method cascade: pdftotext (M1) > pdf-parse (M2) > pure-extract+isUsefulText (M3) > pdfjs-dist (M4) > openai-files-api (M5) > google-vision (M6)',
  'FIX: app/api/bill-upload/route.ts -- isUsefulText() quality gate: requires length>=100 and >=2 of: $amount, kWh, street address, account keyword, 3+ digit number -- blocks junk text from M3',
  'FIX: app/api/bill-upload/route.ts -- pdf-parse called correctly for v2.x module (exports { PDFParse: fn }, not default)',
  'FIX: app/api/bill-upload/route.ts -- pdftotext promoted to Method 1 (was fallback) -- available on Vercel serverless via poppler-utils',
  'LOG: [FILE_UPLOADED] replaces old 3-line console.log block -- single structured line with name/type/size/openai',
  'LOG: [PDF_PARSE_STARTED/SUCCESS/FAILED] per-method structured logs in extractPdfText cascade',
  'LOG: [OCR_STARTED/OCR_SUCCESS/OCR_FAILED] around extractImageTextSmart for image files',
  'LOG: [AI_EXTRACTION_STARTED] reason=zero_fields_extracted | reason=low_field_count before extractBillDataWithAI calls',
  'LOG: [AI_EXTRACTION_COMPLETE] fields=... confidence=... after extractBillDataWithAI returns',
  // v47.13 -- Bill upload pipeline & utility rate fixes
  'T1 FIX: lib/utility-rules.ts -- MIN_VALID_RETAIL_RATE raised from $0.06 to $0.10 (residential retail floor; $0.069 CMP supply charge is now correctly flagged as suspect)',
  'T1 FIX: validateAndCorrectUtilityRate -- added DB rate override logic: if extracted rate < 50% of known DB rate, treat as supply-only and use DB rate instead',
  'T1 FIX: validateAndCorrectUtilityRate -- added suspect field to return type for downstream transparency',
  'T1 FIX: app/api/bill-upload/route.ts -- structured logs: [BILL_PARSE_COMPLETE], [UTILITY_RATE_SELECTED], [UTILITY_RATE_SOURCE] with rate, source, suspect flag',
  'T2 FIX: components/onboarding/BillUploadModal.tsx -- handleCreateAll now wraps billData in _billAnalysis format that rowToProject expects for hydration on reload',
  'T2 FIX: BillUploadModal -- also sends utilityName, utilityRatePerKwh, stateCode, city as top-level project fields for immediate use without DB reload',
  'T2 FIX: BillUploadModal -- log [PROJECT_CREATED_FROM_BILL] and [BILL_SAVED_TO_PROJECT] after each step',
  'T3/T4 FIX: store/appStore.ts loadActiveProject -- log [PROJECT_RELOADED] with billAnalysis, utilityRatePerKwh, utilityName, stateCode after DB fetch',
  // v47.12 -- Proposal pipeline fixes (7 issues from E2E testing)
  'Issue 1 FIX: app/projects/[id]/page.tsx handleBillComplete -- PUT /api/clients/[id] when OCR extracts customerName and current name is placeholder (contains "customer", < 3 chars, etc.)',
  'Issue 1 FIX: updatedProject merge includes new client name in local React state immediately after bill save',
  'Issue 2 FIX: app/proposals/page.tsx ProposalPreview -- systemType derived from layout.systemType > project.systemType > "roof" (never hardcoded to roof)',
  'Issue 3 FIX: app/proposals/page.tsx -- "Roof Attachment Hardware" BOM section gated with (systemType === "roof" || systemType === "ROOF_MOUNT") -- fence/ground/carport no longer show roof racking',
  'Issue 4 FIX: app/proposals/page.tsx -- utilityRate priority: project.utilityRatePerKwh (bill-pipeline retail rate) > client.utilityRate (stale) > 0.15 national fallback',
  'Issue 4 FIX: app/proposals/page.tsx -- annualSavings same priority chain for consistent $ calculations',
  'Issue 5 FIX: lib/pvwatts.ts -- added "northern" climate zone for lat >= 43deg eastern US (ME, VT, NH, MN, WI, ND, MT) with June production peak matching NREL data',
  'Issue 5 FIX: lib/pvwatts.ts -- getClimateZone() returns "northern" for lat >= 43 && lng >= -100 (eastern); continental retained for Pacific NW',
  'Issue 5 FIX: lib/pvwatts.ts -- northern CLIMATE_MULTIPLIERS: [0.42,0.58,0.82,1.05,1.23,1.32,1.27,1.14,0.90,0.68,0.45,0.35] -- June peak (idx 5 = 1.32)',
  'Issue 6 FIX: app/proposals/page.tsx -- SREC_STATES whitelist: DC,MA,MD,NJ,PA,OH,IL,DE,CT,RI,NY,VA,NC,MI,MO,IN -- SREC section hidden for ME and all non-SREC states',
  'Issue 7 FIX: lib/incentives/stateIncentives.ts -- Incentive interface adds optional systemTypes field for per-incentive system-type restrictions',
  'Issue 7 FIX: lib/incentives/stateIncentives.ts -- normaliseSystemTypeKey() maps raw systemType string (ROOF_MOUNT/SOL_FENCE/etc.) to canonical key',
  'Issue 7 FIX: lib/incentives/stateIncentives.ts -- calculateIncentives() accepts optional systemType param; skips incentives whose systemTypes array excludes the current type',
  'Issue 7 FIX: app/proposals/page.tsx -- calculateIncentives() call now passes systemType as 6th argument',
  'VERIFIED: Maine stateIncentives has no SREC entries (only property_tax_exemption + sales_tax_exemption) -- correct for ME market',
  // v47.11 -- Utility rate database rebuild + bill pipeline fix
  'ROOT CAUSE 1: UTILITY_RETAIL_RATES in utility-rules.ts had stale/incorrect rates -- CMP was $0.198 (2022 EIA), actual 2024 rate is $0.265/kWh (EIA ME avg Jan-Sep 2024)',
  'ROOT CAUSE 2: STATE_UTILITY_FALLBACK avgRate values in utilityDetector.ts were 2022-era EIA data -- ME/VT/NH/CT/CA/HI/MI/AK all needed updating',
  'ROOT CAUSE 3: utility_policies DB table had only default_residential_rate column -- no retail_rate (all-in) vs supply_rate (energy-only) distinction',
  'ROOT CAUSE 4: utilityMatcher.ts read only default_residential_rate -- would return stale/supply-only rate as the effective rate for solar calculations',
  'ROOT CAUSE 5: handleBillComplete rate fallback used hardcoded 0.13 when bill rate unavailable -- did not use DB retail rate as priority 2',
  'FIX: lib/utility-rules.ts -- Added UtilityRateBreakdown interface with retailRate/supplyRate/distributionRate/transmissionRate/fixedMonthlyCharge/netMeteringType/lastUpdated/rateSource',
  'FIX: lib/utility-rules.ts -- UTILITY_RATE_BREAKDOWNS replaces flat UTILITY_RETAIL_RATES dict; backward-compat shim auto-derives UTILITY_RETAIL_RATES from it',
  'FIX: lib/utility-rules.ts -- CMP retail_rate corrected: $0.198 -> $0.265/kWh (EIA + CMP tariff sheet 14, 2024)',
  'FIX: lib/utility-rules.ts -- Versant Power: $0.198 -> $0.272/kWh; GMP: $0.198 -> $0.215/kWh; Unitil: $0.228 -> $0.235/kWh',
  'FIX: lib/utility-rules.ts -- PG&E: $0.32 -> $0.338/kWh; PSE&G: $0.17 -> $0.178/kWh; ComEd: $0.13 -> $0.148/kWh; Ameren: $0.12 -> $0.128/kWh',
  'FIX: lib/utility-rules.ts -- MAX_VALID_RETAIL_RATE raised $0.50 -> $0.60 (HI/CA rates exceed old ceiling)',
  'FIX: lib/utility-rules.ts -- Added getUtilityRateBreakdown() export: returns full UtilityRateBreakdown for a utility by name',
  'FIX: lib/utilityDetector.ts -- STATE_UTILITY_FALLBACK avgRate updated for 8 states: ME 0.198->0.265, VT 0.198->0.215, NH 0.228->0.235, CT 0.248->0.252, CA 0.298->0.318, HI 0.388->0.395, MI 0.178->0.188, AK 0.228->0.258',
  'FIX: lib/utilityMatcher.ts -- MatchedUtility interface adds retailRate + effectiveRate fields',
  'FIX: lib/utilityMatcher.ts -- P1/P2 queries now SELECT retail_rate column; effectiveRate = retailRate ?? defaultResidentialRate',
  'FIX: lib/utilityMatcher.ts -- P3/P4 fallback returns include retailRate: null, effectiveRate: fallbackRate',
  'FIX: app/api/bill-upload/route.ts -- Uses matchedUtility.effectiveRate (not defaultResidentialRate) as DB rate; logs retailRate vs legacyRate vs effectiveRate',
  'FIX: app/projects/[id]/page.tsx -- handleBillComplete now reads result.matchedUtility?.effectiveRate as priority-2 rate source',
  'FIX: app/projects/[id]/page.tsx -- 3-tier rate priority: bill_rate (if non-default) > DB retail rate > state average > national default 0.13',
  'FIX: app/projects/[id]/page.tsx -- handleBillComplete signature now includes matchedUtility?: { effectiveRate, retailRate, ... }',
  'FIX: app/api/migrate/route.ts -- Migration 011: adds retail_rate/supply_rate/distribution_rate/transmission_rate/fixed_monthly_charge/net_metering_type/last_updated/rate_source columns to utility_policies',
  'FIX: app/api/migrate/route.ts -- Migration 011: seeds accurate 2024/2025 retail rates for 12 major utilities (CMP, Versant, Eversource, National Grid, GMP, Unitil, PGE, SCE, FPL, Duke, PSE&G, ComEd, Ameren)',
  'LOGGING: [BILL_PARSED] now logs dbRetailRate for rate source tracing',
  'LOGGING: [bill-upload] now logs retailRate vs legacyRate vs effectiveRate for each matched utility',
  // v47.10 -- Force dynamic on all API routes
  'ROOT CAUSE: Next.js attempted to statically render API routes at build time; routes accessing request.headers/cookies()/DB at render time triggered DYNAMIC_SERVER_USAGE error',
  'ROOT CAUSE: /api/settings/branding and /api/stats confirmed failing in Vercel logs with digest: DYNAMIC_SERVER_USAGE -- login flow broken',
  'FIX: Audited all 97 route.ts files in /app/api -- 57 already had force-dynamic; 40 were missing it',
  "FIX: Added export const dynamic = 'force-dynamic' to all 40 missing routes -- forces runtime evaluation, never static rendering",
  'FIX: Added export const revalidate = 0 to all 40 routes -- disables static caching, ensures fresh data on every request',
  'ROUTES PATCHED: auth/login, auth/logout, auth/register, auto-design, auto-size, bill-upload, bill-upload/test, clients/[id], clients, dev-check, dsm, elevation, engineering/structural-v2, enterprise/contact, equipment/save, geocode, hardware, incentives, maps-session, migrate, ocr, pricing, production, projects/[id]/layout, projects/[id], projects/[id]/versions/[versionId], projects/[id]/versions, projects, proposals/[id], proposals/[id]/share, proposals, settings/branding, settings/logo, settings/profile, solar, stats, stripe/checkout, stripe/portal, tile, utility-detect',
  "VERIFIED: All 97/97 route.ts files now contain export const dynamic = 'force-dynamic'",
  // v47.9 -- Definitive deployment startup fix
  'ROOT CAUSE 1: channel_binding=require in DATABASE_URL caused SSL handshake failures during Neon proxy cold start -- errors mis-classified as fatal causing DB_CONFIG_ERROR banner',
  'ROOT CAUSE 2: getDbWithRetry() delays 1s/2s/4s=7s too aggressive for Vercel Hobby 10s timeout -- probe retries consumed entire timeout budget before actual query ran',
  'ROOT CAUSE 3: No module-level Neon singleton -- neon(url) called on every /api/auth/me request (mount/focus/tab-switch) creating redundant HTTP clients and SELECT 1 probe overhead',
  'ROOT CAUSE 4: auth routes had no maxDuration export -- Vercel Hobby killed functions at 10s default while retries were in progress, producing 504 instead of 503 DB_STARTING',
  'ROOT CAUSE 5: engineering-automation.ts imported synchronous getDb() from auth.ts -- engineering routes returned 500 (not 503) on cold start, breaking frontend error handling',
  'FIX: lib/db-ready.ts -- getDatabaseUrl() now strips channel_binding=require -> channel_binding=disable at runtime (Vercel env var sanitization)',
  'FIX: lib/.env.local -- DATABASE_URL updated to use channel_binding=disable',
  'FIX: lib/db-ready.ts -- module-level Neon singleton (_cachedSql) created once per function instance cold start, not per request',
  'FIX: lib/db-ready.ts -- _instanceWarm flag: after first successful SELECT 1 probe, subsequent getDbReady() calls skip probe entirely (~0ms overhead on warm paths)',
  'FIX: lib/db-ready.ts -- MAX_RETRIES 3->5, BASE_DELAY 1000ms->300ms; delays now 300/600/1200/2400/4800ms = 9.1s total budget (was 7s but consumed 70% of Hobby timeout)',
  'FIX: lib/db-ready.ts -- isTransientDbError() SCRAM/channel-binding errors now explicitly transient (were falling through to non-retryable causing DB_CONFIG_ERROR)',
  'FIX: app/api/auth/login/route.ts -- maxDuration=30 added; prevents Vercel from killing during retry loop',
  'FIX: app/api/auth/me/route.ts -- maxDuration=30 added; prevents 504 timeout during DB cold-start retries',
  'FIX: app/api/auth/register/route.ts -- maxDuration=30 added; consistent with login/me',
  'FIX: lib/engineering-automation.ts -- replaced getDb() from ./auth with getDbReady() from db-neon; all 11 call sites updated to await (await getSql())`SQL`',
  'LOGGING: [SERVER_INSTANCE_STARTED] emitted by db-ready.ts and db-neon.ts on module load (once per cold start)',
  'LOGGING: [ENVIRONMENT_LOADED] DATABASE_URL presence + NODE_ENV + VERCEL_ENV logged at startup',
  'LOGGING: [ENV_DATABASE_URL_STATUS] DATABASE_URL length + channel_binding sanitization logged on every getDatabaseUrl() call',
  'LOGGING: [DB_CLIENT_INIT] neon() singleton creation logged',
  'LOGGING: [DB_CONNECTION_ATTEMPT] each SELECT 1 probe attempt numbered and logged',
  'LOGGING: [DB_CONNECTION_SUCCESS] successful probe logged with attempt number',
  'LOGGING: [DB_CONNECTION_FAILED] failed probe logged with error message + retry delay',
  'LOGGING: [AUTH_LOGIN_REQUEST] login attempt start + email logged',
  'LOGGING: [AUTH_SESSION_CHECK] DB connection acquisition logged in login and me routes',
  // v47.8 -- Bill workflow pipeline bug fix
  'ROOT CAUSE: handleBillComplete PUT body stored _stateCode in bill_data JSONB but never _city -- Location field on System Size page always showed Not set',
  'ROOT CAUSE: rowToProject() hydrated stateCode/utilityName/utilityRatePerKwh from bill_data JSONB but had no city hydration path -- city was lost on every DB round-trip',
  'ROOT CAUSE: updatedProject merge in handleBillComplete included stateCode override but completely omitted city -- city was lost immediately after the modal closed',
  'ROOT CAUSE: getProjectWithDetails() had its own inline bill_data hydration block that also lacked city hydration -- detail fetches returned project without city too',
  'ROOT CAUSE: store cache returned stale project on navigation (loadActiveProject returns cached entry) -- bill data appeared missing if store was not updated after save',
  'FIX: page.tsx handleBillComplete -- added city = result.locationData?.city capture',
  'FIX: page.tsx handleBillComplete -- bill_data JSONB now includes _city field alongside _stateCode/_utilityName/_utilityRatePerKwh/_billAnalysis',
  'FIX: page.tsx handleBillComplete -- updatedProject merge now includes city: city || json.data.city (was missing entirely)',
  'FIX: page.tsx handleBillComplete -- calls syncProjectToStore(updatedProject) after save to keep in-memory store cache warm',
  'FIX: db-neon.ts rowToProject() -- added city hydration from bill_data._city; city now included in returned Project object',
  'FIX: db-neon.ts getProjectWithDetails() -- same city hydration from bill_data._city in inline hydration block',
  'FIX: store/appStore.ts -- added syncProjectToStore(project) action: replaces project in store array + localSaveProject without re-fetching',
  'FIX: store/appStore.ts -- added syncProjectToStore to AppStore interface',
  'LOGGING: [BILL_PARSED] logs annualKwh/utilityName/utilityRate/stateCode/city after OCR result processing',
  'LOGGING: [BILL_SAVING] logs projectId/systemKw/utilityName/annualKwh/stateCode/city before PUT',
  'LOGGING: [BILL_SAVED_TO_PROJECT] logs all key fields after successful PUT response',
  'LOGGING: [PROJECT_STATE_UPDATED] logs billAnalysis presence + utilityName/stateCode/city/utilityRate after setProject',
  'LOGGING: [SYSTEM_SIZE_LOADED] SystemSizeTab useEffect logs all 8 key fields on every project prop change',
  // v47.6 -- Critical production stability audit
  'ROOT CAUSE: All non-auth API routes used getDb() (synchronous, no retry) -- any Neon cold start caused immediate DbConfigError/500 across entire app',
  'ROOT CAUSE: db-neon.ts exported functions (getProjectById, updateProject, getClientsByUser, etc.) all called getDb() internally -- 22 functions affected',
  'ROOT CAUSE: 65 direct API route files called getDb() from @/lib/auth or @/lib/db-neon without retry',
  'ROOT CAUSE: All non-auth catch blocks returned raw 500 -- UserContext retries on 503 DB_STARTING but treats 500 as transient without code; frontend had no semantic signal',
  'FIX: lib/db-neon.ts -- all 22 internal getDb() calls replaced with await getDbReady() -- ALL exported db functions now cold-start resilient',
  'FIX: lib/db-neon.ts -- new handleRouteDbError(routeLabel, error) utility: DbConfigError->503 DB_CONFIG_ERROR; all other->503 DB_STARTING with Retry-After: 3',
  'FIX: app/api/projects/* -- all routes (GET/PUT/DELETE project, layout, versions) now use handleRouteDbError',
  'FIX: app/api/clients/* -- all routes (GET/POST/PUT/DELETE client) now use handleRouteDbError',
  'FIX: app/api/proposals/* -- all routes (GET/POST/PUT proposal, share) now use handleRouteDbError',
  'FIX: app/api/settings/* -- profile, branding, logo routes now use handleRouteDbError',
  'FIX: app/api/engineering/* -- plan-set, preliminary, auto-configure, override, assist, slg, save-outputs, latest-run, run-from-file, and all others use handleRouteDbError',
  'FIX: app/api/admin/* -- all 19 admin routes (users, utilities, incentives, free-pass, etc.) use handleRouteDbError',
  'FIX: app/api/production/route.ts, equipment/*, stripe/*, stats/* -- all use handleRouteDbError',
  'VERIFIED: TypeScript build passes with zero errors after all replacements',
  'PRESERVED: auth routes (login, me, register) retain their existing per-route DbConfigError handling (not changed)',
  'PRESERVED: Non-DB 500s (missing MIGRATE_SECRET, OCR errors, external API failures) remain as-is -- not DB cold-start paths',
  // v47.5 -- Bill upload workflow pipeline fix
  'project/[id]/page.tsx: handleUploadBill now opens inline BillUploadFlow modal (not 404 route)',
  'project/[id]/page.tsx: handleBillComplete builds BillAnalysis + PUTs to /api/projects/[id]',
  'project/[id]/page.tsx: setProject() with hydrated billAnalysis after save -- workflow recomputes',
  'db-neon.ts: updateProject() now persists bill_data JSONB column',
  'db-neon.ts: rowToProject() hydrates billAnalysis/utilityName/utilityRatePerKwh/stateCode from bill_data',
  'db-neon.ts: getProjectWithDetails() also hydrates billAnalysis from bill_data._billAnalysis',
  // v47.4 -- Bill parser audit
  'billParser.ts: U1 header search 500->1000 chars; U3 case-insensitive; hardened rate patterns; P2 min 50',
  'utility-rules.ts: CMP, Versant, Eversource, National Grid, GMP, Unitil added to registry',
  'billOcrEngine.ts: improved Vision prompt for CMP bill format',
  // v47.3 -- UserContext logout fix
  'ROOT CAUSE: refreshUser() called setUser(null) on retry exhaustion (Neon cold start after idle)',
  'FIX: contexts/UserContext.tsx -- fetchUserWithRetry() returns transient on retry exhaustion; only 401 triggers logout',
  'FIX: contexts/UserContext.tsx -- FetchStatus string enum: ok/logout/retry/preserve',
  // v47.2 -- Production stability: defense-in-depth DB error handling
  'ROOT CAUSE: isTransientDbError() used blacklist approach -- any Neon cold-start error with unusual message fell through to non-transient, causing DB_CONFIG_ERROR mis-classification',
  'ROOT CAUSE: login/route.ts catch used msg.includes(DATABASE_URL) -- matched Neon connection string errors during cold start, showed Database not configured to users',
  'ROOT CAUSE: me/route.ts generic 500 fallthrough -- UserContext does not retry on 500, so unrecognized errors appeared as logout',
  'ROOT CAUSE: UserContext treated any non-200 non-503 as definitive logout (if (!res.ok) return null)',
  'FIX: lib/db-ready.ts -- isTransientDbError() rewritten with WHITELIST-FATAL approach: only explicit pg auth/permission/missing errors are fatal; all unknown errors default to transient',
  'FIX: lib/db-ready.ts -- AUTH_DB_STARTING / AUTH_DB_CONFIG_ERROR log codes on every error path for Vercel log searchability',
  'FIX: app/api/auth/me/route.ts -- handleDbError() centralizes all DB error responses; defaults to DB_STARTING for ALL non-DbConfigError errors (never 500)',
  'FIX: app/api/auth/me/route.ts -- inner fallback query wrapped in own try/catch; connection errors in fallback correctly return DB_STARTING not 500',
  'FIX: app/api/auth/me/route.ts -- AUTH_DB_STARTING/AUTH_DB_CONFIG_ERROR/AUTH_DB_QUERY_ERROR log tags on every code path with stage= context',
  'FIX: app/api/auth/login/route.ts -- removed msg.includes(DATABASE_URL) from config error check; only DbConfigError is fatal',
  'FIX: app/api/auth/login/route.ts -- all non-DbConfigError errors return DB_STARTING (not 500/Login failed); same safe-default pattern',
  'FIX: contexts/UserContext.tsx -- HTTP 500 from /api/auth/me now retries (not logout); only HTTP 401 = definitive logout',
  // v47.1 -- Production stability: deployment cold-start session fix
  'ROOT CAUSE: /api/auth/me used getDb() (no retry) -- UserContext called on mount/focus/30s -- cold start = null user = apparent logout',
  'FIX: app/api/auth/me/route.ts -- switched getDb() to getDbReady() (3x retry, 1s/2s/4s backoff); returns DB_STARTING 503 on transient failure (not 500)',
  'FIX: app/api/auth/me/route.ts -- DB_CONFIG_ERROR vs DB_STARTING error codes prevent UserContext from misclassifying cold starts as logouts',
  'FIX: contexts/UserContext.tsx -- fetchUserWithRetry() wraps fetchUserFromDb(); retries up to 5x (3s each) on DB_STARTING 503 before clearing user state',
  'FIX: contexts/UserContext.tsx -- 503/DB_STARTING never clears user state; only 401 is treated as definitive logout',
  'FIX: app/api/auth/register/route.ts -- switched getDb() to getDbReady(); proper DB_STARTING/DB_CONFIG_ERROR error codes',
  'FIX: lib/adminAuth.ts -- requireAdmin() and requireAdminApi() switched to getDbReady() with retry',
  'FIX: lib/auth.ts -- makeSessionCookie() adds Secure flag in production (NODE_ENV=production) for HTTPS-only cookie delivery',
  'FIX: lib/auth.ts -- clearSessionCookie() adds matching Secure flag',
  'FIX: lib/auth.ts -- exports DbConfigError re-export from db-ready for convenience',
  'FIX: lib/db-neon.ts -- getDb() now throws DbConfigError (non-retryable) instead of plain Error; routes can distinguish config vs transient',
  'FIX: lib/db-neon.ts -- exports getDbReady() async wrapper and DbConfigError for routes importing from db-neon',
  // v47.0 -- Utility bill parsing pipeline audit
  'FIX: lib/billOcr.ts -- validateBillData() accepts optional BillValidationContext; suppresses stale utility/rate warnings when values resolved post-match',
  'FIX: lib/billOcr.ts -- rate warning range updated to $0.06-$0.50/kWh; unusual rate warning replaces hard rejection',
  'FIX: lib/utility-rules.ts -- MIN_VALID_RETAIL_RATE lowered 0.07->0.06; MAX_VALID_RETAIL_RATE=0.50 added; rates above max corrected to DB rate',
  'FIX: app/api/bill-upload/route.ts -- validateBillData() moved from pre-geocoding (line 242) to post-rate-correction; context passes resolvedMatchedUtility + finalRate',
  'FIX: app/api/bill-upload/route.ts -- UI warnings now reflect fully resolved state (utility matched, rate corrected) not raw parse output',
  // v46.9 -- DB readiness guard
  'NEW: lib/db-ready.ts -- getDbWithRetry() 3x retry with 1s/2s/4s exponential backoff for Neon cold starts',
  'NEW: lib/db-ready.ts -- probeDbReady() SELECT 1 wake probe before auth queries',
  'NEW: lib/db-ready.ts -- isTransientDbError() classifies transient vs fatal DB errors',
  'NEW: lib/db-ready.ts -- DbConfigError non-retryable class for missing DATABASE_URL',
  'FIX: lib/auth.ts -- getDbReady() async wrapper uses getDbWithRetry; getDb() kept for non-auth routes',
  'FIX: app/api/auth/login/route.ts -- uses getDbReady() with retry; returns code=DB_STARTING on 503; Retry-After header',
  'FIX: app/auth/login/page.tsx -- detects DB_STARTING 503; shows Starting server... banner; auto-retries up to 5x with countdown',
  // v46.8 -- Panel clearing fix
  'FIX: SolarEngine3D.tsx -- finalizeFence: set lastRenderedPanelsRef.current before onPanelsChange to prevent orphaned entities',
  'FIX: SolarEngine3D.tsx -- handleRoofClick: same lastRenderedPanelsRef sync fix',
  'FIX: SolarEngine3D.tsx -- handleGroundClick: same lastRenderedPanelsRef sync fix',
  'FIX: SolarEngine3D.tsx -- finalizePlane: same lastRenderedPanelsRef sync fix',
  'FIX: SolarEngine3D.tsx -- Row finalization: same lastRenderedPanelsRef sync fix',
  // v46.7 -- TS build fixes
  'NEW: lib/utilityMatcher.ts -- normalizeUtilityName() strips noise words; matchUtility() P1 exact / P2 pg_trgm fuzzy / P3 state fallback / P4 auto-discover',
  'FIX: app/api/bill-upload/route.ts -- calls matchUtility() after parseBill(); applies DB rate (default_residential_rate) to billData.electricityRate',
  'FIX: app/api/bill-upload/route.ts -- geo detectUtility() is now fallback-only; parsed name match wins',
  'FIX: app/api/bill-upload/route.ts -- bill persisted to bills table when projectId in form data',
  'NEW: app/api/migrate/route.ts -- Migration 009: default_residential_rate + source on utility_policies; pg_trgm extension; GIN index',
  'NEW: app/api/migrate/route.ts -- Migration 010: bills table (project_id, utility_name, monthly_kwh, annual_kwh, electric_rate, parsed_json)',
  'NEW: lib/db-neon.ts -- saveBill() and getBillsByProject() functions',
  'NEW: app/api/bills/route.ts -- GET ?projectId= and POST endpoints',
  'FIX: components/onboarding/BillUploadModal.tsx -- step 6 persists bill to /api/bills after project creation',
  'FIX: lib/utility-rules.ts -- getProductionFactor() accepts stateCode param; state-aware factors (ME/VT/NH=1050, CA/AZ/NV=1600, FL/TX=1500, NY/NJ/CT=1100)',
  'FIX: app/api/bill-upload/route.ts -- passes locationData.stateCode to getProductionFactor()',
  // v46.5 -- Bill parser P3 fix
  'billParser: parseBarGraphTable -- Monthly Usage Summary values are monthly kWh totals (not daily averages x days)',
  // v46.4 -- Bill parser comma-kWh fix
  'billParser: parseHandwrittenList -- fix comma-kWh (1,234 kWh) regex {1,3} -> {0,2}',
  'billParser: parsePrintedTable -- fix comma-kWh regex {2,4} -> {0,3} + val>=100 guard',
  // v46.3 -- Build fix
  'version.ts: rewritten with ASCII-only strings to prevent TypeScript merge-conflict false positives',
  // v46.2 -- Bill parser fixes
  'billParser: parseHandwrittenList -- skip year-number false matches (Jan 2025 362 => 362 not 2025)',
  'billParser: parseHandwrittenList -- date context guard (Jan 15, 2025 / Jan 15 2025 => skip 15)',
  'billParser: parseHandwrittenList -- comma-number support (1,234 kWh)',
  'billParser: extractCurrentMonth -- added Energy Charge pattern + kWh@ pattern',
  'billParser: annual cross-check now correctly computes 0.0% diff when explicit == computed',
  // v46.1 -- OCR extraction repair
  'billImagePreprocess.ts: EXIF auto-rotate, grayscale, normalize, sharpen, threshold, upscale to 2400px',
  'ocr/route.ts: multi-pass Tesseract -- PSM 3 (auto) + PSM 6 (document block), best result wins',
  'ocr/route.ts: raw OCR text logged before any parsing -- full debug visibility',
  'ocr/route.ts: preprocessing pipeline applied before every OCR run',
  'billOcr.ts: extractBillDataWithAI() -- structured JSON fallback when 0 fields extracted',
  'route.ts: AI fallback triggered when extractedFields === 0 or < 2',
  'route.ts: raw OCR text logged to console before parsing',
  'vercel.json: dev=preview, master=manual-only -- no accidental production deploys',
  'main.yml: manual-trigger-only production deploy with DEPLOY confirmation guard',
  'next.config.js: sharp + exif-reader added to webpack externals',
  // v46.0 -- Deterministic bill parser
  'route: parseBill() from billParser.ts is now the single authoritative final parser',
  'route: parseBillTextWithLLM() removed -- no LLM rewrites of numeric fields ever',
  'billParser: strict source priority P1 printed table > P2 handwritten > P3 bar graph',
  'billParser: rate returns null if not found -- never guesses',
  // v45.9 -- SaaS Tesseract OCR
  'app/api/ocr/route.ts -- dedicated OCR endpoint, webpack-isolated',
  'OCR pipeline: Tesseract.js WASM (primary) => Tesseract CLI (secondary) => OpenAI Vision (fallback)',
];

export function getBuildBadge(): string {
  return `SolarPro ${BUILD_VERSION} - ${BUILD_DATE}`;
}