export const BUILD_VERSION     = 'v60.1';
export const APP_VERSION       = BUILD_VERSION;
export const BUILD_DATE        = '2026-04-28'; // v60.1
export const BUILD_DESCRIPTION = 'v60.1: ARRAY_UNDERSIZED_FOR_BRAND warning — surfaces clear guidance when array is too small for chosen string brand, recommends micros';
export const BUILD_FEATURES: string[] = [
  // v60.1 (newest — must be first for releaseHistory drift-guard)
  'Stage 19.1 (v60.1) — ARRAY_UNDERSIZED_FOR_BRAND warning: when no model in the brand can produce DC/AC ≥1.00, surfaces actionable message with minimum panels needed and micro recommendation',
  // v60.0
  'Stage 19.0 (v60.0) — Ratio-aware inverter tier selection: pickRatioAwareTier() replaces blind DC-kW tier lookup — scans ALL brand models, computes DC/AC ratio for each, picks closest to 1.25 target while staying ≥1.00 hard floor — universal fix for all brands and future onboarded brands',
  'Stage 19.0 (v60.0) — attemptDownsize() Rule 1 relaxed: unit count increase now allowed when current ratio is below MIN_DC_AC_RATIO (1.00) — enables 2× smaller model when that is the only way to reach valid ratio',
  'Stage 19.0 (v60.0) — Sol-Ark example: 24p/9.6kW now selects 8K-2P ×1 (ratio 1.20) instead of 12K-2P ×1 (ratio 0.80); 36p/14.4kW selects 12K-2P ×1 (ratio 1.20) instead of 15K-2P ×1 (ratio 0.96)',
  // v59.1
  'Stage 18.6 (v59.1) — Battery Storage panel moved to top of right column — eliminates dead space in 3-col layout when inverter/strings section is shorter than the left column',
  // v59.0
  'Stage 18.5 (v59.0) — Engineering logic audit: compacted battery/generator disabled states, fixed systemType dropdown (roof/ground/fence), fixed utilityMeter default (Bidirectional Net Meter), fixed batteryEnabled BOM payload to respect UI toggle',
  // v58.9
  'Stage 18.4 (v58.9) — Brand audit complete: 46 equipment registry entries added for SMA, Fronius, GoodWe, Sungrow, Growatt, Solis, Tesla, Tigo, APsystems, Hoymiles, Enphase IQ8 variants, and Sol-Ark. All 13 brands now pass full pipeline audit (sizing → registry → brand inference → BOM)',
  // v58.8
  'Stage 18.3 (v58.8) — 3-layer deep fix for SolarEdge BOM: (1) API route guard detects optimizer peripheral as inverterId and resolves central inverter from brand profile; (2) BOM engine Stage 1 safeOptimizerEntry guard prevents string_inverter from being used as optimizer, falls back to inverterEntry.requiredAccessories default; (3) page state stores optimizerPeripheralId separately from inverterId',
  'Stage 18.2 (v58.7) — BOM Stage 1 fix: split InverterConfig.inverterId (central inverter for sizing) from optimizerPeripheralId (optimizer SKU for BOM Stage 1). Fixes SE11400H×36 appearing in Stage 1 Array instead of P505 optimizer ×36',
  'Stage 18.1 (v58.6) — ROOT CAUSE FIX: EcosystemPicker onApply handler now resolves central string inverter (se-11400h) from brand profile when optimizer peripheral (se-p505) selected — prevents brand inference failure → Enphase fallback → 36-micro BOM',
  // v58.5
  'Stage 18.0 (v58.5) — BOM inverter count fix: v57.4/v57.5/v58.3 guards prevent optimizer string-count leaking as inverter count (36→1 for SE11400H 36-panel system)',
  'Stage 18.0 (v58.5) — Enphase IQ8 datasheet corrections: IQ8+ acOutputW 295→290W, maxInputCurrent 14.0→15.0A; IQ8M acOutputW 330→325W, acOutputCurrentMax 1.39→1.35A; IQ8H dcInputWMax 600→540W, acOutputCurrentMax 1.59→1.58A',
  'Stage 18.0 (v58.5) — SMA SB-10.0 brand profile: maxParallelStringsPerMppt=1 marked as intentional override (overridesEquipmentDb: true) to pass brandProfileDriftGuard CI',
  'Stage 18.0 (v58.5) — Engineering page: IQ8+ fallback constants corrected 0.295→0.290 kW and 295→290 W in micro kW calc',
  // v56.0
  'Stage 17.0 (v56.0) — Compliance tab V2: rule accordion (FAIL/WARNING/PASS groups), severity heat map, pass rate ring, jurisdiction panel, auto-resolutions panel, 2-col layout',
  'Stage 17.0 (v56.0) — Electrical tab V2: conductor cards (AC conductor, conduit, disconnect, grounding), conduit schedule table, wire runs panel, inline violation banners',
  'Stage 17.0 (v56.0) — Structural tab V2: expanded max-w-4xl → max-w-none for full-width consistency',
  'Stage 17.0 (v56.0) — Diagram tab V2: enhanced hero with KPI strip, max-w-none, SLD zoom/pan/export all preserved',
  'Stage 17.0 (v56.0) — Schedule tab V2: max-w-none, overflow-x-auto on print sheet, all PVWatts/table logic preserved',
  'Stage 17.0 (v56.0) — Permit tab V2: readiness progress ring, sheet status grid (2-col), package readiness bar, 5-col layout',
  'Stage 17.0 (v56.0) — BOM tab V2: enhanced hero strip with gradient, summary chips (kW/panels/cost), violet accent consistent',
  'Stage 17.0 (v56.0) — Files tab V2: max-w-none, all pipeline/artifact/upload logic preserved',
  // v55.0
  'Stage 16.0 (v55.0) — Config tab full UX overhaul: 3-col responsive grid (1-col mobile / 2-col lg / 3-col xl), SystemFlowBar read-only flow diagram (Array→Inverter→AC Run→Disconnect→Main Panel + Battery/Generator nodes)',
  'Stage 16.0 (v55.0) — Config tab: ENABLE_CONFIG_V2_UI feature flag with legacy fallback, branch visualization bars (micro AC branches / string inverter strings)',
  'Stage 16.0 (v55.0) — Config tab: Battery card collapsible OFF/ON with kWh/backup%/runtime strip, Generator section same collapse pattern, inline validation alerts near Electrical Service inputs',
  'Stage 16.0 (v55.0) — Config tab: Engineering Summary panel — 6 KPI tiles (kW-DC, kW-AC, DC/AC ratio, panels, branches, health) + system health grid, segmented topology control',
  // v54.0
  'Stage 15.0 (v54.0) — Engineering page audit: buildCalcPayload() dynamic panel dims from equipment DB (was hardcoded 70.9×41.7" / 44 lbs) — now reads actual selected panel length/width/weight',
  'Stage 15.0 (v54.0) — Engineering page audit: rackingWeight dynamic from mountingSystem rail spec (was hardcoded 8 lbs) — now computed from rail.weightLbsPerFt × panel span',
  'Stage 15.0 (v54.0) — Engineering page audit: meanRoofHeight wired to ASCE 7-22 Kz calc (was hardcoded 15 ft) — affects velocity pressure qz = 0.00256 × Kz × Kzt × Kd × V²',
  'Stage 15.0 (v54.0) — Engineering page audit: panelOrientation wired to structural calc (was hardcoded portrait) — affects array geometry and load distribution',
  'Stage 15.0 (v54.0) — Roof attachment diagram full rebuild: 3-view SVG (Top-Down Array Layout, Cross-Section load path, Isometric 3D) replacing primitive rectangle diagram',
  'Stage 15.0 (v54.0) — Structural tab Site & Wind Parameters: meanRoofHeight input (8-60 ft) with story-count quick-select (1/2/3-story), panelOrientation portrait/landscape selector',
  // v53.0
  'Stage 14.0 (v53.0) — Engineering page: 21 section cards elevated to eng-panel (glassmorphic, amber-blue gradient top stripe, depth shadow, hover glow)',
  'Stage 14.0 (v53.0) — Engineering page: 29 form inputs → eng-input (glass dark bg, amber focus ring + glow, custom dropdown chevron via eng-select)',
  'Stage 14.0 (v53.0) — Engineering page: 37 field labels → eng-label (uppercase tracking, 11px, weight 600, slate-400/75)',
  'Stage 14.0 (v53.0) — Engineering page: ComplianceSummaryBar → precision compliance-rail with per-segment status glow bars (pass=emerald, warn=amber, fail=red+pulse)',
  'Stage 14.0 (v53.0) — Engineering page: autocomplete dropdown → bg-slate-900/95 glass with amber border glow; auto-field styled eng-auto-field (amber tint+mono)',
  // v52.0
  'Stage 13.0 (v52.0) — Projects page: flat divide-y list → elevated card grid with per-status color glow (blue/amber/emerald/green), top accent stripe, 3 KPI tiles (kW/kWh/cost), 5-step pipeline progress bar, CTA button, grid↔list view toggle',
  'Stage 13.0 (v52.0) — Projects page: ProjectCard with radial glow blob, animated urgency badges (Hot/Stale), hover scale effect, per-type icon tiles (Home/Trees/Layers), full status dropdown with header, action menu with backdrop-blur',
  'Stage 13.0 (v52.0) — Clients page: ClientCard premium elevation — hue-matched gradient avatar, colored top stripe, contact pills with icon squares, 2-tile KPI grid (usage/bill), per-hue monthly sparkline bars, action row',
  'Stage 13.0 (v52.0) — Dashboard WorkQueueRow: elevated cards with per-status left accent stripe, status shadow glow, urgency radial glow blob, rounded icon tile, inline kW badge, modal CTA button with amber glass style',
  // v51.0
  'Stage 12.0 (v51.0) — Engineering Tab Heroes: structural integrity hero (ASCE 7/IBC wind+snow+pitch KPIs), SLD hero (ANSI C/IEEE 315 spec strip + system stats), permit hero (14-sheet package + compliance status), files hero (client workspace + auto-generated file count)',
  'Stage 12.0 (v51.0) — AppShell glassmorphism: deep slate-900/97 sidebar + backdrop-blur(20px) header + amber gradient accent stripe + radial glow logo + nav-active shadow glow + scrollbar-thin',
  'Stage 12.0 (v51.0) — globals.css: glow-amber/blue/emerald/red/purple utilities, card-elevated hover treatment, glass-dark, nav-item-active, accent-stripe-top, pulseRing animation, scrollbar-thin',
  'Stage 12.0 (v51.0) — Dashboard: glass hero command header with LIVE badge + greeting + pipeline summary, elevated financial pressure bar with icon tiles (pipeline/awaiting close/stalled)',
  'Stage 12.0 (v51.0) — Projects: glass hero command header with pipeline stats, elevated 5-col pipeline status bar with follow-up/schedule contextual hints',
  'Stage 12.0 (v51.0) — Clients: glass hero command header with 3-stat footer bar (total/with-usage/avg-bill-yr)',
  'Stage 12.0 (v51.0) — Analytics: glass hero command header integrating time-range selector pill bar',
  'Stage 12.0 (v51.0) — Proposals: glass hero command header with proposal engine badge + generate action',
  'Stage 12.0 (v51.0) — Settings: glass hero command header with settings icon tile',
  // v50.0
  'Stage 11.0 (v50.0) — Engineering UI Overhaul: sticky glassy command bar with live KPI chips (compliance badge, BOM cost, NEC version), project name + kW DC/AC identity strip',
  'Stage 11.0 (v50.0) — Engineering UI Overhaul: tab bar with active glow underline, keyboard shortcut hints (1-0), compliance/BOM status dots on tabs',
  'Stage 11.0 (v50.0) — Engineering UI Overhaul: Config tab system overview hero with KPI grid (kW DC/AC, panels, BOM cost), compliance chips, jurisdiction bar',
  'Stage 11.0 (v50.0) — Engineering UI Overhaul: Compliance tab animated SVG gauge (pass-rate %), 6-card rule grid (electrical/structural/NEC rules/errors/warnings/auto-fixed)',
  'Stage 11.0 (v50.0) — Engineering UI Overhaul: Electrical tab conductor flow diagram (PV→inverter→OCPD→busbar→backfeed) with voltage-drop indicators per segment',
  'Stage 11.0 (v50.0) — Engineering UI Overhaul: Equipment Schedule tab live hero card with panel/inverter/kW/BOM-cost counts before print-ready white card',
  'Stage 11.0 (v50.0) — Engineering UI Overhaul: /admin/distributor-prices UI — 3-section tabbed view (DB overrides, static catalog, category fallbacks), modal CRUD, CSV export',
  // v49.0
  'Stage 10.0 (v49.0) — Distributor Pricing Feed: 3-tier price catalog (CED/Soligent/KWh) stamps unitCost+totalCost on all BOM line items',
  'Stage 10.0 (v49.0) — Distributor Pricing Feed: DB override table migration 015, per-company price overrides win over static catalog',
  'Stage 10.0 (v49.0) — Distributor Pricing Feed: /api/admin/distributor-prices GET/POST/DELETE/PATCH CRUD + 35 unit tests',
  'Stage 9.2 (v49.0) — NEC 2023 Rollup: version-aware labels 690.12(D)/690.7(D)/705.10, AFCI+PCS+polarity notes, 15-state defaults',
  'Stage 9.3 (v49.0) — Proposal PDF Export: server-side wkhtmltopdf pipeline, 7-page HTML/CSS/SVG renderer, GET+POST /api/proposals/[id]/pdf',
  'Stage v48.x post-BOM fixes (v48.0) — (1) extractFilesLegacy photo.name fallback: v1.0/partner surveys with item.name field now get correct filenames instead of photo-N.jpg; (2) renderHardwareSchedule() standalone helper: fence/ground hardware schedule tables now show real computed quantities (piles, rails, clamps, ground rods, conduit) via extractStructuralInputFromCAD + deriveStructuralBOM — no more TBD placeholders; (3) plan-set V4 enrichment: enrichEquipmentItemsFromV4() wired into 7-page plan-set pipeline, merges real part numbers + NEC refs into EquipmentItem[], additive-only + try/catch guarded; (4) extractPhotos v2 tag-based filenames: photo.tag used for meaningful names like roof-overview-1.jpg',
  'Stage v48 PERMIT-BOM (v48.0) — V4 BOM engine wired into 15-page permit pipeline: generateBOMForPermit() replaces static equipment table with live V4 BOM data; gold-standard Equipment Schedule with real manufacturer/model/part numbers + NEC code references; fuzzy inverter registry resolution (4-level: exact → normalized → manufacturer scan → substring); bomForPermit.ts orchestrator + renderBOMTable() standalone helper; 2466/2466 tests passing',
  'Stage 9.4 (v47.437) - Survey V2 UI: SurveyShell progress bar + nav; StepSiteOverview/Roof/Electrical/Obstructions/Photos/Review; ChipGroup chip inputs; ObstructionMap interactive roof diagram; PhotoSlot capture+upload; /survey/[token] page with localStorage autosave; /api/survey/upload-photo Vercel Blob; /api/survey/submit JWT verify + ingest pipeline forward',
  'Stage 9.3 (v47.436) - Fetch + Handoff: payloadFetcher.ts fetches GET /api/surveys/{id} with Bearer auth; tokenMinter.ts mints HS256 JWT for /survey/[token] handoff URL; ingestPipeline Step C wired',
  'Stage 9.2 (v47.435) - Survey Ingest Pipeline: runIngestPipeline() wired into POST /api/webhooks/survey-complete; 202 INGEST_OK or INGEST_FAILED_BUT_LOGGED; 4 new modules in lib/survey/ingest/; CREATE_ORPHAN/ATTACH/TRIAGE strategy; migration 012; +91 tests',
  'Stage 9.1 (v47.434) - Survey Integration Schema + HMAC Verifier + Admin Webhook Log: schemaVersion 1.0; webhook_deliveries table; HMAC-SHA256 verifier; POST /api/webhooks/survey-complete; GET /api/admin/survey-webhook-log; +26 tests',
  'Stage 8.4 (v47.433) - Brand-Profile Centralization: 6 drift corrections across 4 brand profiles (SMA SB-7.7 mpptCount 2->3, SMA SB-10.0 maxParallel 1->6, GoodWe GW10K-MS 10/15/2->9.6/14.4/3, Sungrow SG15RS maxParallel 1->2, SolarEdge generic-string SE-7600H/SE-10000H mpptCount 2->1); ALL overridesEquipmentDb flags removed; drift-guard audit log reports zero overrides',
  'Stage 8.1 + 8.2 (v47.432) - BOM dead-code deletion (-3,278 lines across 7 files) + drift-fence CI tests (+273 tests across 2 new files: rackingDatabaseDriftGuard + brandProfileDriftGuard with overridesEquipmentDb opt-out); 5 pre-existing brand-profile drift points documented via opt-out flag, 2 racking divergences in EXPECTED_DIVERGENCES allowlist - Stage 8.3/8.4 backlog items tracked in-code',
  'Stage 7 - Consolidation Assessment (v47.431, READ-ONLY) - docs/STAGE7_CONSOLIDATION_ASSESSMENT.md identifies 2,228 lines of dead BOM code, racking DB duality, and brand-profile spec drift; recommends Stage 8.1 (BOM deletion) + 8.2 (drift-fence CI tests), defer 8.3/8.4',
  'SolarEdge Allocation Regression Fix (v47.430) - voltageAwarePanelsPerUnit optimizer-topology bypass; sizing now respects mpptCount x maxParallelStringsPerMppt for optimizer inverters (4 new regression-lock tests, 1808/1808 pass)',
  'Racking Visibility in UI (Stage 6) - 174 CI-blocking tests + compatibleRacking in ResolvedBrandEquipment + EcosystemKitPanel Racking section',
  'Battery Ecosystem Smoke Suite - 120 CI-blocking tests + 6 new SKUs (Tigo EI/GO, BYD HVM, Pylontech Force-H2, EG4 PowerPro, HomeGrid Stackd)',
  'Batch Brand Onboarding - Solis + Tesla + Tigo (13 SKUs, 218 datasheet audit tests)',
  'Brand Onboarding Smoke Suite (317 CI-blocking tests)',
  'Command Center',
  'Operations Pipeline',
  'Deal Decision Engine',
  'Stage Action Modal',
  'EcoFlow PowerOcean Integration',
  'SolFence Fence Watcher',
  'Brand-Driven Sizing Engine',
  'Sizing->BOM Adapter',
  'Sizing Recommendation Panel',
  'Auto String Rebuild',
  'Panel Count Source of Truth',
  'String-Capacity Inverter Sizing',
  'Real-Life Inverter Upsizing',
  'Physical-Unit String Indexing',
  'Info-Level Warning Surfacing',
  'System-Wide Validation Layer',
  'Unified Inverter Count Semantics',
  'Brand Compatibility Matrix',
  'Smart Defaults',
  'User Intent Lock',
  'DC/AC Ratio Guardrail',
  'Parallel String Sizing',
  'MPPT-Aware String Allocation',
  'Feasibility-First Sizing',
  'SolarEdge Datasheet Reconciliation',
  'Feasibility-Aware Recommendations',
  'Feasibility-Driven Fix Engine',
  'Voltage-Safe String Sizing',
  'Best-Fit Real-World Sizing Engine',
  'Hard Constraint Enforcement',
  'Feasibility Hard Gate',
  'Smart Parallel Slot Count',
  'Feasibility-Aware Upsize Guard',
  'Sungrow Brand Profile',
  'SMA Brand Profile',
  'GoodWe Brand Profile',
  'Multi-Inverter Compliance Fix',
  'System Config Auto-Fill',
  'National Utility Matching',
  'County Auto-Fill from ZIP',
  'AHJ Auto-Selection',
  'Equipment Ecosystem Schema',
  'Tesla Ecosystem',
  'Enphase Ecosystem',
  'APsystems Ecosystem',
  'Hoymiles Ecosystem',
  'Generac Ecosystem',
  'SolarEdge Ecosystem',
  'Monitoring Gateway Catalog',
  'EV Charger Catalog',
  'Ecosystem Picker UI',
  'Ecosystem Kit Builder',
  'Proposal Ecosystem Branding',
  'Brand Equipment Auto-Discovery',
  'Ecosystem Reference Validator',
  'Sol-Ark Brand Profile',
  'Sol-Ark Hybrid Inverter Family',
  'EcoFlow Ecosystem Tags',
  'Fronius Ecosystem Tags',
  'Sungrow Ecosystem Tags',
  'SMA Ecosystem Tags',
  'GoodWe Ecosystem Tags',
  'Brand Profile Alignment Audit',
  'Datasheet URL Verification',
  'Tier-1 Datasheet Backfill',
  'Battery-Only Ecosystem Apply',
  'Tesla Apply Fix',
  'Generac Datasheet Backfill',
  'Fronius & SMA Datasheet URL Fix',
  'GoodWe Datasheet Fix',
  'Sungrow/EcoFlow Deactivation (No US Catalog)',
  'SolarEdge + Hoymiles Datasheet URLs (Distributor Mirrors)',
  'Panel & Racking Datasheet URL Cleanup',
  'Zero Broken Datasheet URLs',
  'Compliance Tab MPPT Allocation Message Honesty',
  'No Contradictory DC/AC Warnings on Allocation Failure',
  'Topology-Aware String Current (Optimizer vs Panel)',
  'Layout-Drift Warning (Config vs Sizing Recommendation)',
  'Optimizer-System Merge Hint (Compliance Tab)',
  'Topology-Aware Operating Current (MPPT Allocator)',
  'Fixed-Bus DC Voltage Schema (SolarEdge HD-Wave)',
  'Parallel-Strings-Per-MPPT Payload Plumbing',
  'SE7600H Datasheet Reconciliation (1-2 strings)',
  'Overall Status Recompute After V3 Structural Merge',
  'Integrated DC Disconnect Schema (NEC 690.15)',
  'E-DC-DISCONNECT Gated by Inverter Integrated Switch',
  'Fronius Primo Datasheet Reconciliation (Isc 27A)',
  'SMA Sunny Boy US-41 Datasheet Reconciliation',
  'GoodWe DNS + MS-US Datasheet Reconciliation',
  'Sol-Ark Hybrid Datasheet Reconciliation (8K/12K/15K/30K)',
  'Slot-Aware String Generator (Physical MPPT Slot Capacity)',
  'Hybrid Topology End-to-End Wiring',
  'Sol-Ark Self-Limiting MPPT Current (No 1.25x Derivation)',
  'MPPT-Current-Aware String-Length Selection (Feasibility Parity)',
  'Growatt MIN TL-XH-US Hybrid Inverter Family',
  'Panel Compatibility Suggestions (MPPT-Current-Aware Panel Swap)',
  'MPPT Allocator Forced-Spread Second Pass (Brand-Agnostic)',
  'Brand-Agnostic Panel Auto-Swap + UI Education',
  'Panel Auto-Heal (Advisory -> Authoritative Pipeline)',
];

export function getBuildBadge(): string {
  return `${BUILD_VERSION} · ${BUILD_DATE}`;
}