// lib/version.ts -- SolarPro Build Version
export const BUILD_VERSION     = 'v47.11';
export const BUILD_DATE        = '2026-06-10';
export const BUILD_DESCRIPTION = 'v47.11: Utility rate database rebuild + bill pipeline rate fallback -- accurate 2024/2025 EIA rates, new rate breakdown schema, 3-tier rate priority';
export const BUILD_FEATURES    = [
  // v47.11 -- Utility rate database rebuild + bill pipeline fix
  'ROOT CAUSE 1: UTILITY_RETAIL_RATES in utility-rules.ts had stale/incorrect rates -- CMP was $0.198 (2022 EIA), actual 2024 rate is $0.265/kWh (EIA ME avg Jan-Sep 2024)',
  'ROOT CAUSE 2: STATE_UTILITY_FALLBACK avgRate values in utilityDetector.ts were 2022-era EIA data -- ME/VT/NH/CT/CA/HI/MI/AK all needed updating',
  'ROOT CAUSE 3: utility_policies DB table had only default_residential_rate column -- no retail_rate (all-in) vs supply_rate (energy-only) distinction',
  'ROOT CAUSE 4: utilityMatcher.ts read only default_residential_rate -- would return stale/supply-only rate as the effective rate for solar calculations',
  'ROOT CAUSE 5: handleBillComplete rate fallback used hardcoded 0.13 when bill rate unavailable -- did not use DB retail rate as priority 2',
  'FIX: lib/utility-rules.ts -- Added UtilityRateBreakdown interface with retailRate/supplyRate/distributionRate/transmissionRate/fixedMonthlyCharge/netMeteringType/lastUpdated/rateSource',
  'FIX: lib/utility-rules.ts -- UTILITY_RATE_BREAKDOWNS replaces flat UTILITY_RETAIL_RATES dict; backward-compat shim auto-derives UTILITY_RETAIL_RATES from it',
  'FIX: lib/utility-rules.ts -- CMP retail_rate corrected: $0.198 -> $0.265/kWh (EIA + CMP tariff sheet 14, 2024)',
  'FIX: lib/utility-rules.ts -- Versant Power: $0.198 -> $0.272/kWh; GMP: $0.198 -> $0.215/kWh; Unitil: $0.228 -> $0.235/kWh',
  'FIX: lib/utility-rules.ts -- PG&E: $0.32 -> $0.338/kWh; PSE&G: $0.17 -> $0.178/kWh; ComEd: $0.13 -> $0.148/kWh; Ameren: $0.12 -> $0.128/kWh',
  'FIX: lib/utility-rules.ts -- MAX_VALID_RETAIL_RATE raised $0.50 -> $0.60 (HI/CA rates exceed old ceiling)',
  'FIX: lib/utility-rules.ts -- Added getUtilityRateBreakdown() export: returns full UtilityRateBreakdown for a utility by name',
  'FIX: lib/utilityDetector.ts -- STATE_UTILITY_FALLBACK avgRate updated for 8 states: ME 0.198->0.265, VT 0.198->0.215, NH 0.228->0.235, CT 0.248->0.252, CA 0.298->0.318, HI 0.388->0.395, MI 0.178->0.188, AK 0.228->0.258',
  'FIX: lib/utilityMatcher.ts -- MatchedUtility interface adds retailRate + effectiveRate fields',
  'FIX: lib/utilityMatcher.ts -- P1/P2 queries now SELECT retail_rate column; effectiveRate = retailRate ?? defaultResidentialRate',
  'FIX: lib/utilityMatcher.ts -- P3/P4 fallback returns include retailRate: null, effectiveRate: fallbackRate',
  'FIX: app/api/bill-upload/route.ts -- Uses matchedUtility.effectiveRate (not defaultResidentialRate) as DB rate; logs retailRate vs legacyRate vs effectiveRate',
  'FIX: app/projects/[id]/page.tsx -- handleBillComplete now reads result.matchedUtility?.effectiveRate as priority-2 rate source',
  'FIX: app/projects/[id]/page.tsx -- 3-tier rate priority: bill_rate (if non-default) > DB retail rate > state average > national default 0.13',
  'FIX: app/projects/[id]/page.tsx -- handleBillComplete signature now includes matchedUtility?: { effectiveRate, retailRate, ... }',
  'FIX: app/api/migrate/route.ts -- Migration 011: adds retail_rate/supply_rate/distribution_rate/transmission_rate/fixed_monthly_charge/net_metering_type/last_updated/rate_source columns to utility_policies',
  'FIX: app/api/migrate/route.ts -- Migration 011: seeds accurate 2024/2025 retail rates for 12 major utilities (CMP, Versant, Eversource, National Grid, GMP, Unitil, PGE, SCE, FPL, Duke, PSE&G, ComEd, Ameren)',
  'LOGGING: [BILL_PARSED] now logs dbRetailRate for rate source tracing',
  'LOGGING: [bill-upload] now logs retailRate vs legacyRate vs effectiveRate for each matched utility',
  // v47.10 -- Force dynamic on all API routes
  'ROOT CAUSE: Next.js attempted to statically render API routes at build time; routes accessing request.headers/cookies()/DB at render time triggered DYNAMIC_SERVER_USAGE error',
  'ROOT CAUSE: /api/settings/branding and /api/stats confirmed failing in Vercel logs with digest: DYNAMIC_SERVER_USAGE -- login flow broken',
  'FIX: Audited all 97 route.ts files in /app/api -- 57 already had force-dynamic; 40 were missing it',
  "FIX: Added export const dynamic = 'force-dynamic' to all 40 missing routes -- forces runtime evaluation, never static rendering",
  'FIX: Added export const revalidate = 0 to all 40 routes -- disables static caching, ensures fresh data on every request',
  'ROUTES PATCHED: auth/login, auth/logout, auth/register, auto-design, auto-size, bill-upload, bill-upload/test, clients/[id], clients, dev-check, dsm, elevation, engineering/structural-v2, enterprise/contact, equipment/save, geocode, hardware, incentives, maps-session, migrate, ocr, pricing, production, projects/[id]/layout, projects/[id], projects/[id]/versions/[versionId], projects/[id]/versions, projects, proposals/[id], proposals/[id]/share, proposals, settings/branding, settings/logo, settings/profile, solar, stats, stripe/checkout, stripe/portal, tile, utility-detect',
  "VERIFIED: All 97/97 route.ts files now contain export const dynamic = 'force-dynamic'",
  // v47.9 -- Definitive deployment startup fix
  'ROOT CAUSE 1: channel_binding=require in DATABASE_URL caused SSL handshake failures during Neon proxy cold start -- errors mis-classified as fatal causing DB_CONFIG_ERROR banner',
  'ROOT CAUSE 2: getDbWithRetry() delays 1s/2s/4s=7s too aggressive for Vercel Hobby 10s timeout -- probe retries consumed entire timeout budget before actual query ran',
  'ROOT CAUSE 3: No module-level Neon singleton -- neon(url) called on every /api/auth/me request (mount/focus/tab-switch) creating redundant HTTP clients and SELECT 1 probe overhead',
  'ROOT CAUSE 4: auth routes had no maxDuration export -- Vercel Hobby killed functions at 10s default while retries were in progress, producing 504 instead of 503 DB_STARTING',
  'ROOT CAUSE 5: engineering-automation.ts imported synchronous getDb() from auth.ts -- engineering routes returned 500 (not 503) on cold start, breaking frontend error handling',
  'FIX: lib/db-ready.ts -- getDatabaseUrl() now strips channel_binding=require -> channel_binding=disable at runtime (Vercel env var sanitization)',
  'FIX: lib/.env.local -- DATABASE_URL updated to use channel_binding=disable',
  'FIX: lib/db-ready.ts -- module-level Neon singleton (_cachedSql) created once per function instance cold start, not per request',
  'FIX: lib/db-ready.ts -- _instanceWarm flag: after first successful SELECT 1 probe, subsequent getDbReady() calls skip probe entirely (~0ms overhead on warm paths)',
  'FIX: lib/db-ready.ts -- MAX_RETRIES 3->5, BASE_DELAY 1000ms->300ms; delays now 300/600/1200/2400/4800ms = 9.1s total budget (was 7s but consumed 70% of Hobby timeout)',
  'FIX: lib/db-ready.ts -- isTransientDbError() SCRAM/channel-binding errors now explicitly transient (were falling through to non-retryable causing DB_CONFIG_ERROR)',
  'FIX: app/api/auth/login/route.ts -- maxDuration=30 added; prevents Vercel from killing during retry loop',
  'FIX: app/api/auth/me/route.ts -- maxDuration=30 added; prevents 504 timeout during DB cold-start retries',
  'FIX: app/api/auth/register/route.ts -- maxDuration=30 added; consistent with login/me',
  'FIX: lib/engineering-automation.ts -- replaced getDb() from ./auth with getDbReady() from db-neon; all 11 call sites updated to await (await getSql())`SQL`',
  'LOGGING: [SERVER_INSTANCE_STARTED] emitted by db-ready.ts and db-neon.ts on module load (once per cold start)',
  'LOGGING: [ENVIRONMENT_LOADED] DATABASE_URL presence + NODE_ENV + VERCEL_ENV logged at startup',
  'LOGGING: [ENV_DATABASE_URL_STATUS] DATABASE_URL length + channel_binding sanitization logged on every getDatabaseUrl() call',
  'LOGGING: [DB_CLIENT_INIT] neon() singleton creation logged',
  'LOGGING: [DB_CONNECTION_ATTEMPT] each SELECT 1 probe attempt numbered and logged',
  'LOGGING: [DB_CONNECTION_SUCCESS] successful probe logged with attempt number',
  'LOGGING: [DB_CONNECTION_FAILED] failed probe logged with error message + retry delay',
  'LOGGING: [AUTH_LOGIN_REQUEST] login attempt start + email logged',
  'LOGGING: [AUTH_SESSION_CHECK] DB connection acquisition logged in login and me routes',
  // v47.8 -- Bill workflow pipeline bug fix
  'ROOT CAUSE: handleBillComplete PUT body stored _stateCode in bill_data JSONB but never _city -- Location field on System Size page always showed Not set',
  'ROOT CAUSE: rowToProject() hydrated stateCode/utilityName/utilityRatePerKwh from bill_data JSONB but had no city hydration path -- city was lost on every DB round-trip',
  'ROOT CAUSE: updatedProject merge in handleBillComplete included stateCode override but completely omitted city -- city was lost immediately after the modal closed',
  'ROOT CAUSE: getProjectWithDetails() had its own inline bill_data hydration block that also lacked city hydration -- detail fetches returned project without city too',
  'ROOT CAUSE: store cache returned stale project on navigation (loadActiveProject returns cached entry) -- bill data appeared missing if store was not updated after save',
  'FIX: page.tsx handleBillComplete -- added city = result.locationData?.city capture',
  'FIX: page.tsx handleBillComplete -- bill_data JSONB now includes _city field alongside _stateCode/_utilityName/_utilityRatePerKwh/_billAnalysis',
  'FIX: page.tsx handleBillComplete -- updatedProject merge now includes city: city || json.data.city (was missing entirely)',
  'FIX: page.tsx handleBillComplete -- calls syncProjectToStore(updatedProject) after save to keep in-memory store cache warm',
  'FIX: db-neon.ts rowToProject() -- added city hydration from bill_data._city; city now included in returned Project object',
  'FIX: db-neon.ts getProjectWithDetails() -- same city hydration from bill_data._city in inline hydration block',
  'FIX: store/appStore.ts -- added syncProjectToStore(project) action: replaces project in store array + localSaveProject without re-fetching',
  'FIX: store/appStore.ts -- added syncProjectToStore to AppStore interface',
  'LOGGING: [BILL_PARSED] logs annualKwh/utilityName/utilityRate/stateCode/city after OCR result processing',
  'LOGGING: [BILL_SAVING] logs projectId/systemKw/utilityName/annualKwh/stateCode/city before PUT',
  'LOGGING: [BILL_SAVED_TO_PROJECT] logs all key fields after successful PUT response',
  'LOGGING: [PROJECT_STATE_UPDATED] logs billAnalysis presence + utilityName/stateCode/city/utilityRate after setProject',
  'LOGGING: [SYSTEM_SIZE_LOADED] SystemSizeTab useEffect logs all 8 key fields on every project prop change',
  // v47.6 -- Critical production stability audit
  'ROOT CAUSE: All non-auth API routes used getDb() (synchronous, no retry) -- any Neon cold start caused immediate DbConfigError/500 across entire app',
  'ROOT CAUSE: db-neon.ts exported functions (getProjectById, updateProject, getClientsByUser, etc.) all called getDb() internally -- 22 functions affected',
  'ROOT CAUSE: 65 direct API route files called getDb() from @/lib/auth or @/lib/db-neon without retry',
  'ROOT CAUSE: All non-auth catch blocks returned raw 500 -- UserContext retries on 503 DB_STARTING but treats 500 as transient without code; frontend had no semantic signal',
  'FIX: lib/db-neon.ts -- all 22 internal getDb() calls replaced with await getDbReady() -- ALL exported db functions now cold-start resilient',
  'FIX: lib/db-neon.ts -- new handleRouteDbError(routeLabel, error) utility: DbConfigError->503 DB_CONFIG_ERROR; all other->503 DB_STARTING with Retry-After: 3',
  'FIX: app/api/projects/* -- all routes (GET/PUT/DELETE project, layout, versions) now use handleRouteDbError',
  'FIX: app/api/clients/* -- all routes (GET/POST/PUT/DELETE client) now use handleRouteDbError',
  'FIX: app/api/proposals/* -- all routes (GET/POST/PUT proposal, share) now use handleRouteDbError',
  'FIX: app/api/settings/* -- profile, branding, logo routes now use handleRouteDbError',
  'FIX: app/api/engineering/* -- plan-set, preliminary, auto-configure, override, assist, slg, save-outputs, latest-run, run-from-file, and all others use handleRouteDbError',
  'FIX: app/api/admin/* -- all 19 admin routes (users, utilities, incentives, free-pass, etc.) use handleRouteDbError',
  'FIX: app/api/production/route.ts, equipment/*, stripe/*, stats/* -- all use handleRouteDbError',
  'VERIFIED: TypeScript build passes with zero errors after all replacements',
  'PRESERVED: auth routes (login, me, register) retain their existing per-route DbConfigError handling (not changed)',
  'PRESERVED: Non-DB 500s (missing MIGRATE_SECRET, OCR errors, external API failures) remain as-is -- not DB cold-start paths',
  // v47.5 -- Bill upload workflow pipeline fix
  'project/[id]/page.tsx: handleUploadBill now opens inline BillUploadFlow modal (not 404 route)',
  'project/[id]/page.tsx: handleBillComplete builds BillAnalysis + PUTs to /api/projects/[id]',
  'project/[id]/page.tsx: setProject() with hydrated billAnalysis after save -- workflow recomputes',
  'db-neon.ts: updateProject() now persists bill_data JSONB column',
  'db-neon.ts: rowToProject() hydrates billAnalysis/utilityName/utilityRatePerKwh/stateCode from bill_data',
  'db-neon.ts: getProjectWithDetails() also hydrates billAnalysis from bill_data._billAnalysis',
  // v47.4 -- Bill parser audit
  'billParser.ts: U1 header search 500->1000 chars; U3 case-insensitive; hardened rate patterns; P2 min 50',
  'utility-rules.ts: CMP, Versant, Eversource, National Grid, GMP, Unitil added to registry',
  'billOcrEngine.ts: improved Vision prompt for CMP bill format',
  // v47.3 -- UserContext logout fix
  'ROOT CAUSE: refreshUser() called setUser(null) on retry exhaustion (Neon cold start after idle)',
  'FIX: contexts/UserContext.tsx -- fetchUserWithRetry() returns transient on retry exhaustion; only 401 triggers logout',
  'FIX: contexts/UserContext.tsx -- FetchStatus string enum: ok/logout/retry/preserve',
  // v47.2 -- Production stability: defense-in-depth DB error handling
  'ROOT CAUSE: isTransientDbError() used blacklist approach -- any Neon cold-start error with unusual message fell through to non-transient, causing DB_CONFIG_ERROR mis-classification',
  'ROOT CAUSE: login/route.ts catch used msg.includes(DATABASE_URL) -- matched Neon connection string errors during cold start, showed Database not configured to users',
  'ROOT CAUSE: me/route.ts generic 500 fallthrough -- UserContext does not retry on 500, so unrecognized errors appeared as logout',
  'ROOT CAUSE: UserContext treated any non-200 non-503 as definitive logout (if (!res.ok) return null)',
  'FIX: lib/db-ready.ts -- isTransientDbError() rewritten with WHITELIST-FATAL approach: only explicit pg auth/permission/missing errors are fatal; all unknown errors default to transient',
  'FIX: lib/db-ready.ts -- AUTH_DB_STARTING / AUTH_DB_CONFIG_ERROR log codes on every error path for Vercel log searchability',
  'FIX: app/api/auth/me/route.ts -- handleDbError() centralizes all DB error responses; defaults to DB_STARTING for ALL non-DbConfigError errors (never 500)',
  'FIX: app/api/auth/me/route.ts -- inner fallback query wrapped in own try/catch; connection errors in fallback correctly return DB_STARTING not 500',
  'FIX: app/api/auth/me/route.ts -- AUTH_DB_STARTING/AUTH_DB_CONFIG_ERROR/AUTH_DB_QUERY_ERROR log tags on every code path with stage= context',
  'FIX: app/api/auth/login/route.ts -- removed msg.includes(DATABASE_URL) from config error check; only DbConfigError is fatal',
  'FIX: app/api/auth/login/route.ts -- all non-DbConfigError errors return DB_STARTING (not 500/Login failed); same safe-default pattern',
  'FIX: contexts/UserContext.tsx -- HTTP 500 from /api/auth/me now retries (not logout); only HTTP 401 = definitive logout',
  // v47.1 -- Production stability: deployment cold-start session fix
  'ROOT CAUSE: /api/auth/me used getDb() (no retry) -- UserContext called on mount/focus/30s -- cold start = null user = apparent logout',
  'FIX: app/api/auth/me/route.ts -- switched getDb() to getDbReady() (3x retry, 1s/2s/4s backoff); returns DB_STARTING 503 on transient failure (not 500)',
  'FIX: app/api/auth/me/route.ts -- DB_CONFIG_ERROR vs DB_STARTING error codes prevent UserContext from misclassifying cold starts as logouts',
  'FIX: contexts/UserContext.tsx -- fetchUserWithRetry() wraps fetchUserFromDb(); retries up to 5x (3s each) on DB_STARTING 503 before clearing user state',
  'FIX: contexts/UserContext.tsx -- 503/DB_STARTING never clears user state; only 401 is treated as definitive logout',
  'FIX: app/api/auth/register/route.ts -- switched getDb() to getDbReady(); proper DB_STARTING/DB_CONFIG_ERROR error codes',
  'FIX: lib/adminAuth.ts -- requireAdmin() and requireAdminApi() switched to getDbReady() with retry',
  'FIX: lib/auth.ts -- makeSessionCookie() adds Secure flag in production (NODE_ENV=production) for HTTPS-only cookie delivery',
  'FIX: lib/auth.ts -- clearSessionCookie() adds matching Secure flag',
  'FIX: lib/auth.ts -- exports DbConfigError re-export from db-ready for convenience',
  'FIX: lib/db-neon.ts -- getDb() now throws DbConfigError (non-retryable) instead of plain Error; routes can distinguish config vs transient',
  'FIX: lib/db-neon.ts -- exports getDbReady() async wrapper and DbConfigError for routes importing from db-neon',
  // v47.0 -- Utility bill parsing pipeline audit
  'FIX: lib/billOcr.ts -- validateBillData() accepts optional BillValidationContext; suppresses stale utility/rate warnings when values resolved post-match',
  'FIX: lib/billOcr.ts -- rate warning range updated to $0.06-$0.50/kWh; unusual rate warning replaces hard rejection',
  'FIX: lib/utility-rules.ts -- MIN_VALID_RETAIL_RATE lowered 0.07->0.06; MAX_VALID_RETAIL_RATE=0.50 added; rates above max corrected to DB rate',
  'FIX: app/api/bill-upload/route.ts -- validateBillData() moved from pre-geocoding (line 242) to post-rate-correction; context passes resolvedMatchedUtility + finalRate',
  'FIX: app/api/bill-upload/route.ts -- UI warnings now reflect fully resolved state (utility matched, rate corrected) not raw parse output',
  // v46.9 -- DB readiness guard
  'NEW: lib/db-ready.ts -- getDbWithRetry() 3x retry with 1s/2s/4s exponential backoff for Neon cold starts',
  'NEW: lib/db-ready.ts -- probeDbReady() SELECT 1 wake probe before auth queries',
  'NEW: lib/db-ready.ts -- isTransientDbError() classifies transient vs fatal DB errors',
  'NEW: lib/db-ready.ts -- DbConfigError non-retryable class for missing DATABASE_URL',
  'FIX: lib/auth.ts -- getDbReady() async wrapper uses getDbWithRetry; getDb() kept for non-auth routes',
  'FIX: app/api/auth/login/route.ts -- uses getDbReady() with retry; returns code=DB_STARTING on 503; Retry-After header',
  'FIX: app/auth/login/page.tsx -- detects DB_STARTING 503; shows Starting server... banner; auto-retries up to 5x with countdown',
  // v46.8 -- Panel clearing fix
  'FIX: SolarEngine3D.tsx -- finalizeFence: set lastRenderedPanelsRef.current before onPanelsChange to prevent orphaned entities',
  'FIX: SolarEngine3D.tsx -- handleRoofClick: same lastRenderedPanelsRef sync fix',
  'FIX: SolarEngine3D.tsx -- handleGroundClick: same lastRenderedPanelsRef sync fix',
  'FIX: SolarEngine3D.tsx -- finalizePlane: same lastRenderedPanelsRef sync fix',
  'FIX: SolarEngine3D.tsx -- Row finalization: same lastRenderedPanelsRef sync fix',
  // v46.7 -- TS build fixes
  'NEW: lib/utilityMatcher.ts -- normalizeUtilityName() strips noise words; matchUtility() P1 exact / P2 pg_trgm fuzzy / P3 state fallback / P4 auto-discover',
  'FIX: app/api/bill-upload/route.ts -- calls matchUtility() after parseBill(); applies DB rate (default_residential_rate) to billData.electricityRate',
  'FIX: app/api/bill-upload/route.ts -- geo detectUtility() is now fallback-only; parsed name match wins',
  'FIX: app/api/bill-upload/route.ts -- bill persisted to bills table when projectId in form data',
  'NEW: app/api/migrate/route.ts -- Migration 009: default_residential_rate + source on utility_policies; pg_trgm extension; GIN index',
  'NEW: app/api/migrate/route.ts -- Migration 010: bills table (project_id, utility_name, monthly_kwh, annual_kwh, electric_rate, parsed_json)',
  'NEW: lib/db-neon.ts -- saveBill() and getBillsByProject() functions',
  'NEW: app/api/bills/route.ts -- GET ?projectId= and POST endpoints',
  'FIX: components/onboarding/BillUploadModal.tsx -- step 6 persists bill to /api/bills after project creation',
  'FIX: lib/utility-rules.ts -- getProductionFactor() accepts stateCode param; state-aware factors (ME/VT/NH=1050, CA/AZ/NV=1600, FL/TX=1500, NY/NJ/CT=1100)',
  'FIX: app/api/bill-upload/route.ts -- passes locationData.stateCode to getProductionFactor()',
  // v46.5 -- Bill parser P3 fix
  'billParser: parseBarGraphTable -- Monthly Usage Summary values are monthly kWh totals (not daily averages x days)',
  // v46.4 -- Bill parser comma-kWh fix
  'billParser: parseHandwrittenList -- fix comma-kWh (1,234 kWh) regex {1,3} -> {0,2}',
  'billParser: parsePrintedTable -- fix comma-kWh regex {2,4} -> {0,3} + val>=100 guard',
  // v46.3 -- Build fix
  'version.ts: rewritten with ASCII-only strings to prevent TypeScript merge-conflict false positives',
  // v46.2 -- Bill parser fixes
  'billParser: parseHandwrittenList -- skip year-number false matches (Jan 2025 362 => 362 not 2025)',
  'billParser: parseHandwrittenList -- date context guard (Jan 15, 2025 / Jan 15 2025 => skip 15)',
  'billParser: parseHandwrittenList -- comma-number support (1,234 kWh)',
  'billParser: extractCurrentMonth -- added Energy Charge pattern + kWh@ pattern',
  'billParser: annual cross-check now correctly computes 0.0% diff when explicit == computed',
  // v46.1 -- OCR extraction repair
  'billImagePreprocess.ts: EXIF auto-rotate, grayscale, normalize, sharpen, threshold, upscale to 2400px',
  'ocr/route.ts: multi-pass Tesseract -- PSM 3 (auto) + PSM 6 (document block), best result wins',
  'ocr/route.ts: raw OCR text logged before any parsing -- full debug visibility',
  'ocr/route.ts: preprocessing pipeline applied before every OCR run',
  'billOcr.ts: extractBillDataWithAI() -- structured JSON fallback when 0 fields extracted',
  'route.ts: AI fallback triggered when extractedFields === 0 or < 2',
  'route.ts: raw OCR text logged to console before parsing',
  'vercel.json: dev=preview, master=manual-only -- no accidental production deploys',
  'main.yml: manual-trigger-only production deploy with DEPLOY confirmation guard',
  'next.config.js: sharp + exif-reader added to webpack externals',
  // v46.0 -- Deterministic bill parser
  'route: parseBill() from billParser.ts is now the single authoritative final parser',
  'route: parseBillTextWithLLM() removed -- no LLM rewrites of numeric fields ever',
  'billParser: strict source priority P1 printed table > P2 handwritten > P3 bar graph',
  'billParser: rate returns null if not found -- never guesses',
  // v45.9 -- SaaS Tesseract OCR
  'app/api/ocr/route.ts -- dedicated OCR endpoint, webpack-isolated',
  'OCR pipeline: Tesseract.js WASM (primary) => Tesseract CLI (secondary) => OpenAI Vision (fallback)',
];

export function getBuildBadge(): string {
  return `SolarPro ${BUILD_VERSION} - ${BUILD_DATE}`;
}