import type { EngineeringDecisionDefinition, EngineeringDecisionType } from './types';

const NEC_690_8 = { ruleId: 'NEC-690.8', label: 'PV circuit current calculations', reference: 'NEC 690.8', ruleType: 'NEC' as const };
const NEC_690_9 = { ruleId: 'NEC-690.9', label: 'PV overcurrent protection', reference: 'NEC 690.9', ruleType: 'NEC' as const };
const NEC_705_12 = { ruleId: 'NEC-705.12', label: 'Load-side interconnections', reference: 'NEC 705.12', ruleType: 'NEC' as const };
const NEC_690_12 = { ruleId: 'NEC-690.12', label: 'Rapid shutdown', reference: 'NEC 690.12', ruleType: 'NEC' as const };
const NEC_110_3 = { ruleId: 'NEC-110.3', label: 'Listed equipment instructions', reference: 'NEC 110.3(B)', ruleType: 'NEC' as const };
const NEC_250 = { ruleId: 'NEC-250', label: 'Grounding and bonding', reference: 'NEC Article 250', ruleType: 'NEC' as const };
const NEC_300 = { ruleId: 'NEC-300', label: 'Wiring methods', reference: 'NEC Chapter 3', ruleType: 'NEC' as const };
const NEC_690_31 = { ruleId: 'NEC-690.31', label: 'PV wiring methods', reference: 'NEC 690.31', ruleType: 'NEC' as const };
const NEC_690_53 = { ruleId: 'NEC-690.53', label: 'PV source circuit labels', reference: 'NEC 690.53', ruleType: 'NEC' as const };
const NEC_690_56 = { ruleId: 'NEC-690.56', label: 'PV rapid shutdown labels', reference: 'NEC 690.56', ruleType: 'NEC' as const };
const IFC_1207 = { ruleId: 'IFC-1207', label: 'Energy storage location coordination', reference: 'IFC 1207 / local ESS rules', ruleType: 'AHJ' as const };
const AHJ_SETBACK = { ruleId: 'AHJ-ROOF-SETBACK', label: 'Roof access and setback policy', reference: 'AHJ fire setback requirements', ruleType: 'AHJ' as const };
const PROJECT_POLICY = { ruleId: 'PROJECT-DETERMINISTIC-DEFAULTS', label: 'Explicit project default policy', reference: 'SolarPro deterministic default policy', ruleType: 'PROJECT_POLICY' as const };
const DOC_POLICY = { ruleId: 'DOC-PROVENANCE-V1', label: 'Document provenance policy', reference: 'Document Provenance + Requirement Binding Foundation v1', ruleType: 'DOCUMENT_POLICY' as const };

export const ENGINEERING_DECISION_REGISTRY: Record<EngineeringDecisionType, EngineeringDecisionDefinition> = {
  conductor_sizing: {
    decisionType: 'conductor_sizing',
    label: 'Conductor sizing provenance',
    decisionCategory: 'calculation',
    engineeringDomain: 'electrical',
    governingRules: [NEC_690_8, NEC_690_31, NEC_110_3],
    engineeringDependencies: ['requirement:main_service_panel', 'documentSection:E-1.interconnection'],
    requiredInputs: ['system.inverters[].strings[].wireGauge', 'system.inverters[].strings[].isc', 'system.inverters[].strings[].ampacity'],
    optionalInputs: ['project.wireGauge', 'project.conduitType', 'project.wireLength'],
    affectedDocumentSectionIds: ['VAL-1.registry', 'E-1.interconnection', 'SLD.service-equipment'],
    downstreamImpacts: ['permit validation electrical row', 'BOM conductor rows', 'SLD conductor callouts'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'permit_input_allowed_with_explicit_default',
    deterministicEvaluationNotes: ['Uses existing conductor fields as selected values; this registry does not resize conductors.'],
  },
  breaker_sizing: {
    decisionType: 'breaker_sizing',
    label: 'Breaker sizing provenance',
    decisionCategory: 'calculation',
    engineeringDomain: 'electrical',
    governingRules: [NEC_690_8, NEC_690_9, NEC_705_12],
    engineeringDependencies: ['requirement:main_service_panel', 'requirement:utility_meter'],
    requiredInputs: ['project.backfeedBreakerA', 'project.pvBackfeedA', 'system.totalAcKw'],
    optionalInputs: ['project.mainPanelAmps', 'project.panelBusRating'],
    affectedDocumentSectionIds: ['VAL-1.registry', 'E-1.interconnection', 'SLD.service-equipment'],
    downstreamImpacts: ['permit validation electrical row', 'SLD AC OCPD label', 'BOM AC hardware row'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'permit_input_allowed_with_explicit_default',
    deterministicEvaluationNotes: ['Explains existing breaker values or existing deterministic fallback; it does not alter breaker sizing.'],
  },
  ocpd_selection: {
    decisionType: 'ocpd_selection',
    label: 'OCPD selection provenance',
    decisionCategory: 'calculation',
    engineeringDomain: 'electrical',
    governingRules: [NEC_690_9, NEC_110_3],
    engineeringDependencies: ['requirement:main_service_panel'],
    requiredInputs: ['system.inverters[].strings[].ocpd', 'project.backfeedBreakerA'],
    optionalInputs: ['system.topology', 'system.inverters[].type'],
    affectedDocumentSectionIds: ['E-1.interconnection', 'SLD.service-equipment'],
    downstreamImpacts: ['SLD OCPD callouts', 'BOM protection rows'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'permit_input_allowed_with_explicit_default',
    deterministicEvaluationNotes: ['Documents OCPD metadata selected by existing inputs or defaults.'],
  },
  string_topology_selection: {
    decisionType: 'string_topology_selection',
    label: 'String topology selection provenance',
    decisionCategory: 'equipment_selection',
    engineeringDomain: 'electrical',
    governingRules: [NEC_690_8, NEC_110_3],
    engineeringDependencies: ['requirement:roof_overview', 'requirement:main_service_panel'],
    requiredInputs: ['system.topology', 'system.inverters[].strings[]', 'cad.totalPanels'],
    optionalInputs: ['system.inverters[].type'],
    affectedDocumentSectionIds: ['PV-2.layout-verification', 'SLD.service-equipment'],
    downstreamImpacts: ['SLD topology block', 'MPPT assignment metadata', 'BOM inverter rows'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'permit_input_allowed_with_explicit_default',
    deterministicEvaluationNotes: ['Documents selected topology from existing system fields only.'],
  },
  mppt_assignment: {
    decisionType: 'mppt_assignment',
    label: 'MPPT assignment provenance',
    decisionCategory: 'equipment_selection',
    engineeringDomain: 'electrical',
    governingRules: [NEC_110_3],
    engineeringDependencies: ['decision:string_topology_selection'],
    requiredInputs: ['system.inverters[].mpptChannels', 'system.inverters[].strings[]'],
    optionalInputs: ['cad.totalPanels'],
    affectedDocumentSectionIds: ['SLD.service-equipment'],
    downstreamImpacts: ['SLD MPPT allocation metadata'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'permit_input_allowed_with_explicit_default',
    deterministicEvaluationNotes: ['Fallback MPPT count is an explicit provenance event when no MPPT input exists.'],
  },
  inverter_selection: {
    decisionType: 'inverter_selection',
    label: 'Inverter selection provenance',
    decisionCategory: 'equipment_selection',
    engineeringDomain: 'electrical',
    governingRules: [NEC_110_3, NEC_690_8],
    engineeringDependencies: ['requirement:main_service_panel'],
    requiredInputs: ['system.inverters[].manufacturer', 'system.inverters[].model', 'system.inverters[].acOutputKw'],
    optionalInputs: ['system.totalAcKw', 'system.totalDcKw'],
    affectedDocumentSectionIds: ['VAL-1.registry', 'SLD.service-equipment'],
    downstreamImpacts: ['Equipment schedule', 'SLD inverter node', 'BOM inverter row'],
    missingInputBehavior: 'emit_review_required_decision',
    confidencePolicy: 'permit_input_allowed_with_explicit_default',
    deterministicEvaluationNotes: ['Captures selected inverter metadata without changing equipment selection.'],
  },
  ess_placement: {
    decisionType: 'ess_placement',
    label: 'ESS placement provenance',
    decisionCategory: 'layout_assumption',
    engineeringDomain: 'energy_storage',
    governingRules: [IFC_1207, NEC_110_3],
    engineeringDependencies: ['requirement:battery_location'],
    requiredInputs: ['project.batteryModel', 'project.batteryCount', 'project.batteryKwh'],
    optionalInputs: ['project.batteryBackfeedA'],
    affectedDocumentSectionIds: ['ESS-1.location', 'ESS-2.notes'],
    downstreamImpacts: ['ESS permit sheets', 'SLD battery metadata'],
    missingInputBehavior: 'not_applicable',
    confidencePolicy: 'inactive_until_input_present',
    deterministicEvaluationNotes: ['Emitted only when ESS inputs are present or document binding requires an informational ESS status.'],
  },
  rapid_shutdown_placement: {
    decisionType: 'rapid_shutdown_placement',
    label: 'Rapid shutdown placement provenance',
    decisionCategory: 'code_compliance',
    engineeringDomain: 'electrical',
    governingRules: [NEC_690_12, NEC_690_56],
    engineeringDependencies: ['requirement:rapid_shutdown', 'decision:string_topology_selection'],
    requiredInputs: ['project.rapidShutdown', 'system.topology'],
    optionalInputs: ['system.inverters[].type'],
    affectedDocumentSectionIds: ['E-2.placards', 'SLD.rapid-shutdown'],
    downstreamImpacts: ['Placard notes', 'SLD rapid shutdown callout'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'permit_input_allowed_with_explicit_default',
    deterministicEvaluationNotes: ['Captures whether existing permit input marks rapid shutdown as integrated or omitted.'],
  },
  utility_interconnection_assumption: {
    decisionType: 'utility_interconnection_assumption',
    label: 'Utility interconnection assumption provenance',
    decisionCategory: 'code_compliance',
    engineeringDomain: 'interconnection',
    governingRules: [NEC_705_12],
    engineeringDependencies: ['requirement:utility_meter', 'requirement:main_service_panel'],
    requiredInputs: ['project.interconnectionMethod', 'project.utilityName'],
    optionalInputs: ['project.mainPanelAmps', 'project.panelBusRating'],
    affectedDocumentSectionIds: ['E-1.utility-meter', 'E-1.interconnection', 'SLD.utility-meter'],
    downstreamImpacts: ['Utility/interconnection section', 'SLD utility node'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'registry_requirement_required',
    deterministicEvaluationNotes: ['Documents existing utility/interconnection labels and explicit defaults.'],
  },
  setback_assumption: {
    decisionType: 'setback_assumption',
    label: 'Setback assumption provenance',
    decisionCategory: 'layout_assumption',
    engineeringDomain: 'roof_layout',
    governingRules: [AHJ_SETBACK],
    engineeringDependencies: ['requirement:roof_overview', 'geometry:roof-layout-context'],
    requiredInputs: ['project.ahjRoofSetbackIn', 'project.ahjRidgeSetbackIn', 'cad.roof.setbackIn'],
    optionalInputs: ['project.roofPlanes'],
    affectedDocumentSectionIds: ['PV-1.site-verification', 'PV-2.layout-verification'],
    downstreamImpacts: ['Layout verification notes', 'plan-set layout context'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'canonical_evidence_preferred',
    deterministicEvaluationNotes: ['Documents available setback values from AHJ/project/CAD metadata only.'],
  },
  conduit_routing_assumption: {
    decisionType: 'conduit_routing_assumption',
    label: 'Conduit routing assumption provenance',
    decisionCategory: 'layout_assumption',
    engineeringDomain: 'electrical',
    governingRules: [NEC_300, NEC_690_31],
    engineeringDependencies: ['requirement:main_service_panel', 'requirement:utility_meter'],
    requiredInputs: ['project.conduitType', 'project.wireLength'],
    optionalInputs: ['cad.dimensions[]'],
    affectedDocumentSectionIds: ['E-1.interconnection', 'PV-2.layout-context'],
    downstreamImpacts: ['BOM conduit quantities', 'electrical notes'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'permit_input_allowed_with_explicit_default',
    deterministicEvaluationNotes: ['Documents routing metadata and defaults; does not solve conduit route geometry.'],
  },
  grounding_bonding_assumption: {
    decisionType: 'grounding_bonding_assumption',
    label: 'Grounding and bonding assumption provenance',
    decisionCategory: 'code_compliance',
    engineeringDomain: 'electrical',
    governingRules: [NEC_250, NEC_690_31],
    engineeringDependencies: ['requirement:main_service_panel', 'requirement:service_equipment_label'],
    requiredInputs: ['project.conduitType', 'system.topology'],
    optionalInputs: ['project.mainPanelBrand'],
    affectedDocumentSectionIds: ['E-1.interconnection', 'E-2.placards'],
    downstreamImpacts: ['Electrical notes', 'BOM grounding hardware metadata'],
    missingInputBehavior: 'emit_informational_decision',
    confidencePolicy: 'document_metadata_only',
    deterministicEvaluationNotes: ['Documents governing-rule linkage for grounding/bonding notes.'],
  },
  placard_requirement: {
    decisionType: 'placard_requirement',
    label: 'Placard requirement provenance',
    decisionCategory: 'code_compliance',
    engineeringDomain: 'document_control',
    governingRules: [NEC_690_53, NEC_690_56, DOC_POLICY],
    engineeringDependencies: ['requirement:placards', 'decision:rapid_shutdown_placement'],
    requiredInputs: ['project.rapidShutdown', 'system.totalDcKw', 'system.totalAcKw'],
    optionalInputs: ['project.productionMeter'],
    affectedDocumentSectionIds: ['E-2.placards', 'VAL-1.registry'],
    downstreamImpacts: ['Placard sheet', 'permit validation summary'],
    missingInputBehavior: 'emit_informational_decision',
    confidencePolicy: 'document_metadata_only',
    deterministicEvaluationNotes: ['Documents placard governing rules and source inputs without creating label artwork.'],
  },
  layout_orientation_assumption: {
    decisionType: 'layout_orientation_assumption',
    label: 'Layout orientation assumption provenance',
    decisionCategory: 'layout_assumption',
    engineeringDomain: 'roof_layout',
    governingRules: [PROJECT_POLICY, AHJ_SETBACK],
    engineeringDependencies: ['requirement:roof_overview', 'geometry:roof-layout-context'],
    requiredInputs: ['project.panelPositions[].orientation', 'cad.systemType'],
    optionalInputs: ['project.roofPlanes[].azimuth'],
    affectedDocumentSectionIds: ['PV-2.layout-verification', 'PV-2.layout-context'],
    downstreamImpacts: ['Plan-set layout context', 'permit validation layout row'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'canonical_evidence_preferred',
    deterministicEvaluationNotes: ['Documents existing orientation metadata or explicit unknown/default state.'],
  },
  bom_derivation: {
    decisionType: 'bom_derivation',
    label: 'BOM derivation provenance',
    decisionCategory: 'document_metadata',
    engineeringDomain: 'bom',
    governingRules: [NEC_110_3, DOC_POLICY],
    engineeringDependencies: ['decision:inverter_selection', 'decision:conduit_routing_assumption', 'decision:ocpd_selection'],
    requiredInputs: ['input.bom[].derivedFrom', 'input.bom[].necReference', 'input.bom[].quantity'],
    optionalInputs: ['input.bom[].stageId', 'input.bom[].formula'],
    affectedDocumentSectionIds: ['BOM.equipment-schedule', 'VAL-1.registry'],
    downstreamImpacts: ['Equipment schedule provenance', 'BOM row lineage metadata'],
    missingInputBehavior: 'emit_explicit_default_decision',
    confidencePolicy: 'document_metadata_only',
    deterministicEvaluationNotes: ['Summarizes existing BOM row metadata; does not recalculate BOM quantities.'],
  },
  sld_metadata: {
    decisionType: 'sld_metadata',
    label: 'SLD metadata provenance',
    decisionCategory: 'document_metadata',
    engineeringDomain: 'sld',
    governingRules: [NEC_690_8, NEC_705_12, DOC_POLICY],
    engineeringDependencies: ['decision:string_topology_selection', 'decision:utility_interconnection_assumption', 'decision:breaker_sizing'],
    requiredInputs: ['system.topology', 'project.interconnectionMethod', 'project.rapidShutdown'],
    optionalInputs: ['project.productionMeter', 'project.batteryModel'],
    affectedDocumentSectionIds: ['SLD.service-equipment', 'SLD.utility-meter', 'SLD.rapid-shutdown'],
    downstreamImpacts: ['SLD provenance metadata', 'permit validation SLD row'],
    missingInputBehavior: 'emit_informational_decision',
    confidencePolicy: 'document_metadata_only',
    deterministicEvaluationNotes: ['Captures SLD data-binding lineage only.'],
  },
};

export function getEngineeringDecisionDefinition(decisionType: EngineeringDecisionType): EngineeringDecisionDefinition {
  return ENGINEERING_DECISION_REGISTRY[decisionType];
}

export function listEngineeringDecisionDefinitions(): EngineeringDecisionDefinition[] {
  return Object.values(ENGINEERING_DECISION_REGISTRY).sort((a, b) => a.decisionType.localeCompare(b.decisionType));
}
