/**
 * lib/solardog/knowledgeSeed.ts
 *
 * SolarPro platform knowledge seed data — pure data module with NO DB imports.
 * Safe to import in tests, frontend, and server code alike.
 *
 * v11: "Knows the Website" — seeds every page, button, workflow, and equipment type.
 */

export interface SeedKnowledgeItem {
  type: 'page' | 'button' | 'workflow' | 'equipment' | 'equipment_brand' | 'feature' | 'route' | 'warning' | 'action' | 'preference';
  key: string;
  label: string;
  description: string;
  route: string | null;
  aliases: string[];
  steps: string[];
  relatedActions: string[];
  metadata: Record<string, unknown>;
}

export const SOLARPRO_KNOWLEDGE_SEED: SeedKnowledgeItem[] = [
  // ── PAGES ────────────────────────────────────────────────────────────────
  {
    type: 'page', key: 'dashboard',
    label: 'Dashboard',
    route: '/dashboard',
    description: "Main command center — pipeline stats, revenue, project counts, quick actions. Shows today's commands, open projects, recent activity, and performance KPIs.",
    aliases: ['command center', 'home', 'main', 'overview', 'hq'],
    steps: [],
    relatedActions: ['open_dashboard', 'open_projects'],
    metadata: {},
  },
  {
    type: 'page', key: 'projects',
    label: 'Projects',
    route: '/projects',
    description: 'All projects — leads, active jobs, completed installs, status tracking. Filter by status, search by client name or address, sort by date or size.',
    aliases: ['project list', 'jobs', 'all projects', 'pipeline'],
    steps: [],
    relatedActions: ['open_projects', 'new_project'],
    metadata: {},
  },
  {
    type: 'page', key: 'engineering',
    label: 'Engineering',
    route: '/engineering',
    description: 'Full engineering suite — string sizing, wire sizing, NEC 690 validation, BOM generation, SLD creation, shading analysis. The core technical design hub for every solar system.',
    aliases: ['system design', 'engineering page', 'string sizing', 'nec validation', 'electrical design'],
    steps: [],
    relatedActions: ['run_string_sizing', 'run_wire_sizing', 'run_nec_validation', 'generate_sld', 'generate_bom'],
    metadata: {},
  },
  {
    type: 'page', key: 'design',
    label: 'Design',
    route: '/design',
    description: 'Roof layout tool — place panels on satellite imagery, optimise string groupings, define roof planes with pitch and azimuth. Output feeds directly into engineering.',
    aliases: ['roof design', 'panel layout', 'roof layout', 'layout tool', 'roof tool'],
    steps: [],
    relatedActions: ['open_design', 'auto_layout', 'open_roof_tool'],
    metadata: {},
  },
  {
    type: 'page', key: 'proposals',
    label: 'Proposals',
    route: '/proposals',
    description: 'Branded customer proposals with production estimates, financing options, ITC 30% breakdown, utility savings. Generate PDF proposals for client presentation.',
    aliases: ['proposal', 'quote', 'customer proposal', 'sales doc', 'estimate'],
    steps: [],
    relatedActions: ['generate_proposal', 'open_proposals'],
    metadata: {},
  },
  {
    type: 'page', key: 'clients',
    label: 'Clients',
    route: '/clients',
    description: 'Client database — contact info, project history, communication log. CRM for solar installers. Search, filter, and manage all customer records.',
    aliases: ['client list', 'customers', 'contacts', 'crm', 'homeowners'],
    steps: [],
    relatedActions: ['open_clients'],
    metadata: {},
  },
  {
    type: 'page', key: 'hardware',
    label: 'Hardware Catalog',
    route: '/hardware',
    description: 'Panel, inverter, battery catalog — browse manufacturer specs, compare equipment, select for projects. Contains hundreds of real product specs.',
    aliases: ['catalog', 'equipment catalog', 'panel catalog', 'inverter list', 'battery list'],
    steps: [],
    relatedActions: ['open_hardware'],
    metadata: {},
  },
  {
    type: 'page', key: 'analytics',
    label: 'Analytics',
    route: '/analytics',
    description: 'Business analytics — revenue trends, install volume by month, average system size, project conversion rates. KPIs for company performance.',
    aliases: ['stats', 'reports', 'metrics', 'kpis', 'business insights', 'trends'],
    steps: [],
    relatedActions: ['open_analytics'],
    metadata: {},
  },
  {
    type: 'page', key: 'settings',
    label: 'Settings',
    route: '/settings',
    description: 'Account and company settings — profile, company branding (logo, colors), pricing configuration, default rates, user management.',
    aliases: ['account settings', 'preferences', 'company settings', 'branding', 'profile'],
    steps: [],
    relatedActions: ['open_settings'],
    metadata: {},
  },
  {
    type: 'page', key: 'permit',
    label: 'Permit Package',
    route: '/engineering/permit',
    description: 'Permit documents — single-line diagram (SLD), electrical plan set, permit-ready package for AHJ submission. Fire setbacks, interconnection docs.',
    aliases: ['permit', 'sld', 'single line diagram', 'permit docs', 'plan set', 'ahj docs'],
    steps: [],
    relatedActions: ['generate_sld', 'open_permit'],
    metadata: {},
  },
  {
    type: 'page', key: 'survey',
    label: 'Site Survey',
    route: '/survey',
    description: 'Site survey tools — customer-facing survey links, photo capture, site assessment responses. Handoff data flows into project design.',
    aliases: ['site survey', 'customer survey', 'survey link', 'site assessment'],
    steps: [],
    relatedActions: [],
    metadata: {},
  },
  {
    type: 'page', key: 'billing',
    label: 'Billing',
    route: '/account/billing',
    description: 'Subscription and billing management — current plan, payment method, invoices, plan upgrades.',
    aliases: ['billing', 'subscription', 'payment', 'plan', 'upgrade'],
    steps: [],
    relatedActions: [],
    metadata: {},
  },
  {
    type: 'page', key: 'operations',
    label: 'Operations',
    route: '/operations',
    description: 'Field operations — installation tracking, crew scheduling, milestone management, field handoff.',
    aliases: ['ops', 'field operations', 'scheduling', 'install tracking', 'crews'],
    steps: [],
    relatedActions: [],
    metadata: {},
  },

  // ── BUTTONS ───────────────────────────────────────────────────────────────
  {
    type: 'button', key: 'generate_sld',
    label: 'Generate SLD',
    route: '/engineering',
    description: 'Creates the single-line diagram for the current system. The SLD shows the full electrical schematic — panels, combiner, inverter, disconnect, utility meter. Required for permit submission.',
    aliases: ['sld', 'single line', 'diagram', 'generate diagram', 'create sld'],
    steps: [],
    relatedActions: ['generate_sld'],
    metadata: { location: 'Engineering page, Permit tab' },
  },
  {
    type: 'button', key: 'run_nec_validation',
    label: 'Run NEC Validation',
    route: '/engineering',
    description: 'Validates the system design against NEC 690 rules — checks max system voltage, string Voc vs inverter input, wire ampacity, OCPD sizing, and DC/AC ratio. Returns pass/fail with specific violations listed.',
    aliases: ['nec check', 'validate', 'run nec', 'nec validation', 'electrical check'],
    steps: [],
    relatedActions: ['run_nec_validation'],
    metadata: { location: 'Engineering page' },
  },
  {
    type: 'button', key: 'auto_fix_strings',
    label: 'Auto-Fix Strings',
    route: '/engineering',
    description: "Automatically adjusts modules-per-string and strings-per-MPPT to bring string voltage within the inverter's MPPT range and below NEC max system voltage. Solves Voc violations instantly.",
    aliases: ['fix strings', 'auto fix', 'fix string sizing', 'auto-fix strings'],
    steps: [],
    relatedActions: ['auto_fix_string'],
    metadata: { location: 'Engineering page, String Sizing section' },
  },
  {
    type: 'button', key: 'auto_fix_wire',
    label: 'Auto-Fix Wire',
    route: '/engineering',
    description: 'Automatically selects the correct wire gauge to pass NEC 690.8 ampacity requirements (125% rule applied to Isc). Updates AWG selection to meet code.',
    aliases: ['fix wire', 'fix wire sizing', 'auto fix wire', 'wire gauge fix'],
    steps: [],
    relatedActions: ['auto_fix_wire'],
    metadata: { location: 'Engineering page, Wire Sizing section' },
  },
  {
    type: 'button', key: 'generate_bom',
    label: 'Generate BOM',
    route: '/engineering',
    description: 'Generates the full bill of materials — panels, inverter, racking, wire, conduit, disconnects, combiners, batteries. Includes quantities and costs. Exports to CSV.',
    aliases: ['bom', 'bill of materials', 'generate bom', 'create bom', 'materials list'],
    steps: [],
    relatedActions: ['generate_bom'],
    metadata: { location: 'Engineering page, BOM tab' },
  },
  {
    type: 'button', key: 'run_string_sizing',
    label: 'Run String Sizing',
    route: '/engineering',
    description: 'Calculates Voc × temperature correction factor at minimum design temp, Vmp at max temp, and checks MPPT range compliance. Shows pass/fail for each string group.',
    aliases: ['string sizing', 'calculate strings', 'string calc', 'run strings'],
    steps: [],
    relatedActions: ['run_string_sizing'],
    metadata: { location: 'Engineering page, String Sizing section' },
  },
  {
    type: 'button', key: 'generate_proposal_btn',
    label: 'Generate Proposal',
    route: '/proposals',
    description: 'Generates a branded PDF proposal for the customer — production estimates, 25-year savings, ITC 30% credit, financing options, equipment specs. Customizable with company logo and colors.',
    aliases: ['create proposal', 'generate quote', 'make proposal', 'proposal pdf'],
    steps: [],
    relatedActions: ['generate_proposal'],
    metadata: { location: 'Proposals page' },
  },
  {
    type: 'button', key: 'auto_layout',
    label: 'Auto Layout',
    route: '/design',
    description: 'Automatically places panels on roof planes using available area, setbacks, and shading avoidance. Maximises panel count within constraints.',
    aliases: ['auto place panels', 'auto panel layout', 'automatic layout', 'place panels automatically'],
    steps: [],
    relatedActions: ['auto_layout'],
    metadata: { location: 'Design page' },
  },

  // ── WORKFLOWS ─────────────────────────────────────────────────────────────
  {
    type: 'workflow', key: 'pass_engineering',
    label: 'Get System to Pass Engineering',
    route: '/engineering',
    description: 'Step-by-step workflow to get a solar system to pass all NEC engineering checks. Covers string sizing, wire sizing, NEC validation, and permit readiness.',
    aliases: ['pass engineering', 'fix engineering', 'get to pass', 'engineering workflow', 'pass nec'],
    steps: [
      'Step 1: Open Engineering page for the project',
      'Step 2: Check all active warnings and errors listed',
      'Step 3: Run String Sizing — fix Voc violations (use Auto-Fix Strings if needed)',
      'Step 4: Run Wire Sizing — fix ampacity violations (use Auto-Fix Wire if needed)',
      'Step 5: Run NEC Validation — review full pass/fail report',
      'Step 6: Fix any remaining violations (OCPD sizing, DC/AC ratio, grounding)',
      'Step 7: Confirm zero errors before generating permit docs',
    ],
    relatedActions: ['run_string_sizing', 'run_wire_sizing', 'run_nec_validation', 'auto_fix_string', 'auto_fix_wire'],
    metadata: { estimatedTime: '10-20 minutes', difficulty: 'medium' },
  },
  {
    type: 'workflow', key: 'create_new_project',
    label: 'Create a New Project',
    route: '/projects/new',
    description: 'End-to-end workflow for creating a new solar project from scratch — client info, site address, system type, and initial sizing.',
    aliases: ['new project workflow', 'start a project', 'create project workflow'],
    steps: [
      'Step 1: Navigate to Projects → New Project',
      'Step 2: Enter client name, email, and phone',
      'Step 3: Enter site address (used for weather data and utility lookup)',
      'Step 4: Select system type (grid-tie, battery backup, off-grid)',
      'Step 5: Enter average monthly bill or annual kWh usage',
      'Step 6: Save project — system size is auto-calculated',
      'Step 7: Open Design to place panels, then Engineering to configure and validate',
    ],
    relatedActions: ['new_project', 'open_design', 'open_engineering'],
    metadata: { estimatedTime: '5-10 minutes', difficulty: 'easy' },
  },
  {
    type: 'workflow', key: 'submit_permit',
    label: 'Submit Permit Package',
    route: '/engineering/permit',
    description: 'Workflow to prepare and submit a permit-ready package — SLD, plan set, title block, fire setbacks, interconnection application.',
    aliases: ['permit workflow', 'submit permit', 'prepare permit', 'permit package workflow'],
    steps: [
      'Step 1: Confirm system passes NEC validation (zero errors)',
      'Step 2: Navigate to Engineering → Permit tab',
      'Step 3: Generate SLD (single-line diagram)',
      'Step 4: Review title block — verify AHJ, utility, installer info',
      'Step 5: Add fire setback annotations if required by AHJ',
      'Step 6: Download permit package as PDF',
      'Step 7: Submit to AHJ (via their online portal or in person)',
    ],
    relatedActions: ['generate_sld', 'run_nec_validation', 'open_permit'],
    metadata: { estimatedTime: '15-30 minutes', difficulty: 'medium' },
  },
  {
    type: 'workflow', key: 'generate_proposal_workflow',
    label: 'Generate Customer Proposal',
    route: '/proposals',
    description: 'Workflow to create a professional customer-facing solar proposal with production estimates, savings analysis, and financing options.',
    aliases: ['proposal workflow', 'create proposal workflow', 'customer proposal workflow'],
    steps: [
      'Step 1: Confirm project has system design (panels placed in Design)',
      'Step 2: Verify utility rate and average monthly bill are set',
      'Step 3: Navigate to Proposals page',
      'Step 4: Select proposal template (standard, premium, minimal)',
      'Step 5: Review auto-calculated production, savings, and ITC 30% figures',
      'Step 6: Add financing options if applicable',
      'Step 7: Generate PDF — review before sending to customer',
    ],
    relatedActions: ['generate_proposal', 'open_proposals'],
    metadata: { estimatedTime: '5-15 minutes', difficulty: 'easy' },
  },

  // ── EQUIPMENT ─────────────────────────────────────────────────────────────
  {
    type: 'equipment', key: 'solfence',
    label: 'SolFence',
    route: null,
    description: 'Ground-mounted solar fencing system used for boundary-based installs. Combines perimeter fencing with solar panel mounting — dual-use for agricultural or commercial properties. Panels are fence panels.',
    aliases: ['sol fence', 'fence solar', 'solar fence', 'solar fencing'],
    steps: [],
    relatedActions: [],
    metadata: { mount_type: 'ground', use_case: 'boundary installs, agricultural, commercial perimeter', category: 'mounting_system' },
  },
  {
    type: 'equipment', key: 'string_inverter',
    label: 'String Inverter',
    route: null,
    description: 'Traditional inverter type — all panels in a string feed into one inverter. Most cost-effective for simple roofs. One shaded panel degrades the whole string. Common brands: SMA, Fronius, Growatt.',
    aliases: ['string inverter', 'central inverter', 'traditional inverter'],
    steps: [],
    relatedActions: [],
    metadata: { category: 'inverter', pros: 'low cost, simple', cons: 'string-level shading loss', brands: ['SMA', 'Fronius', 'Growatt', 'Sungrow'] },
  },
  {
    type: 'equipment', key: 'microinverter',
    label: 'Microinverter',
    route: null,
    description: 'Panel-level inverter — each panel has its own inverter. Best for complex roofs with shading or multiple orientations. Higher cost but maximum energy harvest per panel. Leading brand: Enphase IQ series.',
    aliases: ['microinverter', 'micro inverter', 'panel level inverter', 'enphase'],
    steps: [],
    relatedActions: [],
    metadata: { category: 'inverter', pros: 'panel-level MPPT, shading tolerance, monitoring', cons: 'higher cost', brands: ['Enphase'] },
  },
  {
    type: 'equipment', key: 'hybrid_inverter',
    label: 'Hybrid Inverter',
    route: null,
    description: 'Combines solar inverter and battery charger/inverter in one unit. Required for battery backup systems. Can charge from grid or solar. Common brands: SolarEdge StorEdge, SMA Sunny Boy Storage, Goodwe, Sungrow.',
    aliases: ['hybrid inverter', 'battery inverter', 'storage inverter', 'backup inverter'],
    steps: [],
    relatedActions: [],
    metadata: { category: 'inverter', pros: 'single unit for solar + storage', cons: 'higher cost than string only', brands: ['SolarEdge', 'SMA', 'Goodwe', 'Sungrow', 'Fronius'] },
  },
  {
    type: 'equipment', key: 'tesla_powerwall',
    label: 'Tesla Powerwall',
    route: null,
    description: 'AC-coupled lithium battery. 13.5 kWh usable capacity, 11.5 kW peak / 7 kW continuous output. Integrates with most inverters via AC coupling. Popular for whole-home backup. Requires Powerwall gateway for grid-tie.',
    aliases: ['powerwall', 'tesla battery', 'tesla powerwall', 'powerwall 3'],
    steps: [],
    relatedActions: [],
    metadata: { category: 'battery', capacity_kwh: 13.5, coupling: 'AC', chemistry: 'lithium-ion', brand: 'Tesla' },
  },
  {
    type: 'equipment', key: 'enphase_iq_battery',
    label: 'Enphase IQ Battery',
    route: null,
    description: 'AC-coupled LFP battery designed to pair with Enphase microinverters. 3.84 kWh per unit, stackable up to 4 units (15.36 kWh). Safe LFP chemistry. IQ Battery 5P is the latest.',
    aliases: ['enphase battery', 'iq battery', 'enphase iq battery', 'enphase storage'],
    steps: [],
    relatedActions: [],
    metadata: { category: 'battery', capacity_kwh: 3.84, coupling: 'AC', chemistry: 'LFP', brand: 'Enphase' },
  },
  {
    type: 'equipment', key: 'solaredge_optimizers',
    label: 'SolarEdge Power Optimizers',
    route: null,
    description: 'DC optimizers that add panel-level MPPT to a string inverter system. Best of both worlds — low inverter cost + panel-level shading tolerance. Required with SolarEdge HD-Wave inverters. P300, P370, P500, P600 series.',
    aliases: ['power optimizers', 'dc optimizers', 'solaredge optimizers', 'panel optimizers'],
    steps: [],
    relatedActions: [],
    metadata: { category: 'optimizer', brand: 'SolarEdge', compatible_with: 'SolarEdge HD-Wave inverters' },
  },
  {
    type: 'equipment', key: 'roof_mount_racking',
    label: 'Roof Mount Racking',
    route: null,
    description: 'Standard flush or tilt roof mounting system. Types: L-foot with rails (IronRidge, UniRac), integrated mounting (QuickMount PV), ballasted flat roof. Must match roof type (comp shingle, tile, metal, TPO).',
    aliases: ['racking', 'roof mount', 'mounting system', 'panel racking', 'ironridge', 'unirac'],
    steps: [],
    relatedActions: [],
    metadata: { category: 'racking', mount_type: 'roof', brands: ['IronRidge', 'UniRac', 'QuickMount PV', 'Unirac', 'SnapNrack'] },
  },
  {
    type: 'equipment', key: 'ground_mount_racking',
    label: 'Ground Mount Racking',
    route: null,
    description: 'Fixed-tilt or single-axis tracking ground mount systems. Optimal tilt is latitude ± 5°. Single-axis trackers add 20-35% production vs fixed tilt. Requires site prep, concrete footings.',
    aliases: ['ground mount', 'ground racking', 'fixed tilt mount', 'tracker', 'ground mounted system'],
    steps: [],
    relatedActions: [],
    metadata: { category: 'racking', mount_type: 'ground', types: ['fixed_tilt', 'single_axis_tracker', 'dual_axis_tracker'] },
  },
];