/**
 * test-fixtures/roofProject.ts
 * Deterministic roof project fixture — 12-panel residential roof mount.
 */
import type { PermitInput } from '@/lib/permit/types';

function buildRoofPanels() {
  return Array.from({ length: 12 }, (_, i) => ({
    id: `roof-panel-${i + 1}`,
    lat: 33.4484 + (Math.floor(i / 4) * 0.00002),
    lng: -112.0740 + ((i % 4) * 0.00002),
    x: (i % 4) * 1.1,
    y: Math.floor(i / 4) * 1.8,
    tilt: 22,
    azimuth: 180,
    wattage: 430,
    row: Math.floor(i / 4),
    col: i % 4,
    systemType: 'roof',
    orientation: 'portrait',
  }));
}

const ROOF_PLANE = {
  id: 'plane-1',
  vertices: [
    { lat: 33.4484, lng: -112.0742 },
    { lat: 33.4484, lng: -112.0738 },
    { lat: 33.4486, lng: -112.0738 },
    { lat: 33.4486, lng: -112.0742 },
  ],
  pitch: 22,
  azimuth: 180,
  area: 50,
  edgeTypes: ['eave', 'rake', 'ridge', 'rake'],
};

export const roofProject: PermitInput = {
  project: {
    projectName: 'Golden-Roof-Regression',
    clientName: 'Jane Doe',
    address: '123 Sunshine Ave, Phoenix, AZ 85001',
    designer: 'SolarPro Engineering',
    date: '2025-01-15',
    notes: 'Regression test fixture',
    systemType: 'roof',
    mainPanelAmps: 200,
    mainPanelBrand: 'Square D',
    utilityMeter: 'Net Meter #12345',
    utilityName: 'Arizona Public Service',
    acDisconnect: true,
    dcDisconnect: false,
    productionMeter: true,
    rapidShutdown: true,
    conduitType: 'EMT',
    wireGauge: '10 AWG',
    wireLength: 45,
    lat: 33.4484,
    lng: -112.0740,
    roofType: 'Composition Shingle',
    mountingSystem: 'IronRidge XR100',
    mountingSystemId: 'ironridge-xr100',
    roofPitch: 22,
    rafterSize: '2x6',
    rafterSpacing: 24,
    attachmentSpacing: 48,
    city: 'Phoenix',
    state: 'AZ',
    zip: '85001',
    county: 'Maricopa',
    ahjName: 'City of Phoenix',
    ahjWindSpeedMph: 115,
    ahjGroundSnowPsf: 0,
    ahjRoofSetbackIn: 18,
    ahjRidgeSetbackIn: 36,
    ahjNecVersion: 'NEC 2023',
    panelVoc: 41.7,
    panelIsc: 13.85,
    panelWeightLbs: 44.1,
    panelLengthIn: 66.9,
    panelWidthIn: 40.9,
    panelPositions: buildRoofPanels() as any[],
    roofPlanes: [{ ...ROOF_PLANE, source: 'google_solar', confirmed: true }],
  },
  system: {
    totalDcKw: 5.16,
    totalAcKw: 5.0,
    totalPanels: 12,
    dcAcRatio: 1.032,
    topology: 'micro',
    inverters: [{
      manufacturer: 'Enphase',
      model: 'IQ8M',
      type: 'micro',
      acOutputKw: 5.0,
      maxDcVoltage: 60,
      efficiency: 0.97,
      ulListing: 'UL 1741 SA',
      strings: [{
        label: 'String 1',
        panelCount: 12,
        panelManufacturer: 'Canadian Solar',
        panelModel: 'CS6R-430MS',
        panelWatts: 430,
        panelVoc: 41.7,
        panelIsc: 13.85,
        wireGauge: '10 AWG',
        wireLength: 45,
        isc: 13.85,
        ampacity: 30,
        ocpd: 20,
        voltageDrop: 1.8,
      }],
    }],
  },
  compliance: {
    overallStatus: 'pass',
    jurisdiction: { state: 'AZ', necVersion: 'NEC 2023', ahj: 'City of Phoenix' },
    structural: {
      wind: { windSpeed: 115, exposureCategory: 'C' },
      snow: { groundSnowLoad: 0 },
      seismic: { sdc: 'B' },
    },
  },
  layout: {
    type: 'roof',
    panels: buildRoofPanels(),
    geometry: { roofPlanes: [ROOF_PLANE] },
  },
};
