// v48.32 Battery Incentive Additions — States with new TOU coverage
// Inject before closing ]; of BATTERY_INCENTIVE_PROGRAMS array

  // ── Rocky Mountain Power Wattsmart Battery (Utah) ─────────────────────────────
  {
    program_id: 'rmp_wattsmart_battery_ut',
    program_name: 'Rocky Mountain Power Wattsmart Battery',
    utility_ids: ['pacificorp_wy', 'carbon_power_light_ut', 'dixie_power_ut', 'flowell_electric_association_ut'],
    type: 'battery_incentive',
    status: 'active',
    value_description: 'Up to $1,500 rebate for qualifying battery installations',
    value_flat: 1500,
    max_value: 1500,
    min_battery_kwh: 7,
    utility_dispatch: false,
    program_description: 'Rocky Mountain Power Wattsmart Battery program offers rebates for qualifying residential battery storage systems. Battery must be paired with solar or standalone. Utah homeowners can combine with 30% federal ITC on battery cost.',
    enrollment_url: 'https://www.rockymountainpower.net/energy-environment/clean-energy/battery-storage.html',
    solar_pro_note: 'RMP Wattsmart $1,500 rebate stacks with 30% federal ITC on battery. For a 13.5 kWh Tesla Powerwall (~$12,000 installed), net cost after ITC ($3,600) and rebate ($1,500) = ~$6,900. Battery also adds resilience value for Utah customers in wildfire-prone areas. Always include in Utah solar proposals.',
    last_verified: '2025-05',
  },

  // ── Hawaiian Electric Battery Bonus (Hawaii) ──────────────────────────────────
  {
    program_id: 'heco_battery_bonus_hi',
    program_name: 'Hawaiian Electric Smart Export / Battery Bonus Program',
    utility_ids: ['hawaiian_electric'],
    type: 'demand_response',
    status: 'active',
    value_description: '$850–$1,950 annual payment for battery dispatch participation (3–15 kWh systems)',
    value_annual_per_kw: 130,
    max_value: 1950,
    min_battery_kwh: 3,
    utility_dispatch: true,
    max_dispatch_events_per_year: 60,
    max_dispatch_hours_per_event: 2,
    program_description: 'Hawaiian Electric Smart Export program pays battery owners for grid dispatch during peak demand events. Given Hawaii\'s extreme electricity rates and isolated grid, battery storage is both financially essential and grid-critical. Hawaii also has customer self-supply options that eliminate export entirely.',
    enrollment_url: 'https://www.hawaiianelectric.com/products-and-services/customer-renewable-programs/battery-storage',
    solar_pro_note: 'Hawaii solar + battery is almost mandatory under current HECO tariffs. Hawaiian Electric Smart Export adds $850–$1,950/year income on top of the already-excellent self-consumption savings (38–50¢/kWh avoided). For a customer with $400/month electric bill, solar + battery can realistically eliminate or near-eliminate the bill. Hawaii proposals should always be solar + battery.',
    last_verified: '2025-05',
  },

  // ── Green Mountain Power BYOD (Vermont) ───────────────────────────────────────
  {
    program_id: 'gmp_byod_vt_v2',
    program_name: 'Green Mountain Power BYOD Battery Program (Enhanced)',
    utility_ids: ['green_mountain_vt', 'burlington_electric_vt'],
    type: 'demand_response',
    status: 'active',
    value_description: '$10.44/month ($125/yr) ongoing payment for dispatch participation',
    value_annual_per_kw: 9,
    max_value: 125,
    min_battery_kwh: 7,
    utility_dispatch: true,
    max_dispatch_events_per_year: 30,
    max_dispatch_hours_per_event: 4,
    program_description: 'Vermont Green Mountain Power BYOD (Bring Your Own Device) battery program pays qualifying battery owners $10.44/month in perpetuity for allowing utility dispatch during grid stress events. Battery must be customer-owned (not leased from GMP). GMP also rents Powerwalls at $55/month if customer prefers not to buy.',
    enrollment_url: 'https://greenmountainpower.com/innovation/battery-program/',
    solar_pro_note: 'GMP BYOD pays $125/year ongoing — not a one-time rebate. Over 10 years that\'s $1,250 in passive income from battery participation. Combined with Vermont retail NEM, TOU savings, and 30% ITC, Vermont battery + solar provides strong returns despite cold climate. GMP is the most progressive utility in New England for battery programs. Lead with BYOD in Vermont proposals.',
    last_verified: '2025-05',
  },

  // ── Eversource ConnectedSolutions CT (expanded) ───────────────────────────────
  {
    program_id: 'eversource_cs_ct',
    program_name: 'Eversource ConnectedSolutions CT (Battery Demand Response)',
    utility_ids: ['eversource_ct', 'eversource_cl_ct', 'bozrah_lp_ct', 'south_norwalk_electric_works_ct'],
    type: 'demand_response',
    status: 'active',
    value_description: 'Up to $275/kW-year demand response payment (summer season)',
    value_annual_per_kw: 275,
    max_value: 3700,
    min_battery_kwh: 7,
    utility_dispatch: true,
    max_dispatch_events_per_year: 60,
    max_dispatch_hours_per_event: 2,
    program_description: 'Eversource Connecticut ConnectedSolutions battery demand response program. Utility dispatches customer batteries during ISO-NE grid stress events (typically 100–120 hours/summer). Payment is $275/kW-year of battery rated power. A 13.5 kWh/5 kW Powerwall earns ~$1,375/year. Program runs June–September peak season.',
    enrollment_url: 'https://www.eversource.com/content/ct-c/residential/save-money-energy/connected-solutions',
    solar_pro_note: 'Eversource CT ConnectedSolutions is one of the highest-paying battery DR programs in the US ($275/kW-yr). A Tesla Powerwall 3 (11.5 kW) earns $3,162/year just from ConnectedSolutions payments. Combined with: CT TOU savings (30¢/kWh on-peak), RSIP solar rebate, retail NEM, and 30% ITC, Connecticut solar + battery ROI can be under 5 years. ConnectedSolutions is a must-include in every CT battery proposal.',
    last_verified: '2025-05',
  },

  // ── Minnesota Solar*Rewards Battery Incentive ────────────────────────────────
  {
    program_id: 'xcel_mn_battery_rewards',
    program_name: 'Xcel Energy Minnesota Battery Rewards Program',
    utility_ids: ['minnesota_power_mn', 'otter_tail_power_mn'],
    type: 'demand_response',
    status: 'pilot',
    value_description: 'Pilot: $200–$350/year for qualifying battery dispatch participation',
    value_annual_per_kw: 50,
    max_value: 350,
    min_battery_kwh: 7,
    utility_dispatch: true,
    max_dispatch_events_per_year: 20,
    max_dispatch_hours_per_event: 3,
    program_description: 'Minnesota Power and Otter Tail Power are piloting residential battery demand response programs to complement the existing Minnesota Solar*Rewards solar production incentive. Battery owners in pilot territory can earn dispatch payments during winter and summer peak events.',
    enrollment_url: 'https://www.mnpower.com/CustomerService/RatesSolarEnergy',
    solar_pro_note: 'Minnesota Solar*Rewards pays solar production incentives per kWh for the first 10 years. Battery pilot adds DR income. Minnesota has one of the nation\'s strongest NEM laws. For proposals in Minnesota Power or Otter Tail territory, stack Solar*Rewards + NEM + battery pilot + 30% ITC. Confirm pilot availability with utility — program may have limited enrollment.',
    last_verified: '2025-05',
  },

  // ── TVA EnergyRight Battery Incentive (expanded) ─────────────────────────────
  {
    program_id: 'tva_energyright_battery_expanded',
    program_name: 'TVA EnergyRight Storage Program (Expanded)',
    utility_ids: ['tva_al', 'nashville_electric_service_tn', 'memphis_light_gas_water_tn', 'knoxville_utilities_board_tn', 'bristol_tennessee_essential_services_tn', 'fayetteville_public_utilities_tn'],
    type: 'battery_incentive',
    status: 'active',
    value_description: 'Up to $1,000 upfront rebate + $10/month ongoing bill credit per qualifying battery',
    value_flat: 1000,
    max_value: 2200,
    min_battery_kwh: 5,
    utility_dispatch: true,
    max_dispatch_events_per_year: 20,
    max_dispatch_hours_per_event: 2,
    program_description: 'TVA EnergyRight battery storage program offers local power company rebates for qualifying battery installations. Battery must participate in grid dispatch. Programs vary by local distribution utility — Nashville ES, Memphis LGW, and KUB each administer their own version. Combined TVA wholesale backing makes this program stable long-term.',
    enrollment_url: 'https://www.tva.com/energy/our-power-system/grid-innovation/battery-storage',
    solar_pro_note: 'TVA territory (TN, AL, MS, GA, KY, NC, VA portions) has avoided-cost NEM (~2–4¢/kWh for exports). Battery storage is ESSENTIAL for TVA territory solar — self-consumption saves 8–17¢/kWh while exports earn only 2–4¢/kWh. TVA EnergyRight rebate ($1,000 upfront + $10/month) helps justify battery cost. Always pair battery with solar in TVA territory. Without battery, Tennessee/Alabama solar ROI is very poor.',
    last_verified: '2025-05',
  },

  // ── Alabama Power Battery Incentive ──────────────────────────────────────────
  {
    program_id: 'alabama_power_battery',
    program_name: 'Alabama Power Rate Saver / Energy Storage',
    utility_ids: ['alabama_power'],
    type: 'demand_response',
    status: 'limited',
    value_description: 'Up to $500/year bill credit for battery demand response participation',
    value_annual_per_kw: 50,
    max_value: 500,
    min_battery_kwh: 5,
    utility_dispatch: true,
    max_dispatch_events_per_year: 15,
    max_dispatch_hours_per_event: 2,
    program_description: 'Alabama Power Rate Saver program for residential battery and HVAC demand response. Battery owners may qualify for bill credits in exchange for utility dispatch during summer peak demand events. Alabama Power NEM pays avoided-cost rates (~3¢/kWh), making self-consumption the primary solar value driver.',
    enrollment_url: 'https://www.alabamapower.com/account/ways-to-save/energy-storage.html',
    solar_pro_note: 'Alabama Power pays only avoided-cost (~3¢/kWh) for solar exports. Battery storage changes the economics dramatically — self-consumption saves 9–18¢/kWh vs exporting at 3¢. Rate Saver DR credit adds up to $500/year. For Alabama solar proposals, battery is not optional — it is the primary value enabler. Lead with battery + solar as a package. Alabama has good solar resource (400+ sunny days equivalent).',
    last_verified: '2025-05',
  },

  // ── DTE Energy Battery Pilot (Michigan) ──────────────────────────────────────
  {
    program_id: 'dte_mi_battery_pilot',
    program_name: 'DTE Energy Connected Home Battery Program',
    utility_ids: ['dte_mi'],
    type: 'demand_response',
    status: 'pilot',
    value_description: 'Pilot: $30–$60/month bill credit for battery dispatch participation',
    value_annual_per_kw: 70,
    max_value: 720,
    min_battery_kwh: 7,
    utility_dispatch: true,
    max_dispatch_events_per_year: 30,
    max_dispatch_hours_per_event: 2,
    program_description: 'DTE Energy Michigan Connected Home battery pilot program. Battery owners in selected pilot areas receive bill credits in exchange for allowing DTE to dispatch battery during peak grid periods. Pilot is expanding as DTE adds smart grid infrastructure.',
    enrollment_url: 'https://www.dteenergy.com/us/en/residential/home-efficiency/connected-home.html',
    solar_pro_note: 'DTE Michigan TOU (11 AM–7 PM) aligns perfectly with solar production. Battery provides evening coverage after solar drops at 5–7 PM. DTE Connected Home pilot adds $360–$720/year income on top of TOU savings. Michigan retail NEM ensures fair export value. Michigan is an improving solar market — DTE has been expanding solar programs. Good state for solar + battery bundle.',
    last_verified: '2025-05',
  },

  // ── Kentucky Battery Incentive (Duke PowerPair KY equivalent) ────────────────
  {
    program_id: 'duke_ky_battery',
    program_name: 'Duke Energy Kentucky Battery Incentive',
    utility_ids: ['duke_energy_kentucky_ky'],
    type: 'battery_incentive',
    status: 'limited',
    value_description: 'Up to $1,500 rebate for battery storage systems',
    value_flat: 1500,
    max_value: 1500,
    min_battery_kwh: 7,
    utility_dispatch: false,
    program_description: 'Duke Energy Kentucky offers battery incentives for residential customers installing qualifying battery storage systems. Kentucky NEM at avoided-cost makes battery essential for solar ROI. Incentive availability varies — confirm current status with Duke Energy Kentucky customer service.',
    enrollment_url: 'https://www.duke-energy.com/home/products/battery-storage',
    solar_pro_note: 'Kentucky avoided-cost NEM (~2–4¢/kWh exports) makes battery non-negotiable for solar proposals. Duke Kentucky battery rebate ($1,500) combined with 30% federal ITC significantly reduces battery cost. Total battery incentive on a $10,000 battery system: $3,000 ITC + $1,500 rebate = $4,500 off. Net cost $5,500 for battery that saves hundreds per year at 17¢/kWh peak avoidance. Always include battery in KY proposals.',
    last_verified: '2025-05',
  },

