
  // ═══════════════════════════════════════════════════════════════════════
  // v48.28 EXPANSION — Battery Incentive Programs
  // ═══════════════════════════════════════════════════════════════════════

  // ── Duke Energy PowerPair (NC/SC/FL/IN/OH) ───────────────────────────────
  {
    program_id: 'duke_powerpair_all',
    program_name: 'Duke Energy PowerPair Solar+Battery Rebate',
    utility_ids: ['duke_nc', 'duke_sc', 'duke_indiana', 'duke_energy_ohio_oh', 'duke_fl', 'duke_energy_kentucky_ky'],
    type: 'battery_incentive',
    status: 'active',
    value_description: '$6,000–$9,000 rebate for qualifying solar+battery systems (pilot enrollment)',
    value_flat: 9000,
    max_value: 9000,
    min_battery_kwh: 10,
    utility_dispatch: true,
    max_dispatch_events_per_year: 60,
    max_dispatch_hours_per_event: 4,
    enrollment_url: 'https://www.duke-energy.com/home/products/powerpair',
    program_description: 'Duke Energy PowerPair rebates customers who pair a new solar system with battery storage. Utility retains rights to dispatch battery during grid stress events (up to 60 per year, 4 hrs each). Rebate: $6,000 standard, up to $9,000 for income-qualified customers.',
    solar_pro_note: 'PowerPair is excellent deal — $6,000–$9,000 rebate effectively reduces battery cost dramatically. Dispatch events are rare and short. Recommend PowerPair enrollment for all Duke territory solar+battery installs.',
    last_verified: '2025-05',
  },

  // ── Georgia Power Advanced Solar Initiative / Battery DR ──────────────────
  {
    program_id: 'georgia_power_adr',
    program_name: 'Georgia Power Battery Demand Response',
    utility_ids: ['georgia_power', 'cobb_emc_ga', 'sawnee_emc_ga', 'jackson_emc_ga', 'walton_emc_ga', 'snapping_shoals_emc_ga', 'coweta_fayette_emc_ga', 'flint_energies_ga', 'greystone_power_ga', 'carroll_emc_ga'],
    type: 'demand_response',
    status: 'active',
    value_description: 'Battery demand-response bill credits; varies by program year',
    value_annual_per_kw: 150,
    utility_dispatch: true,
    max_dispatch_events_per_year: 40,
    max_dispatch_hours_per_event: 2,
    enrollment_url: 'https://www.georgiapower.com/residential/billing-and-rates/rate-options.html',
    program_description: 'Georgia Power and GA EMC demand response programs allow battery dispatch during peak demand events in exchange for annual bill credits. Georgia Power Advanced Solar Initiative (ASI) for larger commercial systems.',
    solar_pro_note: 'Georgia has mild NEM rules — battery demand-response programs are the primary battery incentive. Consider battery for Georgia Power customers who want to reduce demand charges and earn DR credits.',
    last_verified: '2025-05',
  },

  // ── Eversource ConnectedSolutions (CT/MA/NH) ─────────────────────────────
  {
    program_id: 'eversource_connected',
    program_name: 'ConnectedSolutions Battery Program',
    utility_ids: ['eversource_ct', 'eversource_cl_ct', 'eversource_ma', 'eversource_nh', 'ui_ct', 'natgrid_ma', 'national_grid_ri'],
    type: 'vpp',
    status: 'active',
    value_description: '$225–$275/kW per summer season for battery dispatch',
    value_annual_per_kw: 250,
    max_value: 4000,
    min_battery_kwh: 5,
    utility_dispatch: true,
    max_dispatch_events_per_year: 60,
    max_dispatch_hours_per_event: 3,
    enrollment_url: 'https://www.eversource.com/content/ct/residential/my-account/billing-payments/about-your-bill/managing-costs/connected-solutions',
    program_description: 'Eversource ConnectedSolutions pays ~$225–$275/kW summer season for enrolled batteries that discharge during grid peak events (typically hot summer afternoons). Average payment: $700–$1,200/season for typical residential battery. Available in CT, MA, NH.',
    solar_pro_note: 'ConnectedSolutions is one of the best battery incentive programs in the US. In NE territory: Eversource pays ~$250/kW for battery enrollment. 10 kWh battery earns ~$1,250/summer season on top of self-consumption savings. HIGHLY recommend enrolling all batteries in Eversource territory.',
    last_verified: '2025-05',
  },

  // ── Green Mountain Power BYOD (VT) ───────────────────────────────────────
  {
    program_id: 'gmp_byod_vt',
    program_name: 'GMP Bring Your Own Device (BYOD)',
    utility_ids: ['green_mountain_vt', 'burlington_electric_vt', 'vermont_ec_vt', 'washington_ec_vt'],
    type: 'vpp',
    status: 'active',
    value_description: '$850+/year for enrolled batteries (GMP dispatches during grid events)',
    value_annual_per_kw: 85,
    max_value: 2000,
    utility_dispatch: true,
    max_dispatch_events_per_year: 50,
    max_dispatch_hours_per_event: 2,
    enrollment_url: 'https://greenmountainpower.com/rebates-programs/energy-storage/bring-your-own-device/',
    program_description: 'GMP BYOD enrolls residential batteries in a virtual power plant. GMP dispatches during grid events; customers receive annual payments (~$850+ for typical 13.5 kWh Powerwall). GMP also leases Tesla Powerwalls to customers at $55/month.',
    solar_pro_note: 'Vermont has one of the best solar+storage ecosystems in the country. GMP BYOD + NEM full retail rate + net metering = compelling economics. Always recommend BYOD enrollment for GMP territory battery installs.',
    last_verified: '2025-05',
  },

  // ── National Grid / Unitil ConnectedSolutions (RI/MA) ────────────────────
  {
    program_id: 'natgrid_connected',
    program_name: 'National Grid ConnectedSolutions',
    utility_ids: ['natgrid_ma', 'unitil_ma', 'unitil_nh', 'cape_light_compact_ma'],
    type: 'vpp',
    status: 'active',
    value_description: '$225–$275/kW per summer season',
    value_annual_per_kw: 250,
    utility_dispatch: true,
    max_dispatch_events_per_year: 60,
    enrollment_url: 'https://www.nationalgridus.com/ma-home/clean-energy/energy-storage',
    program_description: 'National Grid ConnectedSolutions (MA) mirrors Eversource program — pays ~$250/kW summer season for battery dispatch participation.',
    solar_pro_note: 'MA ConnectedSolutions: ~$1,250/season for 10 kWh battery. Stacks with MA SMART solar incentive for solar+battery customers. One of the highest battery incentive rates in the US.',
    last_verified: '2025-05',
  },

  // ── PSEG Long Island Battery Storage Program ──────────────────────────────
  {
    program_id: 'pseg_li_battery',
    program_name: 'PSEG Long Island Bring Your Own Battery (BYOB)',
    utility_ids: ['lipa_ny', 'pseg_nj'],
    type: 'vpp',
    status: 'active',
    value_description: '$380/kW over 5 years for enrolled batteries',
    value_annual_per_kw: 76,
    utility_dispatch: true,
    max_dispatch_events_per_year: 40,
    enrollment_url: 'https://www.psegliny.com/aboutpseglongisland/ratesandtariffs/electricservicetariffs/energystoragetariff',
    program_description: 'PSEG Long Island BYOB program pays $380/kW over 5 years (~$76/kW/year) for battery enrollment in demand response. NY also has NYSERDA storage incentives available.',
    solar_pro_note: 'Long Island has very high electricity rates ($0.25–0.35/kWh). BYOB + full retail NEM makes solar+battery extremely compelling. NY-Sun incentives may also be available for the solar component.',
    last_verified: '2025-05',
  },

  // ── APS / SRP Arizona Battery Programs ───────────────────────────────────
  {
    program_id: 'aps_battery_az',
    program_name: 'APS Battery Reward / Storage Rewards Program',
    utility_ids: ['aps_az', 'srp_az', 'tep_az'],
    type: 'battery_incentive',
    status: 'active',
    value_description: '$200–$300/kWh battery rebate (one-time)',
    value_per_kwh_capacity: 250,
    max_value: 3000,
    min_battery_kwh: 8,
    utility_dispatch: false,
    enrollment_url: 'https://www.aps.com/en/residential/rates-and-programs/solar-and-battery-storage/battery-storage',
    program_description: 'APS offers battery storage rebates for residential customers. SRP and TEP have similar programs. Arizona has strong financial incentives for solar+battery given reduced export credit rates.',
    solar_pro_note: 'Arizona export credits are below retail — battery is the primary value driver for new solar installs. APS/SRP battery rebates offset part of battery cost. Combined with high solar production (>6 peak sun hrs), ROI is still excellent.',
    last_verified: '2025-05',
  },

  // ── Xcel Energy Battery Connect (CO/MN) ──────────────────────────────────
  {
    program_id: 'xcel_battery_connect',
    program_name: 'Xcel Energy Battery Connect / OptimizEV',
    utility_ids: ['xcel_co', 'psco_co', 'xcel_mn'],
    type: 'vpp',
    status: 'active',
    value_description: '$200/kW annual payment for battery enrollment',
    value_annual_per_kw: 200,
    utility_dispatch: true,
    max_dispatch_events_per_year: 30,
    max_dispatch_hours_per_event: 4,
    enrollment_url: 'https://www.xcelenergy.com/programs_and_rebates/residential_programs_and_rebates/battery_storage',
    program_description: 'Xcel Energy Battery Connect pays customers for battery dispatch during peak grid events. CO and MN programs. Also includes Solar*Rewards integration for solar+battery customers.',
    solar_pro_note: 'Xcel Battery Connect complements Solar*Rewards performance incentives — solar+battery customers can earn both production incentives (Solar*Rewards) and demand response payments (Battery Connect).',
    last_verified: '2025-05',
  },

  // ── OGE / PSO Oklahoma Battery Programs ───────────────────────────────────
  {
    program_id: 'oge_battery',
    program_name: 'OGE SmartHours Battery Integration',
    utility_ids: ['oge_ok', 'pso_ok'],
    type: 'demand_response',
    status: 'active',
    value_description: 'Bill credits for battery participation in SmartHours peak events',
    value_annual_per_kw: 100,
    utility_dispatch: false,
    enrollment_url: 'https://www.oge.com/wps/portal/oge/save-energy/home/smarthours',
    program_description: 'OGE SmartHours battery integration: customers can earn bill credits by dispatching battery storage during peak demand pricing events. Aligns well with solar self-consumption strategy.',
    solar_pro_note: 'OGE SmartHours TOU rate + battery creates compelling bill savings opportunity in OK. 2–7 PM summer peak is post-solar-peak — battery dispatches stored solar energy during highest-priced hours.',
    last_verified: '2025-05',
  },

  // ── TVA EnergyRight Battery Programs (TN) ────────────────────────────────
  {
    program_id: 'tva_battery',
    program_name: 'TVA Grid Relief Rider / Battery Program',
    utility_ids: ['tva_tn', 'tva_al', 'memphis_light_gas_water_tn', 'nashville_electric_service_tn', 'knoxville_utilities_board_tn'],
    type: 'demand_response',
    status: 'limited',
    value_description: 'Bill credits through local TVA distributor demand response programs; varies by LPC',
    value_annual_per_kw: 50,
    utility_dispatch: true,
    enrollment_url: 'https://energyright.com/for-homes/solar/',
    program_description: 'TVA distributes power to Local Power Companies (LPCs) in TN/AL/MS/KY/VA. TVA has limited NEM options (no statewide mandate) — solar typically credited at avoided-cost. Battery demand response programs available through some LPCs.',
    solar_pro_note: 'TVA territory has no statewide NEM mandate. LPCs have variable solar programs. Solar economics depend heavily on specific LPC policies — some offer retail NEM, others offer only avoided-cost (~3–5 cents/kWh). Battery maximizes self-consumption value. Research specific LPC program before sizing system.',
    last_verified: '2025-05',
  },

  // ── Portland General / PacifiCorp Oregon Battery ──────────────────────────
  {
    program_id: 'pge_or_battery',
    program_name: 'PGE Smart Battery Pilot / OR Storage Rebate',
    utility_ids: ['portland_general_or', 'pacificorp_or', 'eugene_water_electric_board_or'],
    type: 'battery_incentive',
    status: 'pilot',
    value_description: 'Up to $2,500 battery rebate through Oregon Energy Trust or utility pilot',
    value_flat: 2500,
    utility_dispatch: true,
    enrollment_url: 'https://www.energytrust.org/programs/storage/',
    program_description: 'Oregon Energy Trust (OET) offers storage incentives in PGE/PacifiCorp territory. PGE Smart Battery Pilot provides dispatch payments. OR mandates full retail NEM which makes solar fundamental economics strong.',
    solar_pro_note: 'Oregon full retail NEM makes solar compelling without battery. Battery becomes optional value-add — but OET rebates and pilot dispatch payments can improve overall project economics.',
    last_verified: '2025-05',
  },

  // ── NV Energy Battery Storage Rebate ─────────────────────────────────────
  {
    program_id: 'nv_energy_battery',
    program_name: 'NV Energy Battery Rebate Program',
    utility_ids: ['nv_energy'],
    type: 'battery_incentive',
    status: 'active',
    value_description: '$3,000 one-time battery rebate for residential storage systems',
    value_flat: 3000,
    min_battery_kwh: 10,
    utility_dispatch: false,
    enrollment_url: 'https://www.nvenergy.com/account-services/energy-solutions/renewable-energy/solar/battery-storage',
    program_description: 'NV Energy offers $3,000 one-time rebate for qualifying residential battery storage systems (minimum 10 kWh capacity). Nevada NEM is at 75% of retail rate — battery maximizes self-consumption and avoids exporting at reduced rate.',
    solar_pro_note: 'Nevada NEM pays ~75% of retail rate for exports. NV Energy $3,000 battery rebate + high self-consumption value makes battery the standard recommendation for NV solar installs. Nevada Class I NEM for ≤ 25 kW.',
    last_verified: '2025-05',
  },

  // ── Puget Sound Energy FlexPower (WA) ────────────────────────────────────
  {
    program_id: 'pse_flexpay',
    program_name: 'PSE FlexPower / Battery Storage Program',
    utility_ids: ['puget_sound_wa', 'snohomish_county_pud_wa', 'seattle_city_light_wa', 'clark_pud_wa'],
    type: 'demand_response',
    status: 'pilot',
    value_description: 'Annual dispatch payments ~$100–200/kW for enrolled WA batteries',
    value_annual_per_kw: 150,
    utility_dispatch: true,
    enrollment_url: 'https://www.pse.com/en/rates-and-services/electric-rates',
    program_description: 'Puget Sound Energy and WA PUD battery demand-response pilots. Washington mandates full retail NEM (1:1) — battery is supplementary value-add rather than essential economics fix.',
    solar_pro_note: 'WA retail NEM (1:1) means solar economics are strong without battery. PSE FlexPower dispatch payments make battery a bonus revenue stream. Recommend battery for customers wanting backup power + dispatch income.',
    last_verified: '2025-05',
  },

  // ── Dominion Virginia Battery Storage ────────────────────────────────────
  {
    program_id: 'dominion_va_battery',
    program_name: 'Dominion Energy Virginia Battery Storage Program',
    utility_ids: ['dominion_va', 'dominion_sc'],
    type: 'demand_response',
    status: 'active',
    value_description: 'Demand response credits for battery dispatch during peak events',
    value_annual_per_kw: 100,
    utility_dispatch: true,
    max_dispatch_events_per_year: 40,
    enrollment_url: 'https://www.dominionenergy.com/virginia/home/rates-programs/battery-storage',
    program_description: 'Dominion Energy VA battery demand response program. Customers receive annual bill credits for allowing utility to dispatch battery during peak grid events. Virginia mandates full retail NEM — battery adds incremental value on top of NEM.',
    solar_pro_note: 'Virginia full retail NEM makes solar fundamentally strong. Dominion battery DR program adds ~$100/kW/year incremental income. Recommend for customers wanting resilience + demand response income.',
    last_verified: '2025-05',
  },

  // ── Alabama Power / TVA Alabama Battery ──────────────────────────────────
  {
    program_id: 'alabama_power_battery',
    program_name: 'Alabama Power EnergySelect Battery Program',
    utility_ids: ['alabama_power', 'tva_al'],
    type: 'demand_response',
    status: 'limited',
    value_description: 'Limited residential battery DR; primarily commercial programs',
    value_annual_per_kw: 50,
    utility_dispatch: true,
    enrollment_url: 'https://www.alabamapower.com/residential/save-money-and-energy/renewable-energy/solar.html',
    program_description: 'Alabama Power and TVA Alabama have limited residential battery programs. AL does not have statewide NEM mandate — solar credited at avoided-cost (~3–5 cents/kWh). Battery is critical for economic viability.',
    solar_pro_note: 'Alabama has no statewide NEM — solar exports earn only ~3–5 cents/kWh avoided cost. Battery storage is ESSENTIAL for Alabama solar economics — maximize self-consumption at retail rates ($0.12–0.14/kWh).',
    last_verified: '2025-05',
  },

  // ── Mississippi / TVA Mississippi Battery ────────────────────────────────
  {
    program_id: 'ms_battery',
    program_name: 'Mississippi Power / Entergy MS Battery DR',
    utility_ids: ['entergy_ms', 'mississippi_power'],
    type: 'demand_response',
    status: 'limited',
    value_description: 'Limited residential battery programs; contact utility for current offerings',
    utility_dispatch: false,
    enrollment_url: 'https://www.mississippipower.com/residential/energy-savings/solar-energy',
    program_description: 'Mississippi has limited statewide NEM policy — some utilities offer voluntary programs. Solar economics in MS depend on self-consumption. Battery storage recommended.',
    solar_pro_note: 'Mississippi NEM is not mandated statewide. Entergy MS and Mississippi Power offer voluntary programs with below-retail export rates. Battery is recommended to maximize self-consumption value.',
    last_verified: '2025-05',
  },

  // ── FPL / Duke FL Battery Programs ───────────────────────────────────────
  {
    program_id: 'fpl_battery',
    program_name: 'FPL / Duke FL Battery Demand Response',
    utility_ids: ['fpl_fl', 'duke_fl', 'tampa_electric_fl', 'gulf_power_fl', 'jea_fl'],
    type: 'demand_response',
    status: 'active',
    value_description: 'Annual bill credits ~$100–200/kW for battery dispatch enrollment',
    value_annual_per_kw: 150,
    utility_dispatch: true,
    max_dispatch_events_per_year: 30,
    enrollment_url: 'https://www.fpl.com/rates/residential-time-of-use.html',
    program_description: 'Florida IOUs offer battery demand response programs with annual bill credits. Florida mandates full retail NEM — battery adds supplementary dispatch income and backup capability.',
    solar_pro_note: 'Florida NEM is favorable (full retail, no size cap). Battery DR payments are a bonus — primary value is backup power for hurricane season. Recommend battery for resilience + demand response income.',
    last_verified: '2025-05',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // v48.28 EXPANSION — Solar Rebate Programs
  // ═══════════════════════════════════════════════════════════════════════

  // ── New Jersey SREC-II / SuSI ─────────────────────────────────────────────
  {
    program_id: 'nj_susi',
    program_name: 'NJ Successor Solar Incentive (SuSI) Program',
    utility_ids: ['pseg_nj', 'atlantic_city_nj', 'rockland_electric_nj', 'orange_rockland_utilities_nj', 'south_jersey_industries_nj', 'sussex_rural_ec_nj'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'SuSI pays $90–$140/MWh in solar incentives for 15 years (SREC-II market)',
    value_per_kwh_production: 0.10,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://njcleanenergy.com/renewable-energy/programs/solar/solar-transition-srec',
    program_description: 'New Jersey SuSI (Successor Solar Incentive) replaces TREC with SREC-II program. Pays ~$90–$140/MWh for solar production for 15 years. Combined with full retail NEM and 30% ITC, NJ is one of the strongest solar states.',
    solar_pro_note: 'NJ SREC-II + full retail NEM + 30% ITC = one of the best solar ROI in the US (5–7 year payback). SREC-II adds ~$500–$900/year per 6 kW system. Always register for SuSI in NJ.',
    last_verified: '2025-05',
  },

  // ── New York NYSERDA NY-Sun ────────────────────────────────────────────────
  {
    program_id: 'nysun',
    program_name: 'NY-Sun Incentive Program (NYSERDA)',
    utility_ids: ['con_ed_ny', 'nyseg_ny', 'niagara_mohawk_ny', 'central_hudson_ny', 'lipa_ny', 'orange_rockland_ny', 'rg_e_ny', 'rochester_gas_electric_ny', 'o_r_ny'],
    type: 'solar_rebate',
    status: 'active',
    value_description: '$0.20–0.40/W upfront incentive through NY-Sun (varies by sector and utility territory)',
    value_per_kw: 300,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.nyserda.ny.gov/All-Programs/NY-Sun',
    program_description: 'NYSERDA NY-Sun provides upfront incentives for residential solar installations across all NY utility territories. Residential: ~$0.20–0.40/W depending on territory. Combined with 25% state tax credit and federal ITC.',
    solar_pro_note: 'NY-Sun incentive + 25% NY state tax credit + 30% federal ITC = ~55% total incentive on system cost. NY has among the strongest incentive stacking in the US. Ensure contractor is NY-Sun registered.',
    last_verified: '2025-05',
  },

  // ── Maryland SREC Market ───────────────────────────────────────────────────
  {
    program_id: 'md_srec',
    program_name: 'Maryland Solar Renewable Energy Credits (SRECs)',
    utility_ids: ['bge_md', 'pepco_md', 'choptank_md', 'delmarva_md', 'potomac_edison_md', 'southern_maryland_ec_md', 'a_n_ec_md', 'easton_utilities_md'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'SREC market: ~$50–80/MWh; 6 kW system earns ~$400–600/year',
    value_per_kwh_production: 0.065,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://energy.maryland.gov/Residential/Pages/solar/solar_energy.aspx',
    program_description: 'Maryland SRECs are traded on the open market. MD utilities must meet RPS requirements by purchasing SRECs or paying an Alternative Compliance Payment. Current SREC prices ~$50–80/MWh. Combined with full retail NEM and SREC income.',
    solar_pro_note: 'MD SREC market provides $50–80/MWh additional income. Register systems in GATS (PJM EIS) to generate and sell SRECs. Typically $400–600/year additional income per 6 kW system. Strong stacking with full retail NEM.',
    last_verified: '2025-05',
  },

  // ── Massachusetts SMART Program ───────────────────────────────────────────
  {
    program_id: 'ma_smart',
    program_name: 'Massachusetts SMART (Solar Massachusetts Renewable Target)',
    utility_ids: ['eversource_ma', 'eversource_ct', 'natgrid_ma', 'unitil_ma', 'cape_light_compact_ma', 'belmont_municipal_light_ma', 'braintree_electric_light_ma', 'concord_municipal_light_plant_ma', 'danvers_electric_ma', 'reading_municipal_light_ma', 'norwood_municipal_light_ma', 'peabody_municipal_light_ma'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'SMART pays $0.03–0.16/kWh generated for 10 years (varies by utility and allocation block)',
    value_per_kwh_production: 0.09,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.mass.gov/smart-program',
    program_description: 'MA SMART is a performance-based incentive paying per kWh generated for 10 years. Base rate ~$0.03–0.16/kWh depending on utility territory and current allocation block. Battery adder of +$0.01–0.05/kWh for paired storage.',
    solar_pro_note: 'MA SMART + full retail NEM + 30% ITC + MA state tax credit (15%) = one of the strongest solar incentive stacks in the US. Solar+battery customers get additional SMART adder. MA has the highest solar ROI potential in New England.',
    last_verified: '2025-05',
  },

  // ── Connecticut RSIP ──────────────────────────────────────────────────────
  {
    program_id: 'ct_rsip',
    program_name: 'CT Residential Solar Investment Program (RSIP)',
    utility_ids: ['eversource_ct', 'eversource_cl_ct', 'ui_ct', 'groton_utilities_ct'],
    type: 'solar_rebate',
    status: 'active',
    value_description: '$0.463–$0.463/W upfront rebate through CT RSIP (declining block)',
    value_per_kw: 463,
    max_value: 10000,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.ctcleanenergy.com/solar',
    program_description: 'Connecticut RSIP provides upfront incentives for residential solar through declining block structure. CT also has virtual net metering and community solar programs.',
    solar_pro_note: 'CT RSIP + full retail NEM + 30% ITC. CT has very high electricity rates ($0.24–0.32/kWh) — one of the best solar economics in the Northeast. Ensure RSIP enrollment through approved installer.',
    last_verified: '2025-05',
  },

  // ── Colorado Solar Rebates ────────────────────────────────────────────────
  {
    program_id: 'co_rebates',
    program_name: 'Colorado Solar Rebates (Xcel Solar*Rewards + CORE)',
    utility_ids: ['xcel_co', 'psco_co', 'holy_cross_energy_co', 'poudre_valley_rea_co', 'united_power_co', 'mountain_view_electric_association_co'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'Xcel Solar*Rewards: ~$0.02–0.05/kWh production incentive for 10 years; CORE rebates for rural co-ops',
    value_per_kwh_production: 0.03,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.xcelenergy.com/programs_and_rebates/residential_programs_and_rebates/solar_*_rewards_program',
    program_description: 'Xcel Solar*Rewards pays per-kWh production incentive for 10 years (~$0.02–0.05/kWh current rate). Colorado rural co-ops may offer CORE rebates. CO also has full retail NEM.',
    solar_pro_note: 'CO Solar*Rewards is a strong performance incentive on top of full retail NEM. 6 kW system at 0.03/kWh earns ~$250/year for 10 years. Register systems through Xcel for Solar*Rewards enrollment.',
    last_verified: '2025-05',
  },

  // ── Washington State Solar Rebate ─────────────────────────────────────────
  {
    program_id: 'wa_solar_rebate',
    program_name: 'Washington State Solar Incentive / Net Metering',
    utility_ids: ['puget_sound_wa', 'seattle_city_light_wa', 'snohomish_county_pud_wa', 'clark_pud_wa', 'avista_wa', 'chelan_county_pud_wa', 'douglas_county_pud_wa', 'grant_county_pud_wa'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'WA sales tax exemption on solar equipment (saves ~6–10% of system cost)',
    value_per_kw: 0,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.commerce.wa.gov/growing-the-economy/energy/energy-policy/',
    program_description: 'Washington State has full retail NEM mandate and sales tax exemption on solar equipment. WA also has production incentive programs through some utilities.',
    solar_pro_note: 'WA full retail NEM (1:1) is mandated for all utilities. WA sales tax exemption saves 8–10% on solar system cost. PacifiCorp/PSE territories: verify RMP Solar Incentive Program availability for additional production incentives.',
    last_verified: '2025-05',
  },

  // ── Oregon Energy Trust ───────────────────────────────────────────────────
  {
    program_id: 'oet_solar',
    program_name: 'Oregon Energy Trust (OET) Solar Rebate',
    utility_ids: ['portland_general_or', 'pacificorp_or', 'eugene_water_electric_board_or', 'pacific_county_pud_wa', 'clearwater_power_or'],
    type: 'solar_rebate',
    status: 'active',
    value_description: '$0.30–0.50/W upfront cash rebate through Oregon Energy Trust',
    value_per_kw: 400,
    max_value: 5000,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.energytrust.org/programs/solar-electricity/',
    program_description: 'Oregon Energy Trust offers upfront cash rebates for residential solar installations in PGE and PacifiCorp territories. Combined with full retail NEM and 30% ITC.',
    solar_pro_note: 'OR OET rebate ($0.40/W) + full retail NEM + 30% ITC = strong solar incentive stack. OET is funded by utility customers (PGE/PacifiCorp). Must use OET-approved contractor to qualify.',
    last_verified: '2025-05',
  },

  // ── Minnesota Solar*Rewards / SEIA ────────────────────────────────────────
  {
    program_id: 'mn_solar_rewards',
    program_name: 'Xcel Energy Solar*Rewards (Minnesota)',
    utility_ids: ['xcel_mn', 'minnesota_power_mn', 'otter_tail_power_mn', 'connexus_energy_mn', 'dakota_electric_association_mn'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'Solar*Rewards: ~$0.02–0.07/kWh production for 10 years',
    value_per_kwh_production: 0.04,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.xcelenergy.com/programs_and_rebates/residential_programs_and_rebates/solar_*_rewards_program',
    program_description: 'Xcel Energy Solar*Rewards Minnesota pays per-kWh production incentive for 10 years. MN also has full retail NEM mandate. Some MN utilities offer additional community solar garden opportunities.',
    solar_pro_note: 'MN Solar*Rewards + full retail NEM + 30% ITC. Minnesota has good solar resource (4.5–5 peak sun hrs). Solar*Rewards adds ~$350/year for 10 years on a 6 kW system. Strong incentive stack.',
    last_verified: '2025-05',
  },

  // ── Illinois Shines expansion (covers all IL utilities via state program) ──
  {
    program_id: 'il_shines_all',
    program_name: 'Illinois Shines (Adjustable Block Program) — All IL',
    utility_ids: ['swec_il','coles_moultrie_il','norris_electric_il','shelby_electric_il','corn_belt_energy_il','spoon_river_il','cwlp_il','midamerican_il','illinois_rural_ec_il','adams_ec_il','eastern_illini_ec_il','egyptian_ec_il','farmers_mutual_ec_il','illinois_valley_ec_il','jo_carroll_energy_il','kankakee_valley_ec_il','mcdonough_power_coop_il','menard_ec_il','monroe_county_ec_il','tri_county_ec_il','western_illinois_electrical_coop_il','city_of_naperville_electric_il','city_of_rochelle_electric_il'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'Performance-based SRECs: $60–90/MWh for 15 years (all IL utility customers)',
    value_per_kwh_production: 0.07,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://illinoisshines.com',
    program_description: 'Illinois Shines (Adjustable Block Program) is a statewide performance-based incentive available to all IL utility customers regardless of which utility serves them. Pays $60–90/MWh for 15 years.',
    solar_pro_note: 'Illinois Shines applies to ALL Illinois utility customers — rural co-ops, municipals, and IOUs. The state program is utility-agnostic. IL Shines + IL NEM + 30% ITC = strong incentive stack for all IL solar customers.',
    last_verified: '2025-05',
  },

  // ── Rhode Island REF / SREC ────────────────────────────────────────────────
  {
    program_id: 'ri_srec',
    program_name: 'Rhode Island REF / SREC Program',
    utility_ids: ['national_grid_ri', 'pascoag_utility_district_ri', 'block_island_power_company_ri'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'RI SREC market: ~$30–60/MWh; ConnectedSolutions battery adds $250/kW',
    value_per_kwh_production: 0.04,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.ri.gov/energy/renewable/',
    program_description: 'Rhode Island SREC market and REF (Renewable Energy Fund) provide incentives for solar. RI also has full retail NEM mandate. National Grid ConnectedSolutions battery program adds ~$250/kW annual payments.',
    solar_pro_note: 'RI full retail NEM + SREC income + ConnectedSolutions battery program (for storage). RI has high electricity rates ($0.22–0.30/kWh). Strong solar ROI especially with battery.',
    last_verified: '2025-05',
  },

  // ── Vermont Group Net Metering / VBSR ─────────────────────────────────────
  {
    program_id: 'vt_solar_incentives',
    program_name: 'Vermont Net Metering / VBSR Solar Incentives',
    utility_ids: ['burlington_electric_vt', 'vermont_ec_vt', 'washington_ec_vt', 'village_of_hyde_park_electric_vt', 'village_of_johnson_electric_vt', 'village_of_ludlow_electric_vt', 'village_of_morrisville_wl_vt', 'village_of_northfield_electric_vt', 'village_of_readsboro_electric_vt', 'village_of_stowe_electric_vt'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'VT full retail NEM + GMP BYOD battery payments ($850+/yr); SPEED tariff for some systems',
    value_per_kwh_production: 0.02,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://publicservice.vermont.gov/topics/energy_generation/net-metering',
    program_description: 'Vermont Group Net Metering allows sharing solar credits across multiple meters. VT mandates full retail NEM. GMP BYOD adds battery income. Vermont is consistently top-5 solar state for incentive stack.',
    solar_pro_note: 'Vermont: full retail NEM + GMP BYOD battery payments + potential SPEED tariff. All VT utilities must honor NEM. VT municipal utilities often have favorable programs. Strong solar+storage incentive state.',
    last_verified: '2025-05',
  },

  // ── Georgia EMC Solar Rebates ──────────────────────────────────────────────
  {
    program_id: 'ga_emc_solar',
    program_name: 'Georgia EMC / PowerSouth Solar Rebate',
    utility_ids: ['cobb_emc_ga','sawnee_emc_ga','jackson_emc_ga','walton_emc_ga','snapping_shoals_emc_ga','coweta_fayette_emc_ga','flint_energies_ga','greystone_power_ga','carroll_emc_ga','diverse_power_ga','excelsior_emc_ga','habersham_emc_ga','hart_emc_ga','jefferson_energy_coop_ga','little_ocmulgee_emc_ga','middle_georgia_emc_ga','mitchell_emc_ga','ocmulgee_emc_ga','oconee_emc_ga','okefenokee_remc_ga','planters_emc_ga','rayle_emc_ga','satilla_remc_ga','slash_pine_emc_ga','sumter_emc_ga','three_notch_emc_ga','tri_county_emc_ga','upson_emc_ga','withlacoochee_emc_ga'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'Georgia EMCs: NEM at avoided-cost rate + federal ITC. Some EMCs offer small installation rebates.',
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.georgiaemc.com',
    program_description: 'Georgia Electric Membership Corporations (EMCs) are member-owned co-ops. NEM terms vary by individual EMC but typically credit exports at avoided-cost rather than retail rate. Some EMCs offer solar installation rebates.',
    solar_pro_note: 'GA EMCs: NEM typically at avoided cost (~3–5 cents/kWh) rather than full retail. Battery storage is strongly recommended for GA EMC customers to maximize self-consumption at retail rates. Check specific EMC NEM tariff before system sizing.',
    last_verified: '2025-05',
  },

  // ── Nebraska Solar Rebates ────────────────────────────────────────────────
  {
    program_id: 'ne_solar',
    program_name: 'Nebraska Public Power / OPPD Solar Program',
    utility_ids: ['nppd_ne', 'oppd_ne', 'les_ne'],
    type: 'solar_rebate',
    status: 'active',
    value_description: 'OPPD: $500 solar rebate; NE NEM at retail rate for qualifying systems',
    value_flat: 500,
    stackable_with_federal_itc: true,
    enrollment_url: 'https://www.oppd.com/services/for-your-home/solar-energy/',
    program_description: 'Nebraska public power districts offer solar programs. OPPD Solar Connect provides NEM at retail rate and small installation rebates. NPPD has residential solar programs with similar terms.',
    solar_pro_note: 'Nebraska NEM is generally at retail rate for qualifying systems. Nebraska has strong solar resource (5–5.5 peak sun hrs in western NE). Low base electricity rates (~$0.09–0.10/kWh) still make solar viable with federal ITC.',
    last_verified: '2025-05',
  },