/**
 * Segmentation worker — produces polygon-based semantic segmentation masks
 * from survey photos using SAM 2 (Meta's Segment Anything Model 2).
 *
 * Architecture decisions:
 * - PRIMARY: SAM 2 Automatic Mask Generation via Python microservice
 *   (deployed on Render). Produces semantic region masks with
 *   model-predicted confidence scores.
 * - EXPLICIT CANNY: When SAM2_SERVICE_URL is not configured, Canny edge
 *   detection at 512×512 is used as an explicit backend (NOT a fallback).
 *   When SAM2 is configured but fails, NO Canny fallback occurs — the
 *   failure is reported honestly instead of producing garbage visuals.
 * - Photos are prioritized by label so roof-domain photos get SAM 2 first
 * - All masks carry review-only authority — never authoritative geometry
 * - Raw mask data is preserved alongside cleaned polygon outlines
 * - The SAM 2 service URL is configured via SAM2_SERVICE_URL env var
 * - SAM 2 cold start is handled via warm-up ping + poll-based waiting
 *
 * DESIGN PHILOSOPHY: No silent fallback to Canny. If SAM 2 fails for a
 * photo, the user sees "FAILED" — not garbage Canny visuals pretending to
 * be real segmentation. Canny is only used as an explicit backend when
 * SAM 2 is not configured at all (no SAM2_SERVICE_URL set).
 *
 * REVIEW-ONLY / NON-AUTHORITATIVE / NOT CAD GEOMETRY
 */

import type {
  GeometryReconstructionInput,
  SemanticSegmentationMask,
  SegmentationClass,
  NormalizedPoint,
  GeometryReconstructionArtifact,
} from '../../types';
import { REVIEW_ONLY_AUTHORITY, BASE_LIMITATIONS, SEGMENTATION_CLASSES } from '../../types';
import { validateSemanticSegmentationMask } from '../../schemas';
import {
  extractRoofGeometry,
  contourToNormalizedPolygon,
  type ContourClassification,
  type RoofGeometryExtractionResult,
  type ExtractedContour,
} from '@/lib/assistedEvidenceSources/roofGeometryExtractor';
import {
  segmentWithSAM2,
  mapSAM2ClassHint,
  isSAM2Enabled,
  checkSAM2Health,
  waitForSAM2Warm,
  ROOF_RELEVANT_SEGMENTATION_CLASSES,
  type SAM2MaskResult,
} from './sam2Client';

// ---------------------------------------------------------------------------
// Worker version
// ---------------------------------------------------------------------------

export const SEGMENTATION_WORKER_VERSION = '4.0.0-sam2-priority-no-fallback';

// ---------------------------------------------------------------------------
// Limitations
// ---------------------------------------------------------------------------

const SEGMENTATION_WORKER_LIMITATIONS = [
  ...BASE_LIMITATIONS,
  'Segmentation masks are generated by SAM 2.1 Automatic Mask Generation when the SAM2_SERVICE_URL is configured and reachable.',
  'When SAM 2 fails for a photo, NO fallback masks are produced — the failure is reported honestly instead of degrading to Canny edge detection.',
  'Canny edge detection is used as an explicit backend ONLY when SAM2_SERVICE_URL is not configured — it is never a silent fallback.',
  'Polygon outlines are simplified via Douglas-Peucker — approximations of actual mask boundaries.',
  'SAM 2 mask confidence blends predicted IoU (40%) + stability score (60%), scaled to 0-100.',
  'Canny confidence reflects contour-based heuristic certainty, not model prediction quality.',
  'Class hints (roof, wall, sky, etc.) are geometry + position heuristics applied to SAM 2 masks — SAM 2 itself is class-agnostic.',
  'Photos are prioritized by label: roof_plane, roof_edge, ridge, obstructions, roof_surface, overview get SAM 2 first.',
] as const;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Input to the segmentation worker. */
export interface SegmentationWorkerInput {
  surveyId: string;
  sourcePhotos: { fileId: string; fileUrl: string; filename: string | null; label?: string | null }[];
  /** Optional config overrides. */
  config?: {
    /** Minimum confidence threshold for masks (0-100). Default: 30 */
    minConfidence?: number;
    /** Whether to include raw mask data in output. Default: true */
    includeRawMask?: boolean;
    /** Maximum number of polygon points per mask. Default: 50 */
    maxPolygonPoints?: number;
  };
}

// -----------------------------------------------------------------------
// Per-photo segmentation result — honest failure reporting
// -----------------------------------------------------------------------

/** Per-photo status after segmentation attempt. */
export type PhotoSegmentationStatus =
  | 'sam2_success'       // SAM 2 processed this photo successfully
  | 'sam2_failed'        // SAM 2 was attempted but failed (service error, timeout, etc.)
  | 'skipped_budget'     // SAM 2 budget exhausted — this photo was not attempted
  | 'skipped_timeout'    // Stage deadline reached — this photo was not attempted
  | 'skipped_warmup'     // SAM 2 warm-up failed — no photos attempted at all
  | 'skipped_not_configured'; // SAM2_SERVICE_URL not set — Canny-only mode

/** Per-photo segmentation result for honest reporting. */
export interface PhotoSegmentationResult {
  fileId: string;
  filename: string | null;
  label: string | null;
  status: PhotoSegmentationStatus;
  /** Number of masks produced (0 for any non-success status). */
  maskCount: number;
  /** Human-readable reason for failure/skip (null for success). */
  reason: string | null;
}

/** Output of the segmentation worker. */
export interface SegmentationWorkerOutput {
  artifacts: SemanticSegmentationMask[];
  stageTimings: Record<string, number>;
  workerVersion: string;
  /** Which segmentation backend was used: 'sam2' or 'canny'. */
  backend: 'sam2' | 'canny';
  /** Number of photos processed with SAM 2 successfully. */
  sam2PhotoCount: number;
  /** Number of photos where SAM 2 was attempted but failed. */
  failedPhotoCount: number;
  /** Number of photos skipped (budget exhausted, timeout, warm-up failure, etc.). */
  skippedPhotoCount: number;
  /** Number of photos processed with Canny (only when SAM2 not configured). */
  cannyPhotoCount: number;
  /** SAM 2 model info if available. */
  sam2ModelInfo: {
    modelId: string;
    device: string;
    cudaAvailable: boolean;
    inferenceResolution?: string;
  } | null;
  /** Honest per-photo results — no silent fallbacks. */
  photoResults: PhotoSegmentationResult[];
  /** Why SAM2 budget was exhausted (null if not exhausted). */
  budgetExhaustedReason: string | null;
}

// ---------------------------------------------------------------------------
// Pipeline throughput limits (prevent 504 timeout)
// ---------------------------------------------------------------------------

/**
 * Maximum number of source photos to process.
 * Processing 30+ photos with heavy extraction + 6 downstream stages
 * causes 504 timeouts on Vercel (maxDuration=300s). Capping at 15
 * keeps total pipeline time under 4 minutes while still covering
 * most meaningful angles of a house.
 */
const MAX_SOURCE_PHOTOS = 15;

/**
 * Maximum number of source photos to process with SAM 2.
 * SAM 2 on Render Starter (CPU) takes ~40s per photo for inference.
 * With warm-up polling (up to 120s) and downstream pipeline stages,
 * we can only afford ~5 photos with SAM 2 before the 240s pipeline
 * timeout is exceeded. After this limit, remaining photos are skipped
 * (NOT fallen back to Canny — the user sees honest skip reasons).
 */
const MAX_SAM2_PHOTOS = 5;

/**
 * Maximum total segmentation masks to produce across ALL photos.
 * With 12 regions per photo × 15 photos = 180 theoretical max,
 * but classification filtering reduces this. Hard cap prevents
 * downstream stages (line extraction, plane extraction, etc.) from
 * exploding into thousands of artifacts.
 */
const MAX_TOTAL_MASKS = 150;

/**
 * Maximum wall-clock milliseconds the segmentation stage may consume.
 * The full pipeline has PIPELINE_TIMEOUT_MS = 240_000ms (4 minutes).
 * Segmentation is Stage 1, but we must leave time for 5 more stages
 * plus DB writes. Capping at 180s leaves 60s for downstream stages
 * and DB writes — enough for their heuristic implementations.
 */
const SEGMENTATION_STAGE_TIMEOUT_MS = 180_000;

/**
 * Photo labels that get SAM 2 priority. These are roof-domain and
 * site-overview labels that produce the most valuable segmentation
 * masks for geometry reconstruction. Photos with these labels are
 * processed with SAM 2 first; remaining photos are skipped (not Canny).
 *
 * Priority order: roof_plane > roof_edge > ridge > obstructions >
 * roof_surface > overview. Within the same priority level, photos
 * are processed in their original order.
 */
const SAM2_PRIORITY_LABELS: readonly string[] = [
  'roof_plane',
  'roof_edge',
  'ridge',
  'obstructions',
  'roof_surface',
  'overview',
];

/**
 * Compute a sort priority for a photo label. Lower number = higher priority.
 * Labels in SAM2_PRIORITY_LABELS get their index position (0-5).
 * Unlabeled or unrecognized labels get priority 99 (lowest).
 */
function sam2PhotoPriority(label: string | null | undefined): number {
  if (!label) return 99;
  const idx = SAM2_PRIORITY_LABELS.indexOf(label);
  return idx >= 0 ? idx : 99;
}


/** Maps ContourClassification from the extractor to SegmentationClass. */
const CONTOUR_TO_SEGMENTATION_CLASS: Record<ContourClassification, SegmentationClass | null> = {
  probable_roof_plane: 'roof',
  probable_wall_plane: 'wall',
  probable_obstruction: 'obstruction',
  probable_equipment: 'equipment',
  probable_ground_noise: 'ground',
  probable_sky_region: 'sky',
  unknown: null, // Skip unknown classifications
};

// ---------------------------------------------------------------------------
// Main worker function (async — uses sharp for real extraction)
// ---------------------------------------------------------------------------

/**
 * Run the segmentation worker on a set of survey photos.
 *
 * For each source photo:
 * 1. Try SAM 2 Automatic Mask Generation (if SAM2_SERVICE_URL is configured)
 * 2. If SAM 2 succeeds → produce SAM2 masks (emerald green in overlay)
 * 3. If SAM 2 fails → produce NO masks, record honest failure reason
 * 4. If SAM 2 budget exhausted → skip photo, record skip reason
 * 5. If SAM2_SERVICE_URL not configured → use Canny (explicit backend)
 *
 * DESIGN PHILOSOPHY: No silent fallback to Canny. If SAM2 fails, the user
 * sees "FAILED" — not garbage Canny visuals pretending to be real segmentation.
 * Canny is only used as an explicit backend when SAM2 is not configured at all.
 */
export async function runSegmentationWorker(input: SegmentationWorkerInput): Promise<SegmentationWorkerOutput> {
  const timings: Record<string, number> = {};
  const artifacts: SemanticSegmentationMask[] = [];
  const photoResults: PhotoSegmentationResult[] = [];
  let sam2PhotoCount = 0;
  let failedPhotoCount = 0;
  let skippedPhotoCount = 0;
  let cannyPhotoCount = 0;
  let sam2ModelInfo: SegmentationWorkerOutput['sam2ModelInfo'] = null;

  const minConfidence = input.config?.minConfidence ?? 30;
  const includeRawMask = input.config?.includeRawMask ?? true;
  const maxPolygonPoints = input.config?.maxPolygonPoints ?? 50;
  // SAM 2 masks retain more polygon detail because the model produces
  // accurate segment boundaries — Canny contours are lower quality and
  // benefit from aggressive simplification.
  const sam2MaxPolygonPoints = Math.max(maxPolygonPoints, 100);

  const sam2Enabled = isSAM2Enabled();

  // Stage 1: Initialize and validate input
  const t0 = Date.now();
  const rawPhotos = input.sourcePhotos.slice(0, MAX_SOURCE_PHOTOS);
  if (rawPhotos.length === 0) {
    timings['initialization'] = Date.now() - t0;
    return {
      artifacts: [],
      stageTimings: timings,
      workerVersion: SEGMENTATION_WORKER_VERSION,
      backend: sam2Enabled ? 'sam2' : 'canny',
      sam2PhotoCount: 0,
      failedPhotoCount: 0,
      skippedPhotoCount: 0,
      cannyPhotoCount: 0,
      sam2ModelInfo: null,
      photoResults: [],
      budgetExhaustedReason: null,
    };
  }

  // ── SAM 2 PRIORITY SORT ─────────────────────────────────────────
  // Sort photos so that roof-domain labels (roof_plane, roof_edge, etc.)
  // are processed first with SAM 2. This ensures the limited SAM2 budget
  // (MAX_SAM2_PHOTOS=5) is spent on the most valuable photos for geometry
  // reconstruction rather than arbitrary upload-order photos.
  //
  // The sort is stable: photos with the same priority keep their original
  // relative order. Unlabeled photos go to the end.
  const sourcePhotos = [...rawPhotos].sort((a, b) => {
    const pa = sam2PhotoPriority(a.label);
    const pb = sam2PhotoPriority(b.label);
    return pa - pb;
  });

  if (sam2Enabled) {
    const labeledCount = sourcePhotos.filter((p) => sam2PhotoPriority(p.label) < 99).length;
    const roofLabels = sourcePhotos
      .filter((p) => sam2PhotoPriority(p.label) < 99)
      .map((p) => `${p.label}(${p.fileId.slice(0, 8)})`);
    console.info(
      `[SAM2] Photo priority sort: ${sourcePhotos.length} photos — ${labeledCount} with priority labels [${roofLabels.join(', ')}], ${sourcePhotos.length - labeledCount} unlabeled/other. First ${Math.min(MAX_SAM2_PHOTOS, sourcePhotos.length)} photos will get SAM 2.`,
    );
  }

  // ── SAM 2 TIME BUDGET (declared early for use in warm-up + Stage 2) ────────
  let sam2BudgetRemaining = sam2Enabled ? MAX_SAM2_PHOTOS : 0;
  let sam2BudgetExhaustedReason: string | null = null;

  // Log which backend will be attempted
  if (sam2Enabled) {
    console.info(`[SAM2] Segmentation worker: SAM 2 enabled — will warm up service then process photos`);

    // ── CRITICAL: Wait for SAM2 model to load before processing photos ────
    // On Render cold starts, the SAM2 service downloads the model from HuggingFace
    // and loads it into memory. During this time, ALL /segment requests return 502.
    // By polling /health until model_loaded=true, we ensure the model is warm
    // before we send real segmentation requests.
    //
    // The warm-up ping (sent earlier from the route handler) triggers model loading.
    // This poll confirms it's ready. If the service was already warm, this returns
    // immediately (~100ms). If cold, it waits up to 120s for the model to load.
    //
    // IMPORTANT: We cap warm-up at 120s (not 180s) to leave time for actual
    // photo processing within the 180s SEGMENTATION_STAGE_TIMEOUT_MS budget.
    // If warm-up exceeds 120s, ALL photos are skipped — no Canny, honest failure.
    const warmupDeadline = t0 + 120_000; // 120s from pipeline start
    const warmupResult = await waitForSAM2Warm(warmupDeadline);
    if (warmupResult) {
      console.info(
        `[SAM2] Service is WARM — model_loaded=true, device=${warmupResult.device}, model_id=${warmupResult.model_id}`,
      );
    } else {
      console.warn(
        `[SAM2] Service warm-up timed out — ALL photos skipped, no masks will be produced`,
      );
      sam2BudgetRemaining = 0;
      sam2BudgetExhaustedReason = 'warmup_timeout';
    }
  } else {
    console.info(`[SAM2] Segmentation worker: SAM 2 not configured — using Canny as explicit backend`);
  }
  timings['initialization'] = Date.now() - t0;

  // ── If warm-up failed, record ALL photos as skipped and return early ──
  if (sam2Enabled && sam2BudgetExhaustedReason === 'warmup_timeout') {
    for (const photo of sourcePhotos) {
      photoResults.push({
        fileId: photo.fileId,
        filename: photo.filename ?? null,
        label: photo.label ?? null,
        status: 'skipped_warmup',
        maskCount: 0,
        reason: 'SAM 2 service warm-up timed out after 120s — no segmentation possible',
      });
      skippedPhotoCount++;
    }
    timings['mask_generation'] = 0;
    console.warn(
      `[SAM2] Segmentation stage: ALL ${sourcePhotos.length} photos skipped — SAM2 warm-up failed`,
    );
    return {
      artifacts: [],
      stageTimings: timings,
      workerVersion: SEGMENTATION_WORKER_VERSION,
      backend: 'sam2',
      sam2PhotoCount: 0,
      failedPhotoCount: 0,
      skippedPhotoCount,
      cannyPhotoCount: 0,
      sam2ModelInfo: null,
      photoResults,
      budgetExhaustedReason: sam2BudgetExhaustedReason,
    };
  }

  // Stage 2: Extract geometry from each photo
  // ── SAM 2 TIME BUDGET ──────────────────────────────────────────────
  // SAM 2 on Render Starter (CPU) takes ~40s per photo for inference alone.
  // The segmentation stage must finish within a time budget that leaves room
  // for 5 downstream pipeline stages + DB writes within the 300s Vercel
  // maxDuration.
  //
  // Strategy: process up to MAX_SAM2_PHOTOS (5) priority-sorted photos with SAM 2.
  // If SAM2 fails for a photo → NO masks, record honest failure.
  // If SAM2 budget exhausted → skip remaining photos, record skip reason.
  // If SAM2 not configured → use Canny as explicit backend (not fallback).
  // Also enforce a wall-clock deadline: if we've spent too long, skip the rest.
  const segmentationDeadline = t0 + SEGMENTATION_STAGE_TIMEOUT_MS;

  const t1 = Date.now();
  for (const photo of sourcePhotos) {
    if (artifacts.length >= MAX_TOTAL_MASKS) {
      console.info(
        `Segmentation worker: reached MAX_TOTAL_MASKS=${MAX_TOTAL_MASKS}, stopping after ${artifacts.length} masks`
      );
      // Record remaining unprocessed photos as skipped
      break;
    }

    // ── Check segmentation stage deadline ──
    const elapsedMs = Date.now() - t1;
    const remainingMs = segmentationDeadline - Date.now();
    if (sam2Enabled && remainingMs <= 0 && !sam2BudgetExhaustedReason) {
      console.warn(
        `[SAM2] Segmentation stage TIMEOUT after ${elapsedMs}ms — skipping remaining photos`,
      );
      sam2BudgetRemaining = 0;
      sam2BudgetExhaustedReason = `stage_timeout_after_${elapsedMs}ms`;
    }

    try {
      // ── SAM 2 PATH ──
      // Only attempt SAM2 if we have budget remaining AND time remaining
      const useSAM2 = sam2Enabled && sam2BudgetRemaining > 0 && remainingMs > 50_000;

      if (useSAM2) {
        console.info(
          `[SAM2] Processing photo ${photo.fileId} (${photo.filename ?? 'unnamed'}, label=${photo.label ?? 'none'}) — attempting SAM 2 (budget=${sam2BudgetRemaining} remaining, ${Math.round(remainingMs / 1000)}s left)`,
        );
        const sam2Result = await segmentWithSAM2FromPhoto(photo.fileUrl);
        if (sam2Result !== null) {
          // ── SAM 2 SUCCESS — produce masks ──
          sam2BudgetRemaining--;
          sam2PhotoCount++;
          if (sam2Result.modelInfo && !sam2ModelInfo) {
            sam2ModelInfo = sam2Result.modelInfo;
          }

          let masksProduced = 0;
          let filteredNonRoof = 0;
          for (const mask of sam2Result.masks) {
            if (artifacts.length >= MAX_TOTAL_MASKS) break;

            const segmentationClass = mapSAM2ClassHint(mask.classHint);
            if (segmentationClass === null) continue;

            // ── Roof-relevant filter ──
            // Even though the Python service now filters with roof_only=true,
            // we double-filter here to catch any non-roof masks that slip
            // through (e.g. stale Python deploy, classification edge cases).
            // Sky, ground, and tree masks are NOT useful for geometry
            // reconstruction and pollute the overlay with wrong lines.
            if (!ROOF_RELEVANT_SEGMENTATION_CLASSES.has(segmentationClass)) {
              filteredNonRoof++;
              continue;
            }

            if (mask.confidence < minConfidence) continue;

            const truncatedPolygon = mask.polygon.slice(0, sam2MaxPolygonPoints);
            const maskBounds = computeMaskBounds(truncatedPolygon);

            const artifact: SemanticSegmentationMask = {
              artifactType: 'semantic_segmentation_mask',
              id: `seg-${photo.fileId}-${segmentationClass}-${mask.maskIndex}-${SEGMENTATION_WORKER_VERSION}`,
              fileId: photo.fileId,
              segmentationClass,
              polygon: truncatedPolygon,
              confidence: mask.confidence,
              maskBounds,
              workerVersion: SEGMENTATION_WORKER_VERSION,
              authority: { ...REVIEW_ONLY_AUTHORITY },
              limitations: [...SEGMENTATION_WORKER_LIMITATIONS],
            };

            if (includeRawMask) {
              artifact.rawMask = `sam2-${segmentationClass}-area${Math.round(mask.area)}-stability${mask.stabilityScore}`;
              artifact.maskWidth = sam2Result.imageWidth;
              artifact.maskHeight = sam2Result.imageHeight;
            }

            const validationResult = validateSemanticSegmentationMask(artifact);
            if (validationResult.valid) {
              artifacts.push(validationResult.data);
              masksProduced++;
            }
          }
          console.info(
            `[SAM2] Photo ${photo.fileId} (${photo.label ?? 'unlabeled'}): SAM 2 SUCCESS — ${masksProduced} masks (filtered ${filteredNonRoof} non-roof, sam2PhotoCount=${sam2PhotoCount}, budget=${sam2BudgetRemaining} remaining)`,
          );
          photoResults.push({
            fileId: photo.fileId,
            filename: photo.filename ?? null,
            label: photo.label ?? null,
            status: 'sam2_success',
            maskCount: masksProduced,
            reason: null,
          });
          continue; // SAM 2 succeeded, done with this photo
        }

        // ── SAM 2 FAILED — NO fallback to Canny. Record honest failure. ──
        sam2BudgetRemaining--;
        failedPhotoCount++;
        console.warn(
          `[SAM2] Photo ${photo.fileId} (${photo.label ?? 'unlabeled'}): SAM 2 FAILED — no masks produced for this photo (budget=${sam2BudgetRemaining} remaining)`,
        );
        photoResults.push({
          fileId: photo.fileId,
          filename: photo.filename ?? null,
          label: photo.label ?? null,
          status: 'sam2_failed',
          maskCount: 0,
          reason: `SAM 2 service call failed — no masks produced`,
        });
        continue; // Skip Canny — no shitty fallback visuals

      } else if (sam2Enabled && sam2BudgetRemaining <= 0 && !sam2BudgetExhaustedReason) {
        // ── SAM2 budget just exhausted ──
        sam2BudgetExhaustedReason = 'max_photos_reached';
        console.info(
          `[SAM2] Photo ${photo.fileId} (${photo.label ?? 'unlabeled'}): SKIPPED — SAM 2 budget exhausted (MAX_SAM2_PHOTOS=${MAX_SAM2_PHOTOS})`,
        );
        photoResults.push({
          fileId: photo.fileId,
          filename: photo.filename ?? null,
          label: photo.label ?? null,
          status: 'skipped_budget',
          maskCount: 0,
          reason: `SAM 2 budget exhausted (${MAX_SAM2_PHOTOS} photos already processed) — not attempted`,
        });
        skippedPhotoCount++;
        continue;

      } else if (sam2Enabled && sam2BudgetExhaustedReason) {
        // ── Subsequent photos after budget exhaustion ──
        console.info(
          `[SAM2] Photo ${photo.fileId} (${photo.label ?? 'unlabeled'}): SKIPPED (${sam2BudgetExhaustedReason})`,
        );
        photoResults.push({
          fileId: photo.fileId,
          filename: photo.filename ?? null,
          label: photo.label ?? null,
          status: sam2BudgetExhaustedReason.startsWith('stage_timeout') ? 'skipped_timeout' : 'skipped_budget',
          maskCount: 0,
          reason: `SAM 2 skipped: ${sam2BudgetExhaustedReason}`,
        });
        skippedPhotoCount++;
        continue;

      } else if (!sam2Enabled) {
        // ── CANNY EXPLICIT BACKEND (SAM2 not configured) ──
        // This is NOT a fallback — it's the primary backend when SAM2 is not available.
        // User deliberately chose not to configure SAM2_SERVICE_URL.
        cannyPhotoCount++;
        const geometry = await extractGeometryFromPhoto(photo.fileUrl);

        let contourIndex = 0;
        let masksProduced = 0;
        for (const contour of geometry.contours) {
          const segmentationClass = CONTOUR_TO_SEGMENTATION_CLASS[contour.classification];
          if (segmentationClass === null) continue;
          if (contour.confidence < minConfidence) continue;

          const polygon = contourToNormalizedPolygon(contour, geometry.extractionSize, geometry.extractionSize);
          const truncatedPolygon = polygon.slice(0, maxPolygonPoints);
          const maskBounds = computeMaskBounds(truncatedPolygon);

          const mask: SemanticSegmentationMask = {
            artifactType: 'semantic_segmentation_mask',
            id: `seg-${photo.fileId}-${segmentationClass}-${contourIndex}-${SEGMENTATION_WORKER_VERSION}`,
            fileId: photo.fileId,
            segmentationClass,
            polygon: truncatedPolygon,
            confidence: contour.confidence,
            maskBounds,
            workerVersion: SEGMENTATION_WORKER_VERSION,
            authority: { ...REVIEW_ONLY_AUTHORITY },
            limitations: [...SEGMENTATION_WORKER_LIMITATIONS],
          };

          if (includeRawMask) {
            mask.rawMask = `canny-contour-${segmentationClass}-area${contour.area}`;
            mask.maskWidth = geometry.extractionSize;
            mask.maskHeight = geometry.extractionSize;
          }

          const validationResult = validateSemanticSegmentationMask(mask);
          if (validationResult.valid) {
            artifacts.push(validationResult.data);
            masksProduced++;
          }
          contourIndex++;
        }
        photoResults.push({
          fileId: photo.fileId,
          filename: photo.filename ?? null,
          label: photo.label ?? null,
          status: 'skipped_not_configured',
          maskCount: masksProduced,
          reason: `SAM 2 not configured (SAM2_SERVICE_URL not set) — Canny backend used`,
        });
      }
    } catch (error) {
      failedPhotoCount++;
      const errMsg = error instanceof Error ? error.message : String(error);
      console.warn(
        `[SAM2] Photo ${photo.fileId}: UNHANDLED ERROR — ${errMsg}`,
      );
      photoResults.push({
        fileId: photo.fileId,
        filename: photo.filename ?? null,
        label: photo.label ?? null,
        status: 'sam2_failed',
        maskCount: 0,
        reason: `Unhandled error: ${errMsg}`,
      });
    }
  }
  timings['mask_generation'] = Date.now() - t1;

  // Log segmentation summary — honest counts
  const backend = sam2Enabled ? 'sam2' : 'canny';
  console.info(
    `[SAM2] Segmentation stage complete: ${artifacts.length} masks in ${timings['mask_generation']}ms — backend=${backend} sam2_success=${sam2PhotoCount} failed=${failedPhotoCount} skipped=${skippedPhotoCount} canny=${cannyPhotoCount} out of ${sourcePhotos.length} total${sam2BudgetExhaustedReason ? ` (budget_exhausted: ${sam2BudgetExhaustedReason})` : ''}`,
  );

  // Stage 4: Post-validation pass
  const t2 = Date.now();
  const validatedArtifacts = artifacts.filter((artifact) => {
    const result = validateSemanticSegmentationMask(artifact);
    return result.valid;
  });
  timings['validation'] = Date.now() - t2;

  return {
    artifacts: validatedArtifacts,
    stageTimings: timings,
    workerVersion: SEGMENTATION_WORKER_VERSION,
    backend: sam2PhotoCount > 0 ? 'sam2' : (cannyPhotoCount > 0 ? 'canny' : 'sam2'),
    sam2PhotoCount,
    failedPhotoCount,
    skippedPhotoCount,
    cannyPhotoCount,
    sam2ModelInfo,
    photoResults,
    budgetExhaustedReason: sam2BudgetExhaustedReason,
  };
}

// ---------------------------------------------------------------------------
// URL helper for logging (avoids logging full URLs with tokens)
// ---------------------------------------------------------------------------

/**
 * Extract the hostname from a URL for safe logging.
 * Returns the full URL string if parsing fails.
 */
function tryExtractHost(url: string): string {
  try {
    const parsed = new URL(url);
    return parsed.host;
  } catch {
    return url.slice(0, 80);
  }
}

// ---------------------------------------------------------------------------
// Geometry extraction helpers
// ---------------------------------------------------------------------------

/**
 * Extract geometry from a photo URL using the SAM 2 service.
 * Fetches image bytes, sends them to SAM 2, and returns the result.
 * Returns null if SAM 2 is unavailable or fails — caller records honest failure.
 */
async function segmentWithSAM2FromPhoto(
  fileUrl: string,
): Promise<import('./sam2Client').SAM2SegmentationResult | null> {
  const t0 = Date.now();
  const urlHost = tryExtractHost(fileUrl);

  try {
    // Fetch image bytes
    console.info(`[SAM2] Image fetch: START — ${urlHost} (timeout=30s)`);
    const response = await fetch(fileUrl, {
      signal: AbortSignal.timeout(30_000),
    });

    if (!response.ok) {
      const fetchElapsedMs = Date.now() - t0;
      console.warn(
        `[SAM2] Image fetch: FAILED — HTTP ${response.status} in ${fetchElapsedMs}ms from ${urlHost}`,
      );
      throw new Error(`Failed to fetch image: HTTP ${response.status}`);
    }
    const arrayBuffer = await response.arrayBuffer();
    const bytes = Buffer.from(arrayBuffer);
    const fetchElapsedMs = Date.now() - t0;
    console.info(
      `[SAM2] Image fetch: OK — ${bytes.length} bytes (${(bytes.length / 1024).toFixed(1)}KB) in ${fetchElapsedMs}ms from ${urlHost}`,
    );

    // Call SAM 2 service (with 502/503 retry built in)
    // Use min_area_fraction=0.05 (matches Python default) to filter small
    // ground patches and tree segments. The roof_only=true param is set in
    // sam2Client.ts to filter non-roof masks on the Python side as well.
    const sam2Result = await segmentWithSAM2(bytes, 0.05);
    const totalElapsedMs = Date.now() - t0;

    if (sam2Result !== null) {
      console.info(
        `[SAM2] Photo pipeline: SUCCESS — ${sam2Result.masks.length} masks, total=${totalElapsedMs}ms (fetch=${fetchElapsedMs}ms, service=${sam2Result.processingTimeMs}ms)`,
      );
    } else {
      console.warn(
        `[SAM2] Photo pipeline: SAM2 service returned null after ${totalElapsedMs}ms (fetch=${fetchElapsedMs}ms) — recording honest failure`,
      );
    }

    return sam2Result;
  } catch (error) {
    const elapsedMs = Date.now() - t0;
    const message = error instanceof Error ? error.message : String(error);
    const isTimeout = error instanceof DOMException && error.name === 'TimeoutError';
    console.warn(
      `[SAM2] Photo pipeline: FAILED${isTimeout ? ' (FETCH TIMEOUT at 30s)' : ''} in ${elapsedMs}ms — ${message}`,
    );
    return null;
  }
}

/**
 * Extract geometry from a photo URL using the roofGeometryExtractor.
 * Handles fetch errors gracefully and returns an empty result on failure.
 * Only used when SAM2 is not configured (Canny as explicit backend).
 */
async function extractGeometryFromPhoto(fileUrl: string): Promise<RoofGeometryExtractionResult> {
  const t0 = Date.now();
  const urlHost = tryExtractHost(fileUrl);

  // Fetch image bytes
  console.info(`[SAM2] Canny image fetch: START — ${urlHost} (timeout=30s)`);
  const response = await fetch(fileUrl, {
    signal: AbortSignal.timeout(30_000),
  });

  if (!response.ok) {
    const fetchElapsedMs = Date.now() - t0;
    console.warn(
      `[SAM2] Canny image fetch: FAILED — HTTP ${response.status} in ${fetchElapsedMs}ms from ${urlHost}`,
    );
    throw new Error(`Failed to fetch image: HTTP ${response.status}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  const bytes = Buffer.from(arrayBuffer);
  const fetchElapsedMs = Date.now() - t0;
  console.info(
    `[SAM2] Canny image fetch: OK — ${bytes.length} bytes (${(bytes.length / 1024).toFixed(1)}KB) in ${fetchElapsedMs}ms from ${urlHost}`,
  );

  // Run real contour extraction
  const result = await extractRoofGeometry(bytes);
  const totalElapsedMs = Date.now() - t0;
  console.info(
    `[SAM2] Canny extraction: ${result.contours.length} contours in ${totalElapsedMs}ms (fetch=${fetchElapsedMs}ms)`,
  );
  return result;
}

// ---------------------------------------------------------------------------
// Bounding box computation
// ---------------------------------------------------------------------------

/**
 * Compute the bounding box of a polygon in normalized coordinates,
 * returning a NormalizedRegion (x, y, width, height, coordinateSystem).
 */
function computeMaskBounds(polygon: NormalizedPoint[]): import('@/lib/assistedEvidenceSources/overlayCoordinateConversion').NormalizedRegion {
  let xMin = 1000;
  let yMin = 1000;
  let xMax = 0;
  let yMax = 0;

  for (const pt of polygon) {
    if (pt.x < xMin) xMin = pt.x;
    if (pt.y < yMin) yMin = pt.y;
    if (pt.x > xMax) xMax = pt.x;
    if (pt.y > yMax) yMax = pt.y;
  }

  return {
    x: xMin,
    y: yMin,
    width: xMax - xMin,
    height: yMax - yMin,
    coordinateSystem: 'normalized_image_0_1000',
  };
}

// ---------------------------------------------------------------------------
// Convenience: run from GeometryReconstructionInput
// ---------------------------------------------------------------------------

/**
 * Run the segmentation worker from a standard GeometryReconstructionInput.
 * Converts the input format and delegates to runSegmentationWorker.
 * Returns only the artifacts (backward-compatible).
 */
export async function runSegmentationFromReconstructionInput(
  input: GeometryReconstructionInput,
): Promise<GeometryReconstructionArtifact[]> {
  const workerInput: SegmentationWorkerInput = {
    surveyId: input.surveyId,
    sourcePhotos: input.sourcePhotos.map((p) => ({
      fileId: p.fileId,
      fileUrl: p.fileUrl,
      filename: p.filename,
      label: p.label ?? null,
    })),
    config: input.config as SegmentationWorkerInput['config'] | undefined,
  };

  const output = await runSegmentationWorker(workerInput);
  return output.artifacts;
}

/**
 * Run the segmentation worker from a standard GeometryReconstructionInput
 * and return the FULL output (including backend info for SAM 2 tracking).
 */
export async function runSegmentationFullOutput(
  input: GeometryReconstructionInput,
): Promise<SegmentationWorkerOutput> {
  const workerInput: SegmentationWorkerInput = {
    surveyId: input.surveyId,
    sourcePhotos: input.sourcePhotos.map((p) => ({
      fileId: p.fileId,
      fileUrl: p.fileUrl,
      filename: p.filename,
      label: p.label ?? null,
    })),
    config: input.config as SegmentationWorkerInput['config'] | undefined,
  };

  return runSegmentationWorker(workerInput);
}
