/**
 * Segmentation worker — produces polygon-based semantic segmentation masks
 * from survey photos using real 512×512 Canny contour extraction.
 *
 * This worker uses the `roofGeometryExtractor` module to perform actual
 * edge detection, contour tracing, and classification on survey photos,
 * then maps the extracted contours to `SemanticSegmentationMask` artifacts.
 *
 * Architecture decisions:
 * - Real Canny edge detection + contour tracing at 512×512 via sharp
 * - Contours are classified and mapped to SEGMENTATION_CLASSES
 * - All masks carry review-only authority — never authoritative geometry
 * - Raw mask data is preserved alongside cleaned polygon outlines
 * - When a real segmentation model (e.g., SAM) becomes available, this
 *   worker can be upgraded to use it instead
 *
 * REVIEW-ONLY / NON-AUTHORITATIVE / NOT CAD GEOMETRY
 */

import type {
  GeometryReconstructionInput,
  SemanticSegmentationMask,
  SegmentationClass,
  NormalizedPoint,
  GeometryReconstructionArtifact,
} from '../../types';
import { REVIEW_ONLY_AUTHORITY, BASE_LIMITATIONS, SEGMENTATION_CLASSES } from '../../types';
import { validateSemanticSegmentationMask } from '../../schemas';
import {
  extractRoofGeometry,
  contourToNormalizedPolygon,
  type ContourClassification,
  type RoofGeometryExtractionResult,
  type ExtractedContour,
} from '@/lib/assistedEvidenceSources/roofGeometryExtractor';

// ---------------------------------------------------------------------------
// Worker version
// ---------------------------------------------------------------------------

export const SEGMENTATION_WORKER_VERSION = '2.0.0-segmentation-worker';

// ---------------------------------------------------------------------------
// Limitations
// ---------------------------------------------------------------------------

const SEGMENTATION_WORKER_LIMITATIONS = [
  ...BASE_LIMITATIONS,
  'Segmentation masks are generated by 512×512 Canny edge detection + contour tracing — not from a trained segmentation model.',
  'When a real segmentation model (e.g., SAM) is available, this worker will be upgraded.',
  'Polygon outlines are simplified via Douglas-Peucker — approximations of actual mask boundaries.',
  'Mask confidence reflects contour-based heuristic certainty, not model prediction quality.',
  'Contour classification is based on geometry heuristics (size, position, aspect ratio) — not semantic understanding.',
] as const;

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Input to the segmentation worker. */
export interface SegmentationWorkerInput {
  surveyId: string;
  sourcePhotos: { fileId: string; fileUrl: string; filename: string | null }[];
  /** Optional config overrides. */
  config?: {
    /** Minimum confidence threshold for masks (0-100). Default: 30 */
    minConfidence?: number;
    /** Whether to include raw mask data in output. Default: true */
    includeRawMask?: boolean;
    /** Maximum number of polygon points per mask. Default: 50 */
    maxPolygonPoints?: number;
  };
}

/** Output of the segmentation worker. */
export interface SegmentationWorkerOutput {
  artifacts: SemanticSegmentationMask[];
  stageTimings: Record<string, number>;
  workerVersion: string;
}

// ---------------------------------------------------------------------------
// Classification → SegmentationClass mapping
// ---------------------------------------------------------------------------

/** Maps ContourClassification from the extractor to SegmentationClass. */
const CONTOUR_TO_SEGMENTATION_CLASS: Record<ContourClassification, SegmentationClass | null> = {
  probable_roof_plane: 'roof',
  probable_wall_plane: 'wall',
  probable_obstruction: 'obstruction',
  probable_equipment: 'equipment',
  probable_ground_noise: 'ground',
  probable_sky_region: 'sky',
  unknown: null, // Skip unknown classifications
};

// ---------------------------------------------------------------------------
// Main worker function (async — uses sharp for real extraction)
// ---------------------------------------------------------------------------

/**
 * Run the segmentation worker on a set of survey photos.
 *
 * For each source photo, fetches the image bytes, runs 512×512 Canny
 * contour extraction via `roofGeometryExtractor`, and maps the extracted
 * contours to `SemanticSegmentationMask` artifacts.
 *
 * The worker is designed to be idempotent — same input always produces
 * same output for the same image content.
 */
export async function runSegmentationWorker(input: SegmentationWorkerInput): Promise<SegmentationWorkerOutput> {
  const timings: Record<string, number> = {};
  const artifacts: SemanticSegmentationMask[] = [];

  const minConfidence = input.config?.minConfidence ?? 30;
  const includeRawMask = input.config?.includeRawMask ?? true;
  const maxPolygonPoints = input.config?.maxPolygonPoints ?? 50;

  // Stage 1: Initialize and validate input
  const t0 = Date.now();
  const sourcePhotos = input.sourcePhotos;
  if (sourcePhotos.length === 0) {
    timings['initialization'] = Date.now() - t0;
    return {
      artifacts: [],
      stageTimings: timings,
      workerVersion: SEGMENTATION_WORKER_VERSION,
    };
  }
  timings['initialization'] = Date.now() - t0;

  // Stage 2: Extract real geometry from each photo
  const t1 = Date.now();
  for (const photo of sourcePhotos) {
    try {
      const geometry = await extractGeometryFromPhoto(photo.fileUrl);

      // Stage 3: Convert contours to segmentation masks
      let contourIndex = 0;
      for (const contour of geometry.contours) {
        const segmentationClass = CONTOUR_TO_SEGMENTATION_CLASS[contour.classification];

        // Skip contours that don't map to a segmentation class
        if (segmentationClass === null) continue;

        // Skip low-confidence masks
        if (contour.confidence < minConfidence) continue;

        // Convert contour polygon to NormalizedPoint[]
        const polygon = contourToNormalizedPolygon(contour, geometry.extractionSize, geometry.extractionSize);

        // Truncate polygon to max points
        const truncatedPolygon = polygon.slice(0, maxPolygonPoints);

        // Compute bounding box
        const maskBounds = computeMaskBounds(truncatedPolygon);

        // Include contourIndex in ID to ensure uniqueness — multiple contours
        // of the same class can exist (e.g., multiple roof planes)
        const mask: SemanticSegmentationMask = {
          artifactType: 'semantic_segmentation_mask',
          id: `seg-${photo.fileId}-${segmentationClass}-${contourIndex}-${SEGMENTATION_WORKER_VERSION}`,
          fileId: photo.fileId,
          segmentationClass,
          polygon: truncatedPolygon,
          confidence: contour.confidence,
          maskBounds,
          workerVersion: SEGMENTATION_WORKER_VERSION,
          authority: { ...REVIEW_ONLY_AUTHORITY },
          limitations: [...SEGMENTATION_WORKER_LIMITATIONS],
        };

        // Include raw mask data if requested
        if (includeRawMask) {
          mask.rawMask = `canny-contour-${segmentationClass}-area${contour.area}`;
          mask.maskWidth = geometry.extractionSize;
          mask.maskHeight = geometry.extractionSize;
        }

        // Validate the artifact before including it
        const validationResult = validateSemanticSegmentationMask(mask);
        if (validationResult.valid) {
          artifacts.push(validationResult.data);
        }
        contourIndex++;
      }
    } catch (error) {
      // Skip photos that fail extraction — don't break the whole batch
      console.warn(
        `Segmentation worker: failed to extract geometry from photo ${photo.fileId}: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    }
  }
  timings['mask_generation'] = Date.now() - t1;

  // Stage 4: Post-validation pass
  const t2 = Date.now();
  const validatedArtifacts = artifacts.filter((artifact) => {
    const result = validateSemanticSegmentationMask(artifact);
    return result.valid;
  });
  timings['validation'] = Date.now() - t2;

  return {
    artifacts: validatedArtifacts,
    stageTimings: timings,
    workerVersion: SEGMENTATION_WORKER_VERSION,
  };
}

// ---------------------------------------------------------------------------
// Geometry extraction helper
// ---------------------------------------------------------------------------

/**
 * Extract geometry from a photo URL using the roofGeometryExtractor.
 * Handles fetch errors gracefully and returns an empty result on failure.
 */
async function extractGeometryFromPhoto(fileUrl: string): Promise<RoofGeometryExtractionResult> {
  // Fetch image bytes
  const response = await fetch(fileUrl, {
    signal: AbortSignal.timeout(15_000),
  });
  if (!response.ok) {
    throw new Error(`Failed to fetch image: HTTP ${response.status}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  const bytes = Buffer.from(arrayBuffer);

  // Run real contour extraction
  return extractRoofGeometry(bytes);
}

// ---------------------------------------------------------------------------
// Bounding box computation
// ---------------------------------------------------------------------------

/**
 * Compute the bounding box of a polygon in normalized coordinates,
 * returning a NormalizedRegion (x, y, width, height, coordinateSystem).
 */
function computeMaskBounds(polygon: NormalizedPoint[]): import('@/lib/assistedEvidenceSources/overlayCoordinateConversion').NormalizedRegion {
  let xMin = 1000;
  let yMin = 1000;
  let xMax = 0;
  let yMax = 0;

  for (const pt of polygon) {
    if (pt.x < xMin) xMin = pt.x;
    if (pt.y < yMin) yMin = pt.y;
    if (pt.x > xMax) xMax = pt.x;
    if (pt.y > yMax) yMax = pt.y;
  }

  return {
    x: xMin,
    y: yMin,
    width: xMax - xMin,
    height: yMax - yMin,
    coordinateSystem: 'normalized_image_0_1000',
  };
}

// ---------------------------------------------------------------------------
// Convenience: run from GeometryReconstructionInput
// ---------------------------------------------------------------------------

/**
 * Run the segmentation worker from a standard GeometryReconstructionInput.
 * Converts the input format and delegates to runSegmentationWorker.
 */
export async function runSegmentationFromReconstructionInput(
  input: GeometryReconstructionInput,
): Promise<GeometryReconstructionArtifact[]> {
  const workerInput: SegmentationWorkerInput = {
    surveyId: input.surveyId,
    sourcePhotos: input.sourcePhotos.map((p) => ({
      fileId: p.fileId,
      fileUrl: p.fileUrl,
      filename: p.filename,
    })),
    config: input.config as SegmentationWorkerInput['config'] | undefined,
  };

  const output = await runSegmentationWorker(workerInput);
  return output.artifacts;
}
