name: Promote Vercel Production

on:
  push:
    branches:
      - master

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for Vercel Deployment
        run: sleep 30

      - name: Promote Deployment Alias
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            https://api.vercel.com/v1/integrations/deploy/prj_Solarpro/alias
